/**
 * Configs Registre pour maintenance-industrielle (expansion wave 6 generee).
 *
 * Chaque ConfigRegistre est passe en prop au composant generique
 * <RegistreGenerique /> pour rendre table, filtres, formulaire.
 */
"use client";

import * as Icons from 'lucide-react';
import type { ConfigRegistre, ColonneRegistre, ChampRegistre, FiltreRegistre } from '@/components/registre-generique/typesRegistre';
import { registreAPI } from '@/lib/api-client';

const api = registreAPI("maintenance-industrielle");

function col(name: string, label: string, labelEn: string, opts: Partial<ColonneRegistre> = {}): ColonneRegistre {
  return { name, label, labelEn, ...opts } as ColonneRegistre;
}

function txt(name: string, label: string, labelEn: string, opts: Partial<ChampRegistre> = {}): ChampRegistre {
  return { name, label, labelEn, type: "texte", ...opts } as ChampRegistre;
}

function num(name: string, label: string, labelEn: string, opts: Partial<ChampRegistre> = {}): ChampRegistre {
  return { name, label, labelEn, type: "nombre", ...opts } as ChampRegistre;
}

function dt(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}

function dtx(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}

function area(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "zone" } as ChampRegistre;
}

function chk(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "booleen" } as ChampRegistre;
}

function filtreSel(name: string, label: string, labelEn: string, nomKey: string): FiltreRegistre {
  return { name, label, labelEn, type: "select", nomenclature: nomKey } as FiltreRegistre;
}


export const registreAsset: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "assets",
  tcode: "registre-assets",
  icon: Icons.Cog,
  titre: "Actif technique",
  titreEn: "Technical asset",
  description: "Equipement maintenable (grue, engin, navire, ligne).",
  descriptionEn: "Maintainable equipment (crane, machine, vessel, line).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("assets", params),
  creer: (data) => api.creer("assets", data),
  modifier: (id, data) => api.modifier("assets", id, data),
  unicite: "tag_actif",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("tag_actif", "Tag Actif", "Tag Actif"),
    col("nom", "Nom", "Nom"),
    col("categorie", "Categorie", "Categorie"),
    col("sous_categorie", "Sous Categorie", "Sous Categorie"),
    col("module_source", "Module Source", "Module Source"),
    col("ref_entite_source", "Ref Entite Source", "Ref Entite Source"),
    col("parent_id", "Parent Id", "Parent Id"),
    col("emplacement", "Emplacement", "Emplacement"),
    col("fabricant", "Fabricant", "Fabricant"),
    col("modele", "Modele", "Modele"),
    col("numero_serie", "Numero Serie", "Numero Serie"),
    col("annee_fabrication", "Annee Fabrication", "Annee Fabrication"),
    col("date_mise_service", "Date Mise Service", "Date Mise Service"),
    col("criticite", "Criticite", "Criticite"),
    col("statut", "Statut", "Statut"),
    col("cout_acquisition_xaf", "Cout Acquisition Xaf", "Cout Acquisition Xaf"),
    col("valeur_residuelle_xaf", "Valeur Residuelle Xaf", "Valeur Residuelle Xaf"),
    col("duree_vieutile_ans", "Duree Vieutile Ans", "Duree Vieutile Ans"),
    col("notes_techniques", "Notes Techniques", "Notes Techniques"),
  ],
  champs: [
    txt("tag_actif", "Tag Actif", "Tag Actif", { requisCreation: true }),
    txt("nom", "Nom", "Nom"),
    txt("categorie", "Categorie", "Categorie"),
    txt("sous_categorie", "Sous Categorie", "Sous Categorie"),
    txt("module_source", "Module Source", "Module Source"),
    txt("ref_entite_source", "Ref Entite Source", "Ref Entite Source"),
    num("parent_id", "Parent Id", "Parent Id"),
    txt("emplacement", "Emplacement", "Emplacement"),
    txt("fabricant", "Fabricant", "Fabricant"),
    txt("modele", "Modele", "Modele"),
    txt("numero_serie", "Numero Serie", "Numero Serie"),
    num("annee_fabrication", "Annee Fabrication", "Annee Fabrication"),
    dt("date_mise_service", "Date Mise Service", "Date Mise Service"),
    txt("criticite", "Criticite", "Criticite"),
    txt("statut", "Statut", "Statut"),
    num("cout_acquisition_xaf", "Cout Acquisition Xaf", "Cout Acquisition Xaf"),
    num("valeur_residuelle_xaf", "Valeur Residuelle Xaf", "Valeur Residuelle Xaf"),
    num("duree_vieutile_ans", "Duree Vieutile Ans", "Duree Vieutile Ans"),
    area("notes_techniques", "Notes Techniques", "Notes Techniques"),
  ],
};


export const registreComponent: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "components",
  tcode: "registre-components",
  icon: Icons.Layers,
  titre: "Composant d'actif",
  titreEn: "Asset component",
  description: "Sous-ensemble technique d'un actif (moteur, verin, reducteur).",
  descriptionEn: "Technical sub-assembly of an asset.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("components", params),
  creer: (data) => api.creer("components", data),
  modifier: (id, data) => api.modifier("components", id, data),
  unicite: "code_composant",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("asset_id", "Asset Id", "Asset Id"),
    col("code_composant", "Code Composant", "Code Composant"),
    col("nom_composant", "Nom Composant", "Nom Composant"),
    col("type_composant", "Type Composant", "Type Composant"),
    col("ref_fabricant", "Ref Fabricant", "Ref Fabricant"),
    col("numero_serie", "Numero Serie", "Numero Serie"),
    col("nombre_pieces", "Nombre Pieces", "Nombre Pieces"),
    col("masse_kg", "Masse Kg", "Masse Kg"),
    col("seuil_reforme", "Seuil Reforme", "Seuil Reforme"),
    col("criticite", "Criticite", "Criticite"),
    col("date_mise_service", "Date Mise Service", "Date Mise Service"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("asset_id", "Asset Id", "Asset Id"),
    txt("code_composant", "Code Composant", "Code Composant", { requisCreation: true }),
    txt("nom_composant", "Nom Composant", "Nom Composant"),
    txt("type_composant", "Type Composant", "Type Composant"),
    txt("ref_fabricant", "Ref Fabricant", "Ref Fabricant"),
    txt("numero_serie", "Numero Serie", "Numero Serie"),
    num("nombre_pieces", "Nombre Pieces", "Nombre Pieces"),
    num("masse_kg", "Masse Kg", "Masse Kg"),
    txt("seuil_reforme", "Seuil Reforme", "Seuil Reforme"),
    txt("criticite", "Criticite", "Criticite"),
    dt("date_mise_service", "Date Mise Service", "Date Mise Service"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreSparePart: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "spare_parts",
  tcode: "registre-spare-parts",
  icon: Icons.Package,
  titre: "Piece de rechange",
  titreEn: "Spare part",
  description: "Catalogue des pieces (criticite, fournisseur, seuil stock).",
  descriptionEn: "Parts catalog (criticality, supplier, stock threshold).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("spare-parts", params),
  creer: (data) => api.creer("spare-parts", data),
  modifier: (id, data) => api.modifier("spare-parts", id, data),
  unicite: "reference_interne",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_interne", "Reference Interne", "Reference Interne"),
    col("designation", "Designation", "Designation"),
    col("origine", "Origine", "Origine"),
    col("ref_fabricant", "Ref Fabricant", "Ref Fabricant"),
    col("ref_essaiere_group", "Ref Essaiere Group", "Ref Essaiere Group"),
    col("categorie", "Categorie", "Categorie"),
    col("sous_categorie", "Sous Categorie", "Sous Categorie"),
    col("type_rechange", "Type Rechange", "Type Rechange"),
    col("unite_mesure", "Unite Mesure", "Unite Mesure"),
    col("unit_cost_xaf", "Unit Cost Xaf", "Unit Cost Xaf"),
    col("cost_achat_actuel_xaf", "Cost Achat Actuel Xaf", "Cost Achat Actuel Xaf"),
    col("fournisseur_principal_id", "Fournisseur Principal Id", "Fournisseur Principal Id"),
    col("alternative_fournisseur_id", "Alternative Fournisseur Id", "Alternative Fournisseur Id"),
    col("delai_approvisionnement_j", "Delai Approvisionnement J", "Delai Approvisionnement J"),
    col("duree_vie_moyenne_h", "Duree Vie Moyenne H", "Duree Vie Moyenne H"),
    col("garantie_mois", "Garantie Mois", "Garantie Mois"),
    col("serialise_obligatoire", "Serialise Obligatoire", "Serialise Obligatoire"),
    col("poids_kg", "Poids Kg", "Poids Kg"),
    col("volume_cm3", "Volume Cm3", "Volume Cm3"),
    col("classification_hs", "Classification Hs", "Classification Hs"),
    col("notes_techniques", "Notes Techniques", "Notes Techniques"),
  ],
  champs: [
    txt("reference_interne", "Reference Interne", "Reference Interne", { requisCreation: true }),
    txt("designation", "Designation", "Designation"),
    txt("origine", "Origine", "Origine"),
    txt("ref_fabricant", "Ref Fabricant", "Ref Fabricant"),
    txt("ref_essaiere_group", "Ref Essaiere Group", "Ref Essaiere Group"),
    txt("categorie", "Categorie", "Categorie"),
    txt("sous_categorie", "Sous Categorie", "Sous Categorie"),
    txt("type_rechange", "Type Rechange", "Type Rechange"),
    txt("unite_mesure", "Unite Mesure", "Unite Mesure"),
    num("unit_cost_xaf", "Unit Cost Xaf", "Unit Cost Xaf"),
    num("cost_achat_actuel_xaf", "Cost Achat Actuel Xaf", "Cost Achat Actuel Xaf"),
    num("fournisseur_principal_id", "Fournisseur Principal Id", "Fournisseur Principal Id"),
    num("alternative_fournisseur_id", "Alternative Fournisseur Id", "Alternative Fournisseur Id"),
    num("delai_approvisionnement_j", "Delai Approvisionnement J", "Delai Approvisionnement J"),
    num("duree_vie_moyenne_h", "Duree Vie Moyenne H", "Duree Vie Moyenne H"),
    num("garantie_mois", "Garantie Mois", "Garantie Mois"),
    chk("serialise_obligatoire", "Serialise Obligatoire", "Serialise Obligatoire"),
    num("poids_kg", "Poids Kg", "Poids Kg"),
    num("volume_cm3", "Volume Cm3", "Volume Cm3"),
    txt("classification_hs", "Classification Hs", "Classification Hs"),
    area("notes_techniques", "Notes Techniques", "Notes Techniques"),
  ],
};


export const registreBom: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "bill_of_material",
  tcode: "registre-bill-of-material",
  icon: Icons.ListTree,
  titre: "Nomenclature BOM",
  titreEn: "Bill of material",
  description: "Arborescence piece/quantite par actif ou composant.",
  descriptionEn: "Part/quantity tree per asset or component.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("bill-of-material", params),
  creer: (data) => api.creer("bill-of-material", data),
  modifier: (id, data) => api.modifier("bill-of-material", id, data),
  unicite: "position_index",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("part_id", "Part Id", "Part Id"),
    col("position_index", "Position Index", "Position Index"),
    col("quantite_par_assemblage", "Quantite Par Assemblage", "Quantite Par Assemblage"),
    col("unit", "Unit", "Unit"),
    col("niveau", "Niveau", "Niveau"),
    col("level_parent_id", "Level Parent Id", "Level Parent Id"),
    col("obligatoire", "Obligatoire", "Obligatoire"),
    col("remplacement_interval", "Remplacement Interval", "Remplacement Interval"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    num("part_id", "Part Id", "Part Id"),
    num("position_index", "Position Index", "Position Index", { requisCreation: true }),
    num("quantite_par_assemblage", "Quantite Par Assemblage", "Quantite Par Assemblage"),
    txt("unit", "Unit", "Unit"),
    num("niveau", "Niveau", "Niveau"),
    num("level_parent_id", "Level Parent Id", "Level Parent Id"),
    chk("obligatoire", "Obligatoire", "Obligatoire"),
    txt("remplacement_interval", "Remplacement Interval", "Remplacement Interval"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreSerializedPart: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "serialized_parts",
  tcode: "registre-serialized-parts",
  icon: Icons.Tag,
  titre: "Piece serialisee (singleton)",
  titreEn: "Serialized part",
  description: "Unite unique tracee par numero de serial (cycle de vie, affectation).",
  descriptionEn: "Unique unit tracked by serial (lifecycle, assignment).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("serialized-parts", params),
  creer: (data) => api.creer("serialized-parts", data),
  modifier: (id, data) => api.modifier("serialized-parts", id, data),
  unicite: "numero_serial",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("part_id", "Part Id", "Part Id"),
    col("numero_serial", "Numero Serial", "Numero Serial"),
    col("numero_lot", "Numero Lot", "Numero Lot"),
    col("date_fabrication", "Date Fabrication", "Date Fabrication"),
    col("date_reception", "Date Reception", "Date Reception"),
    col("date_mise_service", "Date Mise Service", "Date Mise Service"),
    col("date_reforme", "Date Reforme", "Date Reforme"),
    col("cycles_utilisation", "Cycles Utilisation", "Cycles Utilisation"),
    col("heures_utilisees", "Heures Utilisees", "Heures Utilisees"),
    col("kilometres_utilises", "Kilometres Utilises", "Kilometres Utilises"),
    col("statut", "Statut", "Statut"),
    col("asset_id_actuel", "Asset Id Actuel", "Asset Id Actuel"),
    col("composant_id_actuel", "Composant Id Actuel", "Composant Id Actuel"),
    col("emplacement_stock", "Emplacement Stock", "Emplacement Stock"),
    col("fournisseur_id", "Fournisseur Id", "Fournisseur Id"),
    col("numero_bl_achat", "Numero Bl  Achat", "Numero Bl Achat"),
    col("numero_facture_achat", "Numero Facture  Achat", "Numero Facture Achat"),
    col("date_garantie_fin", "Date Garantie Fin", "Date Garantie Fin"),
    col("valeur_achat_xaf", "Valeur Achat Xaf", "Valeur Achat Xaf"),
    col("hashs_certificat", "Hashs Certificat", "Hashs Certificat"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("part_id", "Part Id", "Part Id"),
    txt("numero_serial", "Numero Serial", "Numero Serial", { requisCreation: true }),
    txt("numero_lot", "Numero Lot", "Numero Lot"),
    dt("date_fabrication", "Date Fabrication", "Date Fabrication"),
    dt("date_reception", "Date Reception", "Date Reception"),
    dt("date_mise_service", "Date Mise Service", "Date Mise Service"),
    dt("date_reforme", "Date Reforme", "Date Reforme"),
    num("cycles_utilisation", "Cycles Utilisation", "Cycles Utilisation"),
    num("heures_utilisees", "Heures Utilisees", "Heures Utilisees"),
    num("kilometres_utilises", "Kilometres Utilises", "Kilometres Utilises"),
    txt("statut", "Statut", "Statut"),
    num("asset_id_actuel", "Asset Id Actuel", "Asset Id Actuel"),
    num("composant_id_actuel", "Composant Id Actuel", "Composant Id Actuel"),
    txt("emplacement_stock", "Emplacement Stock", "Emplacement Stock"),
    num("fournisseur_id", "Fournisseur Id", "Fournisseur Id"),
    txt("numero_bl_achat", "Numero Bl  Achat", "Numero Bl Achat"),
    txt("numero_facture_achat", "Numero Facture  Achat", "Numero Facture Achat"),
    dt("date_garantie_fin", "Date Garantie Fin", "Date Garantie Fin"),
    num("valeur_achat_xaf", "Valeur Achat Xaf", "Valeur Achat Xaf"),
    area("hashs_certificat", "Hashs Certificat", "Hashs Certificat"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreInventory: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "inventory",
  tcode: "registre-inventory",
  icon: Icons.Boxes,
  titre: "Stock piece",
  titreEn: "Part inventory",
  description: "Quantite disponible par piece/magasin/emplacement.",
  descriptionEn: "On-hand qty per part/location.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("inventory", params),
  creer: (data) => api.creer("inventory", data),
  modifier: (id, data) => api.modifier("inventory", id, data),
  unicite: "part_id",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("part_id", "Part Id", "Part Id"),
    col("magasin_id", "Magasin Id", "Magasin Id"),
    col("emplacement", "Emplacement", "Emplacement"),
    col("quantite_en_stock", "Quantite En Stock", "Quantite En Stock"),
    col("quantite_reservee", "Quantite Reservee", "Quantite Reservee"),
    col("quantite_min", "Quantite Min", "Quantite Min"),
    col("quantite_max", "Quantite Max", "Quantite Max"),
    col("point_commande", "Point Commande", "Point Commande"),
    col("cout_moyen_pondere_xaf", "Cout Moyen Pondere Xaf", "Cout Moyen Pondere Xaf"),
    col("valeur_totale_xaf", "Valeur Totale Xaf", "Valeur Totale Xaf"),
    col("date_dernier_mouvement", "Date Dernier Mouvement", "Date Dernier Mouvement"),
    col("date_dernier_inventaire", "Date Dernier Inventaire", "Date Dernier Inventaire"),
  ],
  champs: [
    num("part_id", "Part Id", "Part Id", { requisCreation: true }),
    num("magasin_id", "Magasin Id", "Magasin Id"),
    txt("emplacement", "Emplacement", "Emplacement"),
    num("quantite_en_stock", "Quantite En Stock", "Quantite En Stock"),
    num("quantite_reservee", "Quantite Reservee", "Quantite Reservee"),
    num("quantite_min", "Quantite Min", "Quantite Min"),
    num("quantite_max", "Quantite Max", "Quantite Max"),
    num("point_commande", "Point Commande", "Point Commande"),
    num("cout_moyen_pondere_xaf", "Cout Moyen Pondere Xaf", "Cout Moyen Pondere Xaf"),
    num("valeur_totale_xaf", "Valeur Totale Xaf", "Valeur Totale Xaf"),
    dtx("date_dernier_mouvement", "Date Dernier Mouvement", "Date Dernier Mouvement"),
    dt("date_dernier_inventaire", "Date Dernier Inventaire", "Date Dernier Inventaire"),
  ],
};


export const registreMovement: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "movements",
  tcode: "registre-movements",
  icon: Icons.ArrowLeftRight,
  titre: "Mouvement de piece",
  titreEn: "Part movement",
  description: "Entree/sortie/transfert/ajustement de stock.",
  descriptionEn: "In/out/transfer/adjust of stock.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("movements", params),
  creer: (data) => api.creer("movements", data),
  modifier: (id, data) => api.modifier("movements", id, data),
  unicite: "reference_mouvement",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_mouvement", "Reference Mouvement", "Reference Mouvement"),
    col("part_id", "Part Id", "Part Id"),
    col("serialized_part_id", "Serialized Part Id", "Serialized Part Id"),
    col("type_mouvement", "Type Mouvement", "Type Mouvement"),
    col("quantite", "Quantite", "Quantite"),
    col("magasin_source_id", "Magasin Source Id", "Magasin Source Id"),
    col("magasin_destination_id", "Magasin Destination Id", "Magasin Destination Id"),
    col("work_order_id", "Work Order Id", "Work Order Id"),
    col("bon_livraison_id", "Bon Livraison Id", "Bon Livraison Id"),
    col("facture_achat_id", "Facture Achat Id", "Facture Achat Id"),
    col("user_id", "User Id", "User Id"),
    col("date_mouvement", "Date Mouvement", "Date Mouvement"),
    col("valeur_xaf", "Valeur Xaf", "Valeur Xaf"),
    col("motif", "Motif", "Motif"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("reference_mouvement", "Reference Mouvement", "Reference Mouvement", { requisCreation: true }),
    num("part_id", "Part Id", "Part Id"),
    num("serialized_part_id", "Serialized Part Id", "Serialized Part Id"),
    txt("type_mouvement", "Type Mouvement", "Type Mouvement"),
    num("quantite", "Quantite", "Quantite"),
    num("magasin_source_id", "Magasin Source Id", "Magasin Source Id"),
    num("magasin_destination_id", "Magasin Destination Id", "Magasin Destination Id"),
    num("work_order_id", "Work Order Id", "Work Order Id"),
    num("bon_livraison_id", "Bon Livraison Id", "Bon Livraison Id"),
    num("facture_achat_id", "Facture Achat Id", "Facture Achat Id"),
    num("user_id", "User Id", "User Id"),
    dtx("date_mouvement", "Date Mouvement", "Date Mouvement"),
    num("valeur_xaf", "Valeur Xaf", "Valeur Xaf"),
    txt("motif", "Motif", "Motif"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreFailureMode: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "failure_modes",
  tcode: "registre-failure-modes",
  icon: Icons.AlertTriangle,
  titre: "Mode de defaillance (FMEA)",
  titreEn: "Failure mode (FMEA)",
  description: "Analyse gravite x occurrence x detection (IPR).",
  descriptionEn: "Severity x occurrence x detection (RPN).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("failure-modes", params),
  creer: (data) => api.creer("failure-modes", data),
  modifier: (id, data) => api.modifier("failure-modes", id, data),
  unicite: "code_fmea",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_fmea", "Code Fmea", "Code Fmea"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("fonction", "Fonction", "Fonction"),
    col("mode_defaillance", "Mode Defaillance", "Mode Defaillance"),
    col("mecanisme", "Mecanisme", "Mecanisme"),
    col("causes", "Causes", "Causes"),
    col("effets", "Effets", "Effets"),
    col("gravite", "Gravite", "Gravite"),
    col("occurrence", "Occurrence", "Occurrence"),
    col("detection", "Detection", "Detection"),
    col("ipr", "Ipr", "Ipr"),
    col("methode_detection", "Methode Detection", "Methode Detection"),
    col("actions_preventives", "Actions Preventives", "Actions Preventives"),
    col("actions_correctives", "Actions Correctives", "Actions Correctives"),
    col("responsable", "Responsable", "Responsable"),
    col("date_evaluation", "Date Evaluation", "Date Evaluation"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("code_fmea", "Code Fmea", "Code Fmea", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    txt("fonction", "Fonction", "Fonction"),
    txt("mode_defaillance", "Mode Defaillance", "Mode Defaillance"),
    txt("mecanisme", "Mecanisme", "Mecanisme"),
    area("causes", "Causes", "Causes"),
    area("effets", "Effets", "Effets"),
    num("gravite", "Gravite", "Gravite"),
    num("occurrence", "Occurrence", "Occurrence"),
    num("detection", "Detection", "Detection"),
    num("ipr", "Ipr", "Ipr"),
    txt("methode_detection", "Methode Detection", "Methode Detection"),
    area("actions_preventives", "Actions Preventives", "Actions Preventives"),
    area("actions_correctives", "Actions Correctives", "Actions Correctives"),
    txt("responsable", "Responsable", "Responsable"),
    dt("date_evaluation", "Date Evaluation", "Date Evaluation"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registrePlan: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "plans",
  tcode: "registre-plans",
  icon: Icons.Calendar,
  titre: "Plan de maintenance",
  titreEn: "Maintenance plan",
  description: "Plan preventif (periodique, heures, km, condition).",
  descriptionEn: "Preventive plan (calendar, hours, km, condition).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("plans", params),
  creer: (data) => api.creer("plans", data),
  modifier: (id, data) => api.modifier("plans", id, data),
  unicite: "code_plan",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_plan", "Code Plan", "Code Plan"),
    col("nom", "Nom", "Nom"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("type_plan", "Type Plan", "Type Plan"),
    col("frequence_type", "Frequence Type", "Frequence Type"),
    col("frequence_valeur", "Frequence Valeur", "Frequence Valeur"),
    col("frequence_unite", "Frequence Unite", "Frequence Unite"),
    col("seuil_declenchement", "Seuil Declenchement", "Seuil Declenchement"),
    col("prochaine_echeance", "Prochaine Echeance", "Prochaine Echeance"),
    col("duree_estimee_h", "Duree Estimee H", "Duree Estimee H"),
    col("criticite", "Criticite", "Criticite"),
    col("cout_estime_par_cycle_xaf", "Cout Estime Par Cycle Xaf", "Cout Estime Par Cycle Xaf"),
    col("skills_requis", "Skills Requis", "Skills Requis"),
    col("outillage_requis", "Outillage Requis", "Outillage Requis"),
    col("pieces_cle", "Pieces Cle", "Pieces Cle"),
    col("version", "Version", "Version"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("code_plan", "Code Plan", "Code Plan", { requisCreation: true }),
    txt("nom", "Nom", "Nom"),
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    txt("type_plan", "Type Plan", "Type Plan"),
    txt("frequence_type", "Frequence Type", "Frequence Type"),
    num("frequence_valeur", "Frequence Valeur", "Frequence Valeur"),
    txt("frequence_unite", "Frequence Unite", "Frequence Unite"),
    txt("seuil_declenchement", "Seuil Declenchement", "Seuil Declenchement"),
    dt("prochaine_echeance", "Prochaine Echeance", "Prochaine Echeance"),
    num("duree_estimee_h", "Duree Estimee H", "Duree Estimee H"),
    txt("criticite", "Criticite", "Criticite"),
    num("cout_estime_par_cycle_xaf", "Cout Estime Par Cycle Xaf", "Cout Estime Par Cycle Xaf"),
    txt("skills_requis", "Skills Requis", "Skills Requis"),
    area("outillage_requis", "Outillage Requis", "Outillage Requis"),
    area("pieces_cle", "Pieces Cle", "Pieces Cle"),
    num("version", "Version", "Version"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreTask: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "tasks",
  tcode: "registre-tasks",
  icon: Icons.ListChecks,
  titre: "Tache de maintenance",
  titreEn: "Maintenance task",
  description: "Pas operatoire d'un plan (gammes, duree, competences).",
  descriptionEn: "Operational step of a plan (range, duration, skills).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("tasks", params),
  creer: (data) => api.creer("tasks", data),
  modifier: (id, data) => api.modifier("tasks", id, data),
  unicite: "code_tache",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_tache", "Code Tache", "Code Tache"),
    col("plan_id", "Plan Id", "Plan Id"),
    col("titre", "Titre", "Titre"),
    col("description_geste", "Description Geste", "Description Geste"),
    col("duree_estimee_min", "Duree Estimee Min", "Duree Estimee Min"),
    col("nb_techniciens", "Nb Techniciens", "Nb Techniciens"),
    col("competence_requise", "Competence Requise", "Competence Requise"),
    col("niveau_habiliture", "Niveau Habiliture", "Niveau Habiliture"),
    col("epi_requis", "Epi Requis", "Epi Requis"),
    col("outillage", "Outillage", "Outillage"),
    col("couples_re_serrage", "Couples Re Serrage", "Couples Re Serrage"),
    col("pieces_requises", "Pieces Requises", "Pieces Requises"),
    col("ordre_execution", "Ordre Execution", "Ordre Execution"),
  ],
  champs: [
    txt("code_tache", "Code Tache", "Code Tache", { requisCreation: true }),
    num("plan_id", "Plan Id", "Plan Id"),
    txt("titre", "Titre", "Titre"),
    area("description_geste", "Description Geste", "Description Geste"),
    num("duree_estimee_min", "Duree Estimee Min", "Duree Estimee Min"),
    num("nb_techniciens", "Nb Techniciens", "Nb Techniciens"),
    txt("competence_requise", "Competence Requise", "Competence Requise"),
    txt("niveau_habiliture", "Niveau Habiliture", "Niveau Habiliture"),
    txt("epi_requis", "Epi Requis", "Epi Requis"),
    area("outillage", "Outillage", "Outillage"),
    txt("couples_re_serrage", "Couples Re Serrage", "Couples Re Serrage"),
    area("pieces_requises", "Pieces Requises", "Pieces Requises"),
    num("ordre_execution", "Ordre Execution", "Ordre Execution"),
  ],
};


export const registreWorkOrder: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "work_orders",
  tcode: "registre-work-orders",
  icon: Icons.ClipboardList,
  titre: "Ordre de travail",
  titreEn: "Work order",
  description: "OT preventif/correctif/amelioratif avec couts et ressources.",
  descriptionEn: "Preventive/corrective/improvement WO with costs & resources.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("work-orders", params),
  creer: (data) => api.creer("work-orders", data),
  modifier: (id, data) => api.modifier("work-orders", id, data),
  unicite: "numero_ot",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("numero_ot", "Numero Ot", "Numero Ot"),
    col("type_ot", "Type Ot", "Type Ot"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("plan_id", "Plan Id", "Plan Id"),
    col("defaillance_id", "Defaillance Id", "Defaillance Id"),
    col("titre", "Titre", "Titre"),
    col("description", "Description", "Description"),
    col("priorite", "Priorite", "Priorite"),
    col("criticite_asset", "Criticite Asset", "Criticite Asset"),
    col("date_detection", "Date Detection", "Date Detection"),
    col("date_ouverture", "Date Ouverture", "Date Ouverture"),
    col("date_prevue_debut", "Date Prevue Debut", "Date Prevue Debut"),
    col("date_prevue_fin", "Date Prevue Fin", "Date Prevue Fin"),
    col("date_reel_debut", "Date Reel Debut", "Date Reel Debut"),
    col("date_reel_fin", "Date Reel Fin", "Date Reel Fin"),
    col("statut", "Statut", "Statut"),
    col("technicien_principal_id", "Technicien Principal Id", "Technicien Principal Id"),
    col("prestataire_id", "Prestataire Id", "Prestataire Id"),
    col("heures_prevues", "Heures Prevues", "Heures Prevues"),
    col("heures_reelles", "Heures Reelles", "Heures Reelles"),
    col("cout_pieces_xaf", "Cout Pieces Xaf", "Cout Pieces Xaf"),
    col("cout_main_oeuvre_xaf", "Cout Main Oeuvre Xaf", "Cout Main Oeuvre Xaf"),
    col("cout_prestataire_xaf", "Cout Prestataire Xaf", "Cout Prestataire Xaf"),
    col("cout_total_xaf", "Cout Total Xaf", "Cout Total Xaf"),
    col("cause_racine_id", "Cause Racine Id", "Cause Racine Id"),
    col("arret_production", "Arret Production", "Arret Production"),
    col("impact_securite", "Impact Securite", "Impact Securite"),
    col("compte_rendu", "Compte Rendu", "Compte Rendu"),
    col("pieces_ressorties", "Pieces Ressorties", "Pieces Ressorties"),
    col("photos_url", "Photos Url", "Photos Url"),
  ],
  champs: [
    txt("numero_ot", "Numero Ot", "Numero Ot", { requisCreation: true }),
    txt("type_ot", "Type Ot", "Type Ot"),
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    num("plan_id", "Plan Id", "Plan Id"),
    num("defaillance_id", "Defaillance Id", "Defaillance Id"),
    txt("titre", "Titre", "Titre"),
    area("description", "Description", "Description"),
    txt("priorite", "Priorite", "Priorite"),
    txt("criticite_asset", "Criticite Asset", "Criticite Asset"),
    dtx("date_detection", "Date Detection", "Date Detection"),
    dtx("date_ouverture", "Date Ouverture", "Date Ouverture"),
    dtx("date_prevue_debut", "Date Prevue Debut", "Date Prevue Debut"),
    dtx("date_prevue_fin", "Date Prevue Fin", "Date Prevue Fin"),
    dtx("date_reel_debut", "Date Reel Debut", "Date Reel Debut"),
    dtx("date_reel_fin", "Date Reel Fin", "Date Reel Fin"),
    txt("statut", "Statut", "Statut"),
    num("technicien_principal_id", "Technicien Principal Id", "Technicien Principal Id"),
    num("prestataire_id", "Prestataire Id", "Prestataire Id"),
    num("heures_prevues", "Heures Prevues", "Heures Prevues"),
    num("heures_reelles", "Heures Reelles", "Heures Reelles"),
    num("cout_pieces_xaf", "Cout Pieces Xaf", "Cout Pieces Xaf"),
    num("cout_main_oeuvre_xaf", "Cout Main Oeuvre Xaf", "Cout Main Oeuvre Xaf"),
    num("cout_prestataire_xaf", "Cout Prestataire Xaf", "Cout Prestataire Xaf"),
    num("cout_total_xaf", "Cout Total Xaf", "Cout Total Xaf"),
    num("cause_racine_id", "Cause Racine Id", "Cause Racine Id"),
    chk("arret_production", "Arret Production", "Arret Production"),
    chk("impact_securite", "Impact Securite", "Impact Securite"),
    area("compte_rendu", "Compte Rendu", "Compte Rendu"),
    area("pieces_ressorties", "Pieces Ressorties", "Pieces Ressorties"),
    area("photos_url", "Photos Url", "Photos Url"),
  ],
};


export const registreAssetFailure: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "asset_failures",
  tcode: "registre-asset-failures",
  icon: Icons.AlertOctagon,
  titre: "Panne actif",
  titreEn: "Asset failure",
  description: "Declaration de panne/dysfonctionnement sur un actif.",
  descriptionEn: "Breakdown reported on an asset.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("asset-failures", params),
  creer: (data) => api.creer("asset-failures", data),
  modifier: (id, data) => api.modifier("asset-failures", id, data),
  unicite: "reference_defaillance",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_defaillance", "Reference Defaillance", "Reference Defaillance"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("mode_id", "Mode Id", "Mode Id"),
    col("date_detection", "Date Detection", "Date Detection"),
    col("detecteur", "Detecteur", "Detecteur"),
    col("source_signalement", "Source Signalement", "Source Signalement"),
    col("severite", "Severite", "Severite"),
    col("description", "Description", "Description"),
    col("symptomes", "Symptomes", "Symptomes"),
    col("code_defaut", "Code Defaut", "Code Defaut"),
    col("heures_arret", "Heures Arret", "Heures Arret"),
    col("cout_indirect_xaf", "Cout Indirect Xaf", "Cout Indirect Xaf"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_defaillance", "Reference Defaillance", "Reference Defaillance", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    num("mode_id", "Mode Id", "Mode Id"),
    dtx("date_detection", "Date Detection", "Date Detection"),
    txt("detecteur", "Detecteur", "Detecteur"),
    txt("source_signalement", "Source Signalement", "Source Signalement"),
    txt("severite", "Severite", "Severite"),
    area("description", "Description", "Description"),
    area("symptomes", "Symptomes", "Symptomes"),
    txt("code_defaut", "Code Defaut", "Code Defaut"),
    num("heures_arret", "Heures Arret", "Heures Arret"),
    num("cout_indirect_xaf", "Cout Indirect Xaf", "Cout Indirect Xaf"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreWoPart: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "wo_parts",
  tcode: "registre-wo-parts",
  icon: Icons.Package,
  titre: "OT - pieces",
  titreEn: "WO parts",
  description: "Consommables affectes a un ordre de travail.",
  descriptionEn: "Consumables issued to a work order.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("wo-parts", params),
  creer: (data) => api.creer("wo-parts", data),
  modifier: (id, data) => api.modifier("wo-parts", id, data),
  unicite: "work_order_id",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("work_order_id", "Work Order Id", "Work Order Id"),
    col("part_id", "Part Id", "Part Id"),
    col("serialized_part_id", "Serialized Part Id", "Serialized Part Id"),
    col("quantite_demandee", "Quantite Demandee", "Quantite Demandee"),
    col("quantite_livree", "Quantite Livree", "Quantite Livree"),
    col("quantite_consommee", "Quantite Consommee", "Quantite Consommee"),
    col("quantite_retour", "Quantite Retour", "Quantite Retour"),
    col("valeur_xaf", "Valeur Xaf", "Valeur Xaf"),
    col("date_sortie", "Date Sortie", "Date Sortie"),
    col("motif_retour", "Motif Retour", "Motif Retour"),
    col("magasin_id", "Magasin Id", "Magasin Id"),
  ],
  champs: [
    num("work_order_id", "Work Order Id", "Work Order Id", { requisCreation: true }),
    num("part_id", "Part Id", "Part Id"),
    num("serialized_part_id", "Serialized Part Id", "Serialized Part Id"),
    num("quantite_demandee", "Quantite Demandee", "Quantite Demandee"),
    num("quantite_livree", "Quantite Livree", "Quantite Livree"),
    num("quantite_consommee", "Quantite Consommee", "Quantite Consommee"),
    num("quantite_retour", "Quantite Retour", "Quantite Retour"),
    num("valeur_xaf", "Valeur Xaf", "Valeur Xaf"),
    dtx("date_sortie", "Date Sortie", "Date Sortie"),
    txt("motif_retour", "Motif Retour", "Motif Retour"),
    num("magasin_id", "Magasin Id", "Magasin Id"),
  ],
};


export const registreWoLabour: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "wo_labours",
  tcode: "registre-wo-labours",
  icon: Icons.Users,
  titre: "OT - main d'oeuvre",
  titreEn: "WO labour",
  description: "Temps technicien impute a un OT.",
  descriptionEn: "Technician time charged to a WO.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("wo-labours", params),
  creer: (data) => api.creer("wo-labours", data),
  modifier: (id, data) => api.modifier("wo-labours", id, data),
  unicite: "work_order_id",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("work_order_id", "Work Order Id", "Work Order Id"),
    col("user_id", "User Id", "User Id"),
    col("role_intervenant", "Role Intervenant", "Role Intervenant"),
    col("date_travail", "Date Travail", "Date Travail"),
    col("heures_prevues", "Heures Prevues", "Heures Prevues"),
    col("heures_reelles", "Heures Reelles", "Heures Reelles"),
    col("taux_horaire_xaf", "Taux Horaire Xaf", "Taux Horaire Xaf"),
    col("cout_total_xaf", "Cout Total Xaf", "Cout Total Xaf"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("work_order_id", "Work Order Id", "Work Order Id", { requisCreation: true }),
    num("user_id", "User Id", "User Id"),
    txt("role_intervenant", "Role Intervenant", "Role Intervenant"),
    dt("date_travail", "Date Travail", "Date Travail"),
    num("heures_prevues", "Heures Prevues", "Heures Prevues"),
    num("heures_reelles", "Heures Reelles", "Heures Reelles"),
    num("taux_horaire_xaf", "Taux Horaire Xaf", "Taux Horaire Xaf"),
    num("cout_total_xaf", "Cout Total Xaf", "Cout Total Xaf"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreWoTool: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "wo_tools",
  tcode: "registre-wo-tools",
  icon: Icons.Wrench,
  titre: "OT - outillage",
  titreEn: "WO tools",
  description: "Outillage mobilise pour un OT.",
  descriptionEn: "Tooling mobilized for a WO.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("wo-tools", params),
  creer: (data) => api.creer("wo-tools", data),
  modifier: (id, data) => api.modifier("wo-tools", id, data),
  unicite: "work_order_id",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("work_order_id", "Work Order Id", "Work Order Id"),
    col("reference_outillage", "Reference Outillage", "Reference Outillage"),
    col("designation", "Designation", "Designation"),
    col("type_outillage", "Type Outillage", "Type Outillage"),
    col("proprietaire", "Proprietaire", "Proprietaire"),
    col("numero_inventaire", "Numero Inventaire", "Numero Inventaire"),
    col("date_pret_debut", "Date Pret Debut", "Date Pret Debut"),
    col("date_pret_fin", "Date Pret Fin", "Date Pret Fin"),
    col("date_calibration", "Date Calibration", "Date Calibration"),
    col("cout_location_xaf", "Cout Location Xaf", "Cout Location Xaf"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("work_order_id", "Work Order Id", "Work Order Id", { requisCreation: true }),
    txt("reference_outillage", "Reference Outillage", "Reference Outillage"),
    txt("designation", "Designation", "Designation"),
    txt("type_outillage", "Type Outillage", "Type Outillage"),
    txt("proprietaire", "Proprietaire", "Proprietaire"),
    txt("numero_inventaire", "Numero Inventaire", "Numero Inventaire"),
    dt("date_pret_debut", "Date Pret Debut", "Date Pret Debut"),
    dt("date_pret_fin", "Date Pret Fin", "Date Pret Fin"),
    dt("date_calibration", "Date Calibration", "Date Calibration"),
    num("cout_location_xaf", "Cout Location Xaf", "Cout Location Xaf"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreRca: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "root_causes",
  tcode: "registre-root-causes",
  icon: Icons.Search,
  titre: "Analyse cause racine",
  titreEn: "Root cause analysis",
  description: "5 Pourquoi / Ishikawa / arbre des causes.",
  descriptionEn: "5 Why / Ishikawa / cause tree.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("root-causes", params),
  creer: (data) => api.creer("root-causes", data),
  modifier: (id, data) => api.modifier("root-causes", id, data),
  unicite: "reference_rca",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_rca", "Reference Rca", "Reference Rca"),
    col("work_order_id", "Work Order Id", "Work Order Id"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("methode", "Methode", "Methode"),
    col("probleme", "Probleme", "Probleme"),
    col("pourquoi_1", "Pourquoi 1", "Pourquoi 1"),
    col("pourquoi_2", "Pourquoi 2", "Pourquoi 2"),
    col("pourquoi_3", "Pourquoi 3", "Pourquoi 3"),
    col("pourquoi_4", "Pourquoi 4", "Pourquoi 4"),
    col("pourquoi_5", "Pourquoi 5", "Pourquoi 5"),
    col("categories_ishikawa", "Categories Ishikawa", "Categories Ishikawa"),
    col("cause_racine", "Cause Racine", "Cause Racine"),
    col("causes_contributives", "Causes Contributives", "Causes Contributives"),
    col("actions_correctives", "Actions Correctives", "Actions Correctives"),
    col("actions_preventives_globales", "Actions Preventives Globales", "Actions Preventives Globales"),
    col("responsable_id", "Responsable Id", "Responsable Id"),
    col("date_cloture", "Date Cloture", "Date Cloture"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_rca", "Reference Rca", "Reference Rca", { requisCreation: true }),
    num("work_order_id", "Work Order Id", "Work Order Id"),
    num("asset_id", "Asset Id", "Asset Id"),
    txt("methode", "Methode", "Methode"),
    area("probleme", "Probleme", "Probleme"),
    area("pourquoi_1", "Pourquoi 1", "Pourquoi 1"),
    area("pourquoi_2", "Pourquoi 2", "Pourquoi 2"),
    area("pourquoi_3", "Pourquoi 3", "Pourquoi 3"),
    area("pourquoi_4", "Pourquoi 4", "Pourquoi 4"),
    area("pourquoi_5", "Pourquoi 5", "Pourquoi 5"),
    area("categories_ishikawa", "Categories Ishikawa", "Categories Ishikawa"),
    area("cause_racine", "Cause Racine", "Cause Racine"),
    area("causes_contributives", "Causes Contributives", "Causes Contributives"),
    area("actions_correctives", "Actions Correctives", "Actions Correctives"),
    area("actions_preventives_globales", "Actions Preventives Globales", "Actions Preventives Globales"),
    num("responsable_id", "Responsable Id", "Responsable Id"),
    dt("date_cloture", "Date Cloture", "Date Cloture"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreOverhaul: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "overhauls",
  tcode: "registre-overhauls",
  icon: Icons.Settings,
  titre: "Campagne revision",
  titreEn: "Overhaul campaign",
  description: "Revision majeure / reconditionnement moteur.",
  descriptionEn: "Major overhaul / engine recondition.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("overhauls", params),
  creer: (data) => api.creer("overhauls", data),
  modifier: (id, data) => api.modifier("overhauls", id, data),
  unicite: "code_overhaul",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_overhaul", "Code Overhaul", "Code Overhaul"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("type_overhaul", "Type Overhaul", "Type Overhaul"),
    col("intervalle_heures", "Intervalle Heures", "Intervalle Heures"),
    col("intervalle_km", "Intervalle Km", "Intervalle Km"),
    col("intervalle_mois", "Intervalle Mois", "Intervalle Mois"),
    col("prochaine_echeance_date", "Prochaine Echeance Date", "Prochaine Echeance Date"),
    col("prochaine_echeance_heures", "Prochaine Echeance Heures", "Prochaine Echeance Heures"),
    col("prestataire_id", "Prestataire Id", "Prestataire Id"),
    col("budget_estime_xaf", "Budget Estime Xaf", "Budget Estime Xaf"),
    col("date_debut", "Date Debut", "Date Debut"),
    col("date_fin", "Date Fin", "Date Fin"),
    col("duree_reelle_j", "Duree Reelle J", "Duree Reelle J"),
    col("kits_pieces_utilises", "Kits Pieces Utilises", "Kits Pieces Utilises"),
    col("rapport_technique", "Rapport Technique", "Rapport Technique"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("code_overhaul", "Code Overhaul", "Code Overhaul", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    txt("type_overhaul", "Type Overhaul", "Type Overhaul"),
    num("intervalle_heures", "Intervalle Heures", "Intervalle Heures"),
    num("intervalle_km", "Intervalle Km", "Intervalle Km"),
    num("intervalle_mois", "Intervalle Mois", "Intervalle Mois"),
    dt("prochaine_echeance_date", "Prochaine Echeance Date", "Prochaine Echeance Date"),
    num("prochaine_echeance_heures", "Prochaine Echeance Heures", "Prochaine Echeance Heures"),
    num("prestataire_id", "Prestataire Id", "Prestataire Id"),
    num("budget_estime_xaf", "Budget Estime Xaf", "Budget Estime Xaf"),
    dt("date_debut", "Date Debut", "Date Debut"),
    dt("date_fin", "Date Fin", "Date Fin"),
    num("duree_reelle_j", "Duree Reelle J", "Duree Reelle J"),
    area("kits_pieces_utilises", "Kits Pieces Utilises", "Kits Pieces Utilises"),
    area("rapport_technique", "Rapport Technique", "Rapport Technique"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreLubrication: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "lubrication",
  tcode: "registre-lubrication",
  icon: Icons.Droplet,
  titre: "Plaine graissage",
  titreEn: "Lubrication schedule",
  description: "Points, lubrifiants, frequences et quantites.",
  descriptionEn: "Points, lubricants, frequencies and quantities.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("lubrication", params),
  creer: (data) => api.creer("lubrication", data),
  modifier: (id, data) => api.modifier("lubrication", id, data),
  unicite: "point_lubrifiant",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("point_lubrifiant", "Point Lubrifiant", "Point Lubrifiant"),
    col("type_lubrifiant", "Type Lubrifiant", "Type Lubrifiant"),
    col("grade", "Grade", "Grade"),
    col("marque", "Marque", "Marque"),
    col("quantite_litre", "Quantite Litre", "Quantite Litre"),
    col("quantite_gramme", "Quantite Gramme", "Quantite Gramme"),
    col("frequence_heures", "Frequence Heures", "Frequence Heures"),
    col("frequence_jours", "Frequence Jours", "Frequence Jours"),
    col("prochaine_date", "Prochaine Date", "Prochaine Date"),
    col("methode", "Methode", "Methode"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    txt("point_lubrifiant", "Point Lubrifiant", "Point Lubrifiant", { requisCreation: true }),
    txt("type_lubrifiant", "Type Lubrifiant", "Type Lubrifiant"),
    txt("grade", "Grade", "Grade"),
    txt("marque", "Marque", "Marque"),
    num("quantite_litre", "Quantite Litre", "Quantite Litre"),
    num("quantite_gramme", "Quantite Gramme", "Quantite Gramme"),
    num("frequence_heures", "Frequence Heures", "Frequence Heures"),
    num("frequence_jours", "Frequence Jours", "Frequence Jours"),
    dt("prochaine_date", "Prochaine Date", "Prochaine Date"),
    txt("methode", "Methode", "Methode"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreConditionReading: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "condition_readings",
  tcode: "registre-condition-readings",
  icon: Icons.Activity,
  titre: "Releve condition",
  titreEn: "Condition reading",
  description: "Vibration / thermo / huile / ultrason.",
  descriptionEn: "Vibration / thermal / oil / ultrasound.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("condition-readings", params),
  creer: (data) => api.creer("condition-readings", data),
  modifier: (id, data) => api.modifier("condition-readings", id, data),
  unicite: "reference_lecture",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_lecture", "Reference Lecture", "Reference Lecture"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("component_id", "Component Id", "Component Id"),
    col("type_technique", "Type Technique", "Type Technique"),
    col("capteur_id", "Capteur Id", "Capteur Id"),
    col("point_mesure", "Point Mesure", "Point Mesure"),
    col("date_lecture", "Date Lecture", "Date Lecture"),
    col("valeur_principale", "Valeur Principale", "Valeur Principale"),
    col("unite", "Unite", "Unite"),
    col("seuil_alerte", "Seuil Alerte", "Seuil Alerte"),
    col("seuil_critical", "Seuil Critical", "Seuil Critical"),
    col("statut_resultat", "Statut Resultat", "Statut Resultat"),
    col("spectre_url", "Spectre Url", "Spectre Url"),
    col("analyse_experte", "Analyse Experte", "Analyse Experte"),
    col("operateur", "Operateur", "Operateur"),
  ],
  champs: [
    txt("reference_lecture", "Reference Lecture", "Reference Lecture", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    num("component_id", "Component Id", "Component Id"),
    txt("type_technique", "Type Technique", "Type Technique"),
    num("capteur_id", "Capteur Id", "Capteur Id"),
    txt("point_mesure", "Point Mesure", "Point Mesure"),
    dtx("date_lecture", "Date Lecture", "Date Lecture"),
    num("valeur_principale", "Valeur Principale", "Valeur Principale"),
    txt("unite", "Unite", "Unite"),
    num("seuil_alerte", "Seuil Alerte", "Seuil Alerte"),
    num("seuil_critical", "Seuil Critical", "Seuil Critical"),
    txt("statut_resultat", "Statut Resultat", "Statut Resultat"),
    txt("spectre_url", "Spectre Url", "Spectre Url"),
    area("analyse_experte", "Analyse Experte", "Analyse Experte"),
    txt("operateur", "Operateur", "Operateur"),
  ],
};


export const registreSensor: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "sensors",
  tcode: "registre-sensors",
  icon: Icons.Radio,
  titre: "Capteur IoT",
  titreEn: "IoT sensor",
  description: "Capteur connecte (type, pas, calibration).",
  descriptionEn: "Connected sensor (type, step, calibration).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("sensors", params),
  creer: (data) => api.creer("sensors", data),
  modifier: (id, data) => api.modifier("sensors", id, data),
  unicite: "code_capteur",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_capteur", "Code Capteur", "Code Capteur"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("composant_id", "Composant Id", "Composant Id"),
    col("type_capteur", "Type Capteur", "Type Capteur"),
    col("protocol", "Protocol", "Protocol"),
    col("adresse_mqtt", "Adresse Mqtt", "Adresse Mqtt"),
    col("url_flux", "Url Flux", "Url Flux"),
    col("frequence_echantillonnage_hz", "Frequence Echantillonnage Hz", "Frequence Echantillonnage Hz"),
    col("resolution_bits", "Resolution Bits", "Resolution Bits"),
    col("unite_sortie", "Unite Sortie", "Unite Sortie"),
    col("plage_min", "Plage Min", "Plage Min"),
    col("plage_max", "Plage Max", "Plage Max"),
    col("seuil_alerte_bas", "Seuil Alerte Bas", "Seuil Alerte Bas"),
    col("seuil_alerte_haut", "Seuil Alerte Haut", "Seuil Alerte Haut"),
    col("calibration_periodicite_mois", "Calibration Periodicite Mois", "Calibration Periodicite Mois"),
    col("derniere_calibration", "Derniere Calibration", "Derniere Calibration"),
    col("fabricant", "Fabricant", "Fabricant"),
    col("modele", "Modele", "Modele"),
    col("numero_serie", "Numero Serie", "Numero Serie"),
    col("statut", "Statut", "Statut"),
    col("date_installation", "Date Installation", "Date Installation"),
  ],
  champs: [
    txt("code_capteur", "Code Capteur", "Code Capteur", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    num("composant_id", "Composant Id", "Composant Id"),
    txt("type_capteur", "Type Capteur", "Type Capteur"),
    txt("protocol", "Protocol", "Protocol"),
    txt("adresse_mqtt", "Adresse Mqtt", "Adresse Mqtt"),
    txt("url_flux", "Url Flux", "Url Flux"),
    num("frequence_echantillonnage_hz", "Frequence Echantillonnage Hz", "Frequence Echantillonnage Hz"),
    num("resolution_bits", "Resolution Bits", "Resolution Bits"),
    txt("unite_sortie", "Unite Sortie", "Unite Sortie"),
    num("plage_min", "Plage Min", "Plage Min"),
    num("plage_max", "Plage Max", "Plage Max"),
    num("seuil_alerte_bas", "Seuil Alerte Bas", "Seuil Alerte Bas"),
    num("seuil_alerte_haut", "Seuil Alerte Haut", "Seuil Alerte Haut"),
    num("calibration_periodicite_mois", "Calibration Periodicite Mois", "Calibration Periodicite Mois"),
    dt("derniere_calibration", "Derniere Calibration", "Derniere Calibration"),
    txt("fabricant", "Fabricant", "Fabricant"),
    txt("modele", "Modele", "Modele"),
    txt("numero_serie", "Numero Serie", "Numero Serie"),
    txt("statut", "Statut", "Statut"),
    dt("date_installation", "Date Installation", "Date Installation"),
  ],
};


export const registrePredictiveModel: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "predictive_models",
  tcode: "registre-predictive-models",
  icon: Icons.Brain,
  titre: "Modele predictif",
  titreEn: "Predictive model",
  description: "Algorithme PdM (seuil, horizon, confiance).",
  descriptionEn: "PdM algorithm (threshold, horizon, confidence).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("predictive-models", params),
  creer: (data) => api.creer("predictive-models", data),
  modifier: (id, data) => api.modifier("predictive-models", id, data),
  unicite: "code_modele",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_modele", "Code Modele", "Code Modele"),
    col("nom", "Nom", "Nom"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("composant_id", "Composant Id", "Composant Id"),
    col("type_modele", "Type Modele", "Type Modele"),
    col("variable_entree", "Variable Entree", "Variable Entree"),
    col("variable_sortie", "Variable Sortie", "Variable Sortie"),
    col("heuristique", "Heuristique", "Heuristique"),
    col("precision_pct", "Precision Pct", "Precision Pct"),
    col("rappel_pct", "Rappel Pct", "Rappel Pct"),
    col("auc", "Auc", "Auc"),
    col("version", "Version", "Version"),
    col("date_entrainement", "Date Entrainement", "Date Entrainement"),
    col("date_debut_production", "Date Debut Production", "Date Debut Production"),
    col("seuil_declenchement_ot", "Seuil Declenchement Ot", "Seuil Declenchement Ot"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("code_modele", "Code Modele", "Code Modele", { requisCreation: true }),
    txt("nom", "Nom", "Nom"),
    num("asset_id", "Asset Id", "Asset Id"),
    num("composant_id", "Composant Id", "Composant Id"),
    txt("type_modele", "Type Modele", "Type Modele"),
    txt("variable_entree", "Variable Entree", "Variable Entree"),
    txt("variable_sortie", "Variable Sortie", "Variable Sortie"),
    area("heuristique", "Heuristique", "Heuristique"),
    num("precision_pct", "Precision Pct", "Precision Pct"),
    num("rappel_pct", "Rappel Pct", "Rappel Pct"),
    num("auc", "Auc", "Auc"),
    txt("version", "Version", "Version"),
    dt("date_entrainement", "Date Entrainement", "Date Entrainement"),
    dt("date_debut_production", "Date Debut Production", "Date Debut Production"),
    num("seuil_declenchement_ot", "Seuil Declenchement Ot", "Seuil Declenchement Ot"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreReliabilityKpi: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "reliability_kpis",
  tcode: "registre-reliability-kpis",
  icon: Icons.Gauge,
  titre: "KPI fiabilite",
  titreEn: "Reliability KPI",
  description: "MTBF / MTTR / MTTF / disponibilite / TRS.",
  descriptionEn: "MTBF / MTTR / MTTF / availability / OEE.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("reliability-kpis", params),
  creer: (data) => api.creer("reliability-kpis", data),
  modifier: (id, data) => api.modifier("reliability-kpis", id, data),
  unicite: "periode",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("asset_id", "Asset Id", "Asset Id"),
    col("periode", "Periode", "Periode"),
    col("nb_defaillances", "Nb Defaillances", "Nb Defaillances"),
    col("nb_ot_preventif", "Nb Ot Preventif", "Nb Ot Preventif"),
    col("nb_ot_curatif", "Nb Ot Curatif", "Nb Ot Curatif"),
    col("heures_fonctionnement", "Heures Fonctionnement", "Heures Fonctionnement"),
    col("heures_arret", "Heures Arret", "Heures Arret"),
    col("mtbf_heures", "Mtbf Heures", "Mtbf Heures"),
    col("mttr_heures", "Mttr Heures", "Mttr Heures"),
    col("mttf_heures", "Mttf Heures", "Mttf Heures"),
    col("disponibilite_pct", "Disponibilite Pct", "Disponibilite Pct"),
    col("cout_maintenance_xaf", "Cout Maintenance Xaf", "Cout Maintenance Xaf"),
    col("cout_indirect_arret_xaf", "Cout Indirect Arret Xaf", "Cout Indirect Arret Xaf"),
    col("oee_pct", "Oee Pct", "Oee Pct"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("asset_id", "Asset Id", "Asset Id"),
    txt("periode", "Periode", "Periode", { requisCreation: true }),
    num("nb_defaillances", "Nb Defaillances", "Nb Defaillances"),
    num("nb_ot_preventif", "Nb Ot Preventif", "Nb Ot Preventif"),
    num("nb_ot_curatif", "Nb Ot Curatif", "Nb Ot Curatif"),
    num("heures_fonctionnement", "Heures Fonctionnement", "Heures Fonctionnement"),
    num("heures_arret", "Heures Arret", "Heures Arret"),
    num("mtbf_heures", "Mtbf Heures", "Mtbf Heures"),
    num("mttr_heures", "Mttr Heures", "Mttr Heures"),
    num("mttf_heures", "Mttf Heures", "Mttf Heures"),
    num("disponibilite_pct", "Disponibilite Pct", "Disponibilite Pct"),
    num("cout_maintenance_xaf", "Cout Maintenance Xaf", "Cout Maintenance Xaf"),
    num("cout_indirect_arret_xaf", "Cout Indirect Arret Xaf", "Cout Indirect Arret Xaf"),
    num("oee_pct", "Oee Pct", "Oee Pct"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreInspection: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "inspections",
  tcode: "registre-inspections",
  icon: Icons.FileCheck,
  titre: "Inspection reglementaire",
  titreEn: "Regulatory inspection",
  description: "Controle obligatoire (BV, APAVE, reglementaire).",
  descriptionEn: "Statutory inspection (BV, APAVE).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("inspections", params),
  creer: (data) => api.creer("inspections", data),
  modifier: (id, data) => api.modifier("inspections", id, data),
  unicite: "numero_pv",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("numero_pv", "Numero Pv", "Numero Pv"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("type_controle", "Type Controle", "Type Controle"),
    col("autorite", "Autorite", "Autorite"),
    col("organisme_controle", "Organisme Controle", "Organisme Controle"),
    col("date_controle", "Date Controle", "Date Controle"),
    col("date_validite", "Date Validite", "Date Validite"),
    col("resultat", "Resultat", "Resultat"),
    col("observations", "Observations", "Observations"),
    col("pv_url", "Pv Url", "Pv Url"),
    col("prochaine_echeance", "Prochaine Echeance", "Prochaine Echeance"),
    col("inspecteur", "Inspecteur", "Inspecteur"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("numero_pv", "Numero Pv", "Numero Pv", { requisCreation: true }),
    num("asset_id", "Asset Id", "Asset Id"),
    txt("type_controle", "Type Controle", "Type Controle"),
    txt("autorite", "Autorite", "Autorite"),
    txt("organisme_controle", "Organisme Controle", "Organisme Controle"),
    dt("date_controle", "Date Controle", "Date Controle"),
    dt("date_validite", "Date Validite", "Date Validite"),
    txt("resultat", "Resultat", "Resultat"),
    area("observations", "Observations", "Observations"),
    txt("pv_url", "Pv Url", "Pv Url"),
    dt("prochaine_echeance", "Prochaine Echeance", "Prochaine Echeance"),
    txt("inspecteur", "Inspecteur", "Inspecteur"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreBudget: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "budgets",
  tcode: "registre-budgets",
  icon: Icons.Wallet,
  titre: "Budget maintenance",
  titreEn: "Maintenance budget",
  description: "Budget prevu vs realise par actif/exercice.",
  descriptionEn: "Planned vs actual budget per asset/year.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("budgets", params),
  creer: (data) => api.creer("budgets", data),
  modifier: (id, data) => api.modifier("budgets", id, data),
  unicite: "exercice",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("asset_id", "Asset Id", "Asset Id"),
    col("exercice", "Exercice", "Exercice"),
    col("budget_prevu_pieces_xaf", "Budget Prevu Pieces Xaf", "Budget Prevu Pieces Xaf"),
    col("budget_prevu_main_oeuvre_xaf", "Budget Prevu Main Oeuvre Xaf", "Budget Prevu Main Oeuvre Xaf"),
    col("budget_prevu_prestataire_xaf", "Budget Prevu Prestataire Xaf", "Budget Prevu Prestataire Xaf"),
    col("budget_total_prevu_xaf", "Budget Total Prevu Xaf", "Budget Total Prevu Xaf"),
    col("consomme_pieces_xaf", "Consomme Pieces Xaf", "Consomme Pieces Xaf"),
    col("consomme_main_oeuvre_xaf", "Consomme Main Oeuvre Xaf", "Consomme Main Oeuvre Xaf"),
    col("consomme_prestataire_xaf", "Consomme Prestataire Xaf", "Consomme Prestataire Xaf"),
    col("total_consomme_xaf", "Total Consomme Xaf", "Total Consomme Xaf"),
    col("ecart_pct", "Ecart Pct", "Ecart Pct"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    num("asset_id", "Asset Id", "Asset Id"),
    txt("exercice", "Exercice", "Exercice", { requisCreation: true }),
    num("budget_prevu_pieces_xaf", "Budget Prevu Pieces Xaf", "Budget Prevu Pieces Xaf"),
    num("budget_prevu_main_oeuvre_xaf", "Budget Prevu Main Oeuvre Xaf", "Budget Prevu Main Oeuvre Xaf"),
    num("budget_prevu_prestataire_xaf", "Budget Prevu Prestataire Xaf", "Budget Prevu Prestataire Xaf"),
    num("budget_total_prevu_xaf", "Budget Total Prevu Xaf", "Budget Total Prevu Xaf"),
    num("consomme_pieces_xaf", "Consomme Pieces Xaf", "Consomme Pieces Xaf"),
    num("consomme_main_oeuvre_xaf", "Consomme Main Oeuvre Xaf", "Consomme Main Oeuvre Xaf"),
    num("consomme_prestataire_xaf", "Consomme Prestataire Xaf", "Consomme Prestataire Xaf"),
    num("total_consomme_xaf", "Total Consomme Xaf", "Total Consomme Xaf"),
    num("ecart_pct", "Ecart Pct", "Ecart Pct"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreVendor: ConfigRegistre = {
  permModule: "maintindustrielle",
  permSousModule: "vendors",
  tcode: "registre-vendors",
  icon: Icons.Building,
  titre: "Prestataire maintenance",
  titreEn: "Maintenance vendor",
  description: "Sous-traitant / specialise (contrat, habilitation).",
  descriptionEn: "Subcontractor (contract, accreditation).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("vendors", params),
  creer: (data) => api.creer("vendors", data),
  modifier: (id, data) => api.modifier("vendors", id, data),
  unicite: "code_prestataire",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_prestataire", "Code Prestataire", "Code Prestataire"),
    col("raison_sociale", "Raison Sociale", "Raison Sociale"),
    col("pays", "Pays", "Pays"),
    col("specialites", "Specialites", "Specialites"),
    col("habilitations", "Habilitations", "Habilitations"),
    col("certifications_iso", "Certifications Iso", "Certifications Iso"),
    col("contact_nom", "Contact Nom", "Contact Nom"),
    col("contact_email", "Contact Email", "Contact Email"),
    col("contact_telephone", "Contact Telephone", "Contact Telephone"),
    col("delai_reponse_h", "Delai Reponse H", "Delai Reponse H"),
    col("astreinte_247", "Astreinte 247", "Astreinte 247"),
    col("zone_intervention", "Zone Intervention", "Zone Intervention"),
    col("tarif_horaire_xaf", "Tarif Horaire Xaf", "Tarif Horaire Xaf"),
    col("note_satisfaction", "Note Satisfaction", "Note Satisfaction"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("code_prestataire", "Code Prestataire", "Code Prestataire", { requisCreation: true }),
    txt("raison_sociale", "Raison Sociale", "Raison Sociale"),
    txt("pays", "Pays", "Pays"),
    txt("specialites", "Specialites", "Specialites"),
    area("habilitations", "Habilitations", "Habilitations"),
    txt("certifications_iso", "Certifications Iso", "Certifications Iso"),
    txt("contact_nom", "Contact Nom", "Contact Nom"),
    txt("contact_email", "Contact Email", "Contact Email"),
    txt("contact_telephone", "Contact Telephone", "Contact Telephone"),
    num("delai_reponse_h", "Delai Reponse H", "Delai Reponse H"),
    chk("astreinte_247", "Astreinte 247", "Astreinte 247"),
    txt("zone_intervention", "Zone Intervention", "Zone Intervention"),
    num("tarif_horaire_xaf", "Tarif Horaire Xaf", "Tarif Horaire Xaf"),
    num("note_satisfaction", "Note Satisfaction", "Note Satisfaction"),
    txt("statut", "Statut", "Statut"),
  ],
};

