/**
 * Configs Registre pour port-operations (Wave 1A expansion).
 *
 * 12 sous-modules operationnels portuaires relies au router /api/v1/port-operations.
 * Chaque ConfigRegistre alimente <RegistreGenerique />.
 */
"use client";

import * as Icons from 'lucide-react';
import type { ConfigRegistre, ColonneRegistre, ChampRegistre } from '@/components/registre-generique/typesRegistre';
import { registreAPI } from '@/lib/api-client';

const api = registreAPI("port-operations");

function col(name: string, label: string, labelEn: string, opts: Partial<ColonneRegistre> = {}): ColonneRegistre {
  return { name, label, labelEn, ...opts } as ColonneRegistre;
}
function txt(name: string, label: string, labelEn: string, opts: Partial<ChampRegistre> = {}): ChampRegistre {
  return { name, label, labelEn, type: "texte", ...opts } as ChampRegistre;
}
function num(key: string, label: string, labelEn: string): ChampRegistre {
  return { key, label, labelEn, type: "number" } as ChampRegistre;
}
function dt(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}
function dtx(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}
function area(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "zone" } as ChampRegistre;
}
function chk(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "booleen" } as ChampRegistre;
}
function sel(name: string, label: string, labelEn: string, nomKey: string): ChampRegistre {
  return { name, label, labelEn, type: "select", nomenclature: nomKey } as ChampRegistre;
}

export const registreDraftSurvey: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "draft_survey",
  tcode: "registre-draft-surveys",
  icon: Icons.Ruler,
  titre: "Constats tirant d'eau et avaries",
  titreEn: "Draft surveys and damages",
  description: "Releve du tirant d'eau et des avaries de coque a l'arrivee et au depart.",
  descriptionEn: "Draft and hull damage report on arrival and departure.",
  aide: "Chaque constat doit etre contresigne par le capitaine.",
  aideEn: "Each report must be co-signed by the captain.",
  lister: (params) => api.lister("draft-surveys", params),
  creer: (data) => api.creer("draft-surveys", data),
  modifier: (id, data) => api.modifier("draft-surveys", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("numero_constat", "Numero", "Number"),
    col("navire_id", "Navire", "Vessel"),
    col("date_constat", "Date", "Date"),
    col("lieu_constat", "Lieu", "Location"),
    col("type_avarie", "Type avarie", "Damage type"),
    col("gravite", "Gravite", "Severity"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("numero_constat", "Numero de constat", "Report number", { requisCreation: true }),
    num("navire_id", "ID navire", "Vessel id"),
    num("escale_id", "ID escale", "Call id"),
    dt("date_constat", "Date du constat", "Report date"),
    txt("lieu_constat", "Lieu du constat", "Location"),
    num("tirant_eau_avant", "Tirant d'eau avant (m)", "Forward draft (m)"),
    num("tirant_eau_arriere", "Tirant d'eau arriere (m)", "Aft draft (m)"),
    sel("type_avarie", "Type d'avarie", "Damage type", "type_avarie"),
    sel("gravite", "Gravite", "Severity", "gravite_avarie"),
    area("description", "Description", "Description"),
    txt("inspecteur", "Inspecteur", "Inspector"),
    txt("capitaine_signataire", "Capitaine signataire", "Signing captain"),
    sel("statut", "Statut", "Status", "statut_constat"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreStevedoringCrew: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "stevedoring_crew",
  tcode: "registre-stevedoring-crews",
  icon: Icons.Users,
  titre: "Equipes de manutention",
  titreEn: "Stevedoring crews",
  description: "Gang de manutention affectes aux operations de quai.",
  descriptionEn: "Stevedoring gangs assigned to quay operations.",
  aide: "Suivre les certifications et dates d'expiration.",
  aideEn: "Track certifications and expiry dates.",
  lister: (params) => api.lister("stevedoring-crews", params),
  creer: (data) => api.creer("stevedoring-crews", data),
  modifier: (id, data) => api.modifier("stevedoring-crews", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "code_gang",
  colonnes: [
    col("code_gang", "Code", "Code"),
    col("nom_gang", "Nom", "Name"),
    col("type_equipe", "Type", "Type"),
    col("chef_gang", "Chef", "Leader"),
    col("nombre_membres", "Membres", "Members"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("code_gang", "Code gang", "Gang code", { requisCreation: true }),
    txt("nom_gang", "Nom du gang", "Gang name"),
    sel("type_equipe", "Type d'equipe", "Crew type", "type_equipage"),
    sel("statut", "Statut", "Status", "statut_gang"),
    txt("chef_gang", "Chef de gang", "Gang leader"),
    num("nombre_membres", "Nombre de membres", "Members count"),
    area("specialites", "Specialites", "Specialties"),
    txt("certification", "Certification", "Certification"),
    dt("date_expiration_certification", "Expiration certification", "Certification expiry"),
    txt("telephone_chef", "Telephone chef", "Leader phone"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreCargoHandlingPlan: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "cargo_plan",
  tcode: "registre-cargo-handling-plans",
  icon: Icons.Package,
  titre: "Plans dechargement / chargement",
  titreEn: "Discharge / loading plans",
  description: "Planification des operations de manutention par cale.",
  descriptionEn: "Handling operations planning by hold.",
  aide: "Comparer prevu / reel pour calculer la cadence.",
  aideEn: "Compare planned vs actual to compute rate.",
  lister: (params) => api.lister("cargo-handling-plans", params),
  creer: (data) => api.creer("cargo-handling-plans", data),
  modifier: (id, data) => api.modifier("cargo-handling-plans", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference_plan",
  colonnes: [
    col("reference_plan", "Reference", "Reference"),
    col("escale_id", "Escale", "Call"),
    col("type_operation", "Type operation", "Operation"),
    col("numero_cale", "Cale", "Hold"),
    col("poids_total_tonnes", "Poids (t)", "Weight (t)"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("reference_plan", "Reference plan", "Plan reference", { requisCreation: true }),
    num("escale_id", "ID escale", "Call id"),
    num("navire_id", "ID navire", "Vessel id"),
    sel("type_operation", "Type d'operation", "Operation type", "type_operation_quai"),
    sel("statut", "Statut", "Status", "statut_plan_manutention"),
    txt("numero_cale", "Numero de cale", "Hold number"),
    num("poids_total_tonnes", "Poids total (t)", "Total weight (t)"),
    num("nombre_colis", "Nombre de colis", "Packages count"),
    num("nombre_conteneurs", "Nombre de conteneurs", "Container count"),
    dtx("date_debut_prevue", "Debut prevu", "Planned start"),
    dtx("date_fin_prevue", "Fin prevue", "Planned end"),
    dtx("date_debut_reelle", "Debut reel", "Actual start"),
    dtx("date_fin_reelle", "Fin reel", "Actual end"),
    num("cadence_prevue_t_h", "Cadence prevue (t/h)", "Planned rate (t/h)"),
    num("cadence_reelle_t_h", "Cadence reelle (t/h)", "Actual rate (t/h)"),
    num("gang_id", "ID gang", "Gang id"),
    num("equipement_id", "ID equipement", "Equipment id"),
    txt("charge_a_bord_port", "Charge a bord (port)", "Load on board (port)"),
    txt("decharge_a_quai_port", "Decharge a quai (port)", "Discharge at quay (port)"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreQuayEquipment: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "quay_equipment",
  tcode: "registre-quay-equipments",
  icon: Icons.Construction,
  titre: "Equipements de quai",
  titreEn: "Quay equipment",
  description: "Inventaire des portiques, reach stackers, retract et autres engins.",
  descriptionEn: "Gantry, reach stacker, retrack and other equipment inventory.",
  aide: "Suivi de la maintenance preventive par date ou heures cumulées.",
  aideEn: "Preventive maintenance tracked by date or hours.",
  lister: (params) => api.lister("quay-equipments", params),
  creer: (data) => api.creer("quay-equipments", data),
  modifier: (id, data) => api.modifier("quay-equipments", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "code_equipement",
  colonnes: [
    col("code_equipement", "Code", "Code"),
    col("designation", "Designation", "Description"),
    col("type_equipement", "Type", "Type"),
    col("etat", "Etat", "Condition"),
    col("capacite_max_tonnes", "Capacite (t)", "Capacity (t)"),
    col("poste_quai_assigne", "Poste", "Berth"),
  ],
  champs: [
    txt("code_equipement", "Code equipement", "Equipment code", { requisCreation: true }),
    txt("designation", "Designation", "Description", { requisCreation: true }),
    sel("type_equipement", "Type", "Type", "type_equipement"),
    sel("etat", "Etat", "Condition", "etat_equipement"),
    txt("marque", "Marque", "Brand"),
    txt("modele", "Modele", "Model"),
    num("capacite_max_tonnes", "Capacite max (t)", "Max capacity (t)"),
    num("portee_max_m", "Portee max (m)", "Max outreach (m)"),
    num("annee_mise_service", "Annee mise en service", "In-service year"),
    txt("fournisseur", "Fournisseur", "Supplier"),
    txt("numero_serial", "Numero de serie", "Serial number"),
    dt("prochaine_maintenance_date", "Prochaine maintenance", "Next maintenance"),
    num("heures_service_cumulees", "Heures cumul", "Cumulative hours"),
    txt("poste_quai_assigne", "Poste de quai assigne", "Assigned berth"),
    num("cout_acquisition_xaf", "Cout acquisition XAF", "Acquisition cost XAF"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registrePilotageSession: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "pilotage",
  tcode: "registre-pilotage-sessions",
  icon: Icons.Compass,
  titre: "Pilotage maritime",
  titreEn: "Maritime pilotage",
  description: "Sessions de pilotage a l'entree / sortie / deplacement.",
  descriptionEn: "Pilotage sessions for entry / exit / movement.",
  aide: "Le pilote doit etre patent et la duree facturable arretee.",
  aideEn: "Pilot must be licensed and billable duration fixed.",
  lister: (params) => api.lister("pilotage-sessions", params),
  creer: (data) => api.creer("pilotage-sessions", data),
  modifier: (id, data) => api.modifier("pilotage-sessions", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("navire_id", "Navire", "Vessel"),
    col("pilote_nom", "Pilote", "Pilot"),
    col("type_mouvement", "Mouvement", "Movement"),
    col("duree_heures", "Duree", "Duration"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("navire_id", "ID navire", "Vessel id"),
    num("escale_id", "ID escale", "Call id"),
    txt("pilote_nom", "Nom du pilote", "Pilot name"),
    txt("pilote_matricule", "Matricule pilote", "Pilot badge"),
    sel("statut", "Statut", "Status", "statut_pilotage"),
    txt("type_mouvement", "Type mouvement", "Movement type"),
    dtx("date_demande", "Date demande", "Request date"),
    dtx("date_debut_reelle", "Debut reel", "Actual start"),
    dtx("date_fin_reelle", "Fin reel", "Actual end"),
    num("duree_heures", "Duree (h)", "Duration (h)"),
    txt("zone_pilotage", "Zone de pilotage", "Pilotage zone"),
    num("distance_nautique_mq", "Distance (milles)", "Distance (NM)"),
    txt("conditions_meteo", "Conditions meteo", "Weather"),
    num("vitesse_navire_noeuds", "Vitesse navire (nds)", "Vessel speed (knots)"),
    num("tirant_eau_navire_m", "Tirant d'eau (m)", "Draft (m)"),
    num("tarif_pilotage_xaf", "Tarif pilotage XAF", "Pilotage fee XAF"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreTowageOperation: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "towage",
  tcode: "registre-towage-operations",
  icon: Icons.Ship,
  titre: "Remorquage",
  titreEn: "Towage",
  description: "Operations de remorquage par remorqueurs du port.",
  descriptionEn: "Towage operations by port tugs.",
  aide: "Puissance bollard et nombre de remorqueurs determinent le tarif.",
  aideEn: "Bollard power and tug count determine the fee.",
  lister: (params) => api.lister("towage-operations", params),
  creer: (data) => api.creer("towage-operations", data),
  modifier: (id, data) => api.modifier("towage-operations", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("navire_id", "Navire", "Vessel"),
    col("remorqueur_nom", "Remorqueur", "Tug"),
    col("nombre_remorqueurs", "Nb", "Count"),
    col("duree_heures", "Duree", "Duration"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("navire_id", "ID navire", "Vessel id"),
    num("escale_id", "ID escale", "Call id"),
    txt("remorqueur_nom", "Nom du remorqueur", "Tug name"),
    txt("remorqueur_immatriculation", "Immatriculation remorqueur", "Tug registration"),
    num("nombre_remorqueurs", "Nombre de remorqueurs", "Number of tugs"),
    txt("type_prestation", "Type de prestation", "Service type"),
    sel("statut", "Statut", "Status", "statut_pilotage"),
    dtx("date_debut_reelle", "Debut reel", "Actual start"),
    dtx("date_fin_reelle", "Fin reel", "Actual end"),
    num("duree_heures", "Duree (h)", "Duration (h)"),
    num("puissance_bollard_t", "Puissance bollard (t)", "Bollard power (t)"),
    txt("zone_operation", "Zone operation", "Operation zone"),
    num("tarif_xaf", "Tarif XAF", "Fee XAF"),
    txt("operateur", "Operateur", "Operator"),
    txt("conditions_meteo", "Conditions meteo", "Weather"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreBunkeringOrder: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "bunkering",
  tcode: "registre-bunkering-orders",
  icon: Icons.Flame,
  titre: "Soute et ravitaillement",
  titreEn: "Bunkering",
  description: "Ordres de ravitaillement en carburant marin.",
  descriptionEn: "Marine fuel bunkering orders.",
  aide: "L'ecart quantite entre BL et mesure doit etre justifie.",
  aideEn: "B/L vs sounding quantity gap must be justified.",
  lister: (params) => api.lister("bunkering-orders", params),
  creer: (data) => api.creer("bunkering-orders", data),
  modifier: (id, data) => api.modifier("bunkering-orders", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("navire_id", "Navire", "Vessel"),
    col("type_carburant", "Carburant", "Fuel"),
    col("quantite_tonnes", "Quantite (t)", "Quantity (t)"),
    col("montant_total_xaf", "Montant", "Amount"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("navire_id", "ID navire", "Vessel id"),
    num("escale_id", "ID escale", "Call id"),
    sel("type_carburant", "Type de carburant", "Fuel type", "type_soute"),
    num("quantite_tonnes", "Quantite (t)", "Quantity (t)"),
    num("densite", "Densite", "Density"),
    num("soufre_pct", "Soufre (%)", "Sulphur (%)"),
    num("prix_tonne_xaf", "Prix tonne XAF", "Price per ton XAF"),
    num("montant_total_xaf", "Montant total XAF", "Total amount XAF"),
    txt("fournisseur", "Fournisseur", "Supplier"),
    txt("barge_nom", "Nom de la barge", "Barge name"),
    dtx("date_operation", "Date operation", "Operation date"),
    txt("heure_debut", "Heure debut", "Start hour"),
    txt("heure_fin", "Heure fin", "End hour"),
    num("debit_t_h", "Debit (t/h)", "Flow rate (t/h)"),
    txt("statut", "Statut", "Status"),
    txt("bon_livraison_ref", "Reference BL", "B/L reference"),
    num("quantitemesuree_t", "Quantite mesuree (t)", "Measured quantity (t)"),
    num("ecart_quantite_t", "Ecart quantite (t)", "Quantity gap (t)"),
    txt("capitaine_signataire", "Capitaine signataire", "Signing captain"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreVesselWasteReceipt: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "vessel_waste",
  tcode: "registre-vessel-waste-receipts",
  icon: Icons.Recycle,
  titre: "Reception dechets MARPOL",
  titreEn: "MARPOL waste reception",
  description: "Recus de collecte des dechets navires par annexe MARPOL.",
  descriptionEn: "Ship waste collection receipts by MARPOL annex.",
  aide: "Chaque dechet doit etre affecte a la bonne annexe MARPOL.",
  aideEn: "Each waste must be assigned to the correct MARPOL annex.",
  lister: (params) => api.lister("vessel-waste-receipts", params),
  creer: (data) => api.creer("vessel-waste-receipts", data),
  modifier: (id, data) => api.modifier("vessel-waste-receipts", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("navire_id", "Navire", "Vessel"),
    col("type_dechet", "Type", "Type"),
    col("quantite", "Quantite", "Quantity"),
    col("date_reception", "Date", "Date"),
    col("conforme", "Conforme", "Compliant"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("navire_id", "ID navire", "Vessel id"),
    num("escale_id", "ID escale", "Call id"),
    sel("type_dechet", "Type de dechet", "Waste type", "type_dechet"),
    num("quantite", "Quantite", "Quantity"),
    txt("unite", "Unite", "Unit"),
    dtx("date_reception", "Date reception", "Reception date"),
    txt("lieu_depot", "Lieu de depot", "Drop location"),
    txt("operateur_collecte", "Operateur collecte", "Collection operator"),
    txt("fichier_destinataire", "Fichier destinataire", "Destination facility"),
    num("cout_collecte_xaf", "Cout collecte XAF", "Collection cost XAF"),
    txt("numero_manifeste_dechet", "Numero manifeste dechet", "Waste manifest number"),
    txt("marpol_annexe", "Annexe MARPOL", "MARPOL annex"),
    txt("capitaine_declare", "Capitaine declarant", "Declaring captain"),
    txt("recu_par", "Recu par", "Received by"),
    chk("conforme", "Conforme", "Compliant"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreTallySheet: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "tally",
  tcode: "registre-tally-sheets",
  icon: Icons.ClipboardCheck,
  titre: "Comptage contradictoire / avaries",
  titreEn: "Joint tally / damage report",
  description: "Feuilles de comptage contradictoire entre terminal et bord.",
  descriptionEn: "Joint tally sheets between terminal and ship.",
  aide: "Ecart manifeste / tally > seuil declenche contestation.",
  aideEn: "Manifest vs tally gap over threshold triggers dispute.",
  lister: (params) => api.lister("tally-sheets", params),
  creer: (data) => api.creer("tally-sheets", data),
  modifier: (id, data) => api.modifier("tally-sheets", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("escale_id", "Escale", "Call"),
    col("type_operation", "Type", "Type"),
    col("poids_tally_t", "Poids tally (t)", "Tally weight (t)"),
    col("ecart_poids_t", "Ecart poids", "Weight gap"),
    col("valide", "Valide", "Validated"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("escale_id", "ID escale", "Call id"),
    num("navire_id", "ID navire", "Vessel id"),
    num("operation_id", "ID operation", "Operation id"),
    sel("type_operation", "Type d'operation", "Operation type", "type_operation_quai"),
    dt("date_tally", "Date tally", "Tally date"),
    txt("poste_quai", "Poste de quai", "Berth"),
    txt("numero_cale", "Numero de cale", "Hold number"),
    num("poids_manifeste_t", "Poids manifeste (t)", "Manifest weight (t)"),
    num("poids_tally_t", "Poids tally (t)", "Tally weight (t)"),
    num("colis_manifeste", "Colis manifeste", "Manifest packages"),
    num("colis_tally", "Colis tally", "Tally packages"),
    num("ecart_poids_t", "Ecart poids (t)", "Weight gap (t)"),
    num("ecart_colis", "Ecart colis", "Package gap"),
    num("nombre_avaries", "Nombre d'avaries", "Damages count"),
    txt("tallyeur", "Tallyeur", "Tallyman"),
    txt("contre_tallyeur", "Contre-tallyeur", "Counter tallyman"),
    chk("valide", "Valide", "Validated"),
    dtx("date_validation", "Date validation", "Validation date"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreDemurrageCase: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "demurrage",
  tcode: "registre-demurrage-cases",
  icon: Icons.Timer,
  titre: "Surestaries et magasinage",
  titreEn: "Demurrage and storage",
  description: "Dossiers de franchise, surestaries et litiges associes.",
  descriptionEn: "Free-time, demurrage and related dispute cases.",
  aide: "Un litige declare bloque la facturation jusqu'a arbitrage.",
  aideEn: "A declared dispute blocks billing until arbitration.",
  lister: (params) => api.lister("demurrage-cases", params),
  creer: (data) => api.creer("demurrage-cases", data),
  modifier: (id, data) => api.modifier("demurrage-cases", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("conteneur_id", "Conteneur", "Container"),
    col("client_id", "Client", "Client"),
    col("nb_jours_facturables", "Jours fact.", "Billable days"),
    col("montant_total_xaf", "Montant XAF", "Amount XAF"),
    col("statut", "Statut", "Status"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("escale_id", "ID escale", "Call id"),
    num("navire_id", "ID navire", "Vessel id"),
    num("conteneur_id", "ID conteneur", "Container id"),
    num("client_id", "ID client", "Client id"),
    dt("date_debut_franchise", "Debut franchise", "Free time start"),
    dt("date_fin_franchise", "Fin franchise", "Free time end"),
    dt("date_retrait_reelle", "Retrait reel", "Actual pickup"),
    num("nb_jours_facturables", "Jours facturables", "Billable days"),
    num("tarif_journalier_xaf", "Tarif journalier XAF", "Daily rate XAF"),
    num("montant_total_xaf", "Montant total XAF", "Total amount XAF"),
    txt("statut", "Statut", "Status"),
    num("facture_id", "ID facture", "Invoice id"),
    chk("litige_declare", "Litige declare", "Dispute filed"),
    area("motif_litige", "Motif du litige", "Dispute reason"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreGatePass: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "gate_pass",
  tcode: "registre-gate-passes",
  icon: Icons.Ticket,
  titre: "Bons de sortie (gate pass)",
  titreEn: "Gate passes",
  description: "Laisser-passer camions / conteneurs aux portes du port.",
  descriptionEn: "Truck / container gate passes at port entrances.",
  aide: "Un gate pass expire n'autorise pas la sortie.",
  aideEn: "An expired gate pass does not authorize exit.",
  lister: (params) => api.lister("gate-passes", params),
  creer: (data) => api.creer("gate-passes", data),
  modifier: (id, data) => api.modifier("gate-passes", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "numero_gate",
  colonnes: [
    col("numero_gate", "Numero", "Number"),
    col("type_sortie", "Type", "Type"),
    col("camion_immatriculation", "Camion", "Truck"),
    col("chauffeur_nom", "Chauffeur", "Driver"),
    col("statut", "Statut", "Status"),
    col("date_passage", "Passage", "Passage"),
  ],
  champs: [
    txt("numero_gate", "Numero gate pass", "Gate pass number", { requisCreation: true }),
    txt("type_sortie", "Type de sortie", "Exit type"),
    num("conteneur_id", "ID conteneur", "Container id"),
    txt("camion_immatriculation", "Immatriculation camion", "Truck plate"),
    txt("chauffeur_nom", "Nom du chauffeur", "Driver name"),
    txt("chauffeur_telephone", "Telephone chauffeur", "Driver phone"),
    sel("statut", "Statut", "Status", "statut_gate_pass"),
    dtx("date_emission", "Date d'emission", "Issue date"),
    dtx("date_passage", "Date de passage", "Passage date"),
    txt("poste_controle", "Poste de controle", "Control post"),
    txt("agent_poste", "Agent du poste", "Post agent"),
    num("poids_camion_kg", "Poids camion (kg)", "Truck weight (kg)"),
    num("poids_charge_kg", "Poids charge (kg)", "Cargo weight (kg)"),
    txt("bl_reference", "Reference BL", "B/L reference"),
    txt("livraison_client", "Client de livraison", "Delivery client"),
    txt("valide_par", "Valide par", "Validated by"),
    area("notes", "Notes", "Notes"),
  ],
};

export const registreYardOperation: ConfigRegistre = {
  permModule: "port_ops",
  permSousModule: "yard_operation",
  tcode: "registre-yard-operations",
  icon: Icons.LayoutGrid,
  titre: "Parc a conteneurs (CY)",
  titreEn: "Container yard (CY)",
  description: "Mouvements de depots, releves, transferts et repositions au CY.",
  descriptionEn: "Depot, lift, transfer and reshuffle moves at CY.",
  aide: "Chaque mouvement doit tracer l'equipment utilise.",
  aideEn: "Each move must record the equipment used.",
  lister: (params) => api.lister("yard-operations", params),
  creer: (data) => api.creer("yard-operations", data),
  modifier: (id, data) => api.modifier("yard-operations", id, data),
  fetchNomenclatures: () => api.getNomenclatures(),
  unicite: "reference",
  colonnes: [
    col("reference", "Reference", "Reference"),
    col("conteneur_id", "Conteneur", "Container"),
    col("type_mouvement", "Mouvement", "Move"),
    col("emplacement_source", "Source", "From"),
    col("emplacement_destination", "Destination", "To"),
    col("date_operation", "Date", "Date"),
  ],
  champs: [
    txt("reference", "Reference", "Reference", { requisCreation: true }),
    num("conteneur_id", "ID conteneur", "Container id"),
    sel("type_mouvement", "Type de mouvement", "Move type", "type_mouvement_yard"),
    txt("emplacement_source", "Emplacement source", "Source slot"),
    txt("emplacement_destination", "Emplacement destination", "Destination slot"),
    txt("zone_yard", "Zone yard", "Yard zone"),
    dtx("date_operation", "Date operation", "Operation date"),
    num("equipment_id", "ID equipment", "Equipment id"),
    txt("operateur_equipment", "Operateur equipment", "Equipment operator"),
    num("poids_conteneur_t", "Poids conteneur (t)", "Container weight (t)"),
    txt("statut", "Statut", "Status"),
    txt("reference_gate_pass", "Reference gate pass", "Gate pass reference"),
    txt("reference_escale", "Reference escale", "Call reference"),
    area("notes", "Notes", "Notes"),
  ],
};
