"""105_maintenance_deep : tables expansion maintenance (genere wave 6)."""
from alembic import op
import sqlalchemy as sa


revision = "105_maintenance_deep"
down_revision = "104_departement_d5_deep"
branch_labels = None
depends_on = None


TABLES = [
    "maint_asset_components",
    "maint_asset_failures",
    "maint_bill_of_material",
    "maint_condition_readings",
    "maint_failure_modes",
    "maint_lubrication_schedules",
    "maint_maintenance_budgets",
    "maint_maintenance_plans",
    "maint_maintenance_tasks",
    "maint_maintenance_vendors",
    "maint_overhaul_campaigns",
    "maint_part_inventory",
    "maint_part_movements",
    "maint_predictive_models",
    "maint_regulatory_inspections",
    "maint_reliability_kpis",
    "maint_root_causes",
    "maint_sensors",
    "maint_serialized_parts",
    "maint_spare_part_catalog",
    "maint_technical_assets",
    "maint_work_order_labours",
    "maint_work_order_parts",
    "maint_work_order_tools",
    "maint_work_orders",
]


def _has(name):
    insp = sa.inspect(op.get_bind())
    return name in set(insp.get_table_names())


def upgrade():
    if not _has("maint_asset_components"):
        op.create_table(
            "maint_asset_components",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("code_composant", sa.String(120), nullable=False, index=True),
            sa.Column("nom_composant", sa.String(220), nullable=False),
            sa.Column("type_composant", sa.String(120), nullable=True, index=True),
            sa.Column("ref_fabricant", sa.String(180), nullable=True, index=True),
            sa.Column("numero_serie", sa.String(180), nullable=True, index=True),
            sa.Column("nombre_pieces", sa.Integer, nullable=True),
            sa.Column("masse_kg", sa.Numeric, nullable=True),
            sa.Column("seuil_reforme", sa.String(220), nullable=True),
            sa.Column("criticite", sa.String(30), nullable=True),
            sa.Column("date_mise_service", sa.Date, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "asset_id", "code_composant", name="uix_maint_comp"),
        )

    if not _has("maint_asset_failures"):
        op.create_table(
            "maint_asset_failures",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_defaillance", sa.String(120), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("mode_id", sa.Integer, sa.ForeignKey("maint_failure_modes.id"), nullable=True, index=True),
            sa.Column("date_detection", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("detecteur", sa.String(180), nullable=True),
            sa.Column("source_signalement", sa.String(80), nullable=True),
            sa.Column("severite", sa.String(30), nullable=True, index=True),
            sa.Column("description", sa.String(200), nullable=True),
            sa.Column("symptomes", sa.String(200), nullable=True),
            sa.Column("code_defaut", sa.String(120), nullable=True, index=True),
            sa.Column("heures_arret", sa.Numeric, nullable=True),
            sa.Column("cout_indirect_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_defaillance", name="uix_maint_def_ref"),
        )

    if not _has("maint_bill_of_material"):
        op.create_table(
            "maint_bill_of_material",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("part_id", sa.Integer, sa.ForeignKey("maint_spare_part_catalog.id"), nullable=False, index=True),
            sa.Column("position_index", sa.Integer, nullable=False),
            sa.Column("quantite_par_assemblage", sa.Numeric, nullable=True),
            sa.Column("unit", sa.String(40), nullable=True),
            sa.Column("niveau", sa.Integer, nullable=True, index=True),
            sa.Column("level_parent_id", sa.Integer, sa.ForeignKey("maint_bill_of_material.id"), nullable=True, index=True),
            sa.Column("obligatoire", sa.Boolean, nullable=True),
            sa.Column("remplacement_interval", sa.String(120), nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "asset_id", "component_id", "part_id", "position_index", name="uix_maint_bom"),
        )

    if not _has("maint_condition_readings"):
        op.create_table(
            "maint_condition_readings",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_lecture", sa.String(140), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("type_technique", sa.String(60), nullable=False, index=True),
            sa.Column("capteur_id", sa.Integer, sa.ForeignKey("maint_sensors.id"), nullable=True, index=True),
            sa.Column("point_mesure", sa.String(180), nullable=True),
            sa.Column("date_lecture", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("valeur_principale", sa.Numeric, nullable=True, index=True),
            sa.Column("unite", sa.String(60), nullable=True),
            sa.Column("seuil_alerte", sa.Numeric, nullable=True),
            sa.Column("seuil_critical", sa.Numeric, nullable=True),
            sa.Column("statut_resultat", sa.String(40), nullable=True, index=True),
            sa.Column("spectre_url", sa.String(280), nullable=True),
            sa.Column("analyse_experte", sa.String(200), nullable=True),
            sa.Column("operateur", sa.String(180), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_lecture", name="uix_maint_cond_ref"),
        )

    if not _has("maint_failure_modes"):
        op.create_table(
            "maint_failure_modes",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_fmea", sa.String(120), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("fonction", sa.String(220), nullable=True),
            sa.Column("mode_defaillance", sa.String(280), nullable=False),
            sa.Column("mecanisme", sa.String(180), nullable=True),
            sa.Column("causes", sa.String(200), nullable=True),
            sa.Column("effets", sa.String(200), nullable=True),
            sa.Column("gravite", sa.Integer, nullable=True, index=True),
            sa.Column("occurrence", sa.Integer, nullable=True, index=True),
            sa.Column("detection", sa.Integer, nullable=True, index=True),
            sa.Column("ipr", sa.Integer, nullable=True, index=True),
            sa.Column("methode_detection", sa.String(220), nullable=True),
            sa.Column("actions_preventives", sa.String(200), nullable=True),
            sa.Column("actions_correctives", sa.String(200), nullable=True),
            sa.Column("responsable", sa.String(180), nullable=True),
            sa.Column("date_evaluation", sa.Date, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_fmea", name="uix_maint_fmea_code"),
        )

    if not _has("maint_lubrication_schedules"):
        op.create_table(
            "maint_lubrication_schedules",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("point_lubrifiant", sa.String(120), nullable=False, index=True),
            sa.Column("type_lubrifiant", sa.String(120), nullable=True),
            sa.Column("grade", sa.String(80), nullable=True),
            sa.Column("marque", sa.String(120), nullable=True),
            sa.Column("quantite_litre", sa.Numeric, nullable=True),
            sa.Column("quantite_gramme", sa.Numeric, nullable=True),
            sa.Column("frequence_heures", sa.Numeric, nullable=True),
            sa.Column("frequence_jours", sa.Integer, nullable=True),
            sa.Column("prochaine_date", sa.Date, nullable=True, index=True),
            sa.Column("methode", sa.String(120), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "asset_id", "point_lubrifiant", name="uix_maint_lubri_point"),
        )

    if not _has("maint_maintenance_budgets"):
        op.create_table(
            "maint_maintenance_budgets",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("exercice", sa.String(8), nullable=False, index=True),
            sa.Column("budget_prevu_pieces_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("budget_prevu_main_oeuvre_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("budget_prevu_prestataire_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("budget_total_prevu_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("consomme_pieces_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("consomme_main_oeuvre_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("consomme_prestataire_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("total_consomme_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("ecart_pct", sa.Numeric, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "asset_id", "exercice", name="uix_maint_budget_asset_year"),
        )

    if not _has("maint_maintenance_plans"):
        op.create_table(
            "maint_maintenance_plans",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_plan", sa.String(120), nullable=False, index=True),
            sa.Column("nom", sa.String(220), nullable=False),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("type_plan", sa.String(40), nullable=False, index=True),
            sa.Column("frequence_type", sa.String(40), nullable=True, index=True),
            sa.Column("frequence_valeur", sa.Numeric, nullable=True),
            sa.Column("frequence_unite", sa.String(40), nullable=True),
            sa.Column("seuil_declenchement", sa.String(180), nullable=True),
            sa.Column("prochaine_echeance", sa.Date, nullable=True, index=True),
            sa.Column("duree_estimee_h", sa.Numeric, nullable=True),
            sa.Column("criticite", sa.String(30), nullable=True, index=True),
            sa.Column("cout_estime_par_cycle_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("skills_requis", sa.String(220), nullable=True),
            sa.Column("outillage_requis", sa.String(200), nullable=True),
            sa.Column("pieces_cle", sa.String(200), nullable=True),
            sa.Column("version", sa.Integer, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_plan", name="uix_maint_plan_code"),
        )

    if not _has("maint_maintenance_tasks"):
        op.create_table(
            "maint_maintenance_tasks",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_tache", sa.String(120), nullable=False, index=True),
            sa.Column("plan_id", sa.Integer, sa.ForeignKey("maint_maintenance_plans.id"), nullable=True, index=True),
            sa.Column("titre", sa.String(220), nullable=False),
            sa.Column("description_geste", sa.String(200), nullable=True),
            sa.Column("duree_estimee_min", sa.Integer, nullable=True),
            sa.Column("nb_techniciens", sa.Integer, nullable=True),
            sa.Column("competence_requise", sa.String(180), nullable=True),
            sa.Column("niveau_habiliture", sa.String(120), nullable=True),
            sa.Column("epi_requis", sa.String(220), nullable=True),
            sa.Column("outillage", sa.String(200), nullable=True),
            sa.Column("couples_re_serrage", sa.String(220), nullable=True),
            sa.Column("pieces_requises", sa.String(200), nullable=True),
            sa.Column("ordre_execution", sa.Integer, nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_tache", name="uix_maint_task_code"),
        )

    if not _has("maint_maintenance_vendors"):
        op.create_table(
            "maint_maintenance_vendors",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_prestataire", sa.String(120), nullable=False, index=True),
            sa.Column("raison_sociale", sa.String(220), nullable=False),
            sa.Column("pays", sa.String(80), nullable=True),
            sa.Column("specialites", sa.String(280), nullable=True),
            sa.Column("habilitations", sa.String(200), nullable=True),
            sa.Column("certifications_iso", sa.String(280), nullable=True),
            sa.Column("contact_nom", sa.String(180), nullable=True),
            sa.Column("contact_email", sa.String(180), nullable=True),
            sa.Column("contact_telephone", sa.String(60), nullable=True),
            sa.Column("delai_reponse_h", sa.Integer, nullable=True),
            sa.Column("astreinte_247", sa.Boolean, nullable=True),
            sa.Column("zone_intervention", sa.String(280), nullable=True),
            sa.Column("tarif_horaire_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("note_satisfaction", sa.Numeric, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_prestataire", name="uix_maint_vendor_code"),
        )

    if not _has("maint_overhaul_campaigns"):
        op.create_table(
            "maint_overhaul_campaigns",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_overhaul", sa.String(120), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("type_overhaul", sa.String(60), nullable=True, index=True),
            sa.Column("intervalle_heures", sa.Numeric, nullable=True),
            sa.Column("intervalle_km", sa.Numeric, nullable=True),
            sa.Column("intervalle_mois", sa.Integer, nullable=True),
            sa.Column("prochaine_echeance_date", sa.Date, nullable=True, index=True),
            sa.Column("prochaine_echeance_heures", sa.Numeric, nullable=True),
            sa.Column("prestataire_id", sa.Integer, sa.ForeignKey("prestataires.id"), nullable=True, index=True),
            sa.Column("budget_estime_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("date_debut", sa.Date, nullable=True, index=True),
            sa.Column("date_fin", sa.Date, nullable=True),
            sa.Column("duree_reelle_j", sa.Integer, nullable=True),
            sa.Column("kits_pieces_utilises", sa.String(200), nullable=True),
            sa.Column("rapport_technique", sa.String(200), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_overhaul", name="uix_maint_overhaul_code"),
        )

    if not _has("maint_part_inventory"):
        op.create_table(
            "maint_part_inventory",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("part_id", sa.Integer, sa.ForeignKey("maint_spare_part_catalog.id"), nullable=False, index=True),
            sa.Column("magasin_id", sa.Integer, sa.ForeignKey("entrepots.id"), nullable=True, index=True),
            sa.Column("emplacement", sa.String(180), nullable=True, index=True),
            sa.Column("quantite_en_stock", sa.Integer, nullable=False),
            sa.Column("quantite_reservee", sa.Integer, nullable=True),
            sa.Column("quantite_min", sa.Integer, nullable=True, index=True),
            sa.Column("quantite_max", sa.Integer, nullable=True),
            sa.Column("point_commande", sa.Integer, nullable=True),
            sa.Column("cout_moyen_pondere_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("valeur_totale_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("date_dernier_mouvement", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_dernier_inventaire", sa.Date, nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "part_id", "magasin_id", "emplacement", name="uix_maint_part_inv"),
        )

    if not _has("maint_part_movements"):
        op.create_table(
            "maint_part_movements",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_mouvement", sa.String(140), nullable=False, index=True),
            sa.Column("part_id", sa.Integer, sa.ForeignKey("maint_spare_part_catalog.id"), nullable=False, index=True),
            sa.Column("serialized_part_id", sa.Integer, sa.ForeignKey("maint_serialized_parts.id"), nullable=True, index=True),
            sa.Column("type_mouvement", sa.String(40), nullable=False, index=True),
            sa.Column("quantite", sa.Numeric, nullable=False),
            sa.Column("magasin_source_id", sa.Integer, sa.ForeignKey("entrepots.id"), nullable=True, index=True),
            sa.Column("magasin_destination_id", sa.Integer, sa.ForeignKey("entrepots.id"), nullable=True, index=True),
            sa.Column("work_order_id", sa.Integer, sa.ForeignKey("maint_work_orders.id"), nullable=True, index=True),
            sa.Column("bon_livraison_id", sa.Integer, nullable=True, index=True),
            sa.Column("facture_achat_id", sa.Integer, nullable=True, index=True),
            sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("date_mouvement", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("valeur_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("motif", sa.String(220), nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_mouvement", name="uix_maint_part_mvmt"),
        )

    if not _has("maint_predictive_models"):
        op.create_table(
            "maint_predictive_models",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_modele", sa.String(120), nullable=False, index=True),
            sa.Column("nom", sa.String(220), nullable=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("composant_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("type_modele", sa.String(80), nullable=True, index=True),
            sa.Column("variable_entree", sa.String(220), nullable=True),
            sa.Column("variable_sortie", sa.String(180), nullable=True),
            sa.Column("heuristique", sa.String(200), nullable=True),
            sa.Column("precision_pct", sa.Numeric, nullable=True),
            sa.Column("rappel_pct", sa.Numeric, nullable=True),
            sa.Column("auc", sa.Numeric, nullable=True),
            sa.Column("version", sa.String(60), nullable=True),
            sa.Column("date_entrainement", sa.Date, nullable=True),
            sa.Column("date_debut_production", sa.Date, nullable=True),
            sa.Column("seuil_declenchement_ot", sa.Numeric, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_modele", name="uix_maint_pred_model"),
        )

    if not _has("maint_regulatory_inspections"):
        op.create_table(
            "maint_regulatory_inspections",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("numero_pv", sa.String(120), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("type_controle", sa.String(120), nullable=True, index=True),
            sa.Column("autorite", sa.String(180), nullable=True, index=True),
            sa.Column("organisme_controle", sa.String(180), nullable=True),
            sa.Column("date_controle", sa.Date, nullable=True, index=True),
            sa.Column("date_validite", sa.Date, nullable=True, index=True),
            sa.Column("resultat", sa.String(60), nullable=True, index=True),
            sa.Column("observations", sa.String(200), nullable=True),
            sa.Column("pv_url", sa.String(280), nullable=True),
            sa.Column("prochaine_echeance", sa.Date, nullable=True, index=True),
            sa.Column("inspecteur", sa.String(180), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "numero_pv", name="uix_maint_reg_pv"),
        )

    if not _has("maint_reliability_kpis"):
        op.create_table(
            "maint_reliability_kpis",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("periode", sa.String(10), nullable=False, index=True),
            sa.Column("nb_defaillances", sa.Integer, nullable=True),
            sa.Column("nb_ot_preventif", sa.Integer, nullable=True),
            sa.Column("nb_ot_curatif", sa.Integer, nullable=True),
            sa.Column("heures_fonctionnement", sa.Numeric, nullable=True),
            sa.Column("heures_arret", sa.Numeric, nullable=True),
            sa.Column("mtbf_heures", sa.Numeric, nullable=True, index=True),
            sa.Column("mttr_heures", sa.Numeric, nullable=True, index=True),
            sa.Column("mttf_heures", sa.Numeric, nullable=True),
            sa.Column("disponibilite_pct", sa.Numeric, nullable=True, index=True),
            sa.Column("cout_maintenance_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cout_indirect_arret_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("oee_pct", sa.Numeric, nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "asset_id", "periode", name="uix_maint_reli_kpi"),
        )

    if not _has("maint_root_causes"):
        op.create_table(
            "maint_root_causes",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_rca", sa.String(120), nullable=False, index=True),
            sa.Column("work_order_id", sa.Integer, sa.ForeignKey("maint_work_orders.id"), nullable=True, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("methode", sa.String(80), nullable=True, index=True),
            sa.Column("probleme", sa.String(200), nullable=False),
            sa.Column("pourquoi_1", sa.String(200), nullable=True),
            sa.Column("pourquoi_2", sa.String(200), nullable=True),
            sa.Column("pourquoi_3", sa.String(200), nullable=True),
            sa.Column("pourquoi_4", sa.String(200), nullable=True),
            sa.Column("pourquoi_5", sa.String(200), nullable=True),
            sa.Column("categories_ishikawa", sa.String(200), nullable=True),
            sa.Column("cause_racine", sa.String(200), nullable=True),
            sa.Column("causes_contributives", sa.String(200), nullable=True),
            sa.Column("actions_correctives", sa.String(200), nullable=True),
            sa.Column("actions_preventives_globales", sa.String(200), nullable=True),
            sa.Column("responsable_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("date_cloture", sa.Date, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_rca", name="uix_maint_rca_ref"),
        )

    if not _has("maint_sensors"):
        op.create_table(
            "maint_sensors",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_capteur", sa.String(120), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("composant_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("type_capteur", sa.String(80), nullable=True, index=True),
            sa.Column("protocol", sa.String(60), nullable=True),
            sa.Column("adresse_mqtt", sa.String(220), nullable=True),
            sa.Column("url_flux", sa.String(280), nullable=True),
            sa.Column("frequence_echantillonnage_hz", sa.Integer, nullable=True),
            sa.Column("resolution_bits", sa.Integer, nullable=True),
            sa.Column("unite_sortie", sa.String(60), nullable=True),
            sa.Column("plage_min", sa.Numeric, nullable=True),
            sa.Column("plage_max", sa.Numeric, nullable=True),
            sa.Column("seuil_alerte_bas", sa.Numeric, nullable=True),
            sa.Column("seuil_alerte_haut", sa.Numeric, nullable=True),
            sa.Column("calibration_periodicite_mois", sa.Integer, nullable=True),
            sa.Column("derniere_calibration", sa.Date, nullable=True),
            sa.Column("fabricant", sa.String(180), nullable=True),
            sa.Column("modele", sa.String(180), nullable=True),
            sa.Column("numero_serie", sa.String(180), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("date_installation", sa.Date, nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_capteur", name="uix_maint_sensor_code"),
        )

    if not _has("maint_serialized_parts"):
        op.create_table(
            "maint_serialized_parts",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("part_id", sa.Integer, sa.ForeignKey("maint_spare_part_catalog.id"), nullable=False, index=True),
            sa.Column("numero_serial", sa.String(180), nullable=False, index=True),
            sa.Column("numero_lot", sa.String(120), nullable=True, index=True),
            sa.Column("date_fabrication", sa.Date, nullable=True),
            sa.Column("date_reception", sa.Date, nullable=True, index=True),
            sa.Column("date_mise_service", sa.Date, nullable=True, index=True),
            sa.Column("date_reforme", sa.Date, nullable=True, index=True),
            sa.Column("cycles_utilisation", sa.Integer, nullable=True),
            sa.Column("heures_utilisees", sa.Numeric, nullable=True),
            sa.Column("kilometres_utilises", sa.Numeric, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("asset_id_actuel", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("composant_id_actuel", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("emplacement_stock", sa.String(220), nullable=True),
            sa.Column("fournisseur_id", sa.Integer, sa.ForeignKey("fournisseurs.id"), nullable=True, index=True),
            sa.Column("numero_bl_achat", sa.String(120), nullable=True, index=True),
            sa.Column("numero_facture_achat", sa.String(120), nullable=True, index=True),
            sa.Column("date_garantie_fin", sa.Date, nullable=True),
            sa.Column("valeur_achat_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("hashs_certificat", sa.String(200), nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "numero_serial", name="uix_maint_serialized_part"),
        )

    if not _has("maint_spare_part_catalog"):
        op.create_table(
            "maint_spare_part_catalog",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_interne", sa.String(120), nullable=False, index=True),
            sa.Column("designation", sa.String(260), nullable=False),
            sa.Column("origine", sa.String(40), nullable=True, index=True),
            sa.Column("ref_fabricant", sa.String(180), nullable=True, index=True),
            sa.Column("ref_essaiere_group", sa.String(180), nullable=True, index=True),
            sa.Column("categorie", sa.String(120), nullable=True, index=True),
            sa.Column("sous_categorie", sa.String(120), nullable=True),
            sa.Column("type_rechange", sa.String(60), nullable=True, index=True),
            sa.Column("unite_mesure", sa.String(40), nullable=True),
            sa.Column("unit_cost_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cost_achat_actuel_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("fournisseur_principal_id", sa.Integer, sa.ForeignKey("fournisseurs.id"), nullable=True, index=True),
            sa.Column("alternative_fournisseur_id", sa.Integer, sa.ForeignKey("fournisseurs.id"), nullable=True),
            sa.Column("delai_approvisionnement_j", sa.Integer, nullable=True),
            sa.Column("duree_vie_moyenne_h", sa.Integer, nullable=True),
            sa.Column("garantie_mois", sa.Integer, nullable=True),
            sa.Column("serialise_obligatoire", sa.Boolean, nullable=True),
            sa.Column("poids_kg", sa.Numeric, nullable=True),
            sa.Column("volume_cm3", sa.Integer, nullable=True),
            sa.Column("classification_hs", sa.String(40), nullable=True),
            sa.Column("notes_techniques", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_interne", name="uix_maint_part_ref"),
        )

    if not _has("maint_technical_assets"):
        op.create_table(
            "maint_technical_assets",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("tag_actif", sa.String(120), nullable=False, index=True),
            sa.Column("nom", sa.String(220), nullable=False),
            sa.Column("categorie", sa.String(120), nullable=True, index=True),
            sa.Column("sous_categorie", sa.String(120), nullable=True),
            sa.Column("module_source", sa.String(80), nullable=True, index=True),
            sa.Column("ref_entite_source", sa.String(120), nullable=True, index=True),
            sa.Column("parent_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=True, index=True),
            sa.Column("emplacement", sa.String(220), nullable=True),
            sa.Column("fabricant", sa.String(180), nullable=True),
            sa.Column("modele", sa.String(180), nullable=True),
            sa.Column("numero_serie", sa.String(180), nullable=True, index=True),
            sa.Column("annee_fabrication", sa.Integer, nullable=True),
            sa.Column("date_mise_service", sa.Date, nullable=True, index=True),
            sa.Column("criticite", sa.String(30), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("cout_acquisition_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("valeur_residuelle_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("duree_vieutile_ans", sa.Integer, nullable=True),
            sa.Column("notes_techniques", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "tag_actif", name="uix_maint_assets_company_tag"),
        )

    if not _has("maint_work_order_labours"):
        op.create_table(
            "maint_work_order_labours",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("work_order_id", sa.Integer, sa.ForeignKey("maint_work_orders.id"), nullable=False, index=True),
            sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False, index=True),
            sa.Column("role_intervenant", sa.String(120), nullable=True),
            sa.Column("date_travail", sa.Date, nullable=False, index=True),
            sa.Column("heures_prevues", sa.Numeric, nullable=True),
            sa.Column("heures_reelles", sa.Numeric, nullable=False),
            sa.Column("taux_horaire_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cout_total_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "work_order_id", "user_id", "date_travail", name="uix_maint_wo_labour"),
        )

    if not _has("maint_work_order_parts"):
        op.create_table(
            "maint_work_order_parts",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("work_order_id", sa.Integer, sa.ForeignKey("maint_work_orders.id"), nullable=False, index=True),
            sa.Column("part_id", sa.Integer, sa.ForeignKey("maint_spare_part_catalog.id"), nullable=False, index=True),
            sa.Column("serialized_part_id", sa.Integer, sa.ForeignKey("maint_serialized_parts.id"), nullable=True, index=True),
            sa.Column("quantite_demandee", sa.Numeric, nullable=False),
            sa.Column("quantite_livree", sa.Numeric, nullable=True),
            sa.Column("quantite_consommee", sa.Numeric, nullable=True),
            sa.Column("quantite_retour", sa.Numeric, nullable=True),
            sa.Column("valeur_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("date_sortie", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("motif_retour", sa.String(220), nullable=True),
            sa.Column("magasin_id", sa.Integer, sa.ForeignKey("entrepots.id"), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "work_order_id", "part_id", "serialized_part_id", name="uix_maint_wo_part"),
        )

    if not _has("maint_work_order_tools"):
        op.create_table(
            "maint_work_order_tools",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("work_order_id", sa.Integer, sa.ForeignKey("maint_work_orders.id"), nullable=False, index=True),
            sa.Column("reference_outillage", sa.String(180), nullable=False, index=True),
            sa.Column("designation", sa.String(220), nullable=True),
            sa.Column("type_outillage", sa.String(80), nullable=True, index=True),
            sa.Column("proprietaire", sa.String(120), nullable=True),
            sa.Column("numero_inventaire", sa.String(180), nullable=True, index=True),
            sa.Column("date_pret_debut", sa.Date, nullable=True),
            sa.Column("date_pret_fin", sa.Date, nullable=True),
            sa.Column("date_calibration", sa.Date, nullable=True),
            sa.Column("cout_location_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "work_order_id", "reference_outillage", name="uix_maint_wo_tool"),
        )

    if not _has("maint_work_orders"):
        op.create_table(
            "maint_work_orders",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("numero_ot", sa.String(120), nullable=False, index=True),
            sa.Column("type_ot", sa.String(40), nullable=False, index=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("maint_technical_assets.id"), nullable=False, index=True),
            sa.Column("component_id", sa.Integer, sa.ForeignKey("maint_asset_components.id"), nullable=True, index=True),
            sa.Column("plan_id", sa.Integer, sa.ForeignKey("maint_maintenance_plans.id"), nullable=True, index=True),
            sa.Column("defaillance_id", sa.Integer, sa.ForeignKey("maint_asset_failures.id"), nullable=True, index=True),
            sa.Column("titre", sa.String(220), nullable=False),
            sa.Column("description", sa.String(200), nullable=True),
            sa.Column("priorite", sa.String(30), nullable=True, index=True),
            sa.Column("criticite_asset", sa.String(30), nullable=True),
            sa.Column("date_detection", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_ouverture", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_prevue_debut", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_prevue_fin", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_reel_debut", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_reel_fin", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("technicien_principal_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("prestataire_id", sa.Integer, sa.ForeignKey("prestataires.id"), nullable=True, index=True),
            sa.Column("heures_prevues", sa.Numeric, nullable=True),
            sa.Column("heures_reelles", sa.Numeric, nullable=True),
            sa.Column("cout_pieces_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cout_main_oeuvre_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cout_prestataire_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cout_total_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("cause_racine_id", sa.Integer, sa.ForeignKey("maint_root_causes.id"), nullable=True, index=True),
            sa.Column("arret_production", sa.Boolean, nullable=True),
            sa.Column("impact_securite", sa.Boolean, nullable=True),
            sa.Column("compte_rendu", sa.String(200), nullable=True),
            sa.Column("pieces_ressorties", sa.String(200), nullable=True),
            sa.Column("photos_url", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "numero_ot", name="uix_maint_wo_numero"),
        )



def downgrade():
    for name in reversed(TABLES):
        if _has(name):
            op.drop_table(name)
