"""106_tracabilite_deep : tables expansion tracabilite (genere wave 6)."""
from alembic import op
import sqlalchemy as sa


revision = "106_tracabilite_deep"
down_revision = "105_maintenance_deep"
branch_labels = None
depends_on = None


TABLES = [
    "trace_access_security",
    "trace_anti_tampering",
    "trace_audit_logs",
    "trace_batch_genealogy",
    "trace_cargo_handoffs",
    "trace_cold_chain",
    "trace_consents",
    "trace_container_seals",
    "trace_custody_transfers",
    "trace_document_hashes",
    "trace_events",
    "trace_geolocations",
    "trace_incident_commands",
    "trace_merkle_proofs",
    "trace_regulatory_exports",
    "trace_retention_policies",
    "trace_serial_genealogy",
    "trace_timestamps",
    "trace_witness_signatures",
]


def _has(name):
    insp = sa.inspect(op.get_bind())
    return name in set(insp.get_table_names())


def upgrade():
    if not _has("trace_access_security"):
        op.create_table(
            "trace_access_security",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=True, index=True),
            sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("email_tente", sa.String(180), nullable=True, index=True),
            sa.Column("type_evenement", sa.String(60), nullable=False, index=True),
            sa.Column("date_evenement", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("ip_source", sa.String(60), nullable=True, index=True),
            sa.Column("user_agent", sa.String(280), nullable=True),
            sa.Column("geo_pays", sa.String(80), nullable=True),
            sa.Column("geo_ville", sa.String(120), nullable=True),
            sa.Column("session_id", sa.String(180), nullable=True, index=True),
            sa.Column("device_fingerprint", sa.String(180), nullable=True, index=True),
            sa.Column("nb_echecs_successifs", sa.Integer, nullable=True),
            sa.Column("severite", sa.String(30), nullable=True, index=True),
            sa.Column("action_remediation", sa.String(220), nullable=True),
            sa.Column("meta_json", sa.String(200), nullable=True),
            sa.Column("hash_self", sa.String(80), nullable=True, index=True),
            sa.Column("hash_prev", sa.String(80), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )

    if not _has("trace_anti_tampering"):
        op.create_table(
            "trace_anti_tampering",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_alerte", sa.String(140), nullable=False, index=True),
            sa.Column("type_alerte", sa.String(80), nullable=False, index=True),
            sa.Column("date_detection", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("severite", sa.String(40), nullable=True, index=True),
            sa.Column("asset_type", sa.String(80), nullable=True, index=True),
            sa.Column("asset_ref", sa.String(180), nullable=True, index=True),
            sa.Column("attendu_hash", sa.String(80), nullable=True, index=True),
            sa.Column("constate_hash", sa.String(80), nullable=True, index=True),
            sa.Column("delta_description", sa.String(200), nullable=True),
            sa.Column("detection_source", sa.String(180), nullable=True),
            sa.Column("investigateur_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("actions_correctives", sa.String(200), nullable=True),
            sa.Column("escalation_autorite", sa.Boolean, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_alerte", name="uix_trace_anti_tamp_ref"),
        )

    if not _has("trace_audit_logs"):
        op.create_table(
            "trace_audit_logs",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=True, index=True),
            sa.Column("event_uid", sa.String(80), nullable=True, index=True),
            sa.Column("actor_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("actor_email", sa.String(180), nullable=True, index=True),
            sa.Column("actor_ip", sa.String(60), nullable=True, index=True),
            sa.Column("user_agent", sa.String(280), nullable=True),
            sa.Column("action", sa.String(80), nullable=True, index=True),
            sa.Column("resource_type", sa.String(80), nullable=True, index=True),
            sa.Column("resource_id", sa.String(180), nullable=True, index=True),
            sa.Column("before_snapshot", sa.String(200), nullable=True),
            sa.Column("after_snapshot", sa.String(200), nullable=True),
            sa.Column("raison_metier", sa.String(220), nullable=True),
            sa.Column("timestamp_server", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("hash_self", sa.String(80), nullable=True, index=True),
            sa.Column("hash_prev", sa.String(80), nullable=True, index=True),
            sa.Column("merkle_root", sa.String(80), nullable=True, index=True),
            sa.Column("validite", sa.Boolean, nullable=True),
            sa.Column("session_id", sa.String(180), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )

    if not _has("trace_batch_genealogy"):
        op.create_table(
            "trace_batch_genealogy",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("child_lot", sa.String(180), nullable=False, index=True),
            sa.Column("child_type", sa.String(80), nullable=True, index=True),
            sa.Column("parent_lot", sa.String(180), nullable=False, index=True),
            sa.Column("parent_type", sa.String(80), nullable=True, index=True),
            sa.Column("proportion", sa.Numeric, nullable=True),
            sa.Column("quantite_mise_en_oeuvre", sa.Numeric, nullable=True),
            sa.Column("unite", sa.String(40), nullable=True),
            sa.Column("date_integration", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("operation", sa.String(120), nullable=True),
            sa.Column("operateur", sa.String(180), nullable=True),
            sa.Column("atelier", sa.String(180), nullable=True, index=True),
            sa.Column("certificate_url", sa.String(280), nullable=True),
            sa.Column("hash_certificat", sa.String(80), nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "child_lot", "parent_lot", name="uix_trace_batch_lineage"),
        )

    if not _has("trace_cargo_handoffs"):
        op.create_table(
            "trace_cargo_handoffs",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_handoff", sa.String(140), nullable=False, index=True),
            sa.Column("type_cargo", sa.String(80), nullable=True, index=True),
            sa.Column("cargo_ref", sa.String(180), nullable=True, index=True),
            sa.Column("mode_precedent", sa.String(60), nullable=True, index=True),
            sa.Column("mode_suivant", sa.String(60), nullable=True, index=True),
            sa.Column("transporteur_precedent", sa.String(180), nullable=True, index=True),
            sa.Column("transporteur_suivant", sa.String(180), nullable=True, index=True),
            sa.Column("lieu_handoff", sa.String(220), nullable=True, index=True),
            sa.Column("date_debut_prise_en_charge", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_fin_prise_en_charge", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("poids_kg", sa.Numeric, nullable=True),
            sa.Column("volume_m3", sa.Numeric, nullable=True),
            sa.Column("nb_colis", sa.Integer, nullable=True),
            sa.Column("temperature_c", sa.Numeric, nullable=True),
            sa.Column("etat_entree", sa.String(80), nullable=True),
            sa.Column("etat_sortie", sa.String(80), nullable=True),
            sa.Column("anomalies_constatees", sa.String(200), nullable=True),
            sa.Column("photos_url", sa.String(200), nullable=True),
            sa.Column("signataire_entree", sa.String(180), nullable=True),
            sa.Column("signataire_sortie", sa.String(180), nullable=True),
            sa.Column("hash_handoff", sa.String(80), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_handoff", name="uix_trace_handoff_ref"),
        )

    if not _has("trace_cold_chain"):
        op.create_table(
            "trace_cold_chain",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("subject_type", sa.String(80), nullable=False, index=True),
            sa.Column("subject_ref", sa.String(180), nullable=False, index=True),
            sa.Column("logger_id", sa.String(180), nullable=True, index=True),
            sa.Column("date_lecture", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("temperature_c", sa.Numeric, nullable=True, index=True),
            sa.Column("humidite_pct", sa.Numeric, nullable=True),
            sa.Column("co2_ppm", sa.Integer, nullable=True),
            sa.Column("o2_pct", sa.Numeric, nullable=True),
            sa.Column("pression_bar", sa.Numeric, nullable=True),
            sa.Column("seuil_min_c", sa.Numeric, nullable=True),
            sa.Column("seuil_max_c", sa.Numeric, nullable=True),
            sa.Column("excursion", sa.Boolean, nullable=True, index=True),
            sa.Column("porte_ouverte", sa.Boolean, nullable=True),
            sa.Column("duree_porte_ouverte_s", sa.Integer, nullable=True),
            sa.Column("device_battery_pct", sa.Numeric, nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        )

    if not _has("trace_consents"):
        op.create_table(
            "trace_consents",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_consentement", sa.String(140), nullable=False, index=True),
            sa.Column("subject_type", sa.String(60), nullable=True, index=True),
            sa.Column("subject_ref", sa.String(180), nullable=True, index=True),
            sa.Column("finalite", sa.String(220), nullable=True),
            sa.Column("categorie_donnees", sa.String(220), nullable=True),
            sa.Column("duree_conservation_mois", sa.Integer, nullable=True),
            sa.Column("tiers_partagables", sa.String(200), nullable=True),
            sa.Column("date_consente", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_retiree", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("canal_recueil", sa.String(80), nullable=True),
            sa.Column("ip_recueil", sa.String(60), nullable=True, index=True),
            sa.Column("preuve_url", sa.String(280), nullable=True),
            sa.Column("hash_preuve", sa.String(80), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_consentement", name="uix_trace_consent_ref"),
        )

    if not _has("trace_container_seals"):
        op.create_table(
            "trace_container_seals",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("numero_sceau", sa.String(120), nullable=False, index=True),
            sa.Column("type_sceau", sa.String(80), nullable=True, index=True),
            sa.Column("conteneur_numero", sa.String(120), nullable=True, index=True),
            sa.Column("b_l_numero", sa.String(120), nullable=True, index=True),
            sa.Column("date_apposition", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("lieu_apposition", sa.String(220), nullable=True),
            sa.Column("operateur_apposition", sa.String(180), nullable=True),
            sa.Column("signature_url", sa.String(280), nullable=True),
            sa.Column("photo_url", sa.String(280), nullable=True),
            sa.Column("date_retrait", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("lieu_retrait", sa.String(220), nullable=True),
            sa.Column("operateur_retrait", sa.String(180), nullable=True),
            sa.Column("numero_recolte", sa.String(120), nullable=True, index=True),
            sa.Column("integrite_verifiee", sa.Boolean, nullable=True),
            sa.Column("anomalie_sceau", sa.String(220), nullable=True),
            sa.Column("autorite_alertee", sa.String(180), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "numero_sceau", name="uix_trace_seal_num"),
        )

    if not _has("trace_custody_transfers"):
        op.create_table(
            "trace_custody_transfers",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_transfert", sa.String(140), nullable=False, index=True),
            sa.Column("asset_type", sa.String(80), nullable=False, index=True),
            sa.Column("asset_ref", sa.String(180), nullable=False, index=True),
            sa.Column("lot_ref", sa.String(180), nullable=True, index=True),
            sa.Column("source_party", sa.String(180), nullable=True, index=True),
            sa.Column("source_contact", sa.String(180), nullable=True),
            sa.Column("target_party", sa.String(180), nullable=True, index=True),
            sa.Column("target_contact", sa.String(180), nullable=True),
            sa.Column("type_transfert", sa.String(80), nullable=True, index=True),
            sa.Column("date_transfert", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("lieu", sa.String(220), nullable=True),
            sa.Column("gps_lat", sa.Numeric, nullable=True),
            sa.Column("gps_lng", sa.Numeric, nullable=True),
            sa.Column("quantite_transferee", sa.Numeric, nullable=True),
            sa.Column("unite", sa.String(40), nullable=True),
            sa.Column("poids_kg", sa.Numeric, nullable=True),
            sa.Column("etat_reception", sa.String(80), nullable=True),
            sa.Column("anomalies", sa.String(200), nullable=True),
            sa.Column("photos_url", sa.String(200), nullable=True),
            sa.Column("signature_source_url", sa.String(280), nullable=True),
            sa.Column("signature_target_url", sa.String(280), nullable=True),
            sa.Column("hash_transfert", sa.String(80), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_transfert", name="uix_trace_custody_ref"),
        )

    if not _has("trace_document_hashes"):
        op.create_table(
            "trace_document_hashes",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("document_ref", sa.String(180), nullable=False, index=True),
            sa.Column("document_type", sa.String(80), nullable=True, index=True),
            sa.Column("version", sa.Integer, nullable=False),
            sa.Column("url", sa.String(280), nullable=True),
            sa.Column("mime", sa.String(80), nullable=True),
            sa.Column("taille_octets", sa.Integer, nullable=True),
            sa.Column("hash_algo", sa.String(40), nullable=True),
            sa.Column("hash_hex", sa.String(128), nullable=True, index=True),
            sa.Column("merkle_root", sa.String(80), nullable=True, index=True),
            sa.Column("signature_url", sa.String(280), nullable=True),
            sa.Column("signer_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("date_emission", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("date_signature", sa.DateTime(timezone=True), nullable=True),
            sa.Column("date_archivage", sa.Date, nullable=True),
            sa.Column("duree_conservation_ans", sa.Integer, nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "document_ref", "version", name="uix_trace_doc_version"),
        )

    if not _has("trace_events"):
        op.create_table(
            "trace_events",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("event_uid", sa.String(80), nullable=False, index=True),
            sa.Column("event_type", sa.String(120), nullable=False, index=True),
            sa.Column("module_source", sa.String(80), nullable=True, index=True),
            sa.Column("asset_type", sa.String(80), nullable=True, index=True),
            sa.Column("asset_id", sa.String(180), nullable=True, index=True),
            sa.Column("subject_ref", sa.String(180), nullable=True, index=True),
            sa.Column("action", sa.String(120), nullable=True),
            sa.Column("payload_json", sa.String(200), nullable=True),
            sa.Column("actor_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("actor_ip", sa.String(60), nullable=True, index=True),
            sa.Column("actor_user_agent", sa.String(280), nullable=True),
            sa.Column("actor_role", sa.String(120), nullable=True),
            sa.Column("correlation_id", sa.String(120), nullable=True, index=True),
            sa.Column("gps_lat", sa.Numeric, nullable=True),
            sa.Column("gps_lng", sa.Numeric, nullable=True),
            sa.Column("timestamp_server", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("timestamp_client", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("hash_self", sa.String(80), nullable=True, index=True),
            sa.Column("hash_prev", sa.String(80), nullable=True, index=True),
            sa.Column("signature_id", sa.Integer, sa.ForeignKey("trace_witness_signatures.id"), nullable=True, index=True),
            sa.Column("est_validite", sa.Boolean, nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "event_uid", name="uix_trace_event_uid"),
        )

    if not _has("trace_geolocations"):
        op.create_table(
            "trace_geolocations",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("subject_type", sa.String(80), nullable=False, index=True),
            sa.Column("subject_ref", sa.String(180), nullable=False, index=True),
            sa.Column("date_position", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("gps_lat", sa.Numeric, nullable=False, index=True),
            sa.Column("gps_lng", sa.Numeric, nullable=False, index=True),
            sa.Column("altitude_m", sa.Numeric, nullable=True),
            sa.Column("vitesse_kmh", sa.Numeric, nullable=True),
            sa.Column("cap_deg", sa.Numeric, nullable=True),
            sa.Column("precision_m", sa.Numeric, nullable=True),
            sa.Column("source", sa.String(80), nullable=True, index=True),
            sa.Column("device_id", sa.String(180), nullable=True, index=True),
            sa.Column("geofence_id", sa.Integer, nullable=True, index=True),
            sa.Column("franchissement", sa.String(80), nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        )

    if not _has("trace_incident_commands"):
        op.create_table(
            "trace_incident_commands",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_incident", sa.String(140), nullable=False, index=True),
            sa.Column("type_incident", sa.String(80), nullable=False, index=True),
            sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("date_fin", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("severite", sa.String(30), nullable=True, index=True),
            sa.Column("description", sa.String(200), nullable=True),
            sa.Column("lieu", sa.String(220), nullable=True),
            sa.Column("gps_lat", sa.Numeric, nullable=True),
            sa.Column("gps_lng", sa.Numeric, nullable=True),
            sa.Column("chef_secours", sa.String(180), nullable=True),
            sa.Column("autorite_alertee", sa.String(220), nullable=True),
            sa.Column("decisions_prises", sa.String(200), nullable=True),
            sa.Column("ressources_engagees", sa.String(200), nullable=True),
            sa.Column("victimes", sa.Integer, nullable=True),
            sa.Column("dommages_materials_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("arret_activite", sa.Boolean, nullable=True),
            sa.Column("communication_presse", sa.Boolean, nullable=True),
            sa.Column("rapport_final_url", sa.String(280), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_incident", name="uix_trace_incident_ref"),
        )

    if not _has("trace_merkle_proofs"):
        op.create_table(
            "trace_merkle_proofs",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("racine_type", sa.String(60), nullable=False, index=True),
            sa.Column("periode", sa.String(20), nullable=False, index=True),
            sa.Column("nb_leaves", sa.Integer, nullable=True),
            sa.Column("merkle_root", sa.String(80), nullable=True, index=True),
            sa.Column("first_leaf_hash", sa.String(80), nullable=True, index=True),
            sa.Column("last_leaf_hash", sa.String(80), nullable=True, index=True),
            sa.Column("chemin_verification", sa.String(200), nullable=True),
            sa.Column("date_publication", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("tsa_id", sa.Integer, sa.ForeignKey("trace_timestamps.id"), nullable=True, index=True),
            sa.Column("publication_externe", sa.String(220), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "periode", "racine_type", name="uix_trace_merkle_period"),
        )

    if not _has("trace_regulatory_exports"):
        op.create_table(
            "trace_regulatory_exports",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("numero_expedition", sa.String(140), nullable=False, index=True),
            sa.Column("autorite_destinataire", sa.String(180), nullable=False, index=True),
            sa.Column("type_declaration", sa.String(120), nullable=True, index=True),
            sa.Column("periode_reference", sa.String(20), nullable=True, index=True),
            sa.Column("date_depot", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("canaux", sa.String(120), nullable=True),
            sa.Column("nb_lignes", sa.Integer, nullable=True),
            sa.Column("montant_declare_xaf", sa.Numeric(18, 2), nullable=True),
            sa.Column("fichier_url", sa.String(280), nullable=True),
            sa.Column("fichier_hash", sa.String(80), nullable=True, index=True),
            sa.Column("numero_recu", sa.String(140), nullable=True, index=True),
            sa.Column("date_recu", sa.DateTime(timezone=True), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("reponse_autorite", sa.String(200), nullable=True),
            sa.Column("anomalies", sa.String(200), nullable=True),
            sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "numero_expedition", name="uix_trace_reg_export"),
        )

    if not _has("trace_retention_policies"):
        op.create_table(
            "trace_retention_policies",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("code_politique", sa.String(120), nullable=False, index=True),
            sa.Column("type_objet", sa.String(120), nullable=True, index=True),
            sa.Column("duree_conservation_ans", sa.Integer, nullable=True, index=True),
            sa.Column("autorite_legale", sa.String(180), nullable=True),
            sa.Column("base_texte", sa.String(280), nullable=True),
            sa.Column("archive_apres_echeance", sa.Boolean, nullable=True),
            sa.Column("destruction_apres_echeance", sa.Boolean, nullable=True),
            sa.Column("modalite_destruction", sa.String(180), nullable=True),
            sa.Column("destination_archive", sa.String(180), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "code_politique", name="uix_trace_retention_code"),
        )

    if not _has("trace_serial_genealogy"):
        op.create_table(
            "trace_serial_genealogy",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("child_serial", sa.String(180), nullable=False, index=True),
            sa.Column("parent_serial", sa.String(180), nullable=False, index=True),
            sa.Column("relation_type", sa.String(80), nullable=True, index=True),
            sa.Column("date_integration", sa.DateTime(timezone=True), nullable=True, index=True),
            sa.Column("lieu_integration", sa.String(220), nullable=True),
            sa.Column("operateur_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True, index=True),
            sa.Column("ordre_assemblage", sa.Integer, nullable=True),
            sa.Column("notes", sa.String(200), nullable=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "child_serial", "parent_serial", name="uix_trace_serial_lineage"),
        )

    if not _has("trace_timestamps"):
        op.create_table(
            "trace_timestamps",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("token_tsa", sa.String(140), nullable=False, index=True),
            sa.Column("autorite_certification", sa.String(180), nullable=True, index=True),
            sa.Column("algorithme_signature", sa.String(60), nullable=True),
            sa.Column("objet_type", sa.String(80), nullable=True, index=True),
            sa.Column("objet_ref", sa.String(180), nullable=True, index=True),
            sa.Column("objet_hash", sa.String(128), nullable=True, index=True),
            sa.Column("date_horodatage", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("precision_seconde", sa.Integer, nullable=True),
            sa.Column("certificate_serial", sa.String(180), nullable=True, index=True),
            sa.Column("certificate_issuer", sa.String(220), nullable=True),
            sa.Column("certificate_valide_jusqu", sa.Date, nullable=True),
            sa.Column("token_blob", sa.String(200), nullable=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "token_tsa", name="uix_trace_tsa_token"),
        )

    if not _has("trace_witness_signatures"):
        op.create_table(
            "trace_witness_signatures",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("company_id", sa.Integer, sa.ForeignKey("companies.id"), nullable=False, index=True),
            sa.Column("reference_signature", sa.String(140), nullable=False, index=True),
            sa.Column("type_signataire", sa.String(60), nullable=True, index=True),
            sa.Column("signataire_nom", sa.String(180), nullable=True),
            sa.Column("signataire_qualite", sa.String(180), nullable=True),
            sa.Column("signataire_email", sa.String(180), nullable=True, index=True),
            sa.Column("signataire_telephone", sa.String(60), nullable=True),
            sa.Column("piece_identite_ref", sa.String(120), nullable=True, index=True),
            sa.Column("document_ref", sa.String(180), nullable=True, index=True),
            sa.Column("event_uid", sa.String(80), nullable=True, index=True),
            sa.Column("type_signature", sa.String(60), nullable=True, index=True),
            sa.Column("signature_blob_url", sa.String(280), nullable=True),
            sa.Column("hash_signature", sa.String(128), nullable=True, index=True),
            sa.Column("date_signature", sa.DateTime(timezone=True), nullable=False, index=True),
            sa.Column("gps_lat", sa.Numeric, nullable=True),
            sa.Column("gps_lng", sa.Numeric, nullable=True),
            sa.Column("ip_signature", sa.String(60), nullable=True, index=True),
            sa.Column("tsa_id", sa.Integer, sa.ForeignKey("trace_timestamps.id"), nullable=True, index=True),
            sa.Column("statut", sa.String(40), nullable=True, index=True),
            sa.Column("is_active", sa.Boolean, nullable=True, index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.UniqueConstraint("company_id", "reference_signature", name="uix_trace_sig_ref"),
        )



def downgrade():
    for name in reversed(TABLES):
        if _has(name):
            op.drop_table(name)
