/**
 * Configs Registre pour tracabilite (expansion wave 6 generee).
 *
 * Chaque ConfigRegistre est passe en prop au composant generique
 * <RegistreGenerique /> pour rendre table, filtres, formulaire.
 */
"use client";

import * as Icons from 'lucide-react';
import type { ConfigRegistre, ColonneRegistre, ChampRegistre, FiltreRegistre } from '@/components/registre-generique/typesRegistre';
import { registreAPI } from '@/lib/api-client';

const api = registreAPI("tracabilite");

function col(name: string, label: string, labelEn: string, opts: Partial<ColonneRegistre> = {}): ColonneRegistre {
  return { name, label, labelEn, ...opts } as ColonneRegistre;
}

function txt(name: string, label: string, labelEn: string, opts: Partial<ChampRegistre> = {}): ChampRegistre {
  return { name, label, labelEn, type: "texte", ...opts } as ChampRegistre;
}

function num(name: string, label: string, labelEn: string, opts: Partial<ChampRegistre> = {}): ChampRegistre {
  return { name, label, labelEn, type: "nombre", ...opts } as ChampRegistre;
}

function dt(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}

function dtx(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "date" } as ChampRegistre;
}

function area(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "zone" } as ChampRegistre;
}

function chk(name: string, label: string, labelEn: string): ChampRegistre {
  return { name, label, labelEn, type: "booleen" } as ChampRegistre;
}

function filtreSel(name: string, label: string, labelEn: string, nomKey: string): FiltreRegistre {
  return { name, label, labelEn, type: "select", nomenclature: nomKey } as FiltreRegistre;
}


export const registreTraceEvent: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "events",
  tcode: "registre-events",
  icon: Icons.Activity,
  titre: "Evenement tracabilite",
  titreEn: "Traceability event",
  description: "Evenement immuable signe (hash chain).",
  descriptionEn: "Immutable signed event (hash chain).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("events", params),
  creer: (data) => api.creer("events", data),
  modifier: (id, data) => api.modifier("events", id, data),
  unicite: "event_uid",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("event_uid", "Event Uid", "Event Uid"),
    col("event_type", "Event Type", "Event Type"),
    col("module_source", "Module Source", "Module Source"),
    col("asset_type", "Asset Type", "Asset Type"),
    col("asset_id", "Asset Id", "Asset Id"),
    col("subject_ref", "Subject Ref", "Subject Ref"),
    col("action", "Action", "Action"),
    col("payload_json", "Payload Json", "Payload Json"),
    col("actor_id", "Actor Id", "Actor Id"),
    col("actor_ip", "Actor Ip", "Actor Ip"),
    col("actor_user_agent", "Actor User Agent", "Actor User Agent"),
    col("actor_role", "Actor Role", "Actor Role"),
    col("correlation_id", "Correlation Id", "Correlation Id"),
    col("gps_lat", "Gps Lat", "Gps Lat"),
    col("gps_lng", "Gps Lng", "Gps Lng"),
    col("timestamp_server", "Timestamp Server", "Timestamp Server"),
    col("timestamp_client", "Timestamp Client", "Timestamp Client"),
    col("hash_self", "Hash Self", "Hash Self"),
    col("hash_prev", "Hash Prev", "Hash Prev"),
    col("signature_id", "Signature Id", "Signature Id"),
    col("est_validite", "Est Validite", "Est Validite"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("event_uid", "Event Uid", "Event Uid", { requisCreation: true }),
    txt("event_type", "Event Type", "Event Type"),
    txt("module_source", "Module Source", "Module Source"),
    txt("asset_type", "Asset Type", "Asset Type"),
    txt("asset_id", "Asset Id", "Asset Id"),
    txt("subject_ref", "Subject Ref", "Subject Ref"),
    txt("action", "Action", "Action"),
    area("payload_json", "Payload Json", "Payload Json"),
    num("actor_id", "Actor Id", "Actor Id"),
    txt("actor_ip", "Actor Ip", "Actor Ip"),
    txt("actor_user_agent", "Actor User Agent", "Actor User Agent"),
    txt("actor_role", "Actor Role", "Actor Role"),
    txt("correlation_id", "Correlation Id", "Correlation Id"),
    num("gps_lat", "Gps Lat", "Gps Lat"),
    num("gps_lng", "Gps Lng", "Gps Lng"),
    dtx("timestamp_server", "Timestamp Server", "Timestamp Server"),
    dtx("timestamp_client", "Timestamp Client", "Timestamp Client"),
    txt("hash_self", "Hash Self", "Hash Self"),
    txt("hash_prev", "Hash Prev", "Hash Prev"),
    num("signature_id", "Signature Id", "Signature Id"),
    chk("est_validite", "Est Validite", "Est Validite"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreCustody: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "custody_transfers",
  tcode: "registre-custody-transfers",
  icon: Icons.ArrowLeftRight,
  titre: "Chaine de custody",
  titreEn: "Chain of custody",
  description: "Transfert de responsabilite entre parties.",
  descriptionEn: "Responsibility handoff between parties.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("custody-transfers", params),
  creer: (data) => api.creer("custody-transfers", data),
  modifier: (id, data) => api.modifier("custody-transfers", id, data),
  unicite: "reference_transfert",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_transfert", "Reference Transfert", "Reference Transfert"),
    col("asset_type", "Asset Type", "Asset Type"),
    col("asset_ref", "Asset Ref", "Asset Ref"),
    col("lot_ref", "Lot Ref", "Lot Ref"),
    col("source_party", "Source Party", "Source Party"),
    col("source_contact", "Source Contact", "Source Contact"),
    col("target_party", "Target Party", "Target Party"),
    col("target_contact", "Target Contact", "Target Contact"),
    col("type_transfert", "Type Transfert", "Type Transfert"),
    col("date_transfert", "Date Transfert", "Date Transfert"),
    col("lieu", "Lieu", "Lieu"),
    col("gps_lat", "Gps Lat", "Gps Lat"),
    col("gps_lng", "Gps Lng", "Gps Lng"),
    col("quantite_transferee", "Quantite Transferee", "Quantite Transferee"),
    col("unite", "Unite", "Unite"),
    col("poids_kg", "Poids Kg", "Poids Kg"),
    col("etat_reception", "Etat Reception", "Etat Reception"),
    col("anomalies", "Anomalies", "Anomalies"),
    col("photos_url", "Photos Url", "Photos Url"),
    col("signature_source_url", "Signature Source Url", "Signature Source Url"),
    col("signature_target_url", "Signature Target Url", "Signature Target Url"),
    col("hash_transfert", "Hash Transfert", "Hash Transfert"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_transfert", "Reference Transfert", "Reference Transfert", { requisCreation: true }),
    txt("asset_type", "Asset Type", "Asset Type"),
    txt("asset_ref", "Asset Ref", "Asset Ref"),
    txt("lot_ref", "Lot Ref", "Lot Ref"),
    txt("source_party", "Source Party", "Source Party"),
    txt("source_contact", "Source Contact", "Source Contact"),
    txt("target_party", "Target Party", "Target Party"),
    txt("target_contact", "Target Contact", "Target Contact"),
    txt("type_transfert", "Type Transfert", "Type Transfert"),
    dtx("date_transfert", "Date Transfert", "Date Transfert"),
    txt("lieu", "Lieu", "Lieu"),
    num("gps_lat", "Gps Lat", "Gps Lat"),
    num("gps_lng", "Gps Lng", "Gps Lng"),
    num("quantite_transferee", "Quantite Transferee", "Quantite Transferee"),
    txt("unite", "Unite", "Unite"),
    num("poids_kg", "Poids Kg", "Poids Kg"),
    txt("etat_reception", "Etat Reception", "Etat Reception"),
    area("anomalies", "Anomalies", "Anomalies"),
    area("photos_url", "Photos Url", "Photos Url"),
    txt("signature_source_url", "Signature Source Url", "Signature Source Url"),
    txt("signature_target_url", "Signature Target Url", "Signature Target Url"),
    txt("hash_transfert", "Hash Transfert", "Hash Transfert"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreBatchGenealogy: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "batch_genealogy",
  tcode: "registre-batch-genealogy",
  icon: Icons.Layers,
  titre: "Genealogie lot",
  titreEn: "Batch genealogy",
  description: "Filiation parent/enfant (melange, conditionnement).",
  descriptionEn: "Parent/child lineage (blend, packing).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("batch-genealogy", params),
  creer: (data) => api.creer("batch-genealogy", data),
  modifier: (id, data) => api.modifier("batch-genealogy", id, data),
  unicite: "child_lot",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("child_lot", "Child Lot", "Child Lot"),
    col("child_type", "Child Type", "Child Type"),
    col("parent_lot", "Parent Lot", "Parent Lot"),
    col("parent_type", "Parent Type", "Parent Type"),
    col("proportion", "Proportion", "Proportion"),
    col("quantite_mise_en_oeuvre", "Quantite Mise En Oeuvre", "Quantite Mise En Oeuvre"),
    col("unite", "Unite", "Unite"),
    col("date_integration", "Date Integration", "Date Integration"),
    col("operation", "Operation", "Operation"),
    col("operateur", "Operateur", "Operateur"),
    col("atelier", "Atelier", "Atelier"),
    col("certificate_url", "Certificate Url", "Certificate Url"),
    col("hash_certificat", "Hash Certificat", "Hash Certificat"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("child_lot", "Child Lot", "Child Lot", { requisCreation: true }),
    txt("child_type", "Child Type", "Child Type"),
    txt("parent_lot", "Parent Lot", "Parent Lot"),
    txt("parent_type", "Parent Type", "Parent Type"),
    num("proportion", "Proportion", "Proportion"),
    num("quantite_mise_en_oeuvre", "Quantite Mise En Oeuvre", "Quantite Mise En Oeuvre"),
    txt("unite", "Unite", "Unite"),
    dtx("date_integration", "Date Integration", "Date Integration"),
    txt("operation", "Operation", "Operation"),
    txt("operateur", "Operateur", "Operateur"),
    txt("atelier", "Atelier", "Atelier"),
    txt("certificate_url", "Certificate Url", "Certificate Url"),
    txt("hash_certificat", "Hash Certificat", "Hash Certificat"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreSerialGenealogy: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "serial_genealogy",
  tcode: "registre-serial-genealogy",
  icon: Icons.Hash,
  titre: "Genealogie serial",
  titreEn: "Serial genealogy",
  description: "Filiation par numero de serial unitaire.",
  descriptionEn: "Lineage by unique serial.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("serial-genealogy", params),
  creer: (data) => api.creer("serial-genealogy", data),
  modifier: (id, data) => api.modifier("serial-genealogy", id, data),
  unicite: "child_serial",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("child_serial", "Child Serial", "Child Serial"),
    col("parent_serial", "Parent Serial", "Parent Serial"),
    col("relation_type", "Relation Type", "Relation Type"),
    col("date_integration", "Date Integration", "Date Integration"),
    col("lieu_integration", "Lieu Integration", "Lieu Integration"),
    col("operateur_id", "Operateur Id", "Operateur Id"),
    col("ordre_assemblage", "Ordre Assemblage", "Ordre Assemblage"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("child_serial", "Child Serial", "Child Serial", { requisCreation: true }),
    txt("parent_serial", "Parent Serial", "Parent Serial"),
    txt("relation_type", "Relation Type", "Relation Type"),
    dtx("date_integration", "Date Integration", "Date Integration"),
    txt("lieu_integration", "Lieu Integration", "Lieu Integration"),
    num("operateur_id", "Operateur Id", "Operateur Id"),
    num("ordre_assemblage", "Ordre Assemblage", "Ordre Assemblage"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreDocHash: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "document_hashes",
  tcode: "registre-document-hashes",
  icon: Icons.FileDigit,
  titre: "Empreinte document",
  titreEn: "Document hash",
  description: "Hash d'integrite versionne d'un document.",
  descriptionEn: "Versioned integrity hash of a document.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("document-hashes", params),
  creer: (data) => api.creer("document-hashes", data),
  modifier: (id, data) => api.modifier("document-hashes", id, data),
  unicite: "document_ref",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("document_ref", "Document Ref", "Document Ref"),
    col("document_type", "Document Type", "Document Type"),
    col("version", "Version", "Version"),
    col("url", "Url", "Url"),
    col("mime", "Mime", "Mime"),
    col("taille_octets", "Taille Octets", "Taille Octets"),
    col("hash_algo", "Hash Algo", "Hash Algo"),
    col("hash_hex", "Hash Hex", "Hash Hex"),
    col("merkle_root", "Merkle Root", "Merkle Root"),
    col("signature_url", "Signature Url", "Signature Url"),
    col("signer_id", "Signer Id", "Signer Id"),
    col("date_emission", "Date Emission", "Date Emission"),
    col("date_signature", "Date Signature", "Date Signature"),
    col("date_archivage", "Date Archivage", "Date Archivage"),
    col("duree_conservation_ans", "Duree Conservation Ans", "Duree Conservation Ans"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("document_ref", "Document Ref", "Document Ref", { requisCreation: true }),
    txt("document_type", "Document Type", "Document Type"),
    num("version", "Version", "Version"),
    txt("url", "Url", "Url"),
    txt("mime", "Mime", "Mime"),
    num("taille_octets", "Taille Octets", "Taille Octets"),
    txt("hash_algo", "Hash Algo", "Hash Algo"),
    txt("hash_hex", "Hash Hex", "Hash Hex"),
    txt("merkle_root", "Merkle Root", "Merkle Root"),
    txt("signature_url", "Signature Url", "Signature Url"),
    num("signer_id", "Signer Id", "Signer Id"),
    dtx("date_emission", "Date Emission", "Date Emission"),
    dtx("date_signature", "Date Signature", "Date Signature"),
    dt("date_archivage", "Date Archivage", "Date Archivage"),
    num("duree_conservation_ans", "Duree Conservation Ans", "Duree Conservation Ans"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreGeolocation: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "geolocations",
  tcode: "registre-geolocations",
  icon: Icons.MapPin,
  titre: "Trace geolocalisation",
  titreEn: "Geolocation trace",
  description: "Position GPS horodatee d'un sujet.",
  descriptionEn: "Timestamped GPS position.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("geolocations", params),
  creer: (data) => api.creer("geolocations", data),
  modifier: (id, data) => api.modifier("geolocations", id, data),
  unicite: "subject_type",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("subject_type", "Subject Type", "Subject Type"),
    col("subject_ref", "Subject Ref", "Subject Ref"),
    col("date_position", "Date Position", "Date Position"),
    col("gps_lat", "Gps Lat", "Gps Lat"),
    col("gps_lng", "Gps Lng", "Gps Lng"),
    col("altitude_m", "Altitude M", "Altitude M"),
    col("vitesse_kmh", "Vitesse Kmh", "Vitesse Kmh"),
    col("cap_deg", "Cap Deg", "Cap Deg"),
    col("precision_m", "Precision M", "Precision M"),
    col("source", "Source", "Source"),
    col("device_id", "Device Id", "Device Id"),
    col("geofence_id", "Geofence Id", "Geofence Id"),
    col("franchissement", "Franchissement", "Franchissement"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("subject_type", "Subject Type", "Subject Type", { requisCreation: true }),
    txt("subject_ref", "Subject Ref", "Subject Ref"),
    dtx("date_position", "Date Position", "Date Position"),
    num("gps_lat", "Gps Lat", "Gps Lat"),
    num("gps_lng", "Gps Lng", "Gps Lng"),
    num("altitude_m", "Altitude M", "Altitude M"),
    num("vitesse_kmh", "Vitesse Kmh", "Vitesse Kmh"),
    num("cap_deg", "Cap Deg", "Cap Deg"),
    num("precision_m", "Precision M", "Precision M"),
    txt("source", "Source", "Source"),
    txt("device_id", "Device Id", "Device Id"),
    num("geofence_id", "Geofence Id", "Geofence Id"),
    txt("franchissement", "Franchissement", "Franchissement"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreColdChain: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "cold_chain",
  tcode: "registre-cold-chain",
  icon: Icons.Snowflake,
  titre: "Chaine du froid",
  titreEn: "Cold chain trace",
  description: "Releves temperature le long du parcours.",
  descriptionEn: "Temperature readings along the journey.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("cold-chain", params),
  creer: (data) => api.creer("cold-chain", data),
  modifier: (id, data) => api.modifier("cold-chain", id, data),
  unicite: "subject_ref",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("subject_type", "Subject Type", "Subject Type"),
    col("subject_ref", "Subject Ref", "Subject Ref"),
    col("logger_id", "Logger Id", "Logger Id"),
    col("date_lecture", "Date Lecture", "Date Lecture"),
    col("temperature_c", "Temperature C", "Temperature C"),
    col("humidite_pct", "Humidite Pct", "Humidite Pct"),
    col("co2_ppm", "Co2 Ppm", "Co2 Ppm"),
    col("o2_pct", "O2 Pct", "O2 Pct"),
    col("pression_bar", "Pression Bar", "Pression Bar"),
    col("seuil_min_c", "Seuil Min C", "Seuil Min C"),
    col("seuil_max_c", "Seuil Max C", "Seuil Max C"),
    col("excursion", "Excursion", "Excursion"),
    col("porte_ouverte", "Porte Ouverte", "Porte Ouverte"),
    col("duree_porte_ouverte_s", "Duree Porte Ouverte S", "Duree Porte Ouverte S"),
    col("device_battery_pct", "Device Battery Pct", "Device Battery Pct"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("subject_type", "Subject Type", "Subject Type"),
    txt("subject_ref", "Subject Ref", "Subject Ref", { requisCreation: true }),
    txt("logger_id", "Logger Id", "Logger Id"),
    dtx("date_lecture", "Date Lecture", "Date Lecture"),
    num("temperature_c", "Temperature C", "Temperature C"),
    num("humidite_pct", "Humidite Pct", "Humidite Pct"),
    num("co2_ppm", "Co2 Ppm", "Co2 Ppm"),
    num("o2_pct", "O2 Pct", "O2 Pct"),
    num("pression_bar", "Pression Bar", "Pression Bar"),
    num("seuil_min_c", "Seuil Min C", "Seuil Min C"),
    num("seuil_max_c", "Seuil Max C", "Seuil Max C"),
    chk("excursion", "Excursion", "Excursion"),
    chk("porte_ouverte", "Porte Ouverte", "Porte Ouverte"),
    num("duree_porte_ouverte_s", "Duree Porte Ouverte S", "Duree Porte Ouverte S"),
    num("device_battery_pct", "Device Battery Pct", "Device Battery Pct"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreIncident: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "incidents",
  tcode: "registre-incidents",
  icon: Icons.Siren,
  titre: "Post commandement incident",
  titreEn: "Incident chain of command",
  description: "Chaine de decision / gestion de crise.",
  descriptionEn: "Decision chain / crisis management.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("incidents", params),
  creer: (data) => api.creer("incidents", data),
  modifier: (id, data) => api.modifier("incidents", id, data),
  unicite: "reference_incident",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_incident", "Reference Incident", "Reference Incident"),
    col("type_incident", "Type Incident", "Type Incident"),
    col("date_debut", "Date Debut", "Date Debut"),
    col("date_fin", "Date Fin", "Date Fin"),
    col("severite", "Severite", "Severite"),
    col("description", "Description", "Description"),
    col("lieu", "Lieu", "Lieu"),
    col("gps_lat", "Gps Lat", "Gps Lat"),
    col("gps_lng", "Gps Lng", "Gps Lng"),
    col("chef_secours", "Chef Secours", "Chef Secours"),
    col("autorite_alertee", "Autorite Alertee", "Autorite Alertee"),
    col("decisions_prises", "Decisions Prises", "Decisions Prises"),
    col("ressources_engagees", "Ressources Engagees", "Ressources Engagees"),
    col("victimes", "Victimes", "Victimes"),
    col("dommages_materials_xaf", "Dommages Materials Xaf", "Dommages Materials Xaf"),
    col("arret_activite", "Arret Activite", "Arret Activite"),
    col("communication_presse", "Communication Presse", "Communication Presse"),
    col("rapport_final_url", "Rapport Final Url", "Rapport Final Url"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_incident", "Reference Incident", "Reference Incident", { requisCreation: true }),
    txt("type_incident", "Type Incident", "Type Incident"),
    dtx("date_debut", "Date Debut", "Date Debut"),
    dtx("date_fin", "Date Fin", "Date Fin"),
    txt("severite", "Severite", "Severite"),
    area("description", "Description", "Description"),
    txt("lieu", "Lieu", "Lieu"),
    num("gps_lat", "Gps Lat", "Gps Lat"),
    num("gps_lng", "Gps Lng", "Gps Lng"),
    txt("chef_secours", "Chef Secours", "Chef Secours"),
    txt("autorite_alertee", "Autorite Alertee", "Autorite Alertee"),
    area("decisions_prises", "Decisions Prises", "Decisions Prises"),
    area("ressources_engagees", "Ressources Engagees", "Ressources Engagees"),
    num("victimes", "Victimes", "Victimes"),
    num("dommages_materials_xaf", "Dommages Materials Xaf", "Dommages Materials Xaf"),
    chk("arret_activite", "Arret Activite", "Arret Activite"),
    chk("communication_presse", "Communication Presse", "Communication Presse"),
    txt("rapport_final_url", "Rapport Final Url", "Rapport Final Url"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreRegExport: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "regulatory_exports",
  tcode: "registre-regulatory-exports",
  icon: Icons.FileOutput,
  titre: "Export reglementaire",
  titreEn: "Regulatory export",
  description: "Dossier transmis a une autorite (douane, SAT).",
  descriptionEn: "File sent to an authority (customs).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("regulatory-exports", params),
  creer: (data) => api.creer("regulatory-exports", data),
  modifier: (id, data) => api.modifier("regulatory-exports", id, data),
  unicite: "numero_expedition",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("numero_expedition", "Numero Expedition", "Numero Expedition"),
    col("autorite_destinataire", "Autorite Destinataire", "Autorite Destinataire"),
    col("type_declaration", "Type Declaration", "Type Declaration"),
    col("periode_reference", "Periode Reference", "Periode Reference"),
    col("date_depot", "Date Depot", "Date Depot"),
    col("canaux", "Canaux", "Canaux"),
    col("nb_lignes", "Nb Lignes", "Nb Lignes"),
    col("montant_declare_xaf", "Montant Declare Xaf", "Montant Declare Xaf"),
    col("fichier_url", "Fichier Url", "Fichier Url"),
    col("fichier_hash", "Fichier Hash", "Fichier Hash"),
    col("numero_recu", "Numero Recu", "Numero Recu"),
    col("date_recu", "Date Recu", "Date Recu"),
    col("statut", "Statut", "Statut"),
    col("reponse_autorite", "Reponse Autorite", "Reponse Autorite"),
    col("anomalies", "Anomalies", "Anomalies"),
    col("user_id", "User Id", "User Id"),
  ],
  champs: [
    txt("numero_expedition", "Numero Expedition", "Numero Expedition", { requisCreation: true }),
    txt("autorite_destinataire", "Autorite Destinataire", "Autorite Destinataire"),
    txt("type_declaration", "Type Declaration", "Type Declaration"),
    txt("periode_reference", "Periode Reference", "Periode Reference"),
    dtx("date_depot", "Date Depot", "Date Depot"),
    txt("canaux", "Canaux", "Canaux"),
    num("nb_lignes", "Nb Lignes", "Nb Lignes"),
    num("montant_declare_xaf", "Montant Declare Xaf", "Montant Declare Xaf"),
    txt("fichier_url", "Fichier Url", "Fichier Url"),
    txt("fichier_hash", "Fichier Hash", "Fichier Hash"),
    txt("numero_recu", "Numero Recu", "Numero Recu"),
    dtx("date_recu", "Date Recu", "Date Recu"),
    txt("statut", "Statut", "Statut"),
    area("reponse_autorite", "Reponse Autorite", "Reponse Autorite"),
    area("anomalies", "Anomalies", "Anomalies"),
    num("user_id", "User Id", "User Id"),
  ],
};


export const registreAuditLog: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "audit_logs",
  tcode: "registre-audit-logs",
  icon: Icons.ScrollText,
  titre: "Journal audit inalterable",
  titreEn: "Immutable audit log",
  description: "Log append-only a chaine de hash.",
  descriptionEn: "Append-only hash-chained log.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("audit-logs", params),
  creer: (data) => api.creer("audit-logs", data),
  modifier: (id, data) => api.modifier("audit-logs", id, data),
  unicite: "action",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("event_uid", "Event Uid", "Event Uid"),
    col("actor_id", "Actor Id", "Actor Id"),
    col("actor_email", "Actor Email", "Actor Email"),
    col("actor_ip", "Actor Ip", "Actor Ip"),
    col("user_agent", "User Agent", "User Agent"),
    col("action", "Action", "Action"),
    col("resource_type", "Resource Type", "Resource Type"),
    col("resource_id", "Resource Id", "Resource Id"),
    col("before_snapshot", "Before Snapshot", "Before Snapshot"),
    col("after_snapshot", "After Snapshot", "After Snapshot"),
    col("raison_metier", "Raison Metier", "Raison Metier"),
    col("timestamp_server", "Timestamp Server", "Timestamp Server"),
    col("hash_self", "Hash Self", "Hash Self"),
    col("hash_prev", "Hash Prev", "Hash Prev"),
    col("merkle_root", "Merkle Root", "Merkle Root"),
    col("validite", "Validite", "Validite"),
    col("session_id", "Session Id", "Session Id"),
  ],
  champs: [
    txt("event_uid", "Event Uid", "Event Uid"),
    num("actor_id", "Actor Id", "Actor Id"),
    txt("actor_email", "Actor Email", "Actor Email"),
    txt("actor_ip", "Actor Ip", "Actor Ip"),
    txt("user_agent", "User Agent", "User Agent"),
    txt("action", "Action", "Action", { requisCreation: true }),
    txt("resource_type", "Resource Type", "Resource Type"),
    txt("resource_id", "Resource Id", "Resource Id"),
    area("before_snapshot", "Before Snapshot", "Before Snapshot"),
    area("after_snapshot", "After Snapshot", "After Snapshot"),
    txt("raison_metier", "Raison Metier", "Raison Metier"),
    dtx("timestamp_server", "Timestamp Server", "Timestamp Server"),
    txt("hash_self", "Hash Self", "Hash Self"),
    txt("hash_prev", "Hash Prev", "Hash Prev"),
    txt("merkle_root", "Merkle Root", "Merkle Root"),
    chk("validite", "Validite", "Validite"),
    txt("session_id", "Session Id", "Session Id"),
  ],
};


export const registreTimestamp: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "timestamps",
  tcode: "registre-timestamps",
  icon: Icons.Clock,
  titre: "Horodatage qualifie",
  titreEn: "Qualified timestamp",
  description: "Preuve d'antecidence (eIDAS / CAMPOST).",
  descriptionEn: "Proof of precedence (eIDAS / CAMPOST).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("timestamps", params),
  creer: (data) => api.creer("timestamps", data),
  modifier: (id, data) => api.modifier("timestamps", id, data),
  unicite: "token_tsa",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("token_tsa", "Token Tsa", "Token Tsa"),
    col("autorite_certification", "Autorite Certification", "Autorite Certification"),
    col("algorithme_signature", "Algorithme Signature", "Algorithme Signature"),
    col("objet_type", "Objet Type", "Objet Type"),
    col("objet_ref", "Objet Ref", "Objet Ref"),
    col("objet_hash", "Objet Hash", "Objet Hash"),
    col("date_horodatage", "Date Horodatage", "Date Horodatage"),
    col("precision_seconde", "Precision Seconde", "Precision Seconde"),
    col("certificate_serial", "Certificate Serial", "Certificate Serial"),
    col("certificate_issuer", "Certificate Issuer", "Certificate Issuer"),
    col("certificate_valide_jusqu", "Certificate Valide Jusqu", "Certificate Valide Jusqu"),
    col("token_blob", "Token Blob", "Token Blob"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("token_tsa", "Token Tsa", "Token Tsa", { requisCreation: true }),
    txt("autorite_certification", "Autorite Certification", "Autorite Certification"),
    txt("algorithme_signature", "Algorithme Signature", "Algorithme Signature"),
    txt("objet_type", "Objet Type", "Objet Type"),
    txt("objet_ref", "Objet Ref", "Objet Ref"),
    txt("objet_hash", "Objet Hash", "Objet Hash"),
    dtx("date_horodatage", "Date Horodatage", "Date Horodatage"),
    num("precision_seconde", "Precision Seconde", "Precision Seconde"),
    txt("certificate_serial", "Certificate Serial", "Certificate Serial"),
    txt("certificate_issuer", "Certificate Issuer", "Certificate Issuer"),
    dt("certificate_valide_jusqu", "Certificate Valide Jusqu", "Certificate Valide Jusqu"),
    area("token_blob", "Token Blob", "Token Blob"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreSignature: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "signatures",
  tcode: "registre-signatures",
  icon: Icons.PenLine,
  titre: "Signature / temoin",
  titreEn: "Witness signature",
  description: "Signature electronique / emargement temoin.",
  descriptionEn: "E-signature / witness countersign.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("signatures", params),
  creer: (data) => api.creer("signatures", data),
  modifier: (id, data) => api.modifier("signatures", id, data),
  unicite: "reference_signature",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_signature", "Reference Signature", "Reference Signature"),
    col("type_signataire", "Type Signataire", "Type Signataire"),
    col("signataire_nom", "Signataire Nom", "Signataire Nom"),
    col("signataire_qualite", "Signataire Qualite", "Signataire Qualite"),
    col("signataire_email", "Signataire Email", "Signataire Email"),
    col("signataire_telephone", "Signataire Telephone", "Signataire Telephone"),
    col("piece_identite_ref", "Piece Identite Ref", "Piece Identite Ref"),
    col("document_ref", "Document Ref", "Document Ref"),
    col("event_uid", "Event Uid", "Event Uid"),
    col("type_signature", "Type Signature", "Type Signature"),
    col("signature_blob_url", "Signature Blob Url", "Signature Blob Url"),
    col("hash_signature", "Hash Signature", "Hash Signature"),
    col("date_signature", "Date Signature", "Date Signature"),
    col("gps_lat", "Gps Lat", "Gps Lat"),
    col("gps_lng", "Gps Lng", "Gps Lng"),
    col("ip_signature", "Ip Signature", "Ip Signature"),
    col("tsa_id", "Tsa Id", "Tsa Id"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_signature", "Reference Signature", "Reference Signature", { requisCreation: true }),
    txt("type_signataire", "Type Signataire", "Type Signataire"),
    txt("signataire_nom", "Signataire Nom", "Signataire Nom"),
    txt("signataire_qualite", "Signataire Qualite", "Signataire Qualite"),
    txt("signataire_email", "Signataire Email", "Signataire Email"),
    txt("signataire_telephone", "Signataire Telephone", "Signataire Telephone"),
    txt("piece_identite_ref", "Piece Identite Ref", "Piece Identite Ref"),
    txt("document_ref", "Document Ref", "Document Ref"),
    txt("event_uid", "Event Uid", "Event Uid"),
    txt("type_signature", "Type Signature", "Type Signature"),
    txt("signature_blob_url", "Signature Blob Url", "Signature Blob Url"),
    txt("hash_signature", "Hash Signature", "Hash Signature"),
    dtx("date_signature", "Date Signature", "Date Signature"),
    num("gps_lat", "Gps Lat", "Gps Lat"),
    num("gps_lng", "Gps Lng", "Gps Lng"),
    txt("ip_signature", "Ip Signature", "Ip Signature"),
    num("tsa_id", "Tsa Id", "Tsa Id"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreMerkleProof: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "merkle_proofs",
  tcode: "registre-merkle-proofs",
  icon: Icons.ShieldCheck,
  titre: "Preuve Merkle",
  titreEn: "Merkle proof",
  description: "Racine Merkle periodique d'un lot d'evenements.",
  descriptionEn: "Periodic Merkle root over events.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("merkle-proofs", params),
  creer: (data) => api.creer("merkle-proofs", data),
  modifier: (id, data) => api.modifier("merkle-proofs", id, data),
  unicite: "periode",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("racine_type", "Racine Type", "Racine Type"),
    col("periode", "Periode", "Periode"),
    col("nb_leaves", "Nb Leaves", "Nb Leaves"),
    col("merkle_root", "Merkle Root", "Merkle Root"),
    col("first_leaf_hash", "First Leaf Hash", "First Leaf Hash"),
    col("last_leaf_hash", "Last Leaf Hash", "Last Leaf Hash"),
    col("chemin_verification", "Chemin Verification", "Chemin Verification"),
    col("date_publication", "Date Publication", "Date Publication"),
    col("tsa_id", "Tsa Id", "Tsa Id"),
    col("publication_externe", "Publication Externe", "Publication Externe"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("racine_type", "Racine Type", "Racine Type"),
    txt("periode", "Periode", "Periode", { requisCreation: true }),
    num("nb_leaves", "Nb Leaves", "Nb Leaves"),
    txt("merkle_root", "Merkle Root", "Merkle Root"),
    txt("first_leaf_hash", "First Leaf Hash", "First Leaf Hash"),
    txt("last_leaf_hash", "Last Leaf Hash", "Last Leaf Hash"),
    area("chemin_verification", "Chemin Verification", "Chemin Verification"),
    dtx("date_publication", "Date Publication", "Date Publication"),
    num("tsa_id", "Tsa Id", "Tsa Id"),
    txt("publication_externe", "Publication Externe", "Publication Externe"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreSeal: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "seals",
  tcode: "registre-seals",
  icon: Icons.BadgeCheck,
  titre: "Sceau conteneur ISO 17712",
  titreEn: "Container seal",
  description: "Sceau haute securite conforme ISO 17712.",
  descriptionEn: "High-security seal (ISO 17712).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("seals", params),
  creer: (data) => api.creer("seals", data),
  modifier: (id, data) => api.modifier("seals", id, data),
  unicite: "numero_sceau",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("numero_sceau", "Numero Sceau", "Numero Sceau"),
    col("type_sceau", "Type Sceau", "Type Sceau"),
    col("conteneur_numero", "Conteneur Numero", "Conteneur Numero"),
    col("b_l_numero", "B L Numero", "B L Numero"),
    col("date_apposition", "Date Apposition", "Date Apposition"),
    col("lieu_apposition", "Lieu Apposition", "Lieu Apposition"),
    col("operateur_apposition", "Operateur Apposition", "Operateur Apposition"),
    col("signature_url", "Signature Url", "Signature Url"),
    col("photo_url", "Photo Url", "Photo Url"),
    col("date_retrait", "Date Retrait", "Date Retrait"),
    col("lieu_retrait", "Lieu Retrait", "Lieu Retrait"),
    col("operateur_retrait", "Operateur Retrait", "Operateur Retrait"),
    col("numero_recolte", "Numero Recolte", "Numero Recolte"),
    col("integrite_verifiee", "Integrite Verifiee", "Integrite Verifiee"),
    col("anomalie_sceau", "Anomalie Sceau", "Anomalie Sceau"),
    col("autorite_alertee", "Autorite Alertee", "Autorite Alertee"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("numero_sceau", "Numero Sceau", "Numero Sceau", { requisCreation: true }),
    txt("type_sceau", "Type Sceau", "Type Sceau"),
    txt("conteneur_numero", "Conteneur Numero", "Conteneur Numero"),
    txt("b_l_numero", "B L Numero", "B L Numero"),
    dtx("date_apposition", "Date Apposition", "Date Apposition"),
    txt("lieu_apposition", "Lieu Apposition", "Lieu Apposition"),
    txt("operateur_apposition", "Operateur Apposition", "Operateur Apposition"),
    txt("signature_url", "Signature Url", "Signature Url"),
    txt("photo_url", "Photo Url", "Photo Url"),
    dtx("date_retrait", "Date Retrait", "Date Retrait"),
    txt("lieu_retrait", "Lieu Retrait", "Lieu Retrait"),
    txt("operateur_retrait", "Operateur Retrait", "Operateur Retrait"),
    txt("numero_recolte", "Numero Recolte", "Numero Recolte"),
    chk("integrite_verifiee", "Integrite Verifiee", "Integrite Verifiee"),
    txt("anomalie_sceau", "Anomalie Sceau", "Anomalie Sceau"),
    txt("autorite_alertee", "Autorite Alertee", "Autorite Alertee"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreCargoHandoff: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "cargo_handoffs",
  tcode: "registre-cargo-handoffs",
  icon: Icons.ArrowRightLeft,
  titre: "Transfert cargo multimodal",
  titreEn: "Cargo handoff",
  description: "Changement de mode (mer/rail/route/air).",
  descriptionEn: "Mode change (sea/rail/road/air).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("cargo-handoffs", params),
  creer: (data) => api.creer("cargo-handoffs", data),
  modifier: (id, data) => api.modifier("cargo-handoffs", id, data),
  unicite: "reference_handoff",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_handoff", "Reference Handoff", "Reference Handoff"),
    col("type_cargo", "Type Cargo", "Type Cargo"),
    col("cargo_ref", "Cargo Ref", "Cargo Ref"),
    col("mode_precedent", "Mode Precedent", "Mode Precedent"),
    col("mode_suivant", "Mode Suivant", "Mode Suivant"),
    col("transporteur_precedent", "Transporteur Precedent", "Transporteur Precedent"),
    col("transporteur_suivant", "Transporteur Suivant", "Transporteur Suivant"),
    col("lieu_handoff", "Lieu Handoff", "Lieu Handoff"),
    col("date_debut_prise_en_charge", "Date Debut Prise En Charge", "Date Debut Prise En Charge"),
    col("date_fin_prise_en_charge", "Date Fin Prise En Charge", "Date Fin Prise En Charge"),
    col("poids_kg", "Poids Kg", "Poids Kg"),
    col("volume_m3", "Volume M3", "Volume M3"),
    col("nb_colis", "Nb Colis", "Nb Colis"),
    col("temperature_c", "Temperature C", "Temperature C"),
    col("etat_entree", "Etat Entree", "Etat Entree"),
    col("etat_sortie", "Etat Sortie", "Etat Sortie"),
    col("anomalies_constatees", "Anomalies Constatees", "Anomalies Constatees"),
    col("photos_url", "Photos Url", "Photos Url"),
    col("signataire_entree", "Signataire Entree", "Signataire Entree"),
    col("signataire_sortie", "Signataire Sortie", "Signataire Sortie"),
    col("hash_handoff", "Hash Handoff", "Hash Handoff"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_handoff", "Reference Handoff", "Reference Handoff", { requisCreation: true }),
    txt("type_cargo", "Type Cargo", "Type Cargo"),
    txt("cargo_ref", "Cargo Ref", "Cargo Ref"),
    txt("mode_precedent", "Mode Precedent", "Mode Precedent"),
    txt("mode_suivant", "Mode Suivant", "Mode Suivant"),
    txt("transporteur_precedent", "Transporteur Precedent", "Transporteur Precedent"),
    txt("transporteur_suivant", "Transporteur Suivant", "Transporteur Suivant"),
    txt("lieu_handoff", "Lieu Handoff", "Lieu Handoff"),
    dtx("date_debut_prise_en_charge", "Date Debut Prise En Charge", "Date Debut Prise En Charge"),
    dtx("date_fin_prise_en_charge", "Date Fin Prise En Charge", "Date Fin Prise En Charge"),
    num("poids_kg", "Poids Kg", "Poids Kg"),
    num("volume_m3", "Volume M3", "Volume M3"),
    num("nb_colis", "Nb Colis", "Nb Colis"),
    num("temperature_c", "Temperature C", "Temperature C"),
    txt("etat_entree", "Etat Entree", "Etat Entree"),
    txt("etat_sortie", "Etat Sortie", "Etat Sortie"),
    area("anomalies_constatees", "Anomalies Constatees", "Anomalies Constatees"),
    area("photos_url", "Photos Url", "Photos Url"),
    txt("signataire_entree", "Signataire Entree", "Signataire Entree"),
    txt("signataire_sortie", "Signataire Sortie", "Signataire Sortie"),
    txt("hash_handoff", "Hash Handoff", "Hash Handoff"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreAccessLog: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "access_logs",
  tcode: "registre-access-logs",
  icon: Icons.Lock,
  titre: "Journal securite acces",
  titreEn: "Access security log",
  description: "Trace des acces/tentatives authentification.",
  descriptionEn: "Access/auth attempt trail.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("access-logs", params),
  creer: (data) => api.creer("access-logs", data),
  modifier: (id, data) => api.modifier("access-logs", id, data),
  unicite: "type_evenement",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("user_id", "User Id", "User Id"),
    col("email_tente", "Email Tente", "Email Tente"),
    col("type_evenement", "Type Evenement", "Type Evenement"),
    col("date_evenement", "Date Evenement", "Date Evenement"),
    col("ip_source", "Ip Source", "Ip Source"),
    col("user_agent", "User Agent", "User Agent"),
    col("geo_pays", "Geo Pays", "Geo Pays"),
    col("geo_ville", "Geo Ville", "Geo Ville"),
    col("session_id", "Session Id", "Session Id"),
    col("device_fingerprint", "Device Fingerprint", "Device Fingerprint"),
    col("nb_echecs_successifs", "Nb Echecs Successifs", "Nb Echecs Successifs"),
    col("severite", "Severite", "Severite"),
    col("action_remediation", "Action Remediation", "Action Remediation"),
    col("meta_json", "Meta Json", "Meta Json"),
    col("hash_self", "Hash Self", "Hash Self"),
    col("hash_prev", "Hash Prev", "Hash Prev"),
  ],
  champs: [
    num("user_id", "User Id", "User Id"),
    txt("email_tente", "Email Tente", "Email Tente"),
    txt("type_evenement", "Type Evenement", "Type Evenement", { requisCreation: true }),
    dtx("date_evenement", "Date Evenement", "Date Evenement"),
    txt("ip_source", "Ip Source", "Ip Source"),
    txt("user_agent", "User Agent", "User Agent"),
    txt("geo_pays", "Geo Pays", "Geo Pays"),
    txt("geo_ville", "Geo Ville", "Geo Ville"),
    txt("session_id", "Session Id", "Session Id"),
    txt("device_fingerprint", "Device Fingerprint", "Device Fingerprint"),
    num("nb_echecs_successifs", "Nb Echecs Successifs", "Nb Echecs Successifs"),
    txt("severite", "Severite", "Severite"),
    txt("action_remediation", "Action Remediation", "Action Remediation"),
    area("meta_json", "Meta Json", "Meta Json"),
    txt("hash_self", "Hash Self", "Hash Self"),
    txt("hash_prev", "Hash Prev", "Hash Prev"),
  ],
};


export const registreConsent: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "consents",
  tcode: "registre-consents",
  icon: Icons.UserCheck,
  titre: "Consentement RGPD",
  titreEn: "Consent grant",
  description: "Consentement loi 2010/041 / RGPD par finalite.",
  descriptionEn: "Consent per purpose (RGPD / Cameroon 2010/041).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("consents", params),
  creer: (data) => api.creer("consents", data),
  modifier: (id, data) => api.modifier("consents", id, data),
  unicite: "reference_consentement",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_consentement", "Reference Consentement", "Reference Consentement"),
    col("subject_type", "Subject Type", "Subject Type"),
    col("subject_ref", "Subject Ref", "Subject Ref"),
    col("finalite", "Finalite", "Finalite"),
    col("categorie_donnees", "Categorie Donnees", "Categorie Donnees"),
    col("duree_conservation_mois", "Duree Conservation Mois", "Duree Conservation Mois"),
    col("tiers_partagables", "Tiers Partagables", "Tiers Partagables"),
    col("date_consente", "Date Consente", "Date Consente"),
    col("date_retiree", "Date Retiree", "Date Retiree"),
    col("canal_recueil", "Canal Recueil", "Canal Recueil"),
    col("ip_recueil", "Ip Recueil", "Ip Recueil"),
    col("preuve_url", "Preuve Url", "Preuve Url"),
    col("hash_preuve", "Hash Preuve", "Hash Preuve"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("reference_consentement", "Reference Consentement", "Reference Consentement", { requisCreation: true }),
    txt("subject_type", "Subject Type", "Subject Type"),
    txt("subject_ref", "Subject Ref", "Subject Ref"),
    txt("finalite", "Finalite", "Finalite"),
    txt("categorie_donnees", "Categorie Donnees", "Categorie Donnees"),
    num("duree_conservation_mois", "Duree Conservation Mois", "Duree Conservation Mois"),
    area("tiers_partagables", "Tiers Partagables", "Tiers Partagables"),
    dtx("date_consente", "Date Consente", "Date Consente"),
    dtx("date_retiree", "Date Retiree", "Date Retiree"),
    txt("canal_recueil", "Canal Recueil", "Canal Recueil"),
    txt("ip_recueil", "Ip Recueil", "Ip Recueil"),
    txt("preuve_url", "Preuve Url", "Preuve Url"),
    txt("hash_preuve", "Hash Preuve", "Hash Preuve"),
    txt("statut", "Statut", "Statut"),
  ],
};


export const registreAntiTampering: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "anti_tampering",
  tcode: "registre-anti-tampering",
  icon: Icons.AlertOctagon,
  titre: "Evenement anti-falsification",
  titreEn: "Anti-tampering event",
  description: "Detection d'alteration (hash mismatch).",
  descriptionEn: "Alteration detection (hash mismatch).",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("anti-tampering", params),
  creer: (data) => api.creer("anti-tampering", data),
  modifier: (id, data) => api.modifier("anti-tampering", id, data),
  unicite: "reference_alerte",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("reference_alerte", "Reference Alerte", "Reference Alerte"),
    col("type_alerte", "Type Alerte", "Type Alerte"),
    col("date_detection", "Date Detection", "Date Detection"),
    col("severite", "Severite", "Severite"),
    col("asset_type", "Asset Type", "Asset Type"),
    col("asset_ref", "Asset Ref", "Asset Ref"),
    col("attendu_hash", "Attendu Hash", "Attendu Hash"),
    col("constate_hash", "Constate Hash", "Constate Hash"),
    col("delta_description", "Delta Description", "Delta Description"),
    col("detection_source", "Detection Source", "Detection Source"),
    col("investigateur_id", "Investigateur Id", "Investigateur Id"),
    col("actions_correctives", "Actions Correctives", "Actions Correctives"),
    col("escalation_autorite", "Escalation Autorite", "Escalation Autorite"),
    col("statut", "Statut", "Statut"),
    col("notes", "Notes", "Notes"),
  ],
  champs: [
    txt("reference_alerte", "Reference Alerte", "Reference Alerte", { requisCreation: true }),
    txt("type_alerte", "Type Alerte", "Type Alerte"),
    dtx("date_detection", "Date Detection", "Date Detection"),
    txt("severite", "Severite", "Severite"),
    txt("asset_type", "Asset Type", "Asset Type"),
    txt("asset_ref", "Asset Ref", "Asset Ref"),
    txt("attendu_hash", "Attendu Hash", "Attendu Hash"),
    txt("constate_hash", "Constate Hash", "Constate Hash"),
    area("delta_description", "Delta Description", "Delta Description"),
    txt("detection_source", "Detection Source", "Detection Source"),
    num("investigateur_id", "Investigateur Id", "Investigateur Id"),
    area("actions_correctives", "Actions Correctives", "Actions Correctives"),
    chk("escalation_autorite", "Escalation Autorite", "Escalation Autorite"),
    txt("statut", "Statut", "Statut"),
    area("notes", "Notes", "Notes"),
  ],
};


export const registreRetentionPolicy: ConfigRegistre = {
  permModule: "tracabilite",
  permSousModule: "retention_policies",
  tcode: "registre-retention-policies",
  icon: Icons.Archive,
  titre: "Politique conservation",
  titreEn: "Retention policy",
  description: "Duree et regle de retention par type d'objet.",
  descriptionEn: "Retention duration/rule per object type.",
  aide: "Registre genere (expansion wave 6).",
  aideEn: "Generated register (wave 6 expansion).",
  lister: (params) => api.lister("retention-policies", params),
  creer: (data) => api.creer("retention-policies", data),
  modifier: (id, data) => api.modifier("retention-policies", id, data),
  unicite: "code_politique",
  fetchNomenclatures: () => api.getNomenclatures(),
  colonnes: [
    col("code_politique", "Code Politique", "Code Politique"),
    col("type_objet", "Type Objet", "Type Objet"),
    col("duree_conservation_ans", "Duree Conservation Ans", "Duree Conservation Ans"),
    col("autorite_legale", "Autorite Legale", "Autorite Legale"),
    col("base_texte", "Base Texte", "Base Texte"),
    col("archive_apres_echeance", "Archive Apres Echeance", "Archive Apres Echeance"),
    col("destruction_apres_echeance", "Destruction Apres Echeance", "Destruction Apres Echeance"),
    col("modalite_destruction", "Modalite Destruction", "Modalite Destruction"),
    col("destination_archive", "Destination Archive", "Destination Archive"),
    col("statut", "Statut", "Statut"),
  ],
  champs: [
    txt("code_politique", "Code Politique", "Code Politique", { requisCreation: true }),
    txt("type_objet", "Type Objet", "Type Objet"),
    num("duree_conservation_ans", "Duree Conservation Ans", "Duree Conservation Ans"),
    txt("autorite_legale", "Autorite Legale", "Autorite Legale"),
    txt("base_texte", "Base Texte", "Base Texte"),
    chk("archive_apres_echeance", "Archive Apres Echeance", "Archive Apres Echeance"),
    chk("destruction_apres_echeance", "Destruction Apres Echeance", "Destruction Apres Echeance"),
    txt("modalite_destruction", "Modalite Destruction", "Modalite Destruction"),
    txt("destination_archive", "Destination Archive", "Destination Archive"),
    txt("statut", "Statut", "Statut"),
  ],
};

