"""Manifests des 13 modules restants de l'expansion ERP.

Chaque module : 10-12 entites avec 8-14 champs, enums, unicite, icone.
Format identique a generate_module.py.
"""

# Common builder helpers to keep the file short
def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── Wave 1C : transport-flotte ─────────────────────────────────────────────
MODULES["transport"] = dict(
    module_key="transport", module_slug="transport-flotte", module_path="transport-flotte",
    perm_module="transport", revision="049", down_revision="048_transit_deep",
    entities=[
        E("vehicle-registry", "vehicle_registrations", "VehicleRegistration", "vehicle-registrations", "vehicle_registry",
          "Fiche vehicule", "Vehicle record",
          "Registre technique des vehicules de la flotte.",
          "Technical registry of fleet vehicles.",
          "Chaque vehicule doit disposer d'une carte grise valide.",
          "Each vehicle must have a valid registration.",
          "Truck", "numero_immatriculation",
          [F("numero_immatriculation", "str", "Immatriculation", "Plate", required=True, search=True),
           F("marque", "str", "Marque", "Brand"), F("modele", "str", "Modele", "Model"),
           F("annee_mise_circulation", "int", "Annee", "Year"),
           F("type_vehicule", "enum", "Type", "Type"),
           F("ptt_tonnes", "num", "PTT (t)", "GVW (t)"),
           F("puissance_cv", "int", "Puissance (CV)", "Power (CV)"),
           F("kilometrage_actuel", "num", "Kilometrage", "Odometer"),
           F("couleur", "str", "Couleur", "Color"), F("carrosserie", "str", "Carrosserie", "Body"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("type_vehicule", ["CAMION", "TRACTEUR", "BENNE", "CITERNE", "FRIGORIFIQUE", "PORTE_CONTENEUR", "UTILITAIRE", "BUS"], "CAMION"),
           EN("statut", ["ACTIF", "IMMOBILISE", "VENDE", "REFORME"], "ACTIF")]),
        E("route-planning", "route_plans", "RoutePlan", "route-plans", "route_plan",
          "Planification tournees", "Route planning",
          "Tournees de livraison et collecte optimisees.", "Optimized delivery/pickup routes.",
          "L'optimisation VRP doit rester sous le seuil de service.",
          "VRP optimization must remain under service threshold.",
          "Route", "code_tournee",
          [F("code_tournee", "str", "Code tournee", "Route code", required=True, search=True),
           F("date_tournee", "date", "Date", "Date"),
           F("chauffeur_id", "int", "Chauffeur", "Driver"),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("nb_points", "int", "Nb points", "Stops"),
           F("distance_km", "num", "Distance (km)", "Distance (km)"),
           F("duree_estimee_h", "num", "Duree estimee", "Est. duration"),
           F("zonale", "str", "Zone", "Zone"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["PLANIFIEE", "EN_COURS", "TERMINEE", "ANNULEE"], "PLANIFIEE")]),
        E("checkpoint-tracking", "checkpoint_controls", "CheckpointControl", "checkpoint-controls", "checkpoint",
          "Controles routiers et pesages", "Roadside checks and weigh-ins",
          "Controles effectues aux balises et ponts-bascules.", "Checks performed at checkpoints and weighbridges.",
          "Un depot de poids declare un litige imminent.",
          "Overweight declaration signals imminent dispute.",
          "MapPin", "numero_pv",
          [F("numero_pv", "str", "Numero PV", "Report number", required=True, search=True),
           F("date_controle", "datetime", "Date", "Date"),
           F("lieu", "str", "Lieu", "Location"),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("poids_reel_t", "num", "Poids reel (t)", "Actual weight (t)"),
           F("poids_autorise_t", "num", "Poids autorise (t)", "Allowed weight (t)"),
           F("type_controle", "enum", "Type", "Type"),
           F("agent", "str", "Agent", "Agent"),
           F("sanction_appliquee", "text", "Sanction", "Sanction"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_controle", ["PESAGE", "DOCUMENTS", "ETAT_TECHNIQUE", "ALCOOL", "VITESSE"], "PESAGE"),
           EN("statut", ["CONFORME", "PV_DRESSE", "IMMOBILISATION"], "CONFORME")]),
        E("cargo-insurance", "cargo_insurances", "CargoInsurance", "cargo-insurances", "cargo_insurance",
          "Assurance marchandise transportee", "Cargo insurance",
          "Polices d'assurance fret par type de transport.", "Freight insurance policies per transport type.",
          "Une franchise mal parametree expose l'exploitant.",
          "Poorly set deductible exposes the operator.",
          "Shield", "numero_police",
          [F("numero_police", "str", "Numero police", "Policy number", required=True, search=True),
           F("assureur", "str", "Assureur", "Insurer"),
           F("type_garantie", "enum", "Type garantie", "Coverage"),
           F("plafond_xaf", "num", "Plafond XAF", "Coverage cap XAF"),
           F("franchise_xaf", "num", "Franchise XAF", "Deductible XAF"),
           F("prime_xaf", "num", "Prime XAF", "Premium XAF"),
           F("date_effet", "date", "Date effet", "Inception"),
           F("date_fin", "date", "Date fin", "Expiry"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("type_garantie", ["TOUS_RISQUES", "FAC", "FAP", "RESP_CIVILE"], "TOUS_RISQUES"),
           EN("statut", ["ACTIVE", "EXPIREE", "RESILIEE"], "ACTIVE")]),
        E("freight-billing", "freight_bills", "FreightBill", "freight-bills", "freight_billing",
          "Facturation fret", "Freight billing",
          "Factures de transport, accessoires et supplement.", "Transport invoices, extras and surcharges.",
          "Facture client = support de la revue de creance.",
          "Customer invoice = basis of receivable review.",
          "Receipt", "numero_facture",
          [F("numero_facture", "str", "Numero", "Number", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("mission_id", "int", "Mission", "Mission"),
           F("montant_ht_xaf", "num", "Montant HT", "Amount excl. tax"),
           F("tva_xaf", "num", "TVA", "VAT"),
           F("total_ttc_xaf", "num", "Total TTC", "Total incl. tax"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("date_echeance", "date", "Echeance", "Due date"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["BROUILLON", "EMISE", "PAYEE", "IMPAYEE", "ANNULEE"], "BROUILLON")]),
        E("subcontractors", "subcontractors", "Subcontractor", "subcontractors", "subcontractor",
          "Transporteurs sous-traitants", "Subcontracted carriers",
          "Referentiel des transporteurs externes et capacites.", "External carriers and capabilities register.",
          "Verifier agrement et assurance avant affectation.",
          "Verify approval and insurance before assignment.",
          "Users", "code_sous_traitant",
          [F("code_sous_traitant", "str", "Code", "Code", required=True, search=True),
           F("raison_sociale", "str", "Raison sociale", "Legal name"),
           F("niu", "str", "NIU", "Tax ID"), F("contact", "str", "Contact", "Contact"),
           F("telephone", "str", "Telephone", "Phone"),
           F("nb_camions", "int", "Nb camions", "Trucks"),
           F("zones_couvertes", "text", "Zones couvertes", "Zones covered"),
           F("agreement_numero", "str", "Numero agrement", "Approval number"),
           F("date_expiration_agreement", "date", "Expiration agrement", "Approval expiry"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["AGREE", "SUSPENDU", "NOIRE", "RETIREE"], "AGREE")]),
        E("dangerous-goods", "dangerous_goods_loads", "DangerousGoodsLoad", "dangerous-goods-loads", "dangerous_goods",
          "Marchandises dangereuses ADR", "ADR dangerous goods",
          "Cargaisons classees ADR avec numero ONU.", "ADR-classified loads with UN number.",
          "Etiquetage et document de transport obligatoires.",
          "Placarding and transport document mandatory.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("mission_id", "int", "Mission", "Mission"),
           F("onu_number", "str", "Numero ONU", "UN number"),
           F("classe_adr", "str", "Classe ADR", "ADR class"),
           F("designation_officielle", "str", "Designation", "Official name"),
           F("groupe_emballage", "enum", "Groupe emballage", "Packing group"),
           F("quantite_kg", "num", "Quantite (kg)", "Quantity (kg)"),
           F("etiquettes", "str", "Etiquettes", "Labels"),
           F("formation_chauffeur", "bool", "Formation chauffeur ADR", "Driver ADR training"),
           F("statut", "enum", "Statut", "Status")],
          [EN("groupe_emballage", ["I", "II", "III", "NA"], "II"),
           EN("statut", ["PLANIFIE", "TRANSPORTE", "LITIGE"], "PLANIFIE")]),
        E("vehicle-documents", "vehicle_documents", "VehicleDocument", "vehicle-documents", "vehicle_document",
          "Cartes grises / assurances / vignettes", "Registration / insurance / stickers",
          "Documents obligatoires par vehicule.", "Mandatory documents per vehicle.",
          "Tout document expire immobilise le vehicule.",
          "Any expired document immobilizes the vehicle.",
          "FileText", "numero_document",
          [F("numero_document", "str", "Numero document", "Document number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("type_document", "enum", "Type", "Type"),
           F("autorite_emission", "str", "Autorite emission", "Issuing authority"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("date_expiration", "date", "Date expiration", "Expiry date"),
           F("numero_police_associe", "str", "Numero police", "Policy number"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("type_document", ["CARTE_GRISE", "ASSURANCE_RC", "VIGNETTE", "CONTROLE_TECHNIQUE", "AUTORISATION_TRANSPORT"], "CARTE_GRISE"),
           EN("statut", ["VALIDE", "EXPIRE", "PERDU", "EN_RENOUVELLEMENT"], "VALIDE")]),
        E("gps-devices", "gps_devices", "GpsDevice", "gps-devices", "gps_device",
          "Boitiers GPS / telematique", "GPS / telematics devices",
          "Inventaire boitiers et plans de suivi.", "Device inventory and tracking plans.",
          "Un boitier hors reseau doit etre remplace sous 48h.",
          "Offline device must be replaced within 48h.",
          "Satellite", "numero_serial_gps",
          [F("numero_serial_gps", "str", "Numero serie", "Serial number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("fournisseur", "str", "Fournisseur", "Provider"),
           F("modele", "str", "Modele", "Model"),
           F("numero_sim", "str", "Numero SIM", "SIM number"),
           F("date_installation", "date", "Installation", "Installation date"),
           F("date_derniere_communication", "datetime", "Derniere comm.", "Last communication"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["ACTIF", "HORS_RESEAU", "PANNE", "DESACTIVE"], "ACTIF")]),
        E("penalty-tracking", "traffic_penalties", "TrafficPenalty", "traffic-penalties", "penalty",
          "Infractions et PV routiers", "Traffic violations and fines",
          "PV recus, suites donnees, reglement.", "Received fines, actions and payments.",
          "Contester dans le delai legal (30j).",
          "Dispute within the legal window (30 days).",
          "Ticket", "numero_pv",
          [F("numero_pv", "str", "Numero PV", "Report number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date_infraction", "date", "Date infraction", "Offense date"),
           F("lieu", "str", "Lieu", "Location"),
           F("type_infraction", "enum", "Type", "Type"),
           F("montant_amende_xaf", "num", "Amende XAF", "Fine XAF"),
           F("points_retires", "int", "Points retires", "Points removed"),
           F("chauffeur_id", "int", "Chauffeur", "Driver"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("type_infraction", ["EXCES_VITESSE", "SURCHARGE", "GRILLE_FEUX", "STATIONNEMENT", "ALCOOL", "PAPIERS"], "EXCES_VITESSE"),
           EN("statut", ["RECUS", "CONTESTE", "PAYE", "PRESSE"], "RECUS")]),
        E("convoy-management", "convoys", "Convoy", "convoys", "convoy",
          "Convois et escorte", "Convoys and escort",
          "Groupements de vehicules sous escorte armee ou civile.", "Vehicle groups under armed or civilian escort.",
          "Le chef de convoi valide le depart et l'arrivee.",
          "Convoy lead authorizes departure and arrival.",
          "Users", "code_convoi",
          [F("code_convoi", "str", "Code convoi", "Convoy code", required=True, search=True),
           F("date_depart", "datetime", "Depart", "Departure"),
           F("date_arrivee", "datetime", "Arrivee", "Arrival"),
           F("nb_vehicules", "int", "Nb vehicules", "Vehicles"),
           F("type_escorte", "enum", "Type escorte", "Escort type"),
           F("chef_convoi", "str", "Chef de convoi", "Convoy lead"),
           F("itineraire", "text", "Itineraire", "Route"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_escorte", ["AUCUNE", "CIVILE", "POLICE", "ARMEE"], "CIVILE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "INCIDENT"], "PLANIFIE")]),
        E("performance-kpi", "fleet_kpis", "FleetKpi", "fleet-kpis", "performance_kpi",
          "TCO et taux de service", "TCO and service rate",
          "Indicateurs de performance de la flotte.", "Fleet performance indicators.",
          "TCO calcule mensuellement par tranche.",
          "TCO calculated monthly by segment.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode_debut", "date", "Debut periode", "Period start"),
           F("periode_fin", "date", "Fin periode", "Period end"),
           F("cout_total_xaf", "num", "Cout total", "Total cost"),
           F("km_parcourus", "num", "Km parcourus", "Kilometers"),
           F("cout_par_km", "num", "Cout par km", "Cost per km"),
           F("taux_dispo_pct", "num", "Taux dispo %", "Availability %"),
           F("taux_service_pct", "num", "Taux service %", "Service rate %"),
           F("nb_accidents", "int", "Accidents", "Accidents"), F("notes", "text", "Notes", "Notes")],
          []),
    ],
)

# ─── Wave 1D : magasin-stock ────────────────────────────────────────────────
MODULES["magasin"] = dict(
    module_key="magasin", module_slug="magasin-stock", module_path="magasin-stock",
    perm_module="magasin", revision="050", down_revision="049_transport_deep",
    entities=[
        E("article-catalog", "article_catalogs", "ArticleCatalog", "article-catalogs", "article_catalog",
          "Referentiel articles / SKU", "Article catalog / SKU",
          "Catalogue articles avec dimensions et unites.", "Article catalog with dimensions and units.",
          "Chaque SKU doit pointer vers une categorie valide.",
          "Every SKU must reference a valid category.",
          "Boxes", "code_sku",
          [F("code_sku", "str", "Code SKU", "SKU code", required=True, search=True),
           F("designation", "str", "Designation", "Name"),
           F("categorie", "str", "Categorie", "Category"),
           F("unite_principale", "str", "Unite", "UoM"),
           F("code_barre", "str", "Code barre", "Barcode"),
           F("poids_unitaire_kg", "num", "Poids unitaire (kg)", "Unit weight (kg)"),
           F("volume_m3", "num", "Volume (m3)", "Volume (m3)"),
           F("prix_achat_moyen_xaf", "num", "PA moyen", "Avg purchase price"),
           F("prix_vente_xaf", "num", "Prix vente", "Sale price"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIF", "OBSOLETE", "BLOQUE"], "ACTIF")]),
        E("supplier-catalog", "supplier_articles", "SupplierArticle", "supplier-articles", "supplier_catalog",
          "Fournisseurs par article", "Suppliers per article",
          "Matrice fournisseurs / prix / delais.", "Supplier / price / lead time matrix.",
          "Au moins 2 fournisseurs references par article critique.",
          "At least 2 suppliers per critical article.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("article_id", "int", "Article", "Article"),
           F("fournisseur_id", "int", "Fournisseur", "Supplier"),
           F("prix_unitaire_xaf", "num", "Prix unitaire XAF", "Unit price XAF"),
           F("delai_livraison_jours", "int", "Delai (j)", "Lead time (d)"),
           F("quantite_min_commande", "num", "Qte min", "MOQ"),
           F("devise", "str", "Devise", "Currency"),
           F("conditions_paiement", "str", "Conditions paiement", "Payment terms"),
           F("actif", "bool", "Actif", "Active")],
          []),
        E("purchase-orders", "purchase_orders_deep", "PurchaseOrderDeep", "purchase-orders", "purchase_order",
          "Commandes d'achat", "Purchase orders",
          "Bons de commande acheteur avec lignes.", "Buyer purchase orders with lines.",
          "La reception genere le bon d'entree automatiquement.",
          "Receipt generates goods-in automatically.",
          "ShoppingCart", "numero_commande",
          [F("numero_commande", "str", "Numero", "Number", required=True, search=True),
           F("fournisseur_id", "int", "Fournisseur", "Supplier"),
           F("date_commande", "date", "Date", "Date"),
           F("date_livraison_prevue", "date", "Livraison prevue", "Planned delivery"),
           F("montant_total_xaf", "num", "Montant XAF", "Amount XAF"),
           F("nb_lignes", "int", "Nb lignes", "Lines"),
           F("acheteur", "str", "Acheteur", "Buyer"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["ROUE", "ENVOYEE", "PARTIELLE", "RECUE", "ANNULEE"], "ROUE")]),
        E("quality-control", "quality_inspections", "QualityInspection", "quality-inspections", "quality_control",
          "Controle qualite a reception", "Receiving quality control",
          "Inspection quantitative et qualitative a reception.", "Quantitative and qualitative receiving inspection.",
          "Toute non-conformite declenche une fiche 8D.",
          "Any non-conformity triggers an 8D sheet.",
          "ClipboardCheck", "numero_controle",
          [F("numero_controle", "str", "Numero", "Number", required=True, search=True),
           F("reception_id", "int", "Reception", "Receipt"),
           F("article_id", "int", "Article", "Article"),
           F("quantite_inspekte", "num", "Qte inspekte", "Inspected quantity"),
           F("quantite_conforme", "num", "Qte conforme", "Conforming quantity"),
           F("quantite_rebutee", "num", "Qte rebutee", "Rejected quantity"),
           F("resultat", "enum", "Resultat", "Result"),
           F("inspecteur", "str", "Inspecteur", "Inspector"),
           F("date_controle", "date", "Date", "Date"), F("observations", "text", "Observations", "Observations")],
          [EN("resultat", ["CONFORME", "PARTIELLE", "NON_CONFORME", "REBUT"], "CONFORME")]),
        E("stock-alerts", "stock_alerts", "StockAlert", "stock-alerts", "stock_alert",
          "Seuils et alertes rupture", "Thresholds and shortage alerts",
          "Seuil mini, max, point de commande.", "Min, max, reorder point.",
          "Le systeme declenche une requisition automatique.",
          "System triggers an automatic requisition.",
          "Bell", "code_alerte",
          [F("code_alerte", "str", "Code alerte", "Alert code", required=True, search=True),
           F("article_id", "int", "Article", "Article"),
           F("depot_id", "int", "Depot", "Warehouse"),
           F("seuil_min", "num", "Seuil mini", "Min threshold"),
           F("seuil_max", "num", "Seuil maxi", "Max threshold"),
           F("point_commande", "num", "Point de commande", "Reorder point"),
           F("quantite_actuelle", "num", "Qte actuelle", "Current qty"),
           F("derniere_alerte", "datetime", "Derniere alerte", "Last alert"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["NORMAL", "ALERTE", "RUPTURE", "SURSTOCK"], "NORMAL")]),
        E("expiry-tracking", "expiry_records", "ExpiryRecord", "expiry-records", "expiry_tracking",
          "Peremption / FEFO", "Expiry / FEFO",
          "Lots dates de peremption par article.", "Lot expiry dates per article.",
          "Priorite FEFO : premier perime, premier sorti.",
          "FEFO priority: first expired, first shipped.",
          "Calendar", "numero_lot",
          [F("numero_lot", "str", "Numero lot", "Lot number", required=True, search=True),
           F("article_id", "int", "Article", "Article"),
           F("quantite", "num", "Quantite", "Quantity"),
           F("date_peremption", "date", "Date peremption", "Expiry date"),
           F("date_reception", "date", "Date reception", "Reception date"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["VALIDE", "PROCHAIN_EXPIRATION", "EXPIRE", "RETIRE"], "VALIDE")]),
        E("serial-tracking", "serial_numbers", "SerialNumber", "serial-numbers", "serial_tracking",
          "Tracabilite numeros serie", "Serial number tracking",
          "Numeros serie / IMEI rattaches a une sortie.", "Serial / IMEI numbers attached to an outbound.",
          "Obligatoire pour materiel informatique.",
          "Mandatory for IT equipment.",
          "Fingerprint", "numero_serial",
          [F("numero_serial", "str", "Numero serie", "Serial", required=True, search=True),
           F("article_id", "int", "Article", "Article"),
           F("numero_lot", "str", "Numero lot", "Lot"),
           F("statut", "enum", "Statut", "Status"),
           F("date_entree", "date", "Date entree", "Entry date"),
           F("date_sortie", "date", "Date sortie", "Exit date"),
           F("destination", "str", "Destination", "Destination"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["EN_STOCK", "SORTI", "RETOUR", "REPARATION", "REFORME"], "EN_STOCK")]),
        E("packing-units", "packing_units", "PackingUnit", "packing-units", "packing_unit",
          "Unites de conditionnement", "Packaging units",
          "Colis, cartons, palettes, conteneurs.", "Parcels, cartons, pallets, containers.",
          "Chaque UC rattachee a une tare.",
          "Each PU has a tare weight.",
          "Package", "code_uc",
          [F("code_uc", "str", "Code UC", "PU code", required=True, search=True),
           F("type_uc", "enum", "Type UC", "Type"),
           F("dimensions", "str", "Dimensions", "Dimensions"),
           F("poids_tare_kg", "num", "Poids tare (kg)", "Tare (kg)"),
           F("capacite_max_kg", "num", "Capacite (kg)", "Capacity (kg)"),
           F("nb_unites_principales", "num", "Nb unites", "Units count"),
           F("actif", "bool", "Actif", "Active")],
          [EN("type_uc", ["COLIS", "CARTON", "PALETTE", "BIG_BAG", "FUT", "CONTEUR"], "COLIS")]),
        E("returns-management", "stock_returns", "StockReturn", "stock-returns", "returns_management",
          "Retours et avoirs stock", "Returns and credit notes",
          "Retours clients / fournisseurs avec motif.", "Client / supplier returns with reason.",
          "Avoir genere seulement apres validation controle qualite.",
          "Credit issued after quality control validation.",
          "Undo2", "numero_retour",
          [F("numero_retour", "str", "Numero retour", "Return number", required=True, search=True),
           F("type_retour", "enum", "Type", "Type"),
           F("client_id", "int", "Client", "Client"),
           F("fournisseur_id", "int", "Fournisseur", "Supplier"),
           F("date_retour", "date", "Date", "Date"),
           F("article_id", "int", "Article", "Article"),
           F("quantite", "num", "Quantite", "Quantity"),
           F("motif", "text", "Motif", "Reason"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_retour", ["CLIENT", "FOURNISSEUR", "INTERNE"], "CLIENT"),
           EN("statut", ["DEMANDE", "ACCEPTE", "REFUSE", "TRAITE"], "DEMANDE")]),
        E("consignment-stock", "consignment_stocks", "ConsignmentStock", "consignment-stocks", "consignment_stock",
          "Stock en consignation", "Consignment stock",
          "Stock detenu pour un tiers.", "Stock held on behalf of a third party.",
          "Facturation au retrait reel, pas au depot.",
          "Billing on actual withdrawal, not on deposit.",
          "DollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("proprietaire_id", "int", "Proprietaire", "Owner"),
           F("article_id", "int", "Article", "Article"),
           F("quantite_deposee", "num", "Qte deposee", "Deposited quantity"),
           F("quantite_retiree", "num", "Qte retiree", "Withdrawn quantity"),
           F("date_depot", "date", "Date depot", "Deposit date"),
           F("date_limite", "date", "Date limite", "Deadline"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("statut", ["EN_COURS", "EPUISE", "RESTITUE", "EXPEDITE"], "EN_COURS")]),
        E("stock-valuation", "stock_valuations", "StockValuation", "stock-valuations", "stock_valuation",
          "Valorisation du stock", "Stock valuation",
          "Calcul CMUP / COI par article et periode.", "Avg cost / FIFO by article and period.",
          "Methode figee pour l'exercice.",
          "Method frozen for the fiscal year.",
          "Calculator", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode", "str", "Periode", "Period"),
           F("article_id", "int", "Article", "Article"),
           F("methode", "enum", "Methode", "Method"),
           F("quantite_fin", "num", "Qte fin", "Ending quantity"),
           F("valeur_cmup_xaf", "num", "Valeur CMUP", "Avg cost value"),
           F("valeur_coi_xaf", "num", "Valeur COI", "FIFO value"),
           F("date_calcul", "date", "Date calcul", "Calculation date")],
          [EN("methode", ["CMUP", "COI", "PMP", "COUT_STANDARD"], "CMUP")]),
        E("wms-analytics", "wms_kpis", "WmsKpi", "wms-kpis", "wms_analytics",
          "KPIs magasin", "Warehouse KPIs",
          "Rotation, rupture, taux de service, cadence de preparation.", "Turnover, shortage, service rate, picking.",
          "Revu mensuellement avec le chef magasinier.",
          "Reviewed monthly with the warehouse lead.",
          "BarChart3", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("rotation", "num", "Rotation", "Turnover"),
           F("rupture_pct", "num", "Rupture %", "Shortage %"),
           F("taux_service_pct", "num", "Taux service %", "Service %"),
           F("cadence_choix_lignes_h", "num", "Cadence lignes/h", "Pick lines/h"),
           F("ecart_inventaire_pct", "num", "Ecart inventaire %", "Inventory gap %"),
           F("notes", "text", "Notes", "Notes")], []),
    ],
)

# ─── Wave 2A : comptabilite-ohada ───────────────────────────────────────────
MODULES["comptabilite"] = dict(
    module_key="comptabilite", module_slug="comptabilite-ohada", module_path="comptabilite-ohada",
    perm_module="compta", revision="051", down_revision="050_magasin_deep",
    entities=[
        E("fixed-assets", "asset_registrations", "AssetRegistration", "asset-registrations", "fixed_asset",
          "Registre immobilisations", "Fixed asset register",
          "Biens inscrits a l'actif avec valeur amortissable.", "Assets recorded with amortizable value.",
          "Chaque bien recoit un numero d'inventaire.",
          "Each asset has an inventory number.",
          "Building", "numero_inventaire",
          [F("numero_inventaire", "str", "Numero inventaire", "Inventory number", required=True, search=True),
           F("designation", "str", "Designation", "Description"),
           F("categorie", "enum", "Categorie OHADA", "OHADA category"),
           F("date_acquisition", "date", "Date acquisition", "Acquisition date"),
           F("valeur_acquisition_xaf", "num", "Valeur acquisition", "Acquisition value"),
           F("valeur_residuelle_xaf", "num", "Valeur residuelle", "Residual value"),
           F("duree_amortissement_an", "int", "Duree (ans)", "Useful life (y)"),
           F("mode_amortissement", "enum", "Mode amortissement", "Amortization"),
           F("compte_immo", "str", "Compte OHADA", "OHADA account"),
           F("statut", "enum", "Statut", "Status")],
          [EN("categorie", ["INCORPORELLE", "CORPORELLE", "FINANCIERE"], "CORPORELLE"),
           EN("mode_amortissement", ["LINEAIRE", "DECLINANT", "PROGRESSIF"], "LINEAIRE"),
           EN("statut", ["ACTIF", "CEDE", "REFORME", "EN_COURS"], "ACTIF")]),
        E("depreciation-schedules", "depreciation_schedules", "DepreciationSchedule", "depreciation-schedules", "depreciation",
          "Plans d'amortissement", "Depreciation schedules",
          "Echeancier annuel par immobilisation.", "Annual schedule per asset.",
          "Le plan est inchange pendant l'exercice.",
          "Schedule is unchanged during the fiscal year.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("asset_id", "int", "Immobilisation", "Asset"),
           F("exercice", "int", "Exercice", "Fiscal year"),
           F("dotation_xaf", "num", "Dotation", "Charge"),
           F("cumul_xaf", "num", "Cumul", "Accumulated"),
           F("valeur_nette_xaf", "num", "Valeur nette", "Net value"),
           F("date_ecriture", "date", "Date ecriture", "Posting date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "PASSER", "ANNULE"], "PLANIFIE")]),
        E("provisions", "provisions", "Provision", "provisions", "provision",
          "Dotations et reprises", "Provision charges and reversals",
          "Provisions pour risque / depreciation.", "Risk or impairment provisions.",
          "Justification comptable obligatoire.",
          "Accounting justification mandatory.",
          "ShieldAlert", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_provision", "enum", "Type", "Type"),
           F("exercice", "int", "Exercice", "Fiscal year"),
           F("montant_xaf", "num", "Montant XAF", "Amount XAF"),
           F("date_constat", "date", "Date constat", "Recognition date"),
           F("compte_charge", "str", "Compte charge", "Expense account"),
           F("comporte_passif", "str", "Compte passif", "Liability account"),
           F("statut", "enum", "Statut", "Status"), F("motivation", "text", "Motivation", "Motivation")],
          [EN("type_provision", ["RISQUE", "DEPRECIATION", "LITIGE", "RESTRUCTURATION"], "RISQUE"),
           EN("statut", ["DOTE", "REPRIS", "MAINTENU"], "DOTE")]),
        E("bank-reconciliation", "bank_reconciliations", "BankReconciliation", "bank-reconciliations", "bank_reconciliation",
          "Rapprochement bancaire", "Bank reconciliation",
          "Pointages banque / compta par periode.", "Bank / GL matching per period.",
          "Un ecart doit etre explique avant cloture.",
          "Discrepancy explained before close.",
          "Landmark", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("compte_banque", "str", "Compte bancaire", "Bank account"),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("solde_banque_xaf", "num", "Solde banque", "Bank balance"),
           F("solde_compta_xaf", "num", "Solde compta", "GL balance"),
           F("ecart_xaf", "num", "Ecart", "Discrepancy"),
           F("nb_lignes_pointees", "int", "Lignes pointees", "Matched lines"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["OUVERT", "EN_COURS", "VALIDE", "BLOQUE"], "OUVERT")]),
        E("intercompany", "intercompany_entries", "IntercompanyEntry", "intercompany-entries", "intercompany",
          "Comptes inter-societes", "Intercompany accounts",
          "Echanges entre entites du groupe.", "Transactions between group entities.",
          "Elimination en consolidation obligatoire.",
          "Elimination in consolidation is mandatory.",
          "Link", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("entite_emettrice", "str", "Entite emettrice", "Origin entity"),
           F("entite_destinatrice", "str", "Entite destinatrice", "Destination entity"),
           F("date_ecriture", "date", "Date", "Date"),
           F("montant_xaf", "num", "Montant XAF", "Amount XAF"),
           F("nature", "enum", "Nature", "Nature"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("nature", ["FACTURATION", "AVANCE", "REMBoursement", "RESTRUCTURATION"], "FACTURATION"),
           EN("statut", ["OUVERT", "LETTRER", "ELIMINE"], "OUVERT")]),
        E("budget-control", "budget_controls", "BudgetControl", "budget-controls", "budget_control",
          "Budget et controle budgetaire", "Budget and control",
          "Budgets par centre de cout, consommations, ecarts.", "Budgets per cost center, consumption, variance.",
          "Le depassement declenche alerte DAF.",
          "Overrun triggers CFO alert.",
          "Wallet", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("centre_cout", "str", "Centre de cout", "Cost center"),
           F("exercice", "int", "Exercice", "Fiscal year"),
           F("budget_prevu_xaf", "num", "Budget prevu", "Planned budget"),
           F("consomme_xaf", "num", "Consomme", "Consumed"),
           F("engagement_xaf", "num", "Engage", "Committed"),
           F("ecart_pct", "num", "Ecart %", "Variance %"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["NORMAL", "ALERTE", "DEPASSE", "BLOQUE"], "NORMAL")]),
        E("audit-trail", "audit_pafs", "AuditPaf", "audit-pafs", "audit_trail",
          "Piste d'audit fiable", "Reliable audit trail",
          "Journal inalterable des ecritures comptables.", "Tamper-proof journal of GL entries.",
          "Chaque modification est une nouvelle ligne.",
          "Any modification is a new line.",
          "Lock", "hash_ligne",
          [F("hash_ligne", "str", "Hash ligne", "Row hash", required=True, search=True),
           F("date_ecriture", "date", "Date ecriture", "Posting date"),
           F("numero_piece", "str", "Numero piece", "Document number"),
           F("compte", "str", "Compte", "Account"),
           F("libelle", "text", "Libelle", "Label"),
           F("debit_xaf", "num", "Debit", "Debit"),
           F("credit_xaf", "num", "Credit", "Credit"),
           F("hash_precedent", "str", "Hash precedent", "Previous hash"),
           F("validite", "bool", "Validite PAF", "PAF valid")],
          []),
        E("tax-declarations", "tax_declarations", "TaxDeclaration", "tax-declarations", "tax_declaration",
          "Declarations fiscales periodiques", "Periodic tax filings",
          "TVA, IS, IRGM, patente.", "VAT, CIT, PAYE, license.",
          "Dépot dans le delai legal sous peine de penalite.",
          "Filed within legal deadline or penalties apply.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_declaration", "enum", "Type declaration", "Tax type"),
           F("periode_debut", "date", "Debut periode", "Period start"),
           F("periode_fin", "date", "Fin periode", "Period end"),
           F("base_imposable_xaf", "num", "Base imposable", "Tax base"),
           F("droits_xaf", "num", "Droits", "Duties"),
           F("date_depot", "date", "Date depot", "Filing date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_declaration", ["TVA", "IS", "IRAM", "IRGM", "PATENTE", "TITRE_FC"], "TVA"),
           EN("statut", ["BROUILLON", "DEPOSE", "PAYE", "RECLAME"], "BROUILLON")]),
        E("payroll-accounts", "payroll_entries", "PayrollEntry", "payroll-entries", "payroll_accounts",
          "Ecritures de paie", "Payroll entries",
          "Journalisation de la paie par periode.", "Payroll booking per period.",
          "Rapproche du livre de paie RH.",
          "Matches RH payroll book.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode", "str", "Periode", "Period"),
           F("masse_salariale_xaf", "num", "Masse salariale", "Payroll mass"),
           F("charges_patronales_xaf", "num", "Charges patronales", "Employer taxes"),
           F("impot_retenu_xaf", "num", "Impot retenu", "Withheld tax"),
           F("net_paye_xaf", "num", "Net paye", "Net paid"),
           F("date_passage", "date", "Date passage", "Posting date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "PASSER", "VALIDE"], "BROUILLON")]),
        E("treasury-accounts", "treasury_accounts", "TreasuryAccount", "treasury-accounts", "treasury_accounts",
          "Comptes de tresorerie", "Treasury accounts",
          "Comptes banque / caisse / regies.", "Bank / cash / petty accounts.",
          "Chaque compte a un responsable nomme.",
          "Each account has a designated owner.",
          "Lock", "code_compte",
          [F("code_compte", "str", "Code compte", "Account code", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("type_compte", "enum", "Type", "Type"),
           F("banque", "str", "Banque", "Bank"),
           F("rib", "str", "RIB", "IBAN"),
           F("solde_actuel_xaf", "num", "Solde actuel", "Current balance"),
           F("devise", "str", "Devise", "Currency"),
           F("responsable", "str", "Responsable", "Owner"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_compte", ["BANQUE", "CAISSE", "REGIE", "VIREMENT"], "BANQUE"),
           EN("statut", ["ACTIF", "GELE", "CLOTURE"], "ACTIF")]),
        E("analytical-accounting", "analytical_sections", "AnalyticalSection", "analytical-sections", "analytical_accounting",
          "Comptabilite analytique", "Cost accounting",
          "Sections analytiques par activite.", "Cost sections per activity.",
          "Cles de repartition validees par DAF.",
          "Allocation keys approved by CFO.",
          "Split", "code_section",
          [F("code_section", "str", "Code section", "Section code", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("type_section", "enum", "Type", "Type"),
           F("cle_repartition", "str", "Cle de repartition", "Allocation key"),
           F("unite_oeuvre", "str", "Unite d'oeuvre", "Cost driver"),
           F("cout_total_xaf", "num", "Cout total", "Total cost"),
           F("actif", "bool", "Actif", "Active")],
          [EN("type_section", ["HOMEGENE", "ANALYTIQUE", "AUXILIAIRE"], "ANALYTIQUE")]),
    ],
)

# ─── Wave 2B : finance-ohada ────────────────────────────────────────────────
MODULES["finance"] = dict(
    module_key="finance", module_slug="finance-ohada", module_path="finance-ohada",
    perm_module="finance", revision="052", down_revision="051_comptabilite_deep",
    entities=[
        E("budget-management", "multiyear_budgets", "MultiyearBudget", "multiyear-budgets", "budget_management",
          "Budget pluriannuel", "Multi-year budget",
          "Budgets strategiques 3-5 ans.", "3-5 year strategic budgets.",
          "Vote en conseil d'administration.", "Approved by the board.",
          "CalendarRange", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("exercice_debut", "int", "Exercice debut", "Start year"),
           F("exercice_fin", "int", "Exercice fin", "End year"),
           F("montant_prevu_xaf", "num", "Montant prevu", "Planned amount"),
           F("axes_strategiques", "text", "Axes strategiques", "Strategic axes"),
           F("vote_ba", "bool", "Vote BA", "Board approved"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "SOUMIS", "ADOPTE", "REJETE"], "BROUILLON")]),
        E("credit-facilities", "credit_facilities", "CreditFacility", "credit-facilities", "credit_facility",
          "Facilites de caisse et credits", "Cash credit facilities",
          "Facilites bancaires autorisees.", "Authorized bank facilities.",
          "Suivi de la consommation par rapport au plafond.",
          "Track usage against limit.",
          "DollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("banque", "str", "Banque", "Bank"),
           F("type_facilite", "enum", "Type", "Type"),
           F("montant_autorise_xaf", "num", "Montant autorise", "Approved amount"),
           F("montant_utilise_xaf", "num", "Montant utilise", "Used amount"),
           F("taux_interet_pct", "num", "Taux interet %", "Interest %"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_facilite", ["CAISSE", "ESCOMPTE", "AFFACTURAGE", "CREDIT_INVESTISSEMENT"], "CAISSE"),
           EN("statut", ["ACTIF", "EXPIRE", "RESILIE"], "ACTIF")]),
        E("cash-pooling", "cash_pools", "CashPool", "cash-pools", "cash_pooling",
          "Centralisation de tresorerie", "Cash pooling",
          "Pools de tresorerie inter-entites.", "Inter-entity cash pools.",
          "Compte rendu mensuel du pilotage.",
          "Monthly treasury review.",
          "Layers", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("entite_pilote", "str", "Entite pilote", "Lead entity"),
           F("entites_participantes", "text", "Entites participantes", "Participating entities"),
           F("montant_pool_xaf", "num", "Montant pool", "Pool amount"),
           F("interet_intragroupe_pct", "num", "Interet intragroupe %", "Intragroup interest %"),
           F("date_debut", "date", "Debut", "Start"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIF", "SUSPENDU", "DISSOUS"], "ACTIF")]),
        E("investment-tracking", "financial_investments", "FinancialInvestment", "financial-investments", "investment_tracking",
          "Investissements financiers", "Financial investments",
          "Placements, obligations, actions.", "Deposits, bonds, equities.",
          "Revue trimestrielle de performance.",
          "Quarterly performance review.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_placement", "enum", "Type placement", "Investment type"),
           F("institution", "str", "Institution", "Institution"),
           F("montant_place_xaf", "num", "Montant place", "Amount placed"),
           F("rendement_attendu_pct", "num", "Rendement attendu %", "Expected yield %"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_echeance", "date", "Echeance", "Maturity"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_placement", ["DAT", "OAT", "ACTION", "FOND", "COMTE_TERME"], "DAT"),
           EN("statut", ["DETENU", "CEDE", "VENU", "EXPIRE"], "DETENU")]),
        E("fx-management", "fx_exposures", "FxExposure", "fx-exposures", "fx_management",
          "Risque de change XAF/EUR/USD", "FX exposure XAF/EUR/USD",
          "Expositions nettes par devise.", "Net exposure per currency.",
          "Couverture au-dela de seuil DAF.",
          "Hedge above CFO threshold.",
          "DollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("devise", "str", "Devise", "Currency"),
           F("exposition_nette", "num", "Exposition nette", "Net exposure"),
           F("valeur_couverte", "num", "Valeur couverte", "Hedged amount"),
           F("instrument_couverture", "enum", "Instrument", "Instrument"),
           F("taux_couverture_pct", "num", "Taux couverture %", "Hedge ratio %"),
           F("date_echeance", "date", "Echeance", "Maturity"),
           F("statut", "enum", "Statut", "Status")],
          [EN("instrument_couverture", ["AUCUNE", "FORWARD", "OPTION", "SWAP"], "AUCUNE"),
           EN("statut", ["OUVERT", "COUVERT", "EXPIRE"], "OUVERT")]),
        E("payment-scheduling", "payment_schedules", "PaymentSchedule", "payment-schedules", "payment_scheduling",
          "Echeancier reglements fournisseurs", "Supplier payment schedule",
          "Planned outbound payments.", "Previsionnel des reglements fournisseurs.",
          "Respect des delais de paiement loi HP.",
          "Respect supplier payment legal delay.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("fournisseur_id", "int", "Fournisseur", "Supplier"),
           F("facture_id", "int", "Facture", "Invoice"),
           F("montant_echeance_xaf", "num", "Montant", "Amount"),
           F("date_echeance", "date", "Echeance", "Due date"),
           F("mode_reglement", "enum", "Mode reglement", "Payment mode"),
           F("statut", "enum", "Statut", "Status")],
          [EN("mode_reglement", ["VIREMENT", "CHEQUE", "ESPECES", "LETTRE_CHANGE"], "VIREMENT"),
           EN("statut", ["PLANIFIE", "PAYE", "RETARDE", "ANNULER"], "PLANIFIE")]),
        E("expense-reports", "expense_reports", "ExpenseReport", "expense-reports", "expense_report",
          "Notes de frais", "Expense reports",
          "Remboursements de frais professionnel.", "Business expense reimbursements.",
          "Justificatifs obligatoires pour chaque ligne.",
          "Receipt mandatory per line.",
          "Receipt", "numero_note_frais",
          [F("numero_note_frais", "str", "Numero", "Number", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("periode", "str", "Periode", "Period"),
           F("montant_total_xaf", "num", "Montant total", "Total amount"),
           F("nb_justificatifs", "int", "Nb justificatifs", "Receipt count"),
           F("date_depot", "date", "Date depot", "Filing date"),
           F("validateur", "str", "Validateur", "Approver"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["SOUMIS", "INCOMPLET", "VALIDE", "REJETE", "PAYE"], "SOUMIS")]),
        E("petty-cash", "petty_cash_boxes", "PettyCashBox", "petty-cash-boxes", "petty_cash",
          "Regies d'avance", "Petty cash",
          "Caisse menue par point de service.", "Cash float per location.",
          "Reconciliation journaliere obligatoire.",
          "Daily reconciliation mandatory.",
          "PiggyBank", "code_regie",
          [F("code_regie", "str", "Code regie", "Float code", required=True, search=True),
           F("lieu", "str", "Lieu", "Location"),
           F("responsable", "str", "Responsable", "Owner"),
           F("fond_initial_xaf", "num", "Fond initial", "Initial float"),
           F("solde_actuel_xaf", "num", "Solde actuel", "Current balance"),
           F("date_derniere_reconciliation", "date", "Derniere recon.", "Last reconciliation"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["NORMAL", "MANQUANT", "EXCEDENTAIRE", "SUSPENDU"], "NORMAL")]),
        E("bank-guarantees", "bank_guarantees", "BankGuarantee", "bank-guarantees", "bank_guarantee",
          "Garanties bancaires", "Bank guarantees",
          "Cautions emises par banque.", "Bonds issued by banks.",
          "Suivi strict des appels a premiere demande.",
          "Track on-demand claims strictly.",
          "Shield", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("banque_emettrice", "str", "Banque emettrice", "Issuing bank"),
           F("beneficiaire", "str", "Beneficiaire", "Beneficiary"),
           F("type_garantie", "enum", "Type", "Type"),
           F("montant_xaf", "num", "Montant XAF", "Amount XAF"),
           F("commission_pct", "num", "Commission %", "Fee %"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_garantie", ["SOUMISSION", "BONNE_EXECUTION", "AVANCE", "VISITE", "RESTITUTION_TVA"], "BONNE_EXECUTION"),
           EN("statut", ["ACTIVE", "EXPIREE", "APPELEE"], "ACTIVE")]),
        E("lease-accounting", "lease_contracts", "LeaseContract", "lease-contracts", "lease_accounting",
          "Credit-leasing / contrats location", "Lease and rental contracts",
          "Contrats leasing avec duree, loyer, valeur residuelle.", "Lease contracts with term, payment, residual.",
          "Conforme OHADA / IFRS 16.",
          "OHADA / IFRS 16 compliant.",
          "FileKey", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_contrat", "enum", "Type", "Type"),
           F("bien_concerne", "str", "Bien concerne", "Asset"),
           F("loyer_mensuel_xaf", "num", "Loyer mensuel", "Monthly payment"),
           F("duree_mois", "int", "Duree (mois)", "Term (months)"),
           F("valeur_residuelle_xaf", "num", "Valeur residuelle", "Residual value"),
           F("date_debut", "date", "Debut", "Start"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_contrat", ["LEASING", "LOCATION", "CREDIT_BAIL", "LOCATION_ACHAT"], "LEASING"),
           EN("statut", ["ACTIF", "FINI", "RESILIE", "LEVE"], "ACTIF")]),
        E("financial-forecast", "cash_forecasts", "CashForecast", "cash-forecasts", "financial_forecast",
          "Previsions de tresorerie", "Cash forecast",
          "Projection de tresorerie 12-24 mois.", "12-24 month cash projection.",
          "Revue hebdomadaire par tresorier.",
          "Weekly review by treasurer.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("horizon_mois", "int", "Horizon (mois)", "Horizon (months)"),
           F("entree_attendue_xaf", "num", "Entrees attendues", "Expected inflow"),
           F("sortie_attendue_xaf", "num", "Sorties attendues", "Expected outflow"),
           F("tresorerie_projete_xaf", "num", "Tresorerie projetee", "Projected cash"),
           F("hypothese", "text", "Hypotheses", "Assumptions"),
           F("date_revision", "date", "Revision", "Revision date")], []),
        E("treasury-alerts", "treasury_alerts", "TreasuryAlert", "treasury-alerts", "treasury_alerts",
          "Alertes tresorerie", "Treasury alerts",
          "Alertes seuil, BFR, echeance.", "Threshold, WC, due date alerts.",
          "Escalade DAF en cas de depassement seuil.",
          "Escalate to CFO if threshold crossed.",
          "BellRing", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_alerte", "enum", "Type", "Type"),
           F("seuil_declencheur", "num", "Seuil declencheur", "Trigger threshold"),
           F("valeur_constatee", "num", "Valeur constatee", "Observed value"),
           F("date_alerte", "datetime", "Date", "Alert date"),
           F("destinataire", "str", "Destinataire", "Recipient"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_alerte", ["SEUIL_BANCAIRE", "BFR", "ECHEANCE_PAIEMENT", "DEPASSEMENT_BUDGET"], "SEUIL_BANCAIRE"),
           EN("statut", ["OUVERTE", "PRISE_EN_CHARGE", "RESOLUE"], "OUVERTE")]),
    ],
)

# ─── Wave 2C : parc-vehicules ───────────────────────────────────────────────
MODULES["parc"] = dict(
    module_key="parc", module_slug="parc-vehicules", module_path="parc-vehicules",
    perm_module="parc", revision="053", down_revision="052_finance_deep",
    entities=[
        E("vehicle-inventory", "vehicle_inventories", "VehicleInventory", "vehicle-inventories", "vehicle_inventory",
          "Inventaire complet du parc", "Full fleet inventory",
          "Liste detaillee des vehicules avec attributs.", "Detailed fleet list with attributes.",
          "Chaque entree correspond a un numerò de serie unique.",
          "Each entry corresponds to a unique serial number.",
          "Truck", "numero_serie",
          [F("numero_serie", "str", "Numero serie", "Serial number", required=True, search=True),
           F("marque", "str", "Marque", "Brand"), F("modele", "str", "Modele", "Model"),
           F("annee", "int", "Annee", "Year"),
           F("carrosserie", "str", "Carrosserie", "Body"),
           F("energie", "enum", "Energie", "Energy"),
           F("kilometrage", "num", "Kilometrage", "Mileage"),
           F("cout_acquisition_xaf", "num", "Cout acquisition", "Acquisition cost"),
           F("valeur_argent_xaf", "num", "Valeur veneur", "Market value")],
          [EN("energie", ["GASOIL", "ESSENCE", "HYBRIDE", "ELECTRIQUE", "GPL", "CNG"], "GASOIL")]),
        E("tyre-management", "tyre_records", "TyreRecord", "tyre-records", "tyre_management",
          "Gestion pneumatiques", "Tyre management",
          "Suivi des gommes par vehicule.", "Tyre tracking per vehicle.",
          "Rotation tous les 15 000 km recommande.",
          "Rotation every 15,000 km recommended.",
          "CircleDot", "numero_gomme",
          [F("numero_gomme", "str", "Numero gomme", "Tyre number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("dimension", "str", "Dimension", "Size"),
           F("marque", "str", "Marque", "Brand"),
           F("position", "enum", "Position", "Position"),
           F("km_parcourus", "num", "Km parcourus", "Kilometers"),
           F("profondeur_couronne_mm", "num", "Profondeur couronne (mm)", "Tread depth (mm)"),
           F("date_montage", "date", "Date montage", "Mount date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("position", ["AV_G", "AV_D", "AR_G", "AR_D", "SPARE"], "AV_G"),
           EN("statut", ["MONTÉE", "REPOSE", "REBOUTE", "RECONSTRUCTION"], "MONTÉE")]),
        E("spare-parts", "spare_parts", "SparePart", "spare-parts", "spare_part",
          "Pieces detachees / stock atelier", "Spare parts / workshop stock",
          "Consommables et pieces atelier.", "Workshop consumables and parts.",
          "Seuil mini et conditionnement a respecter.",
          "Min threshold and packaging respected.",
          "Cog", "code_piece",
          [F("code_piece", "str", "Code piece", "Part code", required=True, search=True),
           F("designation", "str", "Designation", "Description"),
           F("referencence_constructeur", "str", "Ref. constructeur", "Manufacturer ref"),
           F("famille", "enum", "Famille", "Family"),
           F("stock_actuel", "num", "Stock actuel", "Current stock"),
           F("seuil_mini", "num", "Seuil mini", "Min threshold"),
           F("prix_unitaire_xaf", "num", "Prix unitaire", "Unit price"),
           F("fournisseur_principal", "str", "Fournisseur principal", "Main supplier"),
           F("compatibilites", "text", "Compatibilites", "Compatibilities")],
          [EN("famille", ["MOTEUR", "FREINAGE", "SUSPENSION", "ELECTRIQUE", "CARROSSERIE", "CONSO"], "MOTEUR")]),
        E("workshop-scheduling", "workshop_appointments", "WorkshopAppointment", "workshop-appointments", "workshop_scheduling",
          "Planification atelier", "Workshop scheduling",
          "RDV maintenance et reparation.", "Maintenance and repair appointments.",
          "Creneau par mecanicien et par pont.",
          "Slot per mechanic and lift.",
          "Calendar", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date_horaire", "datetime", "Date heure", "Date time"),
           F("type_intervention", "enum", "Type", "Type"),
           F("mecanicien", "str", "Mecanicien", "Mechanic"),
           F("duree_estimee_h", "num", "Duree estimee (h)", "Est. duration (h)"),
           F("cout_estime_xaf", "num", "Cout estime", "Estimated cost"),
           F("statut", "enum", "Statut", "Status"), F("notes", "text", "Notes", "Notes")],
          [EN("type_intervention", ["PREVENTIF", "CORRECTIF", "REVISION", "CONTROLE_TECHNIQUE"], "PREVENTIF"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "ANNULE"], "PLANIFIE")]),
        E("insurance-claims", "insurance_claims", "InsuranceClaim", "insurance-claims", "insurance_claim",
          "Sinistres et assurances", "Insurance claims",
          "Declaration sinistre, suivi indemnisation.", "Loss declaration and compensation tracking.",
          "Delai de declaration contractuel strict.",
          "Contractual declaration deadline strict.",
          "ClipboardList", "numero_sinistre",
          [F("numero_sinistre", "str", "Numero sinistre", "Claim number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date_sinistre", "date", "Date sinistre", "Incident date"),
           F("type_sinistre", "enum", "Type", "Type"),
           F("description", "text", "Description", "Description"),
           F("montant_estime_xaf", "num", "Montant estime", "Estimated amount"),
           F("montant_indemnise_xaf", "num", "Montant indemnise", "Compensation amount"),
           F("assureur", "str", "Assureur", "Insurer"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_sinistre", ["COLLISION", "VOL", "INCENDIE", "BRIS_DE_GLACE", "MARCHANDISES"], "COLLISION"),
           EN("statut", ["OUVERT", "EN_INSTRUCTION", "INDEMNISE", "REJETE"], "OUVERT")]),
        E("registration-tracking", "registration_records", "RegistrationRecord", "registration-records", "registration_tracking",
          "Suivi immatriculation", "Registration tracking",
          "Documents officiels d'immatriculation.", "Official registration documents.",
          "Renouvellement 30j avant expiration.",
          "Renew 30d before expiry.",
          "Contact", "numero_immatriculation",
          [F("numero_immatriculation", "str", "Immatriculation", "Plate", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("proprietaire", "str", "Proprietaire", "Owner"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("date_expiration", "date", "Date expiration", "Expiry date"),
           F("autorite", "str", "Autorite", "Authority"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["VALIDE", "EXPIRE", "EN_RENEW", "TRANSFERT"], "VALIDE")]),
        E("technical-visits", "technical_visits", "TechnicalVisit", "technical-visits", "technical_visit",
          "Visites techniques periodiques", "Periodic technical inspections",
          "Controles techniques obligatoires.", "Mandatory technical inspections.",
          "Report = immobilisation du vehicule.",
          "Failure = vehicle immobilized.",
          "ClipboardCheck", "numero_pv",
          [F("numero_pv", "str", "Numero PV", "Report number", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date_visite", "date", "Date visite", "Inspection date"),
           F("centre_controle", "str", "Centre controle", "Inspection center"),
           F("resultat", "enum", "Resultat", "Result"),
           F("observations", "text", "Observations", "Observations"),
           F("contre_visite_possible", "bool", "Contre-visite possible", "Retest allowed"),
           F("statut", "enum", "Statut", "Status")],
          [EN("resultat", ["CONFORME", "DEFAIT_MINEUR", "DEFAIT_MAJEUR", "REFUS"], "CONFORME"),
           EN("statut", ["PLANIFIE", "FAITE", "ECHEANCE_PROCHAINE"], "PLANIFIE")]),
        E("fuel-consumption", "fuel_consumptions", "FuelConsumption", "fuel-consumptions", "fuel_consumption",
          "Consommation par vehicule", "Per-vehicle fuel consumption",
          "Relevés pleins et consommation moyenne.", "Fuel ups and average consumption.",
          "Ecart > 15% declenche investigation.",
          "Gap > 15% triggers investigation.",
          "Fuel", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date", "date", "Date", "Date"),
           F("litres", "num", "Litres", "Litres"),
           F("prix_total_xaf", "num", "Prix total", "Total cost"),
           F("km_etape", "num", "Km etape", "Stage km"),
           F("conso_l100km", "num", "Conso (L/100km)", "Consumption (L/100km)"),
           F("station", "str", "Station", "Station"),
           F("carburant", "enum", "Carburant", "Fuel type")],
          [EN("carburant", ["GASOIL", "ESSENCE", "GPL", "CNG"], "GASOIL")]),
        E("vehicle-lifecycle", "vehicle_lifecycles", "VehicleLifecycle", "vehicle-lifecycles", "vehicle_lifecycle",
          "Cycle de vie / reforme", "Vehicle lifecycle / decommission",
          "Etapes de la vie du vehicule.", "Life stages of the vehicle.",
          "Reforme validee par DAF et direction technique.",
          "Disposal approved by CFO and technical direction.",
          "Recycle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("date_acquisition", "date", "Acquisition", "Acquisition"),
           F("date_reforme", "date", "Reforme", "Decommission"),
           F("duree_detention_an", "int", "Duree detention (an)", "Ownership (y)"),
           F("km_final", "num", "Km final", "Final km"),
           F("mode_reforme", "enum", "Mode reforme", "Disposal mode"),
           F("valeur_recuperation_xaf", "num", "Valeur recuperation", "Recovery value")],
          [EN("mode_reforme", ["VENTE", "RECYCLAGE", "DON", "DESTRUCTION"], "VENTE")]),
        E("cost-analysis", "cost_analyses", "CostAnalysis", "cost-analyses", "cost_analysis",
          "Analyse couts par vehicule", "Cost analysis per vehicle",
          "Couts par periode et par poste.", "Costs per period and line item.",
          "Indispensable pour le pilotage du TCO.",
          "Essential for TCO steering.",
          "BarChart", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule_id", "int", "Vehicule", "Vehicle"),
           F("periode", "str", "Periode", "Period"),
           F("cout_carburant_xaf", "num", "Carburant", "Fuel"),
           F("cout_maintenance_xaf", "num", "Maintenance", "Maintenance"),
           F("cout_assurance_xaf", "num", "Assurance", "Insurance"),
           F("cout_amortissement_xaf", "num", "Amortissement", "Depreciation"),
           F("cout_total_xaf", "num", "Cout total", "Total cost")], []),
    ],
)
