"""Manifest expansion transit-douane (Wave 1B : 12 submodules)."""

MANIFEST = {
    "module_key": "transit",
    "module_slug": "transit-douane",
    "module_path": "transit-douane",
    "perm_module": "transit",
    "revision": "048",
    "down_revision": "047_port_ops_deep",
    "entities": [
        {
            "slug": "hs-classification",
            "table": "hs_classifications",
            "class_name": "HsClassification",
            "entite": "hs-classifications",
            "perm": "hs_classification",
            "titre": "Classification tarifaire SH",
            "titreEn": "HS Tariff Classification",
            "description": "Referentiel des codes du systeme harmonise appliques aux marchandises.",
            "descriptionEn": "Harmonized System code reference applied to goods.",
            "aide": "Chaque declaration d'origine doit pointer vers un code SH valide.",
            "aideEn": "Each origin declaration must reference a valid HS code.",
            "icon": "BookOpen",
            "unicite": "code_hs",
            "fields": [
                {"name": "code_hs", "type": "str", "required": True, "label": "Code SH", "labelEn": "HS code", "search": True},
                {"name": "designation", "type": "text", "label": "Designation officielle", "labelEn": "Official description"},
                {"name": "section", "type": "str", "label": "Section du SH", "labelEn": "HS section"},
                {"name": "chapitre", "type": "str", "label": "Chapitre", "labelEn": "Chapter"},
                {"name": "position", "type": "str", "label": "Position", "labelEn": "Heading"},
                {"name": "sous_position", "type": "str", "label": "Sous-position", "labelEn": "Subheading"},
                {"name": "unite_mesure", "type": "str", "label": "Unite officielle", "labelEn": "Official UoM"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
            ],
            "enums": [
                {"name": "statut", "values": ["PROVISOIRE", "VALIDE", "ABROGE", "MODIFIE"], "default": "PROVISOIRE"},
            ],
        },
        {
            "slug": "customs-valuation",
            "table": "customs_valuations",
            "class_name": "CustomsValuation",
            "entite": "customs-valuations",
            "perm": "customs_valuation",
            "titre": "Valeur en douane / INCOTERMS",
            "titreEn": "Customs valuation / INCOTERMS",
            "description": "Determinations de valeur en douane selon accords OMC et INCOTERMS 2020.",
            "descriptionEn": "Customs valuation per WTO agreement and INCOTERMS 2020.",
            "aide": "Toute methode autre que transaction doit etre justifiee.",
            "aideEn": "Any method other than transaction must be justified.",
            "icon": "Calculator",
            "unicite": "reference_dossier",
            "fields": [
                {"name": "reference_dossier", "type": "str", "required": True, "label": "Reference dossier", "labelEn": "File reference", "search": True},
                {"name": "dum_id", "type": "int", "label": "ID DUM", "labelEn": "DUM id"},
                {"name": "methode_evaluation", "type": "enum", "label": "Methode d'evaluation", "labelEn": "Valuation method"},
                {"name": "incoterm", "type": "str", "label": "Incoterm", "labelEn": "Incoterm"},
                {"name": "valeur_declaree_xaf", "type": "num", "label": "Valeur declaree XAF", "labelEn": "Declared value XAF"},
                {"name": "valeur_transport_xaf", "type": "num", "label": "Fret XAF", "labelEn": "Freight XAF"},
                {"name": "valeur_assurance_xaf", "type": "num", "label": "Assurance XAF", "labelEn": "Insurance XAF"},
                {"name": "valeur_douane_xaf", "type": "num", "label": "Valeur en douane XAF", "labelEn": "Customs value XAF"},
                {"name": "taux_change", "type": "num", "label": "Taux de change applique", "labelEn": "Applied FX rate"},
                {"name": "date_evaluation", "type": "date", "label": "Date d'evaluation", "labelEn": "Valuation date"},
                {"name": "justification", "type": "text", "label": "Justification methode", "labelEn": "Method justification"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "methode_evaluation", "values": ["TRANSACTION", "IDENTIQUE", "SIMILAIRE", "DEDUCTION", "RECONSTITUEE", "SECOURS"], "default": "TRANSACTION"},
                {"name": "statut", "values": ["BROUILLON", "SOUMIS", "VALIDE", "REDRESSE"], "default": "BROUILLON"},
            ],
        },
        {
            "slug": "origin-certificates",
            "table": "origin_certificates",
            "class_name": "OriginCertificate",
            "entite": "origin-certificates",
            "perm": "origin_certificate",
            "titre": "Certificats d'origine",
            "titreEn": "Origin certificates",
            "description": "Form A, EUR.1, certificats CEMAC/CEA et declarations fournisseur.",
            "descriptionEn": "Form A, EUR.1, CEMAC/CAS form and supplier declarations.",
            "aide": "Verifier validite et visa de la chambre de commerce.",
            "aideEn": "Verify validity and chamber of commerce visa.",
            "icon": "Award",
            "unicite": "numero_certificat",
            "fields": [
                {"name": "numero_certificat", "type": "str", "required": True, "label": "Numero certificat", "labelEn": "Certificate number", "search": True},
                {"name": "type_certificat", "type": "enum", "label": "Type de certificat", "labelEn": "Certificate type"},
                {"name": "pays_origine", "type": "str", "label": "Pays d'origine", "labelEn": "Country of origin"},
                {"name": "exportateur", "type": "str", "label": "Exportateur", "labelEn": "Exporter"},
                {"name": "importateur", "type": "str", "label": "Importateur", "labelEn": "Importer"},
                {"name": "dum_id", "type": "int", "label": "ID DUM", "labelEn": "DUM id"},
                {"name": "date_emission", "type": "date", "label": "Date d'emission", "labelEn": "Issue date"},
                {"name": "date_expiration", "type": "date", "label": "Date d'expiration", "labelEn": "Expiry date"},
                {"name": "chambre_delivrance", "type": "str", "label": "Chambre delivrance", "labelEn": "Issuing chamber"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "type_certificat", "values": ["FORM_A", "EUR1", "CEMAC", "MOYEN_ORIENT", "DECLARATION_FOURNISSEUR", "AUTRE"], "default": "FORM_A"},
                {"name": "statut", "values": ["EMIS", "VERIFIE", "EXPIRE", "REVOQUE"], "default": "EMIS"},
            ],
        },
        {
            "slug": "bonded-warehouse",
            "table": "bonded_warehouses",
            "class_name": "BondedWarehouse",
            "entite": "bonded-warehouses",
            "perm": "bonded_warehouse",
            "titre": "Entrepots sous douane",
            "titreEn": "Bonded warehouses",
            "description": "Registre des entrepots sous douane agree et des marchandises stockees.",
            "descriptionEn": "Registry of approved bonded warehouses and stored goods.",
            "aide": "Chaque entrepot doit disposer d'un agrement en cours de validite.",
            "aideEn": "Each warehouse must hold a valid approval.",
            "icon": "Warehouse",
            "unicite": "code_entrepot",
            "fields": [
                {"name": "code_entrepot", "type": "str", "required": True, "label": "Code entrepot", "labelEn": "Warehouse code", "search": True},
                {"name": "nom", "type": "str", "label": "Nom", "labelEn": "Name"},
                {"name": "agrement_numero", "type": "str", "label": "Numero agrement", "labelEn": "Approval number"},
                {"name": "date_debut_agrement", "type": "date", "label": "Debut agrement", "labelEn": "Approval start"},
                {"name": "date_fin_agrement", "type": "date", "label": "Fin agrement", "labelEn": "Approval end"},
                {"name": "capacite_m2", "type": "num", "label": "Capacite m2", "labelEn": "Capacity m2"},
                {"name": "localisation", "type": "str", "label": "Localisation", "labelEn": "Location"},
                {"name": "gestionnaire", "type": "str", "label": "Gestionnaire", "labelEn": "Operator"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "statut", "values": ["OUVERT", "SUSPENDU", "RETIRE", "CONTROLE_EN_COURS"], "default": "OUVERT"},
            ],
        },
        {
            "slug": "transit-guarantees",
            "table": "transit_guarantees",
            "class_name": "TransitGuarantee",
            "entite": "transit-guarantees",
            "perm": "transit_guarantee",
            "titre": "Cautions et garanties",
            "titreEn": "Guarantees and bonds",
            "description": "Cautions bancaires / garanties globale / individuelle pour operations en transit.",
            "descriptionEn": "Bank bonds / global or individual guarantees for transit operations.",
            "aide": "Le montant couvert doit depasser les droits eventuels.",
            "aideEn": "The covered amount must exceed potential duties.",
            "icon": "ShieldCheck",
            "unicite": "reference_caution",
            "fields": [
                {"name": "reference_caution", "type": "str", "required": True, "label": "Reference caution", "labelEn": "Bond reference", "search": True},
                {"name": "type_garantie", "type": "enum", "label": "Type garantie", "labelEn": "Guarantee type"},
                {"name": "banque_emettrice", "type": "str", "label": "Banque emettrice", "labelEn": "Issuing bank"},
                {"name": "donneur_ordre", "type": "str", "label": "Donneur d'ordre", "labelEn": "Orderer"},
                {"name": "montant_caution_xaf", "type": "num", "label": "Montant XAF", "labelEn": "Amount XAF"},
                {"name": "date_debut", "type": "date", "label": "Date debut", "labelEn": "Start date"},
                {"name": "date_fin", "type": "date", "label": "Date fin", "labelEn": "End date"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "type_garantie", "values": ["GLOBALE", "INDIVIDUELLE", "CAUTION_BANCAIRE", "HYPOTHECAIRE"], "default": "GLOBALE"},
                {"name": "statut", "values": ["ACTIVE", "EXPIREE", "BLOQUEE", "REVOQUEE"], "default": "ACTIVE"},
            ],
        },
        {
            "slug": "export-declarations",
            "table": "export_declarations",
            "class_name": "ExportDeclaration",
            "entite": "export-declarations",
            "perm": "export_declaration",
            "titre": "Declarations export",
            "titreEn": "Export declarations",
            "description": "DGE / declarations d'exportation definitive ou temporaire.",
            "descriptionEn": "Definitive or temporary export declarations.",
            "aide": "Le certificat de sortie est edite apres validation de la DGE.",
            "aideEn": "Exit certificate issued after DGE validation.",
            "icon": "PlaneTakeoff",
            "unicite": "numero_dge",
            "fields": [
                {"name": "numero_dge", "type": "str", "required": True, "label": "Numero DGE", "labelEn": "DGE number", "search": True},
                {"name": "declarant", "type": "str", "label": "Declarant", "labelEn": "Declarant"},
                {"name": "exportateur", "type": "str", "label": "Exportateur", "labelEn": "Exporter"},
                {"name": "pays_destination", "type": "str", "label": "Pays de destination", "labelEn": "Destination country"},
                {"name": "valeur_xaf", "type": "num", "label": "Valeur XAF", "labelEn": "Value XAF"},
                {"name": "poids_net_kg", "type": "num", "label": "Poids net (kg)", "labelEn": "Net weight (kg)"},
                {"name": "regime", "type": "enum", "label": "Regime", "labelEn": "Regime"},
                {"name": "date_depot", "type": "date", "label": "Date depot", "labelEn": "Filing date"},
                {"name": "date_validation", "type": "date", "label": "Date validation", "labelEn": "Validation date"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "regime", "values": ["DEFINITIF", "TEMPORAIRE", "PERFECTIONNEMENT"], "default": "DEFINITIF"},
                {"name": "statut", "values": ["BROUILLON", "DEPOSE", "VALIDE", "REFUSE", "MODIFIE"], "default": "BROUILLON"},
            ],
        },
        {
            "slug": "prohibited-goods",
            "table": "prohibited_goods",
            "class_name": "ProhibitedGood",
            "entite": "prohibited-goods",
            "perm": "prohibited_good",
            "titre": "Marchandises prohibees / contingentees",
            "titreEn": "Prohibited / restricted goods",
            "description": "Liste des produits soumis a interdiction ou licence particuliere.",
            "descriptionEn": "Products under prohibition or special license.",
            "aide": "Chaque ligne declaree doit etre confrontee a cette liste.",
            "aideEn": "Each declared line must be checked against this list.",
            "icon": "Ban",
            "unicite": "code_produit",
            "fields": [
                {"name": "code_produit", "type": "str", "required": True, "label": "Code produit", "labelEn": "Product code", "search": True},
                {"name": "designation", "type": "text", "label": "Designation", "labelEn": "Description"},
                {"name": "code_hs", "type": "str", "label": "Code SH associe", "labelEn": "Associated HS code"},
                {"name": "categorie", "type": "enum", "label": "Categorie restriction", "labelEn": "Restriction category"},
                {"name": "base_legale", "type": "text", "label": "Base legale", "labelEn": "Legal basis"},
                {"name": "autorite_competente", "type": "str", "label": "Autorite competente", "labelEn": "Competent authority"},
                {"name": "conditions_regime", "type": "text", "label": "Conditions de levee", "labelEn": "Release conditions"},
                {"name": "actif", "type": "bool", "label": "Actif", "labelEn": "Active"},
            ],
            "enums": [
                {"name": "categorie", "values": ["INTERDICTION_TOTAL", "LICENCE", "CONTINGENTEMENT", "NORME_QUALITE", "SANITAIRE"], "default": "LICENCE"},
            ],
        },
        {
            "slug": "customs-regimes",
            "table": "customs_regimes",
            "class_name": "CustomsRegime",
            "entite": "customs-regimes",
            "perm": "customs_regime",
            "titre": "Regimes economiques",
            "titreEn": "Economic customs regimes",
            "description": "Admission temporaire, perfectionnement actif/passif, sous douane, exportation temporaire.",
            "descriptionEn": "Temporary admission, inward/outward processing, bonded, temporary export.",
            "aide": "Chaque regime necessite un arrete d'agrement.",
            "aideEn": "Each regime requires an approval decree.",
            "icon": "Settings",
            "unicite": "reference_regime",
            "fields": [
                {"name": "reference_regime", "type": "str", "required": True, "label": "Reference regime", "labelEn": "Regime reference", "search": True},
                {"name": "dum_id", "type": "int", "label": "ID DUM associe", "labelEn": "Linked DUM id"},
                {"name": "type_regime", "type": "enum", "label": "Type de regime", "labelEn": "Regime type"},
                {"name": "duree_max_mois", "type": "int", "label": "Duree max (mois)", "labelEn": "Max duration (months)"},
                {"name": "date_appllication", "type": "date", "label": "Date d'application", "labelEn": "Application date"},
                {"name": "date_echeance", "type": "date", "label": "Date d'echeance", "labelEn": "Due date"},
                {"name": "caution_associee", "type": "str", "label": "Caution associee", "labelEn": "Related bond"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "type_regime", "values": ["ADMISSION_TEMPORAIRE", "PERFECTIONNEMENT_ACTIF", "PERFECTIONNEMENT_PASSIF", "SOUS_DOUANE", "EXPORTATION_TEMPORAIRE"], "default": "ADMISSION_TEMPORAIRE"},
                {"name": "statut", "values": ["OUVERT", "PROROGEE", "CLOTURE", "MANQUANT"], "default": "OUVERT"},
            ],
        },
        {
            "slug": "physical-inspections",
            "table": "physical_inspections",
            "class_name": "PhysicalInspection",
            "entite": "physical-inspections",
            "perm": "physical_inspection",
            "titre": "Visites et inspections physiques",
            "titreEn": "Physical inspections",
            "description": "PV de visite douaniere, nivelles de controle, resultat.",
            "descriptionEn": "Customs inspection report, control channel, result.",
            "aide": "Le niveau de controle est attribue par le moteur de ciblage.",
            "aideEn": "Control level is assigned by the targeting engine.",
            "icon": "Search",
            "unicite": "numero_pv",
            "fields": [
                {"name": "numero_pv", "type": "str", "required": True, "label": "Numero PV", "labelEn": "Report number", "search": True},
                {"name": "dum_id", "type": "int", "label": "ID DUM", "labelEn": "DUM id"},
                {"name": "canal", "type": "enum", "label": "Canal de controle", "labelEn": "Control channel"},
                {"name": "inspecteur", "type": "str", "label": "Inspecteur", "labelEn": "Inspector"},
                {"name": "date_inspection", "type": "datetime", "label": "Date inspection", "labelEn": "Inspection date"},
                {"name": "lieu", "type": "str", "label": "Lieu", "labelEn": "Location"},
                {"name": "resultat", "type": "enum", "label": "Resultat", "labelEn": "Result"},
                {"name": "ecart_poids_kg", "type": "num", "label": "Ecart de poids", "labelEn": "Weight discrepancy"},
                {"name": "ecart_colis", "type": "int", "label": "Ecart colis", "labelEn": "Package discrepancy"},
                {"name": "observations", "type": "text", "label": "Observations", "labelEn": "Observations"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
            ],
            "enums": [
                {"name": "canal", "values": ["VERT", "ORANGE", "ROUGE", "BLEU"], "default": "VERT"},
                {"name": "resultat", "values": ["CONFORME", "ECART_LEGER", "ECART_SUBSTANTIEL", "FRAUDE"], "default": "CONFORME"},
                {"name": "statut", "values": ["PLANIFIEE", "EN_COURS", "CLOTUREE"], "default": "PLANIFIEE"},
            ],
        },
        {
            "slug": "duty-payments",
            "table": "duty_payments",
            "class_name": "DutyPayment",
            "entite": "duty-payments",
            "perm": "duty_payment",
            "titre": "Paiement droits et taxes",
            "titreEn": "Duty and tax payments",
            "description": "Suivi des reglements (acomptes, solde, remboursement) associes aux DUM.",
            "descriptionEn": "Payments tracking (advance, balance, refund) attached to DUMs.",
            "aide": "Rapprochement avec la comptabilite obligatoire.",
            "aideEn": "Reconciliation with accounting is mandatory.",
            "icon": "Receipt",
            "unicite": "numero_quittance",
            "fields": [
                {"name": "numero_quittance", "type": "str", "required": True, "label": "Numero quittance", "labelEn": "Receipt number", "search": True},
                {"name": "dum_id", "type": "int", "label": "ID DUM", "labelEn": "DUM id"},
                {"name": "type_paiement", "type": "enum", "label": "Type paiement", "labelEn": "Payment type"},
                {"name": "droits_percus_xaf", "type": "num", "label": "Droits percus XAF", "labelEn": "Dues collected XAF"},
                {"name": "tva_xaf", "type": "num", "label": "TVA XAF", "labelEn": "VAT XAF"},
                {"name": "taxe_statistique_xaf", "type": "num", "label": "Taxe statistique XAF", "labelEn": "Statistical tax XAF"},
                {"name": "redevance_id", "type": "str", "label": "Redevance associee", "labelEn": "Related retribution"},
                {"name": "mode_reglement", "type": "enum", "label": "Mode reglement", "labelEn": "Payment mode"},
                {"name": "date_paiement", "type": "date", "label": "Date paiement", "labelEn": "Payment date"},
                {"name": "statut", "type": "enum", "label": "Statut", "labelEn": "Status"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "type_paiement", "values": ["ACOMPTE", "SOLDE", "REMBOURSEMENT", "PENALITE"], "default": "SOLDE"},
                {"name": "mode_reglement", "values": ["VIREMENT", "CHEQUE", "ESPECES", "MOBILE_MONEY", "COMPENSATION"], "default": "VIREMENT"},
                {"name": "statut", "values": ["DU", "PARTIEL", "PAYE", "REMBOURSE", "CONTESTE"], "default": "DU"},
            ],
        },
        {
            "slug": "trader-registration",
            "table": "trader_registrations",
            "class_name": "TraderRegistration",
            "entite": "trader-registrations",
            "perm": "trader_registration",
            "titre": "Enregistrement operateur economique",
            "titreEn": "Economic operator registration",
            "description": "Numeros operateur EORI local / agrements OEA.",
            "descriptionEn": "Local EORI numbers / authorized economic operator approvals.",
            "aide": "L'operateur doit etre a jour de ses obligations fiscales.",
            "aideEn": "Operator must be up to date on tax obligations.",
            "icon": "Contact",
            "unicite": "numero_operateur",
            "fields": [
                {"name": "numero_operateur", "type": "str", "required": True, "label": "Numero operateur", "labelEn": "Operator number", "search": True},
                {"name": "raison_sociale", "type": "str", "label": "Raison sociale", "labelEn": "Legal name"},
                {"name": "niu", "type": "str", "label": "NIU", "labelEn": "Tax ID"},
                {"name": "rc_number", "type": "str", "label": "Numero RC", "labelEn": "Reg. commerce"},
                {"name": "type_operateur", "type": "enum", "label": "Type operateur", "labelEn": "Operator type"},
                {"name": "statut_oea", "type": "enum", "label": "Statut OEA", "labelEn": "AEO status"},
                {"name": "date_agrement", "type": "date", "label": "Date agrement", "labelEn": "Approval date"},
                {"name": "date_expiration", "type": "date", "label": "Date expiration", "labelEn": "Expiry date"},
                {"name": "contact_email", "type": "str", "label": "Email contact", "labelEn": "Contact email"},
                {"name": "contact_telephone", "type": "str", "label": "Telephone contact", "labelEn": "Contact phone"},
                {"name": "notes", "type": "text", "label": "Notes", "labelEn": "Notes"},
            ],
            "enums": [
                {"name": "type_operateur", "values": ["IMPORTATEUR", "EXPORTATEUR", "TRANSITAIRE", "COMMISSIONNAIRE", "PRODUCTEUR"], "default": "IMPORTATEUR"},
                {"name": "statut_oea", "values": ["NON_OEA", "OEA_SIMPLE", "OEA_COMPLET", "RETIREE"], "default": "NON_OEA"},
            ],
        },
        {
            "slug": "tariff-reference",
            "table": "tariff_references",
            "class_name": "TariffReference",
            "entite": "tariff-references",
            "perm": "tariff_reference",
            "titre": "Tarif integre CEMAC",
            "titreEn": "CEMAC integrated tariff",
            "description": "Tarif exterieur commun CEMAC, taxes applicables par ligne tarifaire.",
            "descriptionEn": "CEMAC common external tariff and applicable taxes.",
            "aide": "Consulte automatiquement par le moteur de calcul DUM.",
            "aideEn": "Auto-consulted by DUM calculation engine.",
            "icon": "Scale",
            "unicite": "code_ligne_tarifaire",
            "fields": [
                {"name": "code_ligne_tarifaire", "type": "str", "required": True, "label": "Code ligne tarifaire", "labelEn": "Tariff line code", "search": True},
                {"name": "code_hs", "type": "str", "label": "Code SH associe", "labelEn": "Associated HS"},
                {"name": "designation", "type": "text", "label": "Designation", "labelEn": "Description"},
                {"name": "droit_base_pct", "type": "num", "label": "Droit de base %", "labelEn": "Base duty %"},
                {"name": "cotisation_compensatoire_pct", "type": "num", "label": "Cotisation compensatrice %", "labelEn": "Comp. levy %"},
                {"name": "taxe_foretiaire_pct", "type": "num", "label": "Taxe forestiere %", "labelEn": "Forestry tax %"},
                {"name": "redevance_statistique_pct", "type": "num", "label": "Redevance statistique %", "labelEn": "Stat. levy %"},
                {"name": "tva_pct", "type": "num", "label": "TVA %", "labelEn": "VAT %"},
                {"name": "categorie_produit", "type": "enum", "label": "Categorie produit", "labelEn": "Product category"},
                {"name": "date_application", "type": "date", "label": "Date d'application", "labelEn": "Application date"},
                {"name": "date_fin", "type": "date", "label": "Date de fin", "labelEn": "End date"},
            ],
            "enums": [
                {"name": "categorie_produit", "values": ["BASIC", "INTERMEDIAIRE", "FINI", "CAPITAL", "SENSIBLE"], "default": "BASIC"},
            ],
        },
    ],
}
