"""Manifest Vague D — batch D1.

Deux volets :
  1. admin-tenant (module REEL, pas un portail) : +10 objets d'administration
     tenant -> 20. perm_module="admin" (console plateforme, superuser/admin ;
     coherent avec admin-saas/superadmin-cadc deja en « admin »/« superadmin »).
  2. Portails metier « sober & justifie » : on n'invente PAS 20 ecrans creux.
     On ajoute uniquement des enregistrements que le ROLE capture sur le
     terrain (objets distincts des tables maitresses operationnelles), et on
     les monte sous le prefixe /api/v1/<portail> avec un perm_module qui un
     role supervisant DETIENT deja (wildcard ROLE_GRANTS) => endpoints reellement
     atteignables et consommables, pas des ecrans morts.
       - portail-chauffeur  -> perm_module="transport" (« transport.*.* » CHEF_PARC/DISPATCHER)
       - portail-magasinier -> perm_module="magasin"   (« magasin.*.* » CHEF_MAGASIN)

Chaine Alembic 086-088 depuis 085_superadmin_c_deep (tete lineaire unique).
Convention d'honnetete : aucune valeur par defaut fabriquee ; statut = cycle de
vie metier explicite ; NULL = « non enregistre ».
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── admin-tenant (+10 -> 20) ────────────────────────────────────────────────
MODULES["admin_tenant_c"] = dict(
    module_key="admin_tenant_c", module_slug="admin-tenant",
    module_path="admin-tenant", perm_module="admin",
    registre_filename="registres_c",
    revision="086", down_revision="085_superadmin_c_deep",
    entities=[
        E("domain-configs", "admtd_domain_configs", "AdmtDomainConfig", "admtd-domain-configs",
          "domain_config", "Configurations de domaine", "Domain configs",
          "Nom de domaine rattache a un tenant.",
          "Domain name attached to a tenant.",
          "Un domaine verifie avec certificat SSL.", "Verified domain with SSL certificate.",
          "Globe", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("domaine", "str", "Domaine", "Domain"),
           F("type", "str", "Type", "Type"),
           F("certificat_ssl", "bool", "Certificat SSL", "SSL certificate"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["PRINCIPAL", "SECONDIAIRE", "REDIRECTION"]),
           EN("statut", ["EN_ATTENTE", "VERIFIE", "ACTIF", "REVOQUE"])]),

        E("dns-records", "admtd_dns_records", "AdmtDnsRecord", "admtd-dns-records",
          "dns_record", "Enregistrements DNS", "DNS records",
          "Enregistrements DNS configures pour le tenant.",
          "DNS records configured for the tenant.",
          "TTL et valeur font la propagation.", "TTL and value drive propagation.",
          "Network", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom_hote", "str", "Nom d'hote", "Hostname"),
           F("type_enregistrement", "str", "Type", "Type"),
           F("valeur", "str", "Valeur", "Value"),
           F("ttl_secondes", "int", "TTL (s)", "TTL (s)"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_enregistrement", ["A", "CNAME", "MX", "TXT"]),
           EN("statut", ["PROPAGE", "EN_ATTENTE", "SUPPRIME"])]),

        E("data-residency", "admtd_data_residency", "AdmtDataResidency", "admtd-data-residency",
          "data_residency", "Souverainete des donnees", "Data residency",
          "Localisation geographique et hebergement des donnees d' un tenant.",
          "Geographic location and hosting of a tenant's data.",
          "La region et la certification conditionnent la conformite.",
          "Region and certification drive compliance.",
          "Database", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("region", "str", "Region", "Region"),
           F("hebergeur", "str", "Hebergeur", "Host provider"),
           F("certification_conforme", "bool", "Certification conforme", "Certified compliant"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "EN_COURS", "NON_CONFORME", "REVISER"])]),

        E("feature-entitlements", "admtd_feature_entitlements", "AdmtFeatureEntitlement", "admtd-feature-entitlements",
          "feature_entitlement", "Droits fonctionnels", "Feature entitlements",
          "Activation d' un module/fonction pour un tenant.",
          "Activation of a module/feature for a tenant.",
          "Limite et expiration bornent le droit.", "Limit and expiry bound the entitlement.",
          "KeyRound", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("module", "str", "Module", "Module"),
           F("actif", "bool", "Actif", "Active"),
           F("limite", "int", "Limite", "Limit"),
           F("date_expiration", "date", "Expiration", "Expiry date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACCORD", "SUSPENDU", "EXPIRE", "RETIRE"])]),

        E("usage-quotas", "admtd_usage_quotas", "AdmtUsageQuota", "admtd-usage-quotas",
          "usage_quota", "Quotas d' usage", "Usage quotas",
          "Quota alloue et consomme par ressource pour un tenant.",
          "Allocated and consumed quota per resource for a tenant.",
          "La consommation ne doit pas depasser le quota.", "Consumption must not exceed quota.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ressource", "str", "Ressource", "Resource"),
           F("quota_autorise", "int", "Quota autorise", "Allowed quota"),
           F("consomme", "int", "Consomme", "Consumed"),
           F("periode", "str", "Periode", "Period"),
           F("statut", "str", "Statut", "Status")],
          [EN("periode", ["MENSUEL", "TRIMESTRIEL", "ANNUEL"]),
           EN("statut", ["NOMINAL", "PROCHE", "DEPASSE", "BLOQUE"])]),

        E("impersonation-logs", "admtd_impersonation_logs", "AdmtImpersonationLog", "admtd-impersonation-logs",
          "impersonation_log", "Journaux d' impersonation", "Impersonation logs",
          "Trace d' une session d' administration en tant qu' un tenant.",
          "Trace of an admin session acting as a tenant.",
          "Toute impersonation est motivee et bornee dans le temps.",
          "Every impersonation is justified and time-bounded.",
          "UserCog", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("admin", "str", "Admin", "Admin"),
           F("cible_tenant", "str", "Tenant cible", "Target tenant"),
           F("motif", "text", "Motif", "Reason"),
           F("debut", "datetime", "Debut", "Start"),
           F("fin", "datetime", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "TERMINEE", "REVOCABLE", "ANOMALE"])]),

        E("onboarding-steps", "admtd_onboarding_steps", "AdmtOnboardingStep", "admtd-onboarding-steps",
          "onboarding_step", "Etapes d' onboarding", "Onboarding steps",
          "Jalon du demarrage operationnel d' un nouveau tenant.",
          "Milestone of a new tenant's operational go-live.",
          "Ordre et responsable structurent le deploiement.", "Order and owner structure rollout.",
          "ListChecks", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("etape", "str", "Etape", "Step"),
           F("ordre", "int", "Ordre", "Order"),
           F("responsable", "str", "Responsable", "Owner"),
           F("date_completion", "date", "Date completion", "Completion date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_FAIRE", "EN_COURS", "FAITE", "BLOQUEE"])]),

        E("white-label-configs", "admtd_white_label_configs", "AdmtWhiteLabelConfig", "admtd-white-label-configs",
          "white_label_config", "Configurations marque blanche", "White-label configs",
          "Personnalisation de marque affichee pour un tenant.",
          "Branding personalization shown to a tenant.",
          "Nom, logo et couleur definissent l' habillage.", "Name, logo and color define the skin.",
          "Palette", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("nom_affiche", "str", "Nom affiche", "Display name"),
           F("logo_url", "str", "URL logo", "Logo URL"),
           F("couleur_principale", "str", "Couleur principale", "Primary color"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "PUBLIE", "ANCIEN"])]),

        E("tenant-backups", "admtd_tenant_backups", "AdmtTenantBackup", "admtd-tenant-backups",
          "tenant_backup", "Sauvegardes tenant", "Tenant backups",
          "Sauvegarde periodique des donnees d' un tenant.",
          "Periodic backup of a tenant's data.",
          "Taille, frequence et derniere reussite caracterisent la sauvegarde.",
          "Size, cadence and last success characterize the backup.",
          "HardDrive", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("taille_octets", "int", "Taille (octets)", "Size (bytes)"),
           F("frequence", "str", "Frequence", "Cadence"),
           F("derniere_reussite", "datetime", "Derniere reussite", "Last success"),
           F("statut", "str", "Statut", "Status")],
          [EN("frequence", ["QUOTIDIEN", "HEBDOMADAIRE", "MENSUEL"]),
           EN("statut", ["PROGRAMMEE", "EN_COURS", "REUSSIE", "ECHEC"])]),

        E("integration-webhooks", "admtd_integration_webhooks", "AdmtIntegrationWebhook", "admtd-integration-webhooks",
          "integration_webhook", "Webhooks d' integration", "Integration webhooks",
          "Notification sortante vers un systeme externe.",
          "Outbound notification to an external system.",
          "Evenement, URL et secret definissent la livraison.", "Event, URL and secret define delivery.",
          "Webhook", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("url_cible", "str", "URL cible", "Target URL"),
           F("evenement", "str", "Evenement", "Event"),
           F("actif", "bool", "Actif", "Active"),
           F("statut", "str", "Statut", "Status")],
          [EN("evenement", ["COMMANDE", "LIVRAISON", "FACTURE", "TENANT"]),
           EN("statut", ["ACTIF", "EN_ERREUR", "SUSPENDU", "SUPPRIME"])]),
    ],
)

# ─── portail-chauffeur (+19 -> 20) : records captures sur la route ───────────
MODULES["chauffeur_c"] = dict(
    module_key="chauffeur_c", module_slug="portail-chauffeur",
    module_path="portail-chauffeur", perm_module="transport",
    registre_filename="registres_c",
    revision="087", down_revision="086_admin_tenant_c_deep",
    entities=[
        E("trip-sheets", "chf_trip_sheets", "ChfTripSheet", "chf-trip-sheets",
          "trip_sheet", "Feuilles de route", "Trip sheets",
          "Enregistrements de parcours reellement effectues par le chauffeur.",
          "Actual routes performed by the driver.",
          "Km de debut/fin justifient la distance reellement parcourue.",
          "Start/end odometer justify the actual distance.",
          "Route", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("mission", "str", "Mission", "Mission"),
           F("debut", "datetime", "Debut", "Start"),
           F("fin", "datetime", "Fin", "End"),
           F("km_debut", "int", "Km debut", "Start odometer"),
           F("km_fin", "int", "Km fin", "End odometer"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "TERMINEE", "VALIDEE", "ANOMALIE"])]),

        E("daily-vehicle-checks", "chf_daily_vehicle_checks", "ChfDailyVehicleCheck", "chf-daily-vehicle-checks",
          "daily_vehicle_check", "Controles quotidiens du vehicule", "Daily vehicle checks",
          "Checklist de securite avant depart.", "Pre-departure safety checklist.",
          "Les anomalies bloquent le depart jusqu' a resolution.",
          "Defects block departure until resolved.",
          "ClipboardCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("date_controle", "datetime", "Date controle", "Check date"),
           F("points_controles", "int", "Points controles", "Points checked"),
           F("anomalies", "bool", "Anomalies", "Defects"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "ANOMALIE", "IMMOBILISE"])]),

        E("fuel-logs", "chf_fuel_logs", "ChfFuelLog", "chf-fuel-logs",
          "fuel_log", "Carnet carburant", "Fuel logs",
          "Pleins effectues par le chauffeur.", "Fuel-ups performed by the driver.",
          "Litres et prix justifient la consommation.", "Liters and price justify consumption.",
          "Fuel", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("litres", "num", "Litres", "Liters"),
           F("prix", "num", "Prix", "Amount"),
           F("station", "str", "Station", "Station"),
           F("date_plein", "datetime", "Date plein", "Fill date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ENREGISTRE", "JUSTIFIE", "REMBOURSE", "REJETE"])]),

        E("driving-times", "chf_driving_times", "ChfDrivingTimeRecord", "chf-driving-times",
          "driving_time", "Temps de conduite", "Driving times",
          "Durees de conduite brutes (chronotachygraphe).", "Raw driving durations (tachograph).",
          "Depassement du seuil legal = statut HORS_REGLE.",
          "Exceeding the legal limit = out-of-regulation.",
          "Timer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chauffeur", "str", "Chauffeur", "Driver"),
           F("debut", "datetime", "Debut", "Start"),
           F("fin", "datetime", "Fin", "End"),
           F("minutes_conduite", "int", "Minutes de conduite", "Driving minutes"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONDUITE", "DISPO", "REPOS", "HORS_REGLE"])]),

        E("rest-breaks", "chf_rest_breaks", "ChfRestBreak", "chf-rest-breaks",
          "rest_break", "Pauses et repos", "Rest breaks",
          "Repos obligaires pris par le chauffeur.", "Mandatory rest taken by the driver.",
          "La duree et le lieu attestent le respect de la reglementation.",
          "Duration and place evidence regulatory compliance.",
          "Coffee", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chauffeur", "str", "Chauffeur", "Driver"),
           F("debut", "datetime", "Debut", "Start"),
           F("duree_min", "int", "Duree (min)", "Duration (min)"),
           F("lieu", "str", "Lieu", "Place"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PRISE", "INTERROMPU", "MANQUANT"])]),

        E("toll-receipts", "chf_toll_receipts", "ChfTollReceipt", "chf-toll-receipts",
          "toll_receipt", "Recus de peage", "Toll receipts",
          "Frais de peage engages sur la route.", "Toll costs incurred on the road.",
          "Le montant et le troncon justifiant la note de frais.",
          "Amount and section justify the expense.",
          "Receipt", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("peage", "str", "Peage", "Toll booth"),
           F("montant", "num", "Montant", "Amount"),
           F("date_passage", "datetime", "Date passage", "Crossing date"),
           F("troncon", "str", "Troncon", "Section"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ENREGISTRE", "REMBOURSE", "REJETE"])]),

        E("parking-sessions", "chf_parking_sessions", "ChfParkingSession", "chf-parking-sessions",
          "parking_session", "Sessions de parking", "Parking sessions",
          "Arrets decharge / fourriere / parking payant.", "Unloading / impound / paid parking.",
          "Entree et sortie determinent la duree et le frais.",
          "Entry and exit determine duration and cost.",
          "Building2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("lieu", "str", "Lieu", "Place"),
           F("entree", "datetime", "Entree", "Entry"),
           F("sortie", "datetime", "Sortie", "Exit"),
           F("frais", "num", "Frais", "Cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERTE", "FERMEE", "REMBOURSEE"])]),

        E("cargo-seals", "chf_cargo_seals", "ChfCargoSeal", "chf-cargo-seals",
          "cargo_seal", "Plombs de cargaison", "Cargo seals",
          "Pose et verification des plombs sur unite de transport.",
          "Seal placement and check on the transport unit.",
          "Plomb intact a l' arrivee = cargo nonouvert.",
          "Intact seal at arrival = cargo unopened.",
          "Lock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("unite", "str", "Unite", "Unit"),
           F("numero_plomb", "str", "Numero de plomb", "Seal number"),
           F("pose_datetime", "datetime", "Pose", "Sealed at"),
           F("retrait_datetime", "datetime", "Retrait", "Removed at"),
           F("intact", "bool", "Intact", "Intact"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["POSE", "CONTROLE", "ROMPU", "REMPPLACE"])]),

        E("roadside-incidents", "chf_roadside_incidents", "ChfRoadsideIncident", "chf-roadside-incidents",
          "roadside_incident", "Incidents de route", "Roadside incidents",
          "Evenement inattendu survenu en conduite.", "Unexpected event during driving.",
          "Gravite et localisation qualifient l' incident.", "Severity and location qualify it.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_incident", "str", "Type", "Type"),
           F("localisation", "str", "Localisation", "Location"),
           F("date", "datetime", "Date", "Date"),
           F("gravite", "str", "Gravite", "Severity"),
           F("decrit", "text", "Description", "Description"),
           F("statut", "str", "Statut", "Status")],
          [EN("gravite", ["MINEUR", "MAJEUR", "CRITIQUE"]),
           EN("statut", ["OUVERT", "SIGNAL", "RESOLU", "ASSURANCE"])]),

        E("delivery-stops", "chf_delivery_stops", "ChfDeliveryStop", "chf-delivery-stops",
          "delivery_stop", "Points de livraison", "Delivery stops",
          "Escales de livraison d' une tournee.", "Delivery points of a route.",
          "L' ordre structure le sequence de tournee.", "The order drives route sequencing.",
          "MapPin", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tournee", "str", "Tournee", "Route"),
           F("adresse", "str", "Adresse", "Address"),
           F("ordre", "int", "Ordre", "Order"),
           F("arrivee", "datetime", "Arrivee", "Arrival"),
           F("departure", "datetime", "Depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_FAIRE", "VISITE", "ABSENCE", "REFUS"])]),

        E("mileage-logs", "chf_mileage_logs", "ChfMileageLog", "chf-mileage-logs",
          "mileage_log", "Releves de kilometrage", "Mileage logs",
          "Releve compteur kilometrique par le chauffeur.", "Odometer reading by the driver.",
          "La difference entre deux releves donne la distance.", "Delta between two reads gives distance.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("date", "datetime", "Date", "Date"),
           F("km_debut", "int", "Km debut", "Start odometer"),
           F("km_fin", "int", "Km fin", "End odometer"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ENREGISTRE", "VERIFIE", "ANOMALE"])]),

        E("load-securing-checks", "chf_load_securing", "ChfLoadSecuringCheck", "chf-load-securing-checks",
          "load_securing_check", "Controles d' arrimage", "Load securing checks",
          "Verification de la fixation et repartition de charge.",
          "Check of cargo fixation and weight distribution.",
          "Sangles et equilibre conditionnent l' autorisation de depart.",
          "Straps and balance gate the go-ahead.",
          "Anchor", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("unite", "str", "Unite", "Unit"),
           F("sangles_ok", "bool", "Sangles OK", "Straps OK"),
           F("poids_equilibre", "str", "Poids / equilibre", "Weight / balance"),
           F("controle_datetime", "datetime", "Controle", "Checked at"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "A_CORRIGER", "BLOQUE"])]),

        E("border-crossings", "chf_border_crossings", "ChfBorderCrossing", "chf-border-crossings",
          "border_crossing", "Postes frontiere", "Border crossings",
          "Traversees de frontiere avec controle documentaire.",
          "Border transits with document control.",
          "Documents OK conditionne le passage.", "Documents OK gates the crossing.",
          "Flag", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("poste", "str", "Poste", "Post"),
           F("pays", "str", "Pays", "Country"),
           F("entree_sortie", "str", "Entree / sortie", "Entry / exit"),
           F("horodatage", "datetime", "Horodatage", "Timestamp"),
           F("documents_ok", "bool", "Documents OK", "Documents OK"),
           F("statut", "str", "Statut", "Status")],
          [EN("entree_sortie", ["ENTREE", "SORTIE", "TRANSIT"]),
           EN("statut", ["FRANCHI", "BLOQUE", "EN_ATTENTE"])]),

        E("delivery-appointments", "chf_delivery_appointments", "ChfDeliveryAppointment", "chf-delivery-appointments",
          "delivery_appointment", "RDV de livraison", "Delivery appointments",
          "Creneau convenu avec le destinataire.", "Slot agreed with the consignee.",
          "Le respect du creneau evite les retours.", "Keeping the slot avoids returns.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("creneau", "datetime", "Creneau", "Slot"),
           F("site", "str", "Site", "Site"),
           F("contact", "str", "Contact", "Contact"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFIRME", "EN_ATTENTE", "MANQUE", "REPROGRAMME"])]),

        E("ppe-issues", "chf_ppe_issues", "ChfPpeIssue", "chf-ppe-issues",
          "ppe_issue", "Remise d' EPI", "PPE issues",
          "Dotation d' equipements de protection individuelle.",
          "Provision of personal protective equipment.",
          "L' etat et la date attestent la mise a disposition.",
          "Condition and date evidence the provision.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("equipement", "str", "Equipement", "Equipment"),
           F("taille", "str", "Taille", "Size"),
           F("date_remise", "date", "Date remise", "Issue date"),
           F("etat", "str", "Etat", "Condition"),
           F("statut", "str", "Statut", "Status")],
          [EN("etat", ["NEUF", "BON", "USE", "HORS_SERVICE"]),
           EN("statut", ["REMIS", "A_RENOUVELER", "REFORME"])]),

        E("shift-handovers", "chf_shift_handovers", "ChfShiftHandover", "chf-shift-handovers",
          "shift_handover", "Relais de conduite", "Shift handovers",
          "Passation entre deux chauffeurs sur la meme unite.",
          "Handover between two drivers on the same unit.",
          "Les consignes passees engagent le reprenant.", "Passed instructions bind the reliever.",
          "ArrowLeftRight", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("sortant", "str", "Chauffeur sortant", "Outgoing driver"),
           F("entrant", "str", "Chauffeur entrant", "Incoming driver"),
           F("datetime", "datetime", "Date relais", "Handover date"),
           F("consignes", "text", "Consignes", "Instructions"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["FAITE", "PARTIELLE", "CONTESTEE"])]),

        E("breakdown-reports", "chf_breakdown_reports", "ChfBreakdownReport", "chf-breakdown-reports",
          "breakdown_report", "Signalements de panne", "Breakdown reports",
          "Declaration d' une panne vehicule par le chauffeur.",
          "Driver's report of a vehicle breakdown.",
          "L' immobilisation declenche le remorquage / reassignation.",
          "Immobilization triggers towing / reassignment.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("panne", "str", "Panne", "Breakdown"),
           F("lieu", "str", "Lieu", "Place"),
           F("date_signalement", "datetime", "Signalement", "Report date"),
           F("immobilise", "bool", "Immobilise", "Immobilized"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SIGNAL", "PRISE_EN_CHARGE", "REPOUSSE", "IMMOBILISE"])]),

        E("tyre-checks", "chf_tyre_checks", "ChfTyreCheck", "chf-tyre-checks",
          "tyre_check", "Controles pneumatiques", "Tyre checks",
          "Releve de pression et usure par essieu.", "Pressure and wear reading per axle.",
          "Pression et usure hors tolérance = a intervenir.",
          "Out-of-tolerance pressure/wear requires action.",
          "Disc", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("numero_essieu", "int", "Numero d' essieu", "Axle number"),
           F("pression_bar", "num", "Pression (bar)", "Pressure (bar)"),
           F("usure_mm", "num", "Usure (mm)", "Tread (mm)"),
           F("date_controle", "datetime", "Controle", "Checked at"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "A_SURVEILLER", "A_REMPLACER"])]),

        E("cargo-photos", "chf_cargo_photos", "ChfCargoPhoto", "chf-cargo-photos",
          "cargo_photo", "Photos de cargaison", "Cargo photos",
          "Photo etat de la marchandise (chargement / livraison).",
          "Condition photo of the goods (loading / delivery).",
          "La photo atteste de l' etat au moment de la prise.",
          "The photo evidences condition at capture time.",
          "Camera", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("mission", "str", "Mission", "Mission"),
           F("prise", "datetime", "Prise", "Captured at"),
           F("legende", "str", "Legende", "Caption"),
           F("fichier", "str", "Fichier", "File"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CHARGEMENT", "LIVRAISON", "LITIGE", "ARCHEVEE"])]),
    ],
)

# ─── portail-magasinier (+19 -> 20) : taches realisées au depot ──────────────
MODULES["magasinier_c"] = dict(
    module_key="magasinier_c", module_slug="portail-magasinier",
    module_path="portail-magasinier", perm_module="magasin",
    registre_filename="registres_c",
    revision="088", down_revision="087_chauffeur_c_deep",
    entities=[
        E("picking-tasks", "magc_picking_tasks", "MagcPickingTask", "magc-picking-tasks",
          "picking_task", "Taches de preparation", "Picking tasks",
          "Ordre de prelevement par emplacement.", "Pick order per location.",
          "La quantite prelevee doit egaler la quantite demandee.",
          "Picked quantity must equal requested.",
          "ListChecks", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre", "str", "Ordre", "Order"),
           F("emplacement", "str", "Emplacement", "Location"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("prepareur", "str", "Preparateur", "Picker"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_FAIRE", "EN_COURS", "FAIT", "RUPTURE"])]),

        E("packing-slips", "magc_packing_slips", "MagcPackingSlip", "magc-packing-slips",
          "packing_slip", "Bons de colisage", "Packing slips",
          "Consigne du contenu des colis d' une commande.",
          "Record of the parcel contents of an order.",
          "Nb colis et poids engagent l' expedition.", "Parcel count and weight commit the shipment.",
          "Box", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commande", "str", "Commande", "Order"),
           F("nb_colis", "int", "Nombre de colis", "Parcel count"),
           F("poids", "num", "Poids", "Weight"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_PREPARATION", "EMBALLE", "MANQUANT", "EXPEDIE"])]),

        E("put-away-tasks", "magc_putaway_tasks", "MagcPutawayTask", "magc-put-away-tasks",
          "putaway_task", "Taches de mise en place", "Put-away tasks",
          "Rangement de la marchandise recue vers son emplacement.",
          "Moving received goods to their location.",
          "De (reception) vers (emplacement) trace le mouvement.", "From (receiving) to (location) traces the move.",
          "Archive", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("article", "str", "Article", "Item"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("de", "str", "Depuis", "From"),
           F("vers", "str", "Vers", "To"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_FAIRE", "EN_COURS", "FAIT", "BLOQUE"])]),

        E("cycle-counts", "magc_cycle_counts", "MagcCycleCount", "magc-cycle-counts",
          "cycle_count", "Inventaires tournants", "Cycle counts",
          "Comptage ponctuel par emplacement.", "Spot count per location.",
          "L' ecart physique - theorique est mesure.", "Physical minus theoretical variance is measured.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("emplacement", "str", "Emplacement", "Location"),
           F("theorique", "int", "Quantite theorique", "Theoretical qty"),
           F("physique", "int", "Quantite physique", "Physical qty"),
           F("compteur", "str", "Compteur", "Counter"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "FAIT", "ECART", "REGULARISE"])]),

        E("internal-moves", "magc_internal_moves", "MagcInternalMove", "magc-internal-moves",
          "internal_move", "Transferts internes", "Internal moves",
          "Deplacement d' une quantite entre deux emplacements.",
          "Movement of a quantity between two locations.",
          "Origine et destination attestent le chemin.", "Origin and destination evidence the path.",
          "MoveRight", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("article", "str", "Article", "Item"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("origine", "str", "Origine", "Origin"),
           F("destination", "str", "Destination", "Destination"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "EN_COURS", "FAIT", "ANNULE"])]),

        E("goods-issues", "magc_goods_issues", "MagcGoodsIssue", "magc-goods-issues",
          "goods_issue", "Sorties de magasin", "Goods issues",
          "Sortie de matiere sur demande interne.", "Material issue on internal demand.",
          "Le beneficiaire justifie la sortie.", "The requester justifies the issue.",
          "Send", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("demande", "str", "Demande", "Request"),
           F("article", "str", "Article", "Item"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("beneficiaire", "str", "Beneficiaire", "Requester"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "SERVI", "PARTIEL", "RUPTURE"])]),

        E("returns-processing", "magc_returns", "MagcReturnProcessing", "magc-returns-processing",
          "return_processing", "Traitement des retours", "Returns processing",
          "Reception et tri des retours clients/fournisseurs.",
          "Receipt and sorting of client/supplier returns.",
          "Le motif conditionne la destination (repro, destruction).",
          "The reason routes it (reput away, scrap).",
          "Undo2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("retour", "str", "Type de retour", "Return type"),
           F("article", "str", "Article", "Item"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("motif", "str", "Motif", "Reason"),
           F("statut", "str", "Statut", "Status")],
          [EN("retour", ["CLIENT", "FOURNISSEUR", "INTERNE"]),
           EN("statut", ["RECU", "CONTROLE", "REINTEGRE", "REFORME"])]),

        E("label-printing", "magc_label_prints", "MagcLabelPrint", "magc-label-printing",
          "label_print", "Edition d' etiquettes", "Label printing",
          "Impression d' etiquettes articles/palettes.", "Printing of item/pallet labels.",
          "Le type d' etiquette conditionne le contenu imprime.", "Label type drives printed content.",
          "Tags", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("article", "str", "Article", "Item"),
           F("nombre", "int", "Nombre", "Count"),
           F("type_etiquette", "str", "Type d' etiquette", "Label type"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_etiquette", ["ARTICLE", "PALETTE", "COLIS", "DANGER"]),
           EN("statut", ["EN_ATTENTE", "IMPRIME", "ERREUR"])]),

        E("pallet-building", "magc_pallet_builds", "MagcPalletBuild", "magc-pallet-building",
          "pallet_build", "Constitution de palettes", "Pallet building",
          "Gerlement des cartons sur palette.", "Casting cartons onto a pallet.",
          "Hauteur et poids total conditionnent la manutention.", "Height and total weight gate handling.",
          "Layers", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commande", "str", "Commande", "Order"),
           F("nb_cartons", "int", "Nombre de cartons", "Carton count"),
           F("hauteur_cm", "int", "Hauteur (cm)", "Height (cm)"),
           F("poids_total", "num", "Poids total", "Total weight"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "COMPACTE", "FILMEE", "BLOQUE"])]),

        E("equipment-checks", "magc_equipment_checks", "MagcEquipmentCheck", "magc-equipment-checks",
          "equipment_check", "Controles engins", "Equipment checks",
          "Verification quotidienne du materiel de manutention.",
          "Daily check of handling equipment.",
          "Une anomalie immobilise l' engin.", "A defect locks out the equipment.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("equipment", "str", "Engin", "Equipment"),
           F("numero", "str", "Numero", "Number"),
           F("controleur", "str", "Controleur", "Checker"),
           F("date_controle", "datetime", "Controle", "Checked at"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "ANOMALIE", "IMMOBILISE"])]),

        E("safety-inspections", "magc_safety_inspections", "MagcSafetyInspection", "magc-safety-inspections",
          "safety_inspection", "Rondes de securite", "Safety inspections",
          "Inspection periodique des zones du depot.", "Periodic inspection of warehouse zones.",
          "Le nombre d' anomalies qualifie la ronde.", "Anomaly count qualifies the round.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("zone", "str", "Zone", "Zone"),
           F("inspecteur", "str", "Inspecteur", "Inspector"),
           F("date", "datetime", "Date", "Date"),
           F("anomalies", "int", "Anomalies", "Anomalies"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["FAITE", "SANS_ANOMALIE", "A_SUIVRE"])]),

        E("spill-cleanups", "magc_spill_cleanups", "MagcSpillCleanup", "magc-spill-cleanups",
          "spill_cleanup", "Nettoyages de deversement", "Spill cleanups",
          "Traitement d' un deversement de produit.", "Handling of a product spill.",
          "Le produit et le volume dimensionnent l' intervention.", "Product and volume size the response.",
          "Droplets", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("zone", "str", "Zone", "Zone"),
           F("produit", "str", "Produit", "Product"),
           F("volume", "num", "Volume", "Volume"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DETECTE", "CONTENU", "NETTOYE", "CLOTURE"])]),

        E("loading-checks", "magc_loading_checks", "MagcLoadingCheck", "magc-loading-checks",
          "loading_check", "Controles de chargement", "Loading checks",
          "Verification de la charge d' un camion avant depart.",
          "Check of a truck load before departure.",
          "Le nombre de colis charges doit egaler le bordereau.", "Loaded parcels must match the manifest.",
          "Truck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chargement", "str", "Chargement", "Load"),
           F("camion", "str", "Camion", "Truck"),
           F("nb_colis", "int", "Nombre de colis", "Parcel count"),
           F("chargeur", "str", "Chargeur", "Loader"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "COMPLET", "ECART", "PARTI"])]),

        E("receiving-checks", "magc_receiving_checks", "MagcReceivingCheck", "magc-receiving-checks",
          "receiving_check", "Controles de reception", "Receiving checks",
          "Verification de la marchandise entrante.", "Check of inbound goods.",
          "La conformite declenche la mise en stock.", "Conformity triggers put-away.",
          "Package", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("reception", "str", "Reception", "Receipt"),
           F("fournisseur", "str", "Fournisseur", "Supplier"),
           F("nb_colis", "int", "Nombre de colis", "Parcel count"),
           F("conforme", "bool", "Conforme", "Conforming"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "CONFORME", "LITIGE", "REJETE"])]),

        E("putaway-exceptions", "magc_putaway_exceptions", "MagcPutawayException", "magc-putaway-exceptions",
          "putaway_exception", "Exceptions de rangement", "Put-away exceptions",
          "Blocage constate lors d' une mise en place.", "Blockage found during put-away.",
          "Le type de probleme aiguille la resolution.", "Problem type drives resolution.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("article", "str", "Article", "Item"),
           F("emplacement", "str", "Emplacement", "Location"),
           F("type_probleme", "str", "Type de probleme", "Problem type"),
           F("signale_le", "datetime", "Signale", "Flagged at"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_probleme", ["EMPLACEMENT_PLEIN", "ACCES", "ETIQUETTE", "DAMAGE"]),
           EN("statut", ["OUVERTE", "EN_COURS", "RESOLUE"])]),

        E("order-staging", "magc_order_staging", "MagcOrderStaging", "magc-order-staging",
          "order_staging", "Zone de pre-expedition", "Order staging",
          "Préparation en zone de tri avant enlevement.", "Prep in a staging area before collection.",
          "Le nombre de lignes suivies caracterise la prepa.", "Tracked line count characterizes staging.",
          "Boxes", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commande", "str", "Commande", "Order"),
           F("zone_prea", "str", "Zone de preparation", "Staging zone"),
           F("nb_lignes", "int", "Nombre de lignes", "Line count"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "PRET", "EN_ATTENTE_ENLEVEMENT", "ENLEVE"])]),

        E("cold-chain-checks", "magc_cold_checks", "MagcColdChainCheck", "magc-cold-chain-checks",
          "cold_chain_check", "Controles chaine du froid", "Cold-chain checks",
          "Releve de temperature des chambres froides.", "Temperature reading of cold rooms.",
          "Hors plage = rupture de chaine a declarer.", "Out of range = chain break to declare.",
          "Snowflake", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chambre_froide", "str", "Chambre froide", "Cold room"),
           F("temperature_c", "num", "Temperature (C)", "Temperature (C)"),
           F("seuil_mini", "num", "Seuil mini", "Min threshold"),
           F("seuil_maxi", "num", "Seuil maxi", "Max threshold"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "DERIVE", "RUPTURE"])]),

        E("hazmat-handling", "magc_hazmat_handling", "MagcHazmatHandling", "magc-hazmat-handling",
          "hazmat_handling", "Manutention matieres dangereuses", "Hazmat handling",
          "Prise en charge de matieres dangereuses.", "Handling of dangerous goods.",
          "La classe ADR conditionne les precautions.", "The ADR class drives precautions.",
          "Biohazard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("matiere", "str", "Matiere", "Material"),
           F("classe", "str", "Classe", "Class"),
           F("quantite", "num", "Quantite", "Quantity"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("classe", ["1", "2", "3", "5", "6", "8", "9"]),
           EN("statut", ["PREVU", "EN_COURS", "STOCKE", "EVACUE"])]),

        E("dock-assignments", "magc_dock_assignments", "MagcDockAssignment", "magc-dock-assignments",
          "dock_assignment", "Affectations de quai", "Dock assignments",
          "Attribution d' un quai et creneau pour une operation.",
          "Assignment of a dock and slot for an operation.",
          "Le respect du creneau evite l' engorgement des quais.", "Keeping the slot avoids dock congestion.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("quai", "str", "Quai", "Dock"),
           F("camion", "str", "Camion", "Truck"),
           F("creneau", "datetime", "Creneau", "Slot"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "OCCUPE", "LIBERE", "NO_SHOW"])]),
    ],
)
