"""Manifest Vague D — batch EXTRA.

Ramene a 20 les 4 modules de transport generees en session precedente mais
laissees sous le seuil (pipeline-oleoduc 11, courier-express 13, chaine-froid 11,
convoi-exceptionnel 11). On ajoute des enregistrements REELS propres a chaque
mode (relevants terrain, evenements, controles), distincts des tables maitresses
deja presentes dans {pipeline,courier,coldchain,heavylift}_deep.py (nouveau
prefixe de table 2_). perm_module = le wildcard que CHEF_PARC detient deja
(« pipeline.*.* », « courier.*.* », « coldchain.*.* », « heavylift.*.* »).

Chaine Alembic 099-102 depuis 098_collaborateur_d_deep.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── pipeline-oleoduc (+9 -> 20) ─────────────────────────────────────────────
MODULES["pipeline_e"] = dict(
    module_key="pipeline_e", module_slug="pipeline-oleoduc",
    module_path="pipeline-oleoduc", perm_module="pipeline",
    registre_filename="registres_e",
    revision="099", down_revision="098_collaborateur_d_deep",
    entities=[
        E("custody-transfers", "pipe2_custody_transfers", "Pipe2CustodyTransfer", "pipe2-custody-transfers",
          "custody_transfer", "Transferts de custody", "Custody transfers",
          "Transfert de propriete du produit a une interface du pipeline.",
          "Product ownership transfer at a pipeline interface.",
          "Les volumes delivers vs recus mesurent l' ecart de custody.",
          "Delivered vs received volumes measure the custody variance.",
          "ArrowLeftRight", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("interface", "str", "Interface", "Interface"),
           F("produit", "str", "Produit", "Product"),
           F("volume_livre", "num", "Volume livre", "Delivered volume"),
           F("volume_recu", "num", "Volume recu", "Received volume"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERT", "RECONCILE", "ECART", "VALIDE"])]),

        E("pressure-logs", "pipe2_pressure_logs", "Pipe2PressureLog", "pipe2-pressure-logs",
          "pressure_log", "Releves de pression", "Pressure logs",
          "Releve de pression ligne a une station.",
          "Line pressure reading at a station.",
          "La pression doit rester entre les seuils mini et maxi.",
          "Pressure must stay between min and max thresholds.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("station", "str", "Station", "Station"),
           F("pression_bar", "num", "Pression (bar)", "Pressure (bar)"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NOMINAL", "BAS", "HAUT", "ALERTE"])]),

        E("pump-station-reads", "pipe2_pump_reads", "Pipe2PumpStationRead", "pipe2-pump-station-reads",
          "pump_station_read", "Releves de station de pompage", "Pump station reads",
          "Releve de fonctionnement d' une station de pompage.",
          "Operating reading of a pump station.",
          "Le debit et la vibration qualifient la pompe.",
          "Flow and vibration qualify the pump.",
          "Activity", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("station", "str", "Station", "Station"),
           F("debit", "num", "Debit", "Flow rate"),
           F("vibration", "num", "Vibration", "Vibration"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_MARCHE", "ARRET", "DEGRADE", "MAINTENANCE"])]),

        E("corrosion-readings", "pipe2_corrosion", "Pipe2CorrosionReading", "pipe2-corrosion-readings",
          "corrosion_reading", "Releves de corrosion", "Corrosion readings",
          "Mesure d' epaisseur / corrosion sur la canalisation.",
          "Wall-thickness / corrosion measurement on the pipeline.",
          "L' epaisseur sous le seuil minimise declenche la reparation.",
          "Thickness under minimum triggers repair.",
          "Ruler", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("troncon", "str", "Troncon", "Segment"),
           F("epaisseur_mm", "num", "Epaisseur (mm)", "Thickness (mm)"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NOMINAL", "SURVEILLE", "CRITIQUE", "REPAR"])]),

        E("flow-calibrations", "pipe2_flow_calibrations", "Pipe2FlowCalibration", "pipe2-flow-calibrations",
          "flow_calibration", "Etalonnages de debitmetre", "Flow calibrations",
          "Etalonnage d' un debitmetre de transferation.",
          "Calibration of a custodian transfer meter.",
          "Le coefficient d' etalonnage corrige le volume facture.",
          "The calibration factor corrects the billed volume.",
          "Target", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("debitmetre", "str", "Debitmetre", "Flow meter"),
           F("coefficient", "num", "Coefficient", "Factor"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "AJUSTE", "HORS_TOLERANCE", "A_REFAIRE"])]),

        E("batch-quality-tests", "pipe2_batch_quality", "Pipe2BatchQualityTest", "pipe2-batch-quality-tests",
          "batch_quality_test", "Essais qualite de lot", "Batch quality tests",
          "Analyse qualite d' un lot de produit circulant.",
          "Quality analysis of a product batch in transit.",
          "La conformite aux specs libere le lot a la delivery.",
          "Conformity to specs releases the batch at delivery.",
          "FlaskConical", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("lot", "str", "Lot", "Batch"),
           F("produit", "str", "Produit", "Product"),
           F("parametre", "str", "Parametre", "Parameter"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "CONFORME", "HORS_SPEC", "REJETE"])]),

        E("interface-detections", "pipe2_interface_detections", "Pipe2InterfaceDetection", "pipe2-interface-detections",
          "interface_detection", "Detections d' interface", "Interface detections",
          "Detection de la jointure entre deux produits successifs.",
          "Detection of the join between two successive products.",
          "La perte d' interface alimente le bilan matiere.",
          "Interface loss feeds the mass balance.",
          "Crosshair", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("troncon", "str", "Troncon", "Segment"),
           F("volume_interface", "num", "Volume interface", "Interface volume"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DETECTEE", "SEPARER", "RECYCLE", "PERTE"])]),

        E("integrity-assessments", "pipe2_integrity", "Pipe2IntegrityAssessment", "pipe2-integrity-assessments",
          "integrity_assessment", "Evaluations d' integrite", "Integrity assessments",
          "Evaluation globale de l' integrite mecanique d' un troncon.",
          "Overall mechanical integrity assessment of a segment.",
          "Le niveau de risque conditionne la contrainte de pression.",
          "The risk level conditions the pressure constraint.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("troncon", "str", "Troncon", "Segment"),
           F("niveau_risque", "str", "Niveau de risque", "Risk level"),
           F("pression_max", "num", "Pression max", "Max pressure"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("niveau_risque", ["FAIBLE", "MODERE", "ELEVE", "CRITIQUE"]),
           EN("statut", ["EVALUE", "SURVEILLE", "RESTREINT", "COTEE"])]),

        E("spill-response-actions", "pipe2_spill_actions", "Pipe2SpillResponseAction", "pipe2-spill-response-actions",
          "spill_response_action", "Actions de reponse a deversement", "Spill response actions",
          "Action declenchee suite a un deversement detecte.",
          "Action triggered after a detected spill.",
          "Le volume recupere et la cloture attestent la maitrise.",
          "Recovered volume and closure evidence containment.",
          "Droplets", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("lieu", "str", "Lieu", "Location"),
           F("volume_rejete", "num", "Volume rejete", "Released volume"),
           F("volume_recupere", "num", "Volume recupere", "Recovered volume"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DETECTE", "CONTENU", "DECONTAMINE", "CLOTURE", "DECLARE_AUTORITE"])]),
    ],
)

# ─── courier-express (+7 -> 20) ──────────────────────────────────────────────
MODULES["courier_e"] = dict(
    module_key="courier_e", module_slug="courier-express",
    module_path="courier-express", perm_module="courier",
    registre_filename="registres_e",
    revision="100", down_revision="099_pipeline_e_deep",
    entities=[
        E("route-scans", "cour2_route_scans", "Cour2RouteScan", "cour2-route-scans",
          "route_scan", "Scans de tournee", "Route scans",
          "Scan d' un colis realise aux etapes de la tournee.",
          "Parcel scan performed along the route steps.",
          "L' horodatage de scan trace la chaine de possession.",
          "The scan timestamp traces the chain of custody.",
          "ScanLine", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("etape", "str", "Etape", "Step"),
           F("lieu", "str", "Lieu", "Location"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("etape", ["ENLEVEMENT", "HUB", "TOURNEE", "LIVRAISON"]),
           EN("statut", ["SCANE", "MANQUANT", "TARDIF"])]),

        E("last-mile-handoffs", "cour2_last_mile", "Cour2LastMileHandoff", "cour2-last-mile-handoffs",
          "last_mile_handoff", "Remises dernier kilometre", "Last-mile handoffs",
          "Passation d' un colis au livreur dernier kilometre.",
          "Handover of a parcel to the last-mile courier.",
          "La remise au livreur engage sa responsabilite.",
          "The handover to the courier commits his responsibility.",
          "Package", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("livreur", "str", "Livreur", "Courier"),
           F("agencer", "str", "Agence", "Hub"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["REMIS", "EN_ROUTE", "RETOUR_AGENCE", "PERDU"])]),

        E("delivery-attempts", "cour2_delivery_attempts", "Cour2DeliveryAttempt", "cour2-delivery-attempts",
          "delivery_attempt", "Tentatives de livraison", "Delivery attempts",
          "Chaque passage du livreur au point de livraison.",
          "Each courier stop at the delivery point.",
          "Le motif d' echec justifie la nouvelle presentation.",
          "The failure reason justifies re-presentation.",
          "MapPin", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("livreur", "str", "Livreur", "Courier"),
           F("date", "datetime", "Date", "Date"),
           F("motif", "str", "Motif", "Outcome"),
           F("statut", "str", "Statut", "Status")],
          [EN("motif", ["LIVRE", "ABSENT", "REFUSE", "ADRESSE_INVALIDE", "VOLE"])]),

        E("exception-parcels", "cour2_exceptions", "Cour2ExceptionParcel", "cour2-exception-parcels",
          "exception_parcel", "Colis en exception", "Exception parcels",
          "Colis bloque par une anomalie de traitement.",
          "Parcel blocked by a handling anomaly.",
          "La classification de l' exception pilote la resolution.",
          "Exception classification drives resolution.",
          "FileWarning", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("type_exception", "str", "Type", "Exception type"),
           F("detecte_le", "datetime", "Detecte le", "Detected at"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_exception", ["DAMAGE", "ADRESSE", "DOUANE", "LOST", "REFUS"]),
           EN("statut", ["OUVERTE", "EN_COURS", "RESOLUE", "IRRECOVERABLE"])]),

        E("returns-to-sender", "cour2_returns", "Cour2ReturnToSender", "cour2-returns-to-sender",
          "return_to_sender", "Retours expediteur", "Returns to sender",
          "Reexpedition d' un colis non livre a son expediteur.",
          "Re-dispatch of an undelivered parcel to its sender.",
          "Le motif et le trajet de retour encadrent le litige.",
          "The reason and return route bound the dispute.",
          "Send", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("motif", "str", "Motif", "Reason"),
           F("date_depart", "datetime", "Depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_RETOUR", "LIVRE_EXPEDITEUR", "DECLINE"])]),

        E("courier-shift-logs", "cour2_shift_logs", "Cour2CourierShiftLog", "cour2-courier-shift-logs",
          "courier_shift_log", "Journal de vacation livreur", "Courier shift logs",
          "Suivi de vacation et de tournee d' un livreur.",
          "Tracking of a courier's shift and route.",
          "Le nombre de colis livres mesure la productivite.",
          "Parcels delivered measures productivity.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("livreur", "str", "Livreur", "Courier"),
           F("date", "date", "Date", "Date"),
           F("colis_livres", "int", "Colis livres", "Delivered"),
           F("km", "int", "Kilometres", "Kilometers"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERTE", "EN_COURS", "CLOTUREE", "ANOMALIE"])]),

        E("sla-breach-logs", "cour2_sla_breaches", "Cour2SlaBreachLog", "cour2-sla-breach-logs",
          "sla_breach_log", "Journaux de rupture SLA", "SLA breach logs",
          "Constat de depassement de l' engagement de delai.",
          "Record of a missed delivery-time commitment.",
          "Le retard et la compensation associee engagent le client.",
          "The delay and compensation commit the account.",
          "Timer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("colis", "str", "Colis", "Parcel"),
           F("retard_min", "int", "Retard (min)", "Delay (min)"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONSTEEE", "COMPENSE", "EXONERE", "CONTESTEE"])]),
    ],
)

# ─── chaine-froid (+9 -> 20) ─────────────────────────────────────────────────
MODULES["coldchain_e"] = dict(
    module_key="coldchain_e", module_slug="chaine-froid",
    module_path="chaine-froid", perm_module="coldchain",
    registre_filename="registres_e",
    revision="101", down_revision="100_courier_e_deep",
    entities=[
        E("temperature-logs", "cold2_temperature_logs", "Cold2TemperatureLog", "cold2-temperature-logs",
          "temperature_log", "Releves de temperature", "Temperature logs",
          "Releve de temperature d' une unite frigorifique.",
          "Temperature reading of a refrigeration unit.",
          "La temperature doit rester dans la plage cible.",
          "Temperature must stay in the target band.",
          "Thermometer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("unite", "str", "Unite", "Unit"),
           F("temperature", "num", "Temperature", "Temperature"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "HAUTE", "BASSE", "ALERTE"])]),

        E("cold-excursion-events", "cold2_excursions", "Cold2ColdExcursion", "cold2-cold-excursion-events",
          "cold_excursion_event", "Excursions de temperature", "Cold excursion events",
          "Sortie hors plage de temperature d' une cargaison.",
          "Out-of-band temperature of a consignment.",
          "La duree hors plage determine la perte de produit.",
          "The out-of-band duration determines product loss.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("cargaison", "str", "Cargaison", "Consignment"),
           F("temperature_max", "num", "Temperature max", "Max temperature"),
           F("duree_min", "int", "Duree (min)", "Duration (min)"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DETECTEE", "EVALUEE", "PRODUIT_OK", "PRODUIT_PERDU"])]),

        E("probe-calibrations", "cold2_probe_calibrations", "Cold2ProbeCalibration", "cold2-probe-calibrations",
          "probe_calibration", "Etalonnages de sonde", "Probe calibrations",
          "Etalonnage d' une sonde de temperature.",
          "Calibration of a temperature probe.",
          "L' ecart a l' etalon valide ou non la mesure.",
          "The deviation from the reference validates the reading.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("sonde", "str", "Sonde", "Probe"),
           F("ecart", "num", "Ecart", "Deviation"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "AJUSTEE", "HORS_TOLERANCE", "REMPLACER"])]),

        E("blast-freeze-cycles", "cold2_blast_cycles", "Cold2BlastFreezeCycle", "cold2-blast-freeze-cycles",
          "blast_freeze_cycle", "Cycles de surgelation", "Blast freeze cycles",
          "Cycle de surgelation rapide d' un produit.",
          "Rapid freezing cycle of a product.",
          "Le temps a coeur et la temperature finale qualifient le cycle.",
          "Core time and final temperature qualify the cycle.",
          "Snowflake", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("temp_finale", "num", "Temperature finale", "Final temperature"),
           F("duree_min", "int", "Duree (min)", "Duration (min)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "REUSSI", "INCOMPLET", "REPETE"])]),

        E("door-open-events", "cold2_door_events", "Cold2DoorOpenEvent", "cold2-door-open-events",
          "door_open_event", "Evenements d' ouverture de porte", "Door open events",
          "Ouverture de porte d' une chambre froide.",
          "Opening of a cold-room door.",
          "La duree d' ouverture laisse entrer l' air chaud.",
          "The open duration lets warm air in.",
          "DoorOpen", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chambre", "str", "Chambre", "Chamber"),
           F("duree_sec", "int", "Duree (s)", "Duration (s)"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NOMINAL", "LONG", "FORCE", "DEFECTUEUX"])]),

        E("humidity-logs", "cold2_humidity_logs", "Cold2HumidityLog", "cold2-humidity-logs",
          "humidity_log", "Releves d' hygrometrie", "Humidity logs",
          "Releve d' humidite relative d' une chambre.",
          "Relative humidity reading of a chamber.",
          "L' humidite hors plage altere le produit.",
          "Out-of-band humidity affects the product.",
          "Droplet", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("chambre", "str", "Chambre", "Chamber"),
           F("humidite_pct", "num", "Humidite (%)", "Humidity (%)"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "SEC", "HUMIDE", "ALERTE"])]),

        E("refrigerant-charges", "cold2_refrigerant", "Cold2RefrigerantCharge", "cold2-refrigerant-charges",
          "refrigerant_charge", "Recharges de fluide frigorigene", "Refrigerant charges",
          "Recharge / controle du fluide frigorigene d' un circuit.",
          "Recharge / check of a circuit's refrigerant.",
          "La quantite et le type de fluide conditionnent l' efficacité.",
          "Quantity and fluid type condition efficiency.",
          "Fan", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("circuit", "str", "Circuit", "Circuit"),
           F("fluide", "str", "Fluide", "Fluid"),
           F("quantite_kg", "num", "Quantite (kg)", "Quantity (kg)"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLEIN", "BAS", "FUITE", "RECHARGE"])]),

        E("cold-shipment-approvals", "cold2_ship_approvals", "Cold2ShipmentApproval", "cold2-cold-shipment-approvals",
          "cold_shipment_approval", "Validations d' expedition froide", "Cold shipment approvals",
          "Validation de pre-expedition d' une cargaison froide.",
          "Pre-departure validation of a cold consignment.",
          "La temperature au chargement engage la conformite du transport.",
          "Loading temperature commits the transport conformity.",
          "CheckCircle2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("cargaison", "str", "Cargaison", "Consignment"),
           F("temp_chargement", "num", "Temperature chargement", "Loading temp"),
           F("valideur", "str", "Validateur", "Approver"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_ATTENTE", "APPROUVE", "REFUSE", "REPORTE"])]),

        E("ice-battery-charges", "cold2_ice_batteries", "Cold2IceBatteryCharge", "cold2-ice-battery-charges",
          "ice_battery_charge", "Recharges de batteries de glace", "Ice battery charges",
          "Congelation d' une batterie de glace pour caisson isotherme.",
          "Freezing of an ice battery for an isothermal box.",
          "Le niveau de gel conditionne l' autonomie du caisson.",
          "Freeze level conditions the box autonomy.",
          "BatteryCharging", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("caisson", "str", "Caisson", "Box"),
           F("niveau_gel", "str", "Niveau de gel", "Freeze level"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("niveau_gel", ["TOTAL", "PARTIEL", "IMPACT"]),
           EN("statut", ["EN_GEL", "PRET", "UTILISE", "A_REGELER"])]),
    ],
)

# ─── convoi-exceptionnel (+9 -> 20) ──────────────────────────────────────────
MODULES["heavylift_e"] = dict(
    module_key="heavylift_e", module_slug="convoi-exceptionnel",
    module_path="convoi-exceptionnel", perm_module="heavylift",
    registre_filename="registres_e",
    revision="102", down_revision="101_coldchain_e_deep",
    entities=[
        E("lifting-procedures", "heavy2_lift_plans", "Heavy2LiftPlan", "heavy2-lift-plans",
          "lift_plan", "Plans de levage", "Lift plans",
          "Plan technique de levage d' une charge lourde.",
          "Technical plan for lifting a heavy load.",
          "La capacite de la grue doit couvrir le poids + acces.",
          "Crane capacity must cover weight plus radius.",
          "MoveVertical", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("charge", "str", "Charge", "Load"),
           F("poids_tonnes", "num", "Poids (t)", "Weight (t)"),
           F("portee_m", "num", "Portee (m)", "Radius (m)"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ETUDIE", "VALIDE", "EN_COURS", "CLOTURE"])]),

        E("route-feasibility", "heavy2_route_surveys", "Heavy2RouteSurvey", "heavy2-route-surveys",
          "route_survey", "Reconnaissances d' itineraire", "Route surveys",
          "Etude de faisabilite routiere d' un convoi hors gabarit.",
          "Road feasibility study of an oversize convoy.",
          "Le gabarit et les obstacles conditionnent le passage.",
          "Gauge and obstacles condition the passage.",
          "Route", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("itineraire", "str", "Itineraire", "Route"),
           F("largeur_m", "num", "Largeur (m)", "Width (m)"),
           F("hauteur_m", "num", "Hauteur (m)", "Height (m)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIEE", "FAITE", "Faisable", "BLOQUANTE"])]),

        E("escort-schedules", "heavy2_escorts", "Heavy2EscortSchedule", "heavy2-escort-schedules",
          "escort_schedule", "Planning d' escortes", "Escort schedules",
          "Affectation des vehicules d' escorte a un convoi.",
          "Assignment of escort vehicles to a convoy.",
          "Le nb d' escortes depende du gabarit.",
          "Escort count depends on the gauge.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("convoi", "str", "Convoi", "Convoy"),
           F("nb_vehicules", "int", "Nb vehicules", "Vehicles"),
           F("debut", "datetime", "Debut", "Start"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIEE", "AFFECTEE", "EN_COURS", "TERMINEE"])]),

        E("load-moment-calcs", "heavy2_load_moment", "Heavy2LoadMomentCalc", "heavy2-load-moment-calcs",
          "load_moment_calc", "Calculs de moment de charge", "Load moment calcs",
          "Calcul du moment de renversement d' une configuration de levage.",
          "Calculation of the overturning moment of a lift setup.",
          "Le moment applique ne doit pas exceder la capacite.",
          "The applied moment must not exceed capacity.",
          "Scale", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("configuration", "str", "Configuration", "Configuration"),
           F("moment_applique", "num", "Moment applique", "Applied moment"),
           F("capacite", "num", "Capacite", "Capacity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CALCULE", "CONFORME", "LIMITE", "DEPASSE"])]),

        E("crane-setup-records", "heavy2_crane_setup", "Heavy2CraneSetupRecord", "heavy2-crane-setup-records",
          "crane_setup_record", "Montages de grue", "Crane setup records",
          "Enregistrement du montage et calage d' une grue.",
          "Record of a crane's assembly and leveling.",
          "Le calage et le sol porteur valident le montage.",
          "Leveling and ground bearing validate the setup.",
          "Cog", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("grue", "str", "Grue", "Crane"),
           F("portance_sol", "str", "Portance du sol", "Ground bearing"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["MONTEE", "TESTEE", "EXPLOITATION", "DEMONTEE"])]),

        E("permit-obtentions", "heavy2_permits", "Heavy2PermitObtention", "heavy2-permit-obtentions",
          "permit_obtention", "Obtentions d' autorisation", "Permit obtentions",
          "Demande et obtaining du permis de transport exceptionnel.",
          "Application and obtaining of the oversize transport permit.",
          "Le parcours et les autorites traversees encadrent le permis.",
          "Route and crossed authorities bound the permit.",
          "FileBadge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("convoi", "str", "Convoi", "Convoy"),
           F("autorite", "str", "Autorite", "Authority"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "INSTRUIT", "OCTROYE", "REFUSE", "EXPIRE"])]),

        E("lashing-rigs", "heavy2_lashing", "Heavy2LashingRig", "heavy2-lashing-rigs",
          "lashing_rig", "Dispositifs d' arrimage", "Lashing rigs",
          "Configuration d' arrimage d' une charge sur son support.",
          "Rigging configuration of a load on its carrier.",
          "Le nombre de sangles et l' angle valident l' arrimage.",
          "Strap count and angle validate the lashing.",
          "Anchor", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("charge", "str", "Charge", "Load"),
           F("nb_sangles", "int", "Nb sangles", "Straps"),
           F("angle_deg", "int", "Angle (deg)", "Angle (deg)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONCU", "POSE", "CONTROLE", "REFAIRE"])]),

        E("axle-load-readings", "heavy2_axle_loads", "Heavy2AxleLoadReading", "heavy2-axle-load-readings",
          "axle_load_reading", "Releves de charge par essieu", "Axle load readings",
          "Mesure de la charge reposee par essieu du porte-engin.",
          "Measurement of the weight borne per trailer axle.",
          "La charge par essieu ne doit pas depasser la limite legale.",
          "Per-axle load must not exceed the legal limit.",
          "Weight", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("essieu", "int", "Essieu", "Axle"),
           F("charge_t", "num", "Charge (t)", "Load (t)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "LIMITE", "DEPASSEE", "REPARTIR"])]),

        E("convoy-staging-reports", "heavy2_staging", "Heavy2ConvoyStagingReport", "heavy2-convoy-staging-reports",
          "convoy_staging_report", "Comptes-rendus de rassemblement", "Convoy staging reports",
          "Bilan du rassemblement et du depart d' un convoi.",
          "Summary of a convoy's assembly and departure.",
          "Le respect du creneau de depart evite les blocages reseau.",
          "Keeping the departure slot avoids network blockages.",
          "Truck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("convoi", "str", "Convoi", "Convoy"),
           F("lieu_rassemblement", "str", "Lieu de rassemblement", "Staging place"),
           F("depart", "datetime", "Depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "RASSEMBLE", "PARTI", "RETARDE", "ANNULE"])]),
    ],
)
