"""Manifests des 8 modules restants (Wave 3)."""

def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── rh-personnel ───────────────────────────────────────────────────────────
MODULES["rh"] = dict(
    module_key="rh", module_slug="rh-personnel", module_path="rh-personnel",
    perm_module="rh", revision="054", down_revision="053_parc_deep",
    entities=[
        E("recruitment", "recruitments", "Recruitment", "recruitments", "recruitment",
          "Offres et candidatures", "Job offers and applications",
          "Pipeline de recrutement par poste.", "Recruitment pipeline by position.",
          "Avis obligatoire pour chaque candidat.", "Feedback mandatory per candidate.",
          "UserPlus", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("poste", "str", "Poste", "Position"),
           F("departement", "str", "Departement", "Department"),
           F("type_contrat", "enum", "Type contrat", "Contract type"),
           F("date_ouverture", "date", "Ouverture", "Opening"),
           F("date_cloture", "date", "Cloture", "Closing"),
           F("candidats_recus", "int", "Candidats", "Candidates"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_contrat", ["CDI", "CDD", "STAGE", "DETECTION", "INTERIM"], "CDI"),
           EN("statut", ["OUVERTE", "EN_COURS", "POURVUE", "ANNULEE"], "OUVERTE")]),
        E("training", "training_plans", "TrainingPlan", "training-plans", "training",
          "Plan de formation", "Training plan",
          "Actions de formation et habilitations.", "Training and qualification actions.",
          "Habilitation obligatoire avant prise de poste.", "Qualification required before role.",
          "GraduationCap", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("type_action", "enum", "Type", "Type"),
           F("organisme", "str", "Organisme", "Provider"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("duree_heures", "int", "Duree (h)", "Duration (h)"),
           F("cout_xaf", "num", "Cout", "Cost"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_action", ["FORMATION", "HABILITATION", "SEMINAIRE", "CERTIFICATION"], "FORMATION"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "ANNULE"], "PLANIFIE")]),
        E("performance-reviews", "performance_reviews", "PerformanceReview", "performance-reviews", "performance_review",
          "Entretiens d'evaluation", "Performance reviews",
          "Evaluations periodiques des salaries.", "Periodic employee reviews.",
          "Double validation N+1 et RH.", "Dual sign-off by manager and HR.",
          "Star", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("periode", "str", "Periode", "Period"),
           F("date_entretien", "date", "Date entretien", "Interview date"),
           F("evaluateur", "str", "Evaluateur", "Evaluator"),
           F("note_global", "num", "Note globale", "Overall score"),
           F("objectifs_atteints_pct", "num", "Objectifs atteints %", "Goals reached %"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "REALISE", "VALIDE", "REVOIT"], "PLANIFIE")]),
        E("disciplinary", "disciplinary_cases", "DisciplinaryCase", "disciplinary-cases", "disciplinary",
          "Procedures disciplinaires", "Disciplinary procedures",
          "Avertissements, mises a pied, sanctions.", "Warnings, suspensions, sanctions.",
          "Respect du droit de defense.", "Defense rights respected.",
          "Gavel", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("date_fait", "date", "Date du fait", "Incident date"),
           F("type_sanction", "enum", "Type sanction", "Sanction type"),
           F("motif", "text", "Motif", "Reason"),
           F("date_convocation", "date", "Convocation", "Hearing date"),
           F("date_decision", "date", "Decision", "Decision date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_sanction", ["AVERTISSEMENT", "BLAME", "MISE_PIED", "REVOICATION"], "AVERTISSEMENT"),
           EN("statut", ["OUVERTE", "CONVOQUE", "DECIDE", "CLOTURE"], "OUVERTE")]),
        E("org-chart", "org_units", "OrgUnit", "org-units", "org_chart",
          "Organigramme", "Org chart",
          "Unites hierarchiques.", "Hierarchical units.",
          "Chaque unite a un responsable.", "Each unit has a lead.",
          "Network", "code_unite",
          [F("code_unite", "str", "Code unite", "Unit code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("parent_code", "str", "Code parent", "Parent code"),
           F("type_unite", "enum", "Type", "Type"),
           F("responsable", "str", "Responsable", "Lead"),
           F("effectif", "int", "Effectif", "Headcount")],
          [EN("type_unite", ["DIRECTION", "DEPARTEMENT", "SERVICE", "EQUIPE"], "DEPARTEMENT")]),
        E("workforce-planning", "workforce_plans", "WorkforcePlan", "workforce-plans", "workforce_planning",
          "Masse salariale previsionnelle", "Forecast payroll",
          "Projection mensuelle de masse salariale.", "Monthly payroll projection.",
          "Ajustee a chaque mouvement RH.", "Adjusted on HR moves.",
          "Calculator", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("exercice", "int", "Exercice", "Fiscal year"),
           F("mois", "str", "Mois", "Month"),
           F("masse_salariale_prevue_xaf", "num", "Masse prevue", "Forecast payroll"),
           F("effectif_cadre", "int", "Cadres", "Exec headcount"),
           F("effectif_non_cadre", "int", "Non-cadres", "Non-exec headcount"),
           F("hypothese_inflation_pct", "num", "Inflation %", "Inflation %")], []),
        E("contract-management", "employment_contracts", "EmploymentContract", "employment-contracts", "contract_management",
          "Suivi contrats", "Contract tracking",
          "Contrats de travail avec renouvellements.", "Employment contracts and renewals.",
          "Alerte avant expiration CDD.", "Alert before fixed-term expiry.",
          "FileSignature", "numero_contrat",
          [F("numero_contrat", "str", "Numero contrat", "Contract number", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("type_contrat", "enum", "Type contrat", "Contract type"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("avenants", "text", "Avenants", "Amendments"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_contrat", ["CDI", "CDD", "DETECTION", "STAGE", "INTERIM"], "CDI"),
           EN("statut", ["ACTIF", "RENOUVELE", "EXPIRE", "RUPTURE"], "ACTIF")]),
        E("benefits", "employee_benefits", "EmployeeBenefit", "employee-benefits", "benefits",
          "Avantages", "Benefits",
          "Mutuelle, transport, logement.", "Health, transport, housing.",
          "Plafond annuel par categorie.", "Annual ceiling per category.",
          "Gift", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("type_avantage", "enum", "Type avantage", "Benefit type"),
           F("montant_annuel_xaf", "num", "Montant annuel", "Annual amount"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_avantage", ["MUTUELLE", "TRANSPORT", "LOGEMENT", "RESTAURATION", "PREVOYANCE"], "MUTUELLE"),
           EN("statut", ["ACTIF", "SUSPENDU", "ARRETE"], "ACTIF")]),
        E("exit-management", "employee_exits", "EmployeeExit", "employee-exits", "exit_management",
          "Depart / solde tout compte", "Exit / final settlement",
          "Dossiers de sortie.", "Departure files.",
          "Recapitulatif obligatoire.", "Mandatory recap.",
          "DoorClosed", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("type_depart", "enum", "Type depart", "Exit type"),
           F("date_depart", "date", "Date depart", "Exit date"),
           F("preavis_debut", "date", "Preavis debut", "Notice start"),
           F("preavis_fin", "date", "Preavis fin", "Notice end"),
           F("solde_tout_compte_xaf", "num", "Solde tout compte", "Final settlement"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_depart", ["DEMISION", "FIN_CDD", "LICENCIEMENT", "RETRAITE"], "DEMISION"),
           EN("statut", ["OUVERT", "EN_COURS", "CLOTURE"], "OUVERT")]),
        E("attendance-devices", "attendance_devices", "AttendanceDevice", "attendance-devices", "attendance_device",
          "Pointage / badgeuses", "Attendance devices",
          "Terminaux de badgeage.", "Badge terminals.",
          "Sync quotidienne.", "Daily sync.",
          "ScanFace", "code_terminal",
          [F("code_terminal", "str", "Code terminal", "Terminal code", required=True, search=True),
           F("lieu", "str", "Lieu", "Location"),
           F("type_terminal", "enum", "Type", "Type"),
           F("adresse_ip", "str", "Adresse IP", "IP address"),
           F("derniere_synchro", "datetime", "Derniere sync", "Last sync"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_terminal", ["BADGE", "BIOMETRIE", "MOBILE_APP", "QR_CODE"], "BADGE"),
           EN("statut", ["ONLINE", "OFFLINE", "PANNE"], "ONLINE")]),
        E("leave-quotas", "leave_quotas", "LeaveQuota", "leave-quotas", "leave_quota",
          "Droits conges / report N-1", "Leave entitlements / carry-over",
          "Solde conges payes.", "Paid leave balance.",
          "Report plafonne.", "Capped carry-over.",
          "Calendar", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("exercice", "int", "Exercice", "Fiscal year"),
           F("droit_initial_jours", "num", "Droit initial (j)", "Initial entitlement (d)"),
           F("jours_pris", "num", "Jours pris", "Days taken"),
           F("jours_reportes", "num", "Jours reportes", "Days carried"),
           F("solde_actuel", "num", "Solde actuel", "Current balance")], []),
        E("skills-matrix", "employee_skills", "EmployeeSkill", "employee-skills", "skills_matrix",
          "Matrice de competences", "Skills matrix",
          "Competences par employe.", "Skills per employee.",
          "Maj annuelle RH.", "Annual HR update.",
          "Grid3x3", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("competence", "str", "Competence", "Skill"),
           F("niveau", "enum", "Niveau", "Level"),
           F("date_evaluation", "date", "Date evaluation", "Assessment date"),
           F("date_expiration", "date", "Expiration", "Expiry")],
          [EN("niveau", ["DEBUTANT", "INTERMEDIAIRE", "EXPERT", "MAITRE"], "INTERMEDIAIRE")]),
        E("hr-reports", "hr_reports", "HrReport", "hr-reports", "hr_reports",
          "Rapports RH periodiques", "Periodic HR reports",
          "Effectif, absent., turnover.", "Headcount, absence, turnover.",
          "Diffusion mensuelle direction.", "Monthly leadership distribution.",
          "FileBarChart", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("effectif_debut", "int", "Effectif debut", "Opening headcount"),
           F("effectif_fin", "int", "Effectif fin", "Closing headcount"),
           F("taux_absent_pct", "num", "Absent. %", "Absence %"),
           F("taux_turnover_pct", "num", "Turnover %", "Turnover %"),
           F("masse_salariale_xaf", "num", "Masse salariale", "Payroll")], []),
    ],
)

# ─── qhse-securite ───────────────────────────────────────────────────────────
MODULES["qhse"] = dict(
    module_key="qhse", module_slug="qhse-securite", module_path="qhse-securite",
    perm_module="qhse", revision="055", down_revision="054_rh_deep",
    entities=[
        E("environmental-monitoring", "environmental_measurements", "EnvironmentalMeasurement", "environmental-measurements", "environmental",
          "Suivi environnemental", "Environmental monitoring",
          "Bruit, air, eau.", "Noise, air, water.",
          "Comparaison aux normes ICPE / OMS.", "Compared to ICPE / WHO limits.",
          "Activity", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_relevé", "enum", "Type", "Type"),
           F("polluant", "str", "Polluant", "Pollutant"),
           F("valeur", "num", "Valeur", "Value"),
           F("unite", "str", "Unite", "Unit"),
           F("norme_max", "num", "Norme max", "Max threshold"),
           F("station", "str", "Station", "Station"),
           F("date_relevé", "datetime", "Date", "Date"),
           F("conformite", "enum", "Conformite", "Compliance")],
          [EN("type_relevé", ["BRUIT", "AIR", "EAU", "SOL"], "AIR"),
           EN("conformite", ["CONFORME", "NON_CONFORME", "LIMITE"], "CONFORME")]),
        E("waste-management", "waste_records", "WasteRecord", "waste-records", "waste_management",
          "Gestion dechets / BSD", "Waste management / BSW",
          "Bordereau de suivi dechet.", "Waste tracking note.",
          "Tracabilite BSD obligatoire.", "BSW tracking mandatory.",
          "Recycle", "numero_bsd",
          [F("numero_bsd", "str", "Numero BSD", "BSW number", required=True, search=True),
           F("type_dechet", "enum", "Type dechet", "Waste type"),
           F("quantite_kg", "num", "Quantite (kg)", "Quantity (kg)"),
           F("date_production", "date", "Production", "Production date"),
           F("transporteur", "str", "Transporteur", "Carrier"),
           F("destination", "str", "Destination", "Destination"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_dechet", ["ORDINAIRE", "INDUSTRIEL", "DANGEREUX", "RECYCLABLE"], "ORDINAIRE"),
           EN("statut", ["EMI", "TRANSPORTE", "RECU", "TRAITE"], "EMI")]),
        E("chemical-safety", "safety_data_sheets", "SafetyDataSheet", "safety-data-sheets", "chemical_safety",
          "FDS et produits chimiques", "SDS and chemicals",
          "Fiches de donnees de securite.", "Safety data sheets.",
          "Maj a chaque revision fournisseur.", "Update on supplier revision.",
          "FlaskConical", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom_produit", "str", "Nom produit", "Product name"),
           F("numero_ce", "str", "Numero CE", "EC number"),
           F("fournisseur", "str", "Fournisseur", "Supplier"),
           F("phrase_risque", "text", "Phrases de risque", "Risk phrases"),
           F("version_fds", "str", "Version FDS", "SDS version"),
           F("date_revision", "date", "Revision", "Revision date"),
           F("classification", "enum", "Classification", "Classification")],
          [EN("classification", ["NON_CLASSE", "XN", "T", "C", "E", "F"], "NON_CLASSE")]),
        E("emergency-plans", "emergency_plans", "EmergencyPlan", "emergency-plans", "emergency_plan",
          "Plans d'urgence / exercices", "Emergency plans and drills",
          "Evacuation, exercices annuels.", "Evacuation, yearly drills.",
          "Chaque exercice donne une fiche de retour.", "Each drill yields a feedback sheet.",
          "Siren", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_plan", "enum", "Type", "Type"),
           F("zone_concernee", "str", "Zone concernee", "Zone"),
           F("date_elaboration", "date", "Elaboration", "Preparation date"),
           F("date_dernier_exercice", "date", "Dernier exercice", "Last drill"),
           F("frequence_exercice_mois", "int", "Frequence exercice (mois)", "Drill frequency (months)")],
          [EN("type_plan", ["EVACUATION", "INCENDIE", "INONDATION", "ALERT_TOXIQUE"], "EVACUATION")]),
        E("ppe-tracking", "ppe_items", "PpeItem", "ppe-items", "ppe_tracking",
          "EPI equipements protection", "PPE",
          "Dotation EPI par employe.", "PPE per employee.",
          "Renouvellement auto a expiration.", "Auto-renew on expiry.",
          "HardHat", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("type_epi", "enum", "Type EPI", "PPE type"),
           F("taille", "str", "Taille", "Size"),
           F("date_attribution", "date", "Attribution", "Issuance date"),
           F("date_expiration", "date", "Expiration", "Expiry"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_epi", ["CASQUE", "LUNETTES", "GANTS", "CHAUSSURES", "HAUTE_VISIBILITE", "RESPIRATOIRE"], "CASQUE"),
           EN("statut", ["EN_SERVICE", "REMPLACE", "PERTE", "EXPIRE"], "EN_SERVICE")]),
        E("occupational-health", "health_visits", "HealthVisit", "health-visits", "occupational_health",
          "Medecine du travail", "Occupational health",
          "Visites médicales obligatoires.", "Mandatory medical visits.",
          "Report si inaptitude.", "Report if unfit.",
          "Stethoscope", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("employe_id", "int", "Employe", "Employee"),
           F("type_visite", "enum", "Type visite", "Visit type"),
           F("date_visite", "date", "Date visite", "Visit date"),
           F("medecin", "str", "Medecin", "Doctor"),
           F("resultat", "enum", "Resultat", "Result"),
           F("prochaine_visite", "date", "Prochaine visite", "Next visit")],
          [EN("type_visite", ["EMBAUCHE", "PERIODIQUE", "REPRISE", "SUR_DEMANDE"], "EMBAUCHE"),
           EN("resultat", ["APTE", "APTE_AVEC_RESTRICTION", "INAPTE_TEMPORAIRE", "INAPTE_DEFINITIF"], "APTE")]),
        E("risk-assessment", "risk_assessments", "RiskAssessment", "risk-assessments", "risk_assessment",
          "Evaluation des risques (DUER)", "Risk assessment (DUER)",
          "Document unique evaluation des risques.", "Single risk assessment document.",
          "Revue annuelle obligatoire.", "Annual review mandatory.",
          "ShieldAlert", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("unite_travail", "str", "Unite de travail", "Work unit"),
           F("description_risque", "text", "Description risque", "Risk description"),
           F("cotation", "enum", "Cotation", "Rating"),
           F("mesure_prevention", "text", "Mesure prevention", "Prevention measure"),
           F("date_evaluation", "date", "Evaluation", "Assessment date"),
           F("responsable", "str", "Responsable", "Owner")],
          [EN("cotation", ["FAIBLE", "MOYEN", "ELEVE", "CRITIQUE"], "MOYEN")]),
        E("corrective-actions", "corrective_actions", "CorrectiveAction", "corrective-actions", "corrective_action",
          "Actions correctives / 8D", "Corrective actions / 8D",
          "Suites a incidents ou non-conformites.", "Follow-up to incidents or non-conformities.",
          "Cloture = preuve d'efficacite.", "Closure = proof of effectiveness.",
          "CheckCircle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("source_ecart", "str", "Source ecart", "Source deviation"),
           F("description_probleme", "text", "Description probleme", "Problem description"),
           F("cause_racine", "text", "Cause racine", "Root cause"),
           F("action_corrective", "text", "Action corrective", "Corrective action"),
           F("responsable", "str", "Responsable", "Owner"),
           F("date_prevue_cloture", "date", "Cloture prevue", "Planned closure"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["OUVERT", "EN_COURS", "VERIFIE", "CLOTURE"], "OUVERT")]),
        E("management-reviews", "management_reviews", "ManagementReview", "management-reviews", "management_review",
          "Revues de direction", "Management reviews",
          "Revue annuelle du systeme QHSE.", "Annual QHSE review.",
          "PV diffuse a tous les pilotes.", "Minutes shared with all owners.",
          "Presentation", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("date_revue", "date", "Date revue", "Review date"),
           F("participants", "text", "Participants", "Participants"),
           F("sujets", "text", "Sujets", "Topics"),
           F("decisions", "text", "Decisions", "Decisions"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "TENUE", "PV_DIFFUSE"], "PLANIFIE")]),
        E("regulatory-compliance", "compliance_records", "ComplianceRecord", "compliance-records", "regulatory_compliance",
          "Conformite reglementaire", "Regulatory compliance",
          "Veille et preuves de conformite.", "Watch and compliance evidence.",
          "Alerte avant echeance declaration.", "Alert before declaration deadline.",
          "Scale", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("regulation", "str", "Regulation", "Regulation"),
           F("domaine", "enum", "Domaine", "Domain"),
           F("obligation", "text", "Obligation", "Obligation"),
           F("preuve", "text", "Preuve", "Evidence"),
           F("date_constat", "date", "Date constat", "Assessment date"),
           F("prochaine_echeance", "date", "Prochaine echeance", "Next deadline"),
           F("statut", "enum", "Statut", "Status")],
          [EN("domaine", ["ICPE", "ISPS", "CNPS", "MARPOL", "TRAVAIL", "ENVIRONNEMENT"], "ICPE"),
           EN("statut", ["CONFORME", "PARTIEL", "NON_CONFORME"], "CONFORME")]),
        E("quality-audits", "quality_audits", "QualityAudit", "quality-audits", "quality_audit",
          "Audits internes qualite", "Internal quality audits",
          "Audits ISO 9001 / 14001.", "ISO 9001 / 14001 audits.",
          "Rapport + suivi des ecarts.", "Report + gap tracking.",
          "Search", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type_audit", "enum", "Type audit", "Audit type"),
           F("perimetre", "str", "Perimetre", "Scope"),
           F("auditeur", "str", "Auditeur", "Auditor"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("nb_ecarts", "int", "Nb ecarts", "Findings"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_audit", ["INTERNE", "EXTERNE", "CERTIFICATION", "FOURNISSEUR"], "INTERNE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "CLOTURE"], "PLANIFIE")]),
    ],
)

# ─── client-b2b ──────────────────────────────────────────────────────────────
MODULES["b2b"] = dict(
    module_key="b2b", module_slug="client-b2b", module_path="client-b2b",
    perm_module="b2b", revision="056", down_revision="055_qhse_deep",
    entities=[
        E("client-onboarding", "client_onboardings", "ClientOnboarding", "client-onboardings", "client_onboarding",
          "Admission nouveau client", "New client onboarding",
          "Dossier admission / KYC.", "Admission / KYC file.",
          "Piece legale et referentiel bancaire obligatoires.", "Legal paper and bank reference mandatory.",
          "UserPlus", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("raison_sociale", "str", "Raison sociale", "Legal name"),
           F("niu", "str", "NIU", "Tax ID"),
           F("rc", "str", "Registre commerce", "Reg. commerce"),
           F("contact_principal", "str", "Contact", "Contact"),
           F("email", "str", "Email", "Email"),
           F("telephone", "str", "Telephone", "Phone"),
           F("date_demande", "date", "Demande", "Request"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["SOUMIS", "INCOMPLET", "VALIDE", "REFUSE"], "SOUMIS")]),
        E("sla-management", "sla_contracts", "SlaContract", "sla-contracts", "sla_management",
          "Niveau de service / penalisations", "SLA / penalties",
          "Engagement service et mesures.", "Service commitments and measures.",
          "Penalite si 2 mois consecutifs sous seuil.", "Penalty if 2 months under threshold.",
          "Timer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("type_prestation", "str", "Type prestation", "Service type"),
           F("engagement_valeur", "num", "Valeur engagement", "Committed value"),
           F("taux_atteint_pct", "num", "Taux atteint %", "Achieved %"),
           F("penalite_xaf", "num", "Penalite XAF", "Penalty XAF"),
           F("periode", "str", "Periode", "Period"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["CONFORME", "ALERTE", "PENALISE", "EXCEDENT"], "CONFORME")]),
        E("contract-tracking", "b2b_contracts", "B2bContract", "b2b-contracts", "contract_tracking",
          "Contrats cadres / avenants", "Framework contracts / amendments",
          "Contrats long terme clients.", "Long-term client contracts.",
          "Chaque avenant est versionne.", "Each amendment versioned.",
          "FileSignature", "numero_contrat",
          [F("numero_contrat", "str", "Numero contrat", "Contract number", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("type_contrat", "enum", "Type", "Type"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("montant_engage_xaf", "num", "Montant engage", "Committed amount"),
           F("nb_avenants", "int", "Nb avenants", "Amendments"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_contrat", ["CADRE", "PRESTATION", "LICENSE", "PARTENARIAT"], "CADRE"),
           EN("statut", ["ACTIF", "RENEGOCIE", "EXPIRE", "RESILIE"], "ACTIF")]),
        E("satisfaction-surveys", "satisfaction_surveys", "SatisfactionSurvey", "satisfaction-surveys", "satisfaction_survey",
          "Enquetes satisfaction NPS", "Satisfaction / NPS surveys",
          "Enquetes periodiques clients.", "Periodic client surveys.",
          "Score NPS 9-10 vs 0-6.", "NPS score 9-10 vs 0-6.",
          "Smile", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("date_enquete", "date", "Date", "Survey date"),
           F("note_global", "num", "Note globale", "Overall score"),
           F("score_nps", "int", "Score NPS", "NPS score"),
           F("commentaires", "text", "Commentaires", "Comments")], []),
        E("credit-limits", "client_credit_limits", "ClientCreditLimit", "client-credit-limits", "credit_limit",
          "Plafonds de credit client", "Client credit limits",
          "Encours autorise par client.", "Authorized outstanding per client.",
          "Blocage commandes si depassement.", "Order block if exceeded.",
          "CreditCard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("plafond_xaf", "num", "Plafond", "Limit"),
           F("encours_actuel_xaf", "num", "Encours", "Current outstanding"),
           F("delai_paiement_jours", "int", "Delai paiement (j)", "Payment terms (d)"),
           F("date_revision", "date", "Revision", "Review"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["NORMAL", "VIGIE", "BLOQUE"], "NORMAL")]),
        E("document-exchange", "b2b_documents", "B2bDocument", "b2b-documents", "document_exchange",
          "Echange documents contractuels", "Contract document exchange",
          "Echanges pieces contractuelles.", "Contract document exchanges.",
          "Accuse reception obligatoire.", "Receipt ack required.",
          "FolderOpen", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("type_document", "str", "Type document", "Document type"),
           F("nom_fichier", "str", "Nom fichier", "File name"),
           F("date_envoi", "datetime", "Envoi", "Send date"),
           F("date_reception", "datetime", "Reception", "Receipt date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ENVOYE", "RECU", "ACQUITE", "PERDU"], "ENVOYE")]),
        E("service-requests", "service_requests", "ServiceRequest", "service-requests", "service_request",
          "Demandes de service client", "Client service requests",
          "Tickets et demandes clients.", "Client tickets / requests.",
          "SLA reponse contractuel.", "Contractual response SLA.",
          "Inbox", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("type_demande", "str", "Type demande", "Request type"),
           F("description", "text", "Description", "Description"),
           F("date_creation", "datetime", "Creation", "Creation date"),
           F("date_echeance", "datetime", "Echeance", "Due date"),
           F("priorite", "enum", "Priorite", "Priority"),
           F("statut", "enum", "Statut", "Status")],
          [EN("priorite", ["BASSE", "NORMALE", "HAUTE", "URGENTE"], "NORMALE"),
           EN("statut", ["OUVERT", "EN_COURS", "RESOLU", "CLOTURE"], "OUVERT")]),
        E("pricing-agreements", "pricing_agreements", "PricingAgreement", "pricing-agreements", "pricing_agreement",
          "Accords tarifaires / remises", "Pricing agreements / discounts",
          "Grille tarifaire par client.", "Pricing grid per client.",
          "Revue annuelle commerciale.", "Annual sales review.",
          "Tag", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("type_prestation", "str", "Type prestation", "Service type"),
           F("remise_pct", "num", "Remise %", "Discount %"),
           F("palier_volume", "str", "Palier volume", "Volume tier"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIF", "EXPIRE", "RENEGOCIE"], "ACTIF")]),
        E("shipment-booking", "shipment_bookings", "ShipmentBooking", "shipment-bookings", "shipment_booking",
          "Reservation expedition client", "Shipment booking",
          "Reservation creneau quai ou navire.", "Berth / vessel slot reservation.",
          "Confirmation 48h avant.", "Confirmation 48h before.",
          "CalendarCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("escale_id", "int", "Escale", "Call"),
           F("type_expedition", "enum", "Type expedition", "Shipment type"),
           F("date_reservation", "datetime", "Reservation", "Booking date"),
           F("date_prevue", "datetime", "Prevue", "Planned date"),
           F("conteneurs_prevus", "int", "Conteneurs prevus", "Expected containers"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_expedition", ["IMPORT", "EXPORT", "TRANSBORD"], "IMPORT"),
           EN("statut", ["DEMANDE", "CONFIRME", "ANNULE", "REALISE"], "DEMANDE")]),
        E("claim-dispute", "client_claims", "ClientClaim", "client-claims", "claim_dispute",
          "Reclamation / litige client", "Client claim / dispute",
          "Dossier litige commercial.", "Commercial dispute file.",
          "Escalade juridique apres 30j.", "Legal escalation after 30 days.",
          "AlertOctagon", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("objet", "str", "Objet", "Subject"),
           F("description", "text", "Description", "Description"),
           F("date_reclamation", "date", "Reclamation", "Complaint date"),
           F("montant_reclame_xaf", "num", "Montant reclame", "Amount claimed"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["RECU", "INSTRUCTION", "TRANSACTION", "JURIDIQUE", "CLOTURE"], "RECU")]),
        E("account-reports", "account_reports", "AccountReport", "account-reports", "account_report",
          "Releves periodiques compte client", "Client account statements",
          "Releves et balances envoyes.", "Statements and balances sent.",
          "Approbation client = lettrage.", "Client approval = reconciliation.",
          "FileBarChart", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client_id", "int", "Client", "Client"),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("factures_emises_xaf", "num", "Factures emis", "Invoices issued"),
           F("reglements_recus_xaf", "num", "Reglements recus", "Payments received"),
           F("solde_a_payer_xaf", "num", "Solde a payer", "Balance owed")], []),
    ],
)

# ─── reports-bi ──────────────────────────────────────────────────────────────
MODULES["reports"] = dict(
    module_key="reports", module_slug="reports-bi", module_path="reports-bi",
    perm_module="reports", revision="057", down_revision="056_b2b_deep",
    entities=[
        E("data-warehouse", "warehouse_tables", "WarehouseTable", "warehouse-tables", "data_warehouse",
          "Entrepot de donnees", "Data warehouse",
          "Tables ETL et cubes OLAP.", "ETL tables and OLAP cubes.",
          "Fraicheur maximale : 24h.", "Max freshness: 24h.",
          "Database", "code_table",
          [F("code_table", "str", "Code table", "Table code", required=True, search=True),
           F("domaine", "str", "Domaine", "Domain"),
           F("frequence_refresh", "enum", "Refresh", "Refresh"),
           F("volume_lignes", "int", "Volume lignes", "Row count"),
           F("dernier_refresh", "datetime", "Dernier refresh", "Last refresh"),
           F("statut", "enum", "Statut", "Status")],
          [EN("frequence_refresh", ["HEURTAIRE", "QUOTIDIEN", "HEBDO", "MENSUEL"], "QUOTIDIEN"),
           EN("statut", ["ACTIF", "DEGRADE", "KO"], "ACTIF")]),
        E("scorecards", "scorecards", "Scorecard", "scorecards", "scorecard",
          "Tableaux de score par pole", "Scorecards per pole",
          "KPI consolides par direction.", "KPIs consolidated per department.",
          "Revue mensuelle direction.", "Monthly leadership review.",
          "Target", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("pole", "str", "Pole", "Pole"),
           F("periode", "str", "Periode", "Period"),
           F("nb_kpis", "int", "Nb KPI", "KPI count"),
           F("score_global_pct", "num", "Score global %", "Overall score %"),
           F("kpis_rouges", "int", "KPI rouges", "Red KPIs"),
           F("kpis_oranges", "int", "KPI oranges", "Orange KPIs"),
           F("kpis_verts", "int", "KPI verts", "Green KPIs")], []),
        E("benchmarks", "industry_benchmarks", "IndustryBenchmark", "industry-benchmarks", "benchmark",
          "Comparaison sectorielle ports CEMAC", "CEMAC port benchmarks",
          "Indicateurs compares aux ports voisins.", "Metrics vs neighboring ports.",
          "Sources officielles seulement.", "Official sources only.",
          "GitCompare", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("indicateur", "str", "Indicateur", "Indicator"),
           F("valeur_interne", "num", "Valeur interne", "Internal value"),
           F("valeur_benchmark", "num", "Valeur benchmark", "Benchmark value"),
           F("port_reference", "str", "Port reference", "Reference port"),
           F("source", "str", "Source", "Source"),
           F("ecart_pct", "num", "Ecart %", "Gap %")], []),
        E("predictive-analytics", "predictive_models", "PredictiveModel", "predictive-models", "predictive_analytics",
          "Analyses predictives", "Predictive analytics",
          "Modeles ML simples (regression, serie temporelle).", "Simple ML (regression, time series).",
          "Score de precision affiche sur chaque prediction.", "Precision displayed per prediction.",
          "Brain", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom_modele", "str", "Nom modele", "Model name"),
           F("type_modele", "enum", "Type", "Type"),
           F("variable_predite", "str", "Variable predite", "Target variable"),
           F("precision_pct", "num", "Precision %", "Precision %"),
           F("date_entrainement", "datetime", "Entrainement", "Training date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_modele", ["REGRESSION", "SERIE_TEMP", "CLASSIFICATION"], "REGRESSION"),
           EN("statut", ["ACTIF", "ENTRAINEMENT", "OBSOLETE"], "ACTIF")]),
        E("custom-dashboards", "custom_dashboards", "CustomDashboard", "custom-dashboards", "custom_dashboard",
          "Tableaux de bord personnalises", "Custom dashboards",
          "Dashboards configures par utilisateur.", "User-configured dashboards.",
          "Partage possible en lecture seule.", "Shareable in read-only.",
          "LayoutDashboard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("proprietaire", "str", "Proprietaire", "Owner"),
           F("nb_widgets", "int", "Nb widgets", "Widgets"),
           F("partage", "enum", "Partage", "Sharing"),
           F("frequence", "enum", "Frequence", "Frequency"),
           F("actif", "bool", "Actif", "Active")],
          [EN("partage", ["PRIVE", "EQUIPE", "PUBLIC"], "PRIVE"),
           EN("frequence", ["TEMPS_REEL", "HOURLY", "QUOTIDIEN", "HEBDO"], "QUOTIDIEN")]),
        E("export-reports", "report_exports", "ReportExport", "report-exports", "export_reports",
          "Exports planifies / abonnes", "Scheduled / subscribed exports",
          "Envois automatiques de rapports.", "Automatic report delivery.",
          "Format PDF / XLSX / CSV.", "PDF / XLSX / CSV.",
          "Send", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("rapport_source", "str", "Rapport source", "Source report"),
           F("format", "enum", "Format", "Format"),
           F("frequence", "enum", "Frequence", "Frequency"),
           F("destinataires", "text", "Destinataires", "Recipients"),
           F("dernier_envoi", "datetime", "Dernier envoi", "Last send"),
           F("statut", "enum", "Statut", "Status")],
          [EN("format", ["PDF", "XLSX", "CSV", "HTML"], "PDF"),
           EN("frequence", ["QUOTIDIEN", "HEBDO", "MENSUEL", "TRIMESTRIEL"], "MENSUEL"),
           EN("statut", ["ACTIF", "PAUSE", "ERREUR"], "ACTIF")]),
        E("kpi-definitions", "kpi_definitions", "KpiDefinition", "kpi-definitions", "kpi_definition",
          "Catalogue et definitions KPI", "KPI catalog and definitions",
          "Formule, unite, source, proprietaire.", "Formula, unit, source, owner.",
          "Revue annuelle obligatoire.", "Annual review mandatory.",
          "BookMarked", "code_kpi",
          [F("code_kpi", "str", "Code KPI", "KPI code", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("formule", "text", "Formule", "Formula"),
           F("unite", "str", "Unite", "Unit"),
           F("source", "str", "Source", "Source"),
           F("periodicite", "enum", "Periodicite", "Frequency"),
           F("responsable", "str", "Responsable", "Owner"),
           F("actif", "bool", "Actif", "Active")],
          [EN("periodicite", ["QUOTIDIEN", "HEBDO", "MENSUEL", "TRIMESTRIEL", "ANNUEL"], "MENSUEL")]),
        E("drill-down-analytics", "drill_paths", "DrillPath", "drill-paths", "drill_down",
          "Explorations en cascade", "Drill-down analytics",
          "Chemins d'exploration definis.", "Defined exploration paths.",
          "Rebond possible entre modules.", "Cross-module jump allowed.",
          "Layers", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("niveau_1", "str", "Niveau 1", "Level 1"),
           F("niveau_2", "str", "Niveau 2", "Level 2"),
           F("niveau_3", "str", "Niveau 3", "Level 3"),
           F("actif", "bool", "Actif", "Active")], []),
        E("cohort-analysis", "cohort_analyses", "CohortAnalysis", "cohort-analyses", "cohort_analysis",
          "Analyse de cohortes", "Cohort analysis",
          "Groupements clients par date ou segment.", "Client grouping by date or segment.",
          "Suivi retention 12 mois.", "12-month retention tracking.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom_cohorte", "str", "Nom cohort", "Cohort name"),
           F("criteres", "text", "Criteres", "Criteria"),
           F("taille", "int", "Taille", "Size"),
           F("date_debut", "date", "Debut", "Start"),
           F("taux_retention_m1_pct", "num", "Retention M1 %", "M1 retention %"),
           F("taux_retention_m12_pct", "num", "Retention M12 %", "M12 retention %")], []),
        E("anomaly-detection", "anomaly_records", "AnomalyRecord", "anomaly-records", "anomaly_detection",
          "Detection anomalies / seuils", "Anomaly detection / thresholds",
          "Signaux d'alerte automatiques.", "Automatic alert signals.",
          "Revue hebdomadaire DAF.", "Weekly CFO review.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("indicateur", "str", "Indicateur", "Indicator"),
           F("valeur_constatee", "num", "Valeur constatee", "Observed value"),
           F("valeur_attendue", "num", "Valeur attendue", "Expected value"),
           F("seuil_pct", "num", "Seuil %", "Threshold %"),
           F("date_detection", "datetime", "Date detection", "Detection date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["DETECTE", "INVESTIGUE", "RESOLU", "FAUX_POSITIF"], "DETECTE")]),
        E("regulatory-reports", "regulatory_reports", "RegulatoryReport", "regulatory-reports", "regulatory_report",
          "Rapports reglementaires (APN, douane)", "Regulatory reports (CPA, customs)",
          "Declarations obligatoires.", "Mandatory filings.",
          "Depot dans le delai legal.", "Filed within legal deadline.",
          "FileText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("autorite", "str", "Autorite", "Authority"),
           F("type_rapport", "enum", "Type rapport", "Report type"),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("date_depot", "date", "Depot", "Filing date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_rapport", ["APN", "DOUANE", "CNPS", "IMPOTS", "STATISTIQUE"], "APN"),
           EN("statut", ["BROUILLON", "DEPOSE", "ACCEPTE", "REJETE"], "BROUILLON")]),
    ],
)

# ─── admin-saas ──────────────────────────────────────────────────────────────
MODULES["admin"] = dict(
    module_key="admin", module_slug="admin-saas", module_path="admin-saas",
    perm_module="admin", revision="058", down_revision="057_reports_deep",
    entities=[
        E("feature-flags", "feature_flags", "FeatureFlag", "feature-flags", "feature_flag",
          "Gestion fonctionnalites par tenant", "Feature flags per tenant",
          "Active / desactive fonctionnalites.", "Toggle features.",
          "Revue mensuelle produit.", "Monthly product review.",
          "ToggleRight", "code_flag",
          [F("code_flag", "str", "Code flag", "Flag code", required=True, search=True),
           F("description", "text", "Description", "Description"),
           F("actif", "bool", "Actif", "Active"),
           F("tenants_concernes", "text", "Tenants concerns", "Tenants affected"),
           F("date_debut_rollout", "date", "Debut rollout", "Rollout start"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["DRAFT", "BETA", "GLOBALE", "RETIREE"], "BETA")]),
        E("rate-limiting", "api_quotas", "ApiQuota", "api-quotas", "rate_limit",
          "Quotas API et limitations", "API quotas and limits",
          "Appels par tenant / minute.", "Calls per tenant / minute.",
          "Revise selon contrat.", "Reviewed per contract.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("api_group", "str", "Groupe API", "API group"),
           F("limite_minute", "int", "Limite minute", "Per-minute limit"),
           F("limite_jour", "int", "Limite jour", "Daily limit"),
           F("consommation_actuelle", "int", "Consommation actuelle", "Current usage"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["NORMAL", "ALERTE", "BLOQUE"], "NORMAL")]),
        E("white-label", "white_labels", "WhiteLabel", "white-labels", "white_label",
          "Personnalisation marque", "Branding customization",
          "Logo, domaine, couleur par tenant.", "Logo, domain, color per tenant.",
          "Valide par direction marketing.", "Approved by marketing lead.",
          "Palette", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("nom_marque", "str", "Nom marque", "Brand name"),
           F("domaine_personnalise", "str", "Domaine", "Custom domain"),
           F("logo_url", "str", "Logo URL", "Logo URL"),
           F("couleur_primaire", "str", "Couleur primaire", "Primary color"),
           F("couleur_secondaire", "str", "Couleur secondaire", "Secondary color"),
           F("actif", "bool", "Actif", "Active")], []),
        E("onboarding-wizard", "tenant_onboardings", "TenantOnboarding", "tenant-onboardings", "onboarding_wizard",
          "Parcours onboarding nouveau tenant", "New tenant onboarding",
          "Etapes d'activation d'un nouveau client SaaS.", "Activation steps for new SaaS clients.",
          "Objectif : activation sous 14 jours.", "Goal: activation under 14 days.",
          "Wand2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_activation", "date", "Activation", "Activation"),
           F("nb_etapes_completes", "int", "Etapes completes", "Steps done"),
           F("responsable_succeed", "str", "Succeed", "Succeed"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "ACTIF", "ABANONNE", "REFUSE"], "EN_COURS")]),
        E("api-keys", "saas_api_keys", "SaasApiKey", "saas-api-keys", "api_key",
          "Cles API tierces par tenant", "Third-party API keys per tenant",
          "Cles d'acces aux webhooks tierces.", "Access keys for third-party webhooks.",
          "Rotation annuelle.", "Annual rotation.",
          "KeyRound", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("label", "str", "Label", "Label"),
           F("scopes", "text", "Scopes", "Scopes"),
           F("date_creation", "date", "Creation", "Creation"),
           F("date_expiration", "date", "Expiration", "Expiry"),
           F("derniere_utilisation", "datetime", "Derniere utilisation", "Last used"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIF", "REVOKE", "EXPIRE"], "ACTIF")]),
        E("webhooks", "tenant_webhooks", "TenantWebhook", "tenant-webhooks", "webhook",
          "Integration evenements sortants", "Outbound webhook integrations",
          "Evenements pousses vers tiers.", "Events pushed to third parties.",
          "Retries exponentiels 24h.", "Exponential retries 24h.",
          "Webhook", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("url_destination", "str", "URL", "URL"),
           F("evenements_abonnes", "text", "Evenements abonnes", "Subscribed events"),
           F("secret_hmac", "str", "Secret HMAC", "HMAC secret"),
           F("dernier_succes", "datetime", "Dernier succes", "Last success"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIF", "PAUSE", "ERREUR"], "ACTIF")]),
        E("data-migration", "data_migrations", "DataMigration", "data-migrations", "data_migration",
          "Import / migration donnees", "Data import and migration",
          "Import initial ou mise a jour.", "Initial import or update.",
          "Precheck et rollback obligatoires.", "Precheck and rollback required.",
          "Upload", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("type_migration", "enum", "Type", "Type"),
           F("source", "str", "Source", "Source"),
           F("nb_lignes_prevues", "int", "Lignes prevues", "Expected rows"),
           F("nb_lignes_importees", "int", "Lignes importees", "Imported rows"),
           F("nb_lignes_rejetees", "int", "Lignes rejetees", "Rejected rows"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_migration", ["IMPORT_INITIAL", "UPDATE", "MERGE", "ARCHIVE"], "IMPORT_INITIAL"),
           EN("statut", ["PLANIFIE", "EN_COURS", "SUCCES", "ECHEC", "ROLLED_BACK"], "PLANIFIE")]),
        E("support-tickets", "platform_tickets", "PlatformTicket", "platform-tickets", "support_ticket",
          "Tickets support plateforme", "Platform support tickets",
          "Incidents et demandes support SaaS.", "SaaS incidents and requests.",
          "SLA premier reponse 4h.", "First response SLA 4h.",
          "LifeBuoy", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("titre", "str", "Titre", "Title"),
           F("description", "text", "Description", "Description"),
           F("priorite", "enum", "Priorite", "Priority"),
           F("assigne_a", "str", "Assigne a", "Assigned to"),
           F("date_creation", "datetime", "Creation", "Creation"),
           F("statut", "enum", "Statut", "Status")],
          [EN("priorite", ["BASSE", "NORMALE", "HAUTE", "URGENTE"], "NORMALE"),
           EN("statut", ["OUVERT", "EN_COURS", "RESOLU", "CLOTURE"], "OUVERT")]),
        E("billing-engine", "billing_entries", "BillingEntry", "billing-entries", "billing_engine",
          "Moteur de facturation SaaS", "SaaS billing engine",
          "Facturation par abonnement, usage, add-on.", "Subscription, usage, add-on billing.",
          "Reconcilie avec tresorerie.", "Reconciled with treasury.",
          "CreditCard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("periode", "str", "Periode", "Period"),
           F("type_facture", "enum", "Type facture", "Invoice type"),
           F("montant_ht_xaf", "num", "Montant HT", "Amount excl. tax"),
           F("tva_xaf", "num", "TVA", "VAT"),
           F("total_ttc_xaf", "num", "Total TTC", "Total incl. tax"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_facture", ["ABONNEMENT", "USAGE", "ADDON", "PENALITE"], "ABONNEMENT"),
           EN("statut", ["BROUILLON", "EMISE", "PAYEE", "IMPAYEE"], "BROUILLON")]),
        E("usage-analytics", "usage_analytics", "UsageAnalytics", "usage-analytics", "usage_analytics",
          "Analytique d'usage par tenant", "Usage analytics per tenant",
          "Mesure actif / passif des fonctionnalites.", "Track feature adoption.",
          "Aide a la decision upsell / churn.", "Supports upsell / churn decision.",
          "BarChart2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("periode", "str", "Periode", "Period"),
           F("utilisateurs_actifs", "int", "Utilisateurs actifs", "Active users"),
           F("utilisateurs_seats", "int", "Sieges", "Seats"),
           F("taux_adoption_pct", "num", "Adoption %", "Adoption %"),
           F("score_sante", "num", "Score sante", "Health score")], []),
        E("uptime-monitoring", "uptime_records", "UptimeRecord", "uptime-records", "uptime_monitoring",
          "Monitoring disponibilite / SLA", "Uptime and SLA monitoring",
          "Sondage endpoints, latence, erreurs.", "Endpoint probe, latency, errors.",
          "Pinger toutes les minutes.", "Ping every minute.",
          "Activity", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("service", "str", "Service", "Service"),
           F("region", "str", "Region", "Region"),
           F("statut", "enum", "Statut", "Status"),
           F("latence_ms", "int", "Latence (ms)", "Latency (ms)"),
           F("disponibilite_pct", "num", "Disponibilite %", "Availability %"),
           F("date_mesure", "datetime", "Date mesure", "Measurement date")],
          [EN("statut", ["OPERATIONNEL", "DEGRADE", "PANNE"], "OPERATIONNEL")]),
    ],
)

# ─── superadmin-cadc ────────────────────────────────────────────────────────
MODULES["superadmin"] = dict(
    module_key="superadmin", module_slug="superadmin-cadc", module_path="superadmin-cadc",
    perm_module="superadmin", revision="059", down_revision="058_admin_deep",
    entities=[
        E("platform-audit", "platform_audits", "PlatformAudit", "platform-audits", "platform_audit",
          "Audit global plateforme multi-tenant", "Global platform audit",
          "Revues croisees de la plateforme.", "Cross-platform reviews.",
          "Trimestriel.", "Quarterly.",
          "ScanSearch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode_debut", "date", "Debut", "Start"),
           F("periode_fin", "date", "Fin", "End"),
           F("nb_tenants_audites", "int", "Tenants audites", "Tenants audited"),
           F("constats", "text", "Constats", "Findings"),
           F("recommandations", "text", "Recommandations", "Recommendations"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "PUBLIE"], "PLANIFIE")]),
        E("compliance-dashboards", "compliance_dashboards", "ComplianceDashboard", "compliance-dashboards", "compliance_dashboards",
          "Tableaux conformite globale", "Global compliance dashboards",
          "Suivi conformite multi-tenant.", "Cross-tenant compliance.",
          "Diffusion quarterly.", "Quarterly distribution.",
          "Shield", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("domaine", "enum", "Domaine", "Domain"),
           F("nb_tenants_conformes", "int", "Tenants conformes", "Compliant tenants"),
           F("nb_tenants_hors", "int", "Tenants hors", "Non-compliant tenants"),
           F("score_global_pct", "num", "Score global %", "Overall score %"),
           F("date_revue", "date", "Revue", "Review date")],
          [EN("domaine", ["RGPD", "DONNEES_SENSIBLES", "SECURITE", "FISCAL", "SOCIAL"], "RGPD")]),
        E("data-retention", "retention_policies", "RetentionPolicy", "retention-policies", "data_retention",
          "Politique retention / purge", "Retention and purge policy",
          "Durees et modalites de purge.", "Duration and purge rules.",
          "Automatise via cron mensuel.", "Automated via monthly cron.",
          "Trash", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("categorie", "enum", "Categorie", "Category"),
           F("duree_conservation_jours", "int", "Duree (j)", "Duration (d)"),
           F("methode_purge", "enum", "Methode purge", "Purge method"),
           F("base_legale", "text", "Base legale", "Legal basis"),
           F("actif", "bool", "Actif", "Active")],
          [EN("categorie", ["DOCUMENT_METIER", "AUDIT", "PII", "PAIE", "FINANCIER"], "DOCUMENT_METIER"),
           EN("methode_purge", ["ANONYMISATION", "SUPPRESSION", "ARCHIVAGE"], "ANONYMISATION")]),
        E("incident-response", "platform_incidents", "PlatformIncident", "platform-incidents", "incident_response",
          "Reponse incidents plateforme", "Platform incident response",
          "Gestion crise et post-mortem.", "Crisis and post-mortem.",
          "Escalade P1 < 15 min.", "P1 escalation under 15 min.",
          "AlertOctagon", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("priorite", "enum", "Priorite", "Priority"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_resolution", "datetime", "Resolution", "Resolution"),
           F("impact_tenants", "text", "Impact tenants", "Tenants impacted"),
           F("cause_racine", "text", "Cause racine", "Root cause"),
           F("statut", "enum", "Statut", "Status")],
          [EN("priorite", ["P1", "P2", "P3", "P4"], "P2"),
           EN("statut", ["OUVERT", "CONTENU", "RESOLU", "POST_MORTEM"], "OUVERT")]),
        E("access-reviews", "access_reviews", "AccessReview", "access-reviews", "access_review",
          "Revue periodique des acces", "Periodic access review",
          "Certification des droits utilisateurs.", "User rights certification.",
          "Semestrielle par tenant.", "Semi-annual per tenant.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("tenant_id", "int", "Tenant", "Tenant"),
           F("date_revue", "date", "Date revue", "Review date"),
           F("nb_utilisateurs_revus", "int", "Utilisateurs revus", "Users reviewed"),
           F("nb_droits_retires", "int", "Droits retires", "Rights removed"),
           F("revue_par", "str", "Revue par", "Reviewed by"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_COURS", "CLOTURE"], "PLANIFIE")]),
        E("license-management", "software_licenses", "SoftwareLicense", "software-licenses", "license_management",
          "Gestion licences et modules", "License and module management",
          "Suivi des droits d'usage par module.", "Track usage rights per module.",
          "Renouvellement anticipe 60j.", "Renew 60d before expiry.",
          "Award", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("module", "str", "Module", "Module"),
           F("editeur", "str", "Editeur", "Vendor"),
           F("nb_sieges", "int", "Sieges", "Seats"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("cotisation_xaf", "num", "Cotisation XAF", "Fee XAF"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["ACTIVE", "EXPIREE", "RENOUVELEE"], "ACTIVE")]),
        E("partner-network", "technology_partners", "TechnologyPartner", "technology-partners", "partner_network",
          "Reseau partenaires technologiques", "Technology partner network",
          "Partenaires editeurs / integrateurs.", "Editor / integrator partners.",
          "Revue annuelle.", "Annual review.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("type_partenaire", "enum", "Type", "Type"),
           F("produit_associe", "str", "Produit associe", "Related product"),
           F("contrat", "text", "Contrat", "Contract"),
           F("date_debut", "date", "Debut", "Start"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_partenaire", ["EDITEUR", "INTEGRATEUR", "REVENEUR", "TECHNIQUE"], "EDITEUR"),
           EN("statut", ["ACTIF", "PAUSE", "RESILIE"], "ACTIF")]),
        E("revenue-analytics", "saas_revenue_records", "SaasRevenueRecord", "saas-revenue-records", "revenue_analytics",
          "Analytique revenus SaaS / MRR", "SaaS revenue / MRR analytics",
          "MRR, churn, ARPU, expansion.", "MRR, churn, ARPU, expansion.",
          "Revue mensuelle direction.", "Monthly leadership review.",
          "DollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("mois", "str", "Mois", "Month"),
           F("mrr_xaf", "num", "MRR XAF", "MRR XAF"),
           F("churn_mrr_xaf", "num", "Churn MRR", "Churn MRR"),
           F("expansion_mrr_xaf", "num", "Expansion MRR", "Expansion MRR"),
           F("arpu_xaf", "num", "ARPU", "ARPU"),
           F("nb_customers", "int", "Nb clients", "Customer count")], []),
        E("system-config", "global_config_settings", "GlobalConfigSetting", "global-config-settings", "system_config",
          "Configuration systeme globale", "Global system configuration",
          "Parametres transverses plateforme.", "Cross-platform settings.",
          "4-yeyes obligatoire.", "Four-eyes mandatory.",
          "Settings", "code_setting",
          [F("code_setting", "str", "Code setting", "Setting code", required=True, search=True),
           F("valeur", "text", "Valeur", "Value"),
           F("categorie", "enum", "Categorie", "Category"),
           F("description", "text", "Description", "Description"),
           F("modifie_par", "str", "Modifie par", "Modified by"),
           F("date_modif", "datetime", "Date modif", "Modification date"),
           F("statut", "enum", "Statut", "Status")],
          [EN("categorie", ["SECURITE", "METIER", "TECHNIQUE", "CONFORMITE"], "TECHNIQUE"),
           EN("statut", ["ACTIF", "PENDING", "REJETE"], "ACTIF")]),
        E("disaster-recovery", "dr_plans", "DrPlan", "dr-plans", "disaster_recovery",
          "Plan reprise activite", "Business continuity plan",
          "Scenario, RTO, RPO.", "Scenario, RTO, RPO.",
          "Test annuel obligatoire.", "Annual test mandatory.",
          "LifeBuoy", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("scenario", "enum", "Scenario", "Scenario"),
           F("rto_heures", "num", "RTO (h)", "RTO (h)"),
           F("rpo_minutes", "num", "RPO (min)", "RPO (min)"),
           F("solution_secours", "text", "Solution secours", "Failover solution"),
           F("date_dernier_test", "date", "Dernier test", "Last test"),
           F("resultat_test", "enum", "Resultat test", "Test result")],
          [EN("scenario", ["PANNE_DATA_CENTER", "CYBERATTAQUE", "CATASTROPHE_NATURELLE", "ERREUR_HUMAINE"], "PANNE_DATA_CENTER"),
           EN("resultat_test", ["SUCCES", "PARTIEL", "ECHEC"], "SUCCES")]),
    ],
)

# ─── dashboard ──────────────────────────────────────────────────────────────
MODULES["dashboard"] = dict(
    module_key="dashboard", module_slug="dashboard", module_path="dashboard",
    perm_module="dashboard", revision="060", down_revision="059_superadmin_deep",
    entities=[
        E("module-health", "module_healths", "ModuleHealth", "module-healths", "module_health",
          "Sante fonctionnelle des modules", "Module functional health",
          "Etat de marche par module.", "Working state per module.",
          "Refresh toutes les 15 min.", "Refresh every 15 min.",
          "HeartPulse", "code_module",
          [F("code_module", "str", "Code module", "Module code", required=True, search=True),
           F("etat", "enum", "Etat", "State"),
           F("nombre_requetes_jour", "int", "Nb requetes / jour", "Daily calls"),
           F("taux_erreur_pct", "num", "Taux erreur %", "Error rate %"),
           F("latence_p95_ms", "int", "Latence p95 (ms)", "Latency p95 (ms)"),
           F("dernier_incident", "datetime", "Dernier incident", "Last incident")],
          [EN("etat", ["OPERATIONNEL", "DEGRADE", "HORS_SERVICE"], "OPERATIONNEL")]),
        E("activity-feed", "activity_records", "ActivityRecord", "activity-records", "activity_feed",
          "Flux d'activite recent", "Recent activity feed",
          "Timeline multi-module.", "Cross-module timeline.",
          "Visible seulement par utilisateur concerne.", "Only visible to concerned user.",
          "History", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("module_source", "str", "Module source", "Source module"),
           F("type_action", "str", "Type action", "Action type"),
           F("utilisateur", "str", "Utilisateur", "User"),
           F("entite", "str", "Entite", "Entity"),
           F("horodatage", "datetime", "Horodatage", "Timestamp"),
           F("resume", "text", "Resume", "Summary")], []),
        E("task-center", "unified_tasks", "UnifiedTask", "unified-tasks", "task_center",
          "Centre de taches / to-do unifie", "Unified task center",
          "Taches transverses par utilisateur.", "Cross-module tasks per user.",
          "Chaque tache pointe vers objet metier.", "Each task points to a business object.",
          "CheckSquare", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("module_source", "str", "Module source", "Source module"),
           F("entite_id", "int", "ID entite", "Entity id"),
           F("assigne_a", "int", "Assigne a", "Assigned to"),
           F("date_echeance", "datetime", "Echeance", "Due date"),
           F("priorite", "enum", "Priorite", "Priority"),
           F("statut", "enum", "Statut", "Status")],
          [EN("priorite", ["BASSE", "NORMALE", "HAUTE", "URGENTE"], "NORMALE"),
           EN("statut", ["A_FAIRE", "EN_COURS", "FAIT", "ANNULEE"], "A_FAIRE")]),
        E("quick-actions", "quick_actions", "QuickAction", "quick-actions", "quick_actions",
          "Raccourcis operationnels config.", "Configurable operational shortcuts",
          "Actions favorites lancees depuis dashboard.", "Favorite actions from dashboard.",
          "Par user.", "Per user.",
          "Zap", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("libelle", "str", "Libelle", "Label"),
           F("module_source", "str", "Module source", "Source module"),
           F("url_action", "str", "URL action", "Action URL"),
           F("utilisateur_id", "int", "Utilisateur", "User"),
           F("ordre", "int", "Ordre", "Order"),
           F("actif", "bool", "Actif", "Active")], []),
        E("team-performance", "team_performances", "TeamPerformance", "team-performances", "team_performance",
          "Performance et productivite equipes", "Team performance and productivity",
          "KPI collectifs par equipe.", "Team KPIs.",
          "Revu par manager N+1.", "Reviewed by N+1 manager.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("equipe", "str", "Equipe", "Team"),
           F("periode", "str", "Periode", "Period"),
           F("objectifs_atteints_pct", "num", "Objectifs atteints %", "Goals reached %"),
           F("volume_traite", "num", "Volume traite", "Processed volume"),
           F("qualite_score", "num", "Score qualite", "Quality score")], []),
        E("financial-summary", "financial_summaries", "FinancialSummary", "financial-summaries", "financial_summary",
          "Synthese financiere consolidee", "Consolidated financial summary",
          "CA, marge, BFR, tresorerie.", "Revenue, margin, WC, cash.",
          "Update mensuelle.", "Monthly update.",
          "CircleDollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("periode", "str", "Periode", "Period"),
           F("ca_consolide_xaf", "num", "CA consolide", "Consolidated revenue"),
           F("marge_brute_xaf", "num", "Marge brute", "Gross margin"),
           F("ebitda_xaf", "num", "EBITDA", "EBITDA"),
           F("bfr_xaf", "num", "BFR", "Working capital"),
           F("tresorerie_xaf", "num", "Tresorerie", "Cash")], []),
        E("operational-alerts", "operational_alerts", "OperationalAlert", "operational-alerts", "operational_alerts",
          "Alertes operationnelles croisees", "Cross-operational alerts",
          "Signaux critiques multi-modules.", "Cross-module critical signals.",
          "Escalade hierarchique automatique.", "Automatic hierarchical escalation.",
          "AlertOctagon", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("module_source", "str", "Module source", "Source module"),
           F("niveau", "enum", "Niveau", "Level"),
           F("description", "text", "Description", "Description"),
           F("date_alerte", "datetime", "Date", "Date"),
           F("destinataire", "str", "Destinataire", "Recipient"),
           F("statut", "enum", "Statut", "Status")],
          [EN("niveau", ["INFO", "WARNING", "CRITIQUE"], "WARNING"),
           EN("statut", ["OUVERTE", "PRISE_EN_CHARGE", "RESOLUE"], "OUVERTE")]),
        E("document-center", "recent_documents", "RecentDocument", "recent-documents", "document_center",
          "Centre documents recents / partages", "Recent and shared documents",
          "Documents accessibles par utilisateur.", "User-accessible documents.",
          "Permission heritee de la ligne metier.", "Inherited permission from business line.",
          "FolderOpen", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("module_source", "str", "Module source", "Source module"),
           F("entite_id", "int", "ID entite", "Entity id"),
           F("url", "str", "URL", "URL"),
           F("date_creation", "datetime", "Creation", "Creation"),
           F("partage", "enum", "Partage", "Sharing")],
          [EN("partage", ["PRIVE", "EQUIPE", "TENANT", "PUBLIC"], "PRIVE")]),
        E("calendar-agenda", "unified_agenda", "UnifiedAgenda", "unified-agenda", "calendar_agenda",
          "Agenda consolide multi-module", "Cross-module consolidated agenda",
          "Rendez-vous, echeances, evenements.", "Meetings, deadlines, events.",
          "Export ICS disponible.", "ICS export available.",
          "Calendar", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("module_source", "str", "Module source", "Source module"),
           F("entite_id", "int", "ID entite", "Entity id"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("invite_par", "str", "Invite par", "Invited by")], []),
        E("integration-status", "integration_statuses", "IntegrationStatus", "integration-statuses", "integration_status",
          "Etat integrations externes", "External integrations status",
          "Sonde etat des APIs tierces.", "Probe third-party APIs.",
          "Alerte si 3 echecs consecutifs.", "Alert if 3 consecutive failures.",
          "Link2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("nom_integration", "str", "Nom integration", "Integration name"),
           F("url_testee", "str", "URL testee", "Tested URL"),
           F("date_dernier_test", "datetime", "Dernier test", "Last test"),
           F("succes", "bool", "Succes", "Success"),
           F("latence_ms", "int", "Latence (ms)", "Latency (ms)"),
           F("message_erreur", "text", "Message erreur", "Error message")], []),
    ],
)

# ─── amenagement-portuaire (8 additions) ────────────────────────────────────
MODULES["amenagement_extra"] = dict(
    module_key="amenagement_extra", module_slug="amenagement-portuaire", module_path="amenagement-portuaire",
    perm_module="amenagement", revision="061", down_revision="060_dashboard_deep",
    registre_filename="registres_expansion",
    entities=[
        E("construction-tracking", "construction_progress", "ConstructionProgress", "construction-progresses", "construction_tracking",
          "Suivi avancement physique travaux", "Physical construction progress",
          "Pourcentages d'avancement par lot.", "Progress % per lot.",
          "Photo obligatoire a chaque mise a jour.", "Photo required at each update.",
          "Building2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("marche_id", "int", "Marche", "Contract"),
           F("lot", "str", "Lot", "Lot"),
           F("avancement_pct", "num", "Avancement %", "Progress %"),
           F("date_releve", "date", "Releve", "Observation date"),
           F("surface_m2", "num", "Surface m2", "Surface m2"),
           F("observateur", "str", "Observateur", "Observer")], []),
        E("infrastructure-maintenance", "infrastructure_maintenances", "InfrastructureMaintenance", "infrastructure-maintenances", "infrastructure_maintenance",
          "Maintenance preventive ouvrages", "Preventive infrastructure maintenance",
          "Plan de maintenance des ouvrages.", "Maintenance plan for structures.",
          "Conforme aux regles portuaires.", "Compliant with port rules.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ouvrage_id", "int", "Ouvrage", "Structure"),
           F("type_intervention", "enum", "Type intervention", "Intervention type"),
           F("frequence_mois", "int", "Frequence (mois)", "Frequency (months)"),
           F("date_prochaine", "date", "Prochaine", "Next"),
           F("cout_estime_xaf", "num", "Cout estime", "Estimated cost"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_intervention", ["PEINTURE", "ETANCHEITE", "CHARPENTE", "ELECTRIQUE", "HYDRAULIQUE"], "PEINTURE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "FAITE", "RETARDE"], "PLANIFIE")]),
        E("port-security-isps", "isps_records", "IspsRecord", "isps-records", "port_security_isps",
          "Surete ISPS (distinct QHSE)", "ISPS security (distinct from QHSE)",
          "Niveaux de surete, exercices ISPS.", "Security levels, ISPS drills.",
          "PV obligatoire.", "Mandatory minutes.",
          "ShieldAlert", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("niveau_isps", "enum", "Niveau ISPS", "ISPS level"),
           F("date_application", "datetime", "Application", "Applied date"),
           F("motif", "text", "Motif", "Reason"),
           F("authorite_emetteuse", "str", "Autorite emetteuse", "Issuing authority"),
           F("date_levee", "datetime", "Levee", "Lift date")],
          [EN("niveau_isps", ["N1", "N2", "N3"], "N1")]),
        E("port-pricing", "port_perceptions", "PortPerception", "port-perceptions", "port_pricing",
          "Redevances et perceptions portuaires", "Port fees and perceptions",
          "Grille tarifaire du domaine portuaire.", "Port fee grid.",
          "Validee par arrete ministeriel.", "Approved by ministerial decree.",
          "Calculator", "code_perception",
          [F("code_perception", "str", "Code", "Code", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("type_perception", "enum", "Type", "Type"),
           F("base_calcul", "str", "Base calcul", "Calculation base"),
           F("tarif_xaf", "num", "Tarif XAF", "Fee XAF"),
           F("unite", "str", "Unite", "Unit"),
           F("arrete_reference", "str", "Arrete", "Decree ref"),
           F("date_application", "date", "Application", "Application date")],
          [EN("type_perception", ["TONNAGE", "OCCUPATION_QUAI", "MANUTENTION", "PILOTAGE", "SALETE"], "TONNAGE")]),
        E("activity-report", "annual_activity_reports", "AnnualActivityReport", "annual-activity-reports", "activity_report",
          "Rapport d'activite annuel", "Annual activity report",
          "Bilan annuel portuaire.", "Annual port summary.",
          "Approuve par conseil d'administration.", "Board approved.",
          "FileBarChart2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("annee", "int", "Annee", "Year"),
           F("tonnage_traite_t", "num", "Tonnage traite (t)", "Tonnage handled (t)"),
           F("nb_escales", "int", "Nb escales", "Call count"),
           F("nb_conteneurs_evp", "int", "EVP", "TEU"),
           F("recettes_xaf", "num", "Recettes XAF", "Revenue XAF"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "SOUMIS", "APPROUVE", "PUBLIE"], "BROUILLON")]),
        E("domain-cartography", "sig_layers", "SigLayer", "sig-layers", "domain_cartography",
          "SIG / cartographie domaine", "Port GIS / cartography",
          "Couches SIG du domaine.", "Port GIS layers.",
          "Refonte tous les 5 ans.", "Refresh every 5 years.",
          "Map", "code_couche",
          [F("code_couche", "str", "Code couche", "Layer code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("type_couche", "enum", "Type couche", "Layer type"),
           F("projection", "str", "Projection", "Projection"),
           F("date_maj", "date", "Derniere MAJ", "Last update"),
           F("superficie_ha", "num", "Superficie (ha)", "Area (ha)")],
          [EN("type_couche", ["FONCIER", "BATI", "HYDRO", "VOIRIE", "RESEAU"], "FONCIER")]),
        E("archive-management", "domain_archives", "DomainArchive", "domain-archives", "archive_management",
          "Archivage pieces domaniales", "Domain paper archive",
          "Inventaire archives domaniales.", "Domain archive inventory.",
          "Duree conservation reglementaire.", "Regulatory retention period.",
          "Archive", "cote_archive",
          [F("cote_archive", "str", "Cote archive", "Archive ref", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("type_piece", "enum", "Type piece", "Document type"),
           F("periode_couverte", "str", "Periode", "Period covered"),
           F("localisation", "str", "Localisation", "Location"),
           F("duree_conservation_an", "int", "Duree conservation (an)", "Retention (y)"),
           F("statut", "enum", "Statut", "Status")],
          [EN("type_piece", ["TITRE_PROPRIETE", "ARRETE", "CONVENTION", "PLAN", "RAPPORT"], "ARRETE"),
           EN("statut", ["ACTIF", "ARCHIVE_INTERMEDIAIRE", "DEFINITIF"], "ACTIF")]),
        E("development-kpi", "amenagement_kpis", "AmenagementKpi", "amenagement-kpis", "development_kpi",
          "Tableau bord indicateurs amenagement", "Amenagement KPI dashboard",
          "Suivi des indicateurs amenagement.", "Track development KPIs.",
          "Revue trimestrielle direction technique.", "Quarterly review.",
          "Gauge", "code_kpi",
          [F("code_kpi", "str", "Code KPI", "KPI code", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("periode", "str", "Periode", "Period"),
           F("valeur", "num", "Valeur", "Value"),
           F("objectif", "num", "Objectif", "Target"),
           F("ecart_pct", "num", "Ecart %", "Gap %"),
           F("statut", "enum", "Statut", "Status")],
          [EN("statut", ["EN_DESSOUS", "CONFORME", "EN_AVANCE"], "CONFORME")]),
    ],
)
