"""Manifest Wave 4 : modules de transport multimodal.

Deux nouveaux modules couvrant les modes ferroviaire et aerien, avec 12 sous-modules
chacun, alignes sur le patron declaratif des vagues precedentes.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── transport-ferroviaire ─────────────────────────────────────────────────
MODULES["ferroviaire"] = dict(
    module_key="ferroviaire", module_slug="transport-ferroviaire",
    module_path="transport-ferroviaire", perm_module="ferroviaire",
    revision="062", down_revision="061_amenagement_extra_deep",
    entities=[
        E("wagon-fleet", "rail_wagons", "RailWagon", "rail-wagons", "wagon_fleet",
          "Parc wagons", "Rail wagon fleet",
          "Referentiel des wagons du parc fret (couvert, tombereau, citerne, plateau, porte-conteneurs).",
          "Fleet register of freight wagons (box, gondola, tank, flat, container).",
          "Revision periodique par type selon reglementation UIC.", "Periodic overhaul per UIC rules.",
          "TrainFront", "numeration_wagon",
          [F("numeration_wagon", "str", "Numeration UIC", "UIC number", required=True, search=True),
           F("type_wagon", "str", "Type", "Type"),
           F("capacite_tonnes", "int", "Capacite (t)", "Capacity (t)"),
           F("livree", "str", "Livree proprietaire", "Owner livery"),
           F("date_mise_circulation", "date", "Mise en circulation", "In-service date"),
           F("prochaine_revision", "date", "Prochaine revision", "Next overhaul"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CIRCULANT", "ATELIER", "REFORME", "IMMOBILISE"], "CIRCULANT")]),

        E("locomotive-fleet", "rail_locomotives", "RailLocomotive", "rail-locomotives", "locomotive_fleet",
          "Parc locomotives", "Locomotive fleet",
          "Locomotives electriques, diesels et rames automotrices.",
          "Electric, diesel and EMU fleet.",
          "Kilometrage decisive pour plan de maintenance.", "Mileage drives maintenance plan.",
          "TrainTrack", "numero_series",
          [F("numero_series", "str", "Numero de serie", "Series number", required=True, search=True),
           F("modele", "str", "Modele", "Model"),
           F("type_energie", "str", "Energie", "Energy"),
           F("puissance_kw", "int", "Puissance (kW)", "Power (kW)"),
           F("vitesse_max_kmh", "int", "Vitesse max (km/h)", "Max speed"),
           F("kilometrage_actuel", "int", "Kilometrage", "Mileage"),
           F("prochaine_revision_km", "int", "Revision prochaine (km)", "Next overhaul (km)"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_energie", ["ELECTRIQUE", "DIESEL", "BI_MODE", "HYBRIDE"], "DIESEL"),
           EN("statut", ["OPERATIONNELLE", "MAINTENANCE", "PANNE", "STOREE"], "OPERATIONNELLE")]),

        E("train-paths", "rail_train_paths", "RailTrainPath", "rail-train-paths", "train_paths",
          "Sillons de circulation", "Train paths",
          "Graphique des sillons attribues par le gestionnaire d'infrastructure.",
          "Path allocation by infrastructure manager.",
          "Sillon non consomme = penalite GI.", "Unused path = IM penalty.",
          "CalendarClock", "code_sillon",
          [F("code_sillon", "str", "Code sillon", "Path code", required=True, search=True),
           F("gare_origine", "str", "Gare origine", "Origin station"),
           F("gare_destination", "str", "Gare destination", "Destination station"),
           F("date_circulation", "date", "Date", "Date"),
           F("heure_depart", "str", "Heure depart", "Departure time"),
           F("heure_arrivee", "str", "Heure arrivee", "Arrival time"),
           F("numero_train", "str", "Numero train", "Train number"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ATTRIBUE", "CIRCULE", "SUPPRIME", "RETARDE"], "ATTRIBUE")]),

        E("shunting-yards", "rail_shunting_yards", "RailShuntingYard", "rail-shunting-yards", "shunting_yards",
          "Gares de triage", "Shunting yards",
          "Installations de tri et de formation des rames.",
          "Classification and marshalling installations.",
          "Suivi occupation voies de tri.", "Track occupation tracking.",
          "Layers", "code_triage",
          [F("code_triage", "str", "Code", "Code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("localisation", "str", "Localisation", "Location"),
           F("nb_voies_tri", "int", "Nb voies de tri", "Classification tracks"),
           F("nb_voies_parc", "int", "Nb voies parc", "Storage tracks"),
           F("capacite_journee_wagons", "int", "Capacite wagons/jour", "Wagons per day"),
           F("taux_occupation_pct", "int", "Taux occupation (%)", "Occupancy (%)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OPERATIONNEL", "SATURE", "MAINTENANCE", "FERME"], "OPERATIONNEL")]),

        E("rail-terminals", "rail_terminals", "RailTerminal", "rail-terminals", "rail_terminals",
          "Terminaux fer portuaires", "Port rail terminals",
          "Interfaces terminal portuaire / reseau fer (relic modal).",
          "Port-rail interface for modal shift.",
          "Tracabilite du transfert container train / navire.", "Container train/vessel traceability.",
          "Container", "code_terminal",
          [F("code_terminal", "str", "Code terminal", "Terminal code", required=True, search=True),
           F("port_associe", "str", "Port associe", "Associated port"),
           F("nb_voies_fond", "int", "Nb voies a quai", "Quay tracks"),
           F("longueur_quai_m", "int", "Longueur quai (m)", "Quay length (m)"),
           F("equipement_manutention", "str", "Equipement manutention", "Lifting equipment"),
           F("debit_conteneur_h", "int", "Debit (TEU/h)", "Throughput (TEU/h)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "SATURATION", "TRAVAUX", "FERME"], "ACTIF")]),

        E("consistency-plans", "rail_consistency_plans", "RailConsistencyPlan", "rail-consistency-plans", "consistency",
          "Plans de composition", "Train composition plans",
          "Description de la composition theorique d'un train (ordre, masse, longueur).",
          "Theoretical composition per train (order, mass, length).",
          "Limite longueur quai et effort traction.", "Constrained by quay length and traction effort.",
          "ListOrdered", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("code_sillon", "str", "Code sillon", "Path code"),
           F("type_train", "str", "Type train", "Train type"),
           F("nb_wagons", "int", "Nombre wagons", "Wagons count"),
           F("masse_totale_tonnes", "int", "Masse totale (t)", "Total mass (t)"),
           F("longueur_totale_m", "int", "Longueur (m)", "Length (m)"),
           F("locomotive_atteltee", "str", "Locomotive", "Locomotive"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_train", ["FRET_COMPLET", "CONTENEURS", "VRAC_LIQUIDE", "INTERMODAL", "MATERIEL"], "FRET_COMPLET"),
           EN("statut", ["PLANIFIE", "COMPOSE", "PARTI", "ANNULE"], "PLANIFIE")]),

        E("waybills-rail", "rail_waybills", "RailWaybill", "rail-waybills", "waybills",
          "Lettres de voiture CIM/OTIF", "CIM/OTIF waybills",
          "Titres de transport fer internationaux (CIM) ou nationaux.",
          "CIM or domestic rail consignment notes.",
          "Cublie obligatoire pour tout chargement.", "Mandatory for every wagon loading.",
          "FileText", "numero_lcv",
          [F("numero_lcv", "str", "Numero LCV", "Waybill number", required=True, search=True),
           F("expediteur", "str", "Expediteur", "Sender"),
           F("destinataire", "str", "Destinataire", "Consignee"),
           F("gare_depart", "str", "Gare depart", "Origin station"),
           F("gare_arrivee", "str", "Gare arrivee", "Destination station"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("valeur_marchandise_xaf", "int", "Valeur marchandise", "Goods value"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMISE", "CHARGEE", "TRANSIT", "LIVREE", "LITIGE"], "EMISE")]),

        E("rail-tariffs", "rail_tariffs", "RailTariff", "rail-tariffs", "tariffs",
          "Tarification fret fer", "Rail freight tariffs",
          "Grille tarifaire par relation, type marchandise et tonnage.",
          "Tariff grid by relation, commodity and tonnage.",
          "Source UIC/OTIF + remises contractuelles.", "UIC/OTIF source with contract discounts.",
          "Calculator", "code_tarif",
          [F("code_tarif", "str", "Code tarif", "Tariff code", required=True, search=True),
           F("relation", "str", "Relation", "Route"),
           F("type_marchandise", "str", "Type marchandise", "Commodity"),
           F("prix_par_tonne_km_xaf", "int", "Prix (XAF/t.km)", "Price (XAF/t.km)"),
           F("remise_volume_pct", "int", "Remise volume (%)", "Volume discount (%)"),
           F("date_debut_validite", "date", "Debut validite", "Valid from"),
           F("date_fin_validite", "date", "Fin validite", "Valid until"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "BROUILLON", "EXPIRE", "GELE"], "ACTIF")]),

        E("wagon-tracking", "rail_wagon_tracking", "RailWagonTracking", "rail-wagon-tracking", "tracking",
          "Suivi wagons / telegrammes RID", "Wagon tracking / RID telegrams",
          "Position et etat de chaque wagon en temps reel via CID/TELEGRAMMES.",
          "Real-time wagon position via CID/RID telegrams.",
          "Retrecage wagons critiques (matieres dangereuses).", "Narrowing for dangerous goods.",
          "MapPin", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("numeration_wagon", "str", "Numeration wagon", "Wagon number"),
           F("code_lcv", "str", "Code LCV", "Waybill code"),
           F("gare_actuelle", "str", "Gare actuelle", "Current station"),
           F("date_position", "datetime", "Horodatage position", "Position timestamp"),
           F("evenement", "str", "Evenement", "Event"),
           F("geolocalisation_gps", "str", "GPS", "GPS"),
           F("statut", "str", "Statut", "Status")],
          [EN("evenement", ["DEPART", "ARRIVEE", "TRANSIT", "CHARGEMENT", "DECHARGEMENT", "IMMO"], "TRANSIT"),
           EN("statut", ["EN_ROUTE", "EN_GARE", "LIVRE", "BLOQUE", "PERDU"], "EN_ROUTE")]),

        E("wagon-maintenance", "rail_wagon_maintenance", "RailWagonMaintenance", "rail-wagon-maintenance", "maintenance",
          "Maintenance parc wagon", "Wagon maintenance",
          "Ateliers, revisions periodiques et immobilisations techniques.",
          "Workshops, periodic overhauls and technical holds.",
          "Revision decennale obligatoire (UIC 541).", "Mandatory decennial overhaul (UIC 541).",
          "Wrench", "reference",
          [F("reference", "str", "Reference ordre", "Work order reference", required=True, search=True),
           F("numeration_wagon", "str", "Wagon concerne", "Wagon number"),
           F("atelier", "str", "Atelier", "Workshop"),
           F("type_intervention", "str", "Type intervention", "Intervention type"),
           F("date_debut", "date", "Date debut", "Start date"),
           F("date_fin_prevue", "date", "Fin prevue", "Planned end"),
           F("date_retour_service", "date", "Retour service", "Return to service"),
           F("cout_xaf", "int", "Cout", "Cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_intervention", ["REVISION_LEGERE", "REVISION_LOURDE", "REPARATION", "CONTROLE_TECHNIQUE", "PEINTURE"], "REVISION_LEGERE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "SURSEAN", "REFORME"], "PLANIFIE")]),

        E("rail-safety", "rail_safety_records", "RailSafetyRecord", "rail-safety-records", "safety",
          "Securite circulations", "Circulation safety",
          "ETCS / signalisation / incidents securite ferroviaire.",
          "ETCS, signalling and safety incidents.",
          "Rapport obligatoire EPSF dans les 24h pour incident grave.", "Mandatory EPSF report within 24h for serious incidents.",
          "ShieldAlert", "reference",
          [F("reference", "str", "Reference rapport", "Report reference", required=True, search=True),
           F("date_evenement", "datetime", "Date evenement", "Event date"),
           F("type_incident", "str", "Type incident", "Incident type"),
           F("gravite", "str", "Gravite", "Severity"),
           F("lgn_concernee", "str", "Ligne concernee", "Line involved"),
           F("wagon_train_implique", "str", "Wagon/train implique", "Wagon/train involved"),
           F("description", "text", "Description", "Description"),
           F("mesure_correctrice", "text", "Mesure corrective", "Corrective measure"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_incident", ["AUCUN", "SIGNALEMENT", "FREIN_dURGENCE", "DERAILLEMENT", "COLLISION", "MARQUAGE_DANGER"], "SIGNALEMENT"),
           EN("gravite", ["NEANT", "MINEURE", "MAJEURE", "CRITIQUE"], "MINEURE"),
           EN("statut", ["OUVERT", "ENQUETE", "CLOTURE", "TRANSFERT_JUSTICE"], "OUVERT")]),

        E("intermodal-corridors", "rail_corridors", "RailCorridor", "rail-corridors", "corridors",
          "Corridors fer-port", "Rail-port corridors",
          "Cartographie des corridors logistiques (Dorsal, Abidjan-Lagos, Douane Yaounde-Douala).",
          "Map of logistics corridors (Dorsal, Abidjan-Lagos, Yaounde-Douala customs).",
          "Coordination multi-operateurs / RFF.", "Multi-operator / rail-infrastructure coordination.",
          "Route", "code_corridor",
          [F("code_corridor", "str", "Code corridor", "Corridor code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("pays_traverses", "str", "Pays traverses", "Countries"),
           F("longueur_km", "int", "Longueur (km)", "Length (km)"),
           F("gares_focales", "text", "Gares focales", "Hub stations"),
           F("operateurs", "text", "Operateurs", "Operators"),
           F("debit_annuel_teu", "int", "Debit annuel TEU", "Annual TEU"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "OPERATIONNEL", "EXTENSION", "ABANDONNE"], "OPERATIONNEL")]),
    ],
)


# ─── transport-aerien ─────────────────────────────────────────────────────
MODULES["aerien"] = dict(
    module_key="aerien", module_slug="transport-aerien",
    module_path="transport-aerien", perm_module="aerien",
    revision="063", down_revision="062_ferroviaire_deep",
    entities=[
        E("aircraft-fleet", "air_aircraft", "Aircraft", "air-aircraft", "fleet",
          "Flotte aeronefs", "Aircraft fleet",
          "Avions cargo, passagers et mixtes.",
          "Cargo, passenger and combi aircraft.",
          "Navigabilite = certificat + checks a jour.", "Airworthiness = certificate + up-to-date checks.",
          "Plane", "immatriculation",
          [F("immatriculation", "str", "Immatriculation", "Registration", required=True, search=True),
           F("modele", "str", "Modele", "Model"),
           F("operateur", "str", "Operateur", "Operator"),
           F("capacite_tonnes", "int", "Capacite (t)", "Payload (t)"),
           F("autonomie_km", "int", "Autonomie (km)", "Range (km)"),
           F("heures_vol_total", "int", "Heures vol totales", "Total flight hours"),
           F("certificat_navigabilite_fin", "date", "Fin CofA", "CofA expiry"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OPERATIONNEL", "MAINTENANCE", "STORE", "MISE_A_L_ECHANGE", "REFORME"], "OPERATIONNEL")]),

        E("air-waybills", "air_waybills", "AirWaybill", "air-waybills", "awb",
          "Lia / lettres de transport aerien", "Air waybills",
          "AWB maitre (MAWB) et secondaire (HAWB).",
          "Master (MAWB) and house (HAWB) air waybills.",
          "Format IATA 3 chiffres + 8 chiffres + check digit.", "IATA 3-8-1 digit format.",
          "FileSignature", "numero_awb",
          [F("numero_awb", "str", "Numero AWB", "AWB number", required=True, search=True),
           F("type_awb", "str", "Type AWB", "AWB type"),
           F("expediteur", "str", "Expediteur", "Shipper"),
           F("destinataire", "str", "Destinataire", "Consignee"),
           F("aeroport_depart", "str", "Aeroport depart", "Departure airport"),
           F("aeroport_arrivee", "str", "Aeroport arrivee", "Arrival airport"),
           F("nb_pieces", "int", "Nombre de colis", "Pieces"),
           F("poids_kg", "int", "Poids (kg)", "Weight (kg)"),
           F("valeur_declaree_xaf", "int", "Valeur declaree", "Declared value"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_awb", ["MAWB", "HAWB"], "MAWB"),
           EN("statut", ["EMISE", "EN_VOL", "ARRIVEE", "LIVREE", "BLOQUEE", "LITIGE"], "EMISE")]),

        E("slots-coordination", "air_slots", "AirSlot", "air-slots", "slots",
          "Creneaux aeroportuaires", "Airport slots",
          "Coordination IATA (BABY) des creneaux decollage/atterrissage.",
          "IATA (BABY) slot coordination for take-off/landing.",
          "Regle 80/20 : sous peine perte historique.", "Use-it-or-lose-it 80/20 rule.",
          "Clock", "reference",
          [F("reference", "str", "Reference slot", "Slot reference", required=True, search=True),
           F("aeroport", "str", "Aeroport", "Airport"),
           F("season", "str", "Season IATA", "Season"),
           F("vol_attribue", "str", "Vol attribue", "Flight assigned"),
           F("journee", "str", "Journee", "Weekday"),
           F("heure_obtc", "str", "Heure OBT/C", "OBT/C time"),
           F("slot_historique", "bool", "Slot historique", "Grandfathered"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ATTRIBUE", "RETOURNE", "CONTESTE", "PERTE_HISTORIQUE", "TEMPORAIRE"], "ATTRIBUE")]),

        E("ground-handling", "air_handling_jobs", "GroundHandlingJob", "air-handling-jobs", "handling",
          "Traitement au sol", "Ground handling",
          "Prestations au sol : passagers, fret, chargement, ravitaillement.",
          "Ground services: pax, cargo, load, fuelling.",
          "Facture IH / GH aux compagnies.", "Handling invoice per flight.",
          "Package", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vol", "str", "Numero vol", "Flight number"),
           F("aeroport", "str", "Aeroport", "Airport"),
           F("date_traitement", "datetime", "Date", "Date"),
           F("prestataire", "str", "Prestataire", "Handler"),
           F("nb_pieces_fret", "int", "Pieces fret", "Cargo pieces"),
           F("poids_fret_kg", "int", "Poids fret (kg)", "Cargo weight"),
           F("cout_xaf", "int", "Cout", "Cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "RETARDE", "ANNULE"], "PLANIFIE")]),

        E("uld-management", "air_uld", "ULDInventory", "air-uld-inventory", "uld",
          "Parc ULD", "ULD inventory",
          "Conteneurs et palettes aerienes (AKE, PAG, PMC).",
          "Air containers and pallets (AKE, PAG, PMC).",
          "Tracabilite par numero unique IATA.", "Unique IATA number tracking.",
          "Boxes", "numero_uld",
          [F("numero_uld", "str", "Numero ULD", "ULD number", required=True, search=True),
           F("type_uld", "str", "Type ULD", "ULD type"),
           F("proprietaire", "str", "Proprietaire", "Owner"),
           F("position_actuelle", "str", "Position actuelle", "Current location"),
           F("etat", "str", "Etat", "Condition"),
           F("date_derniere_inspection", "date", "Derniere inspection", "Last inspection"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_uld", ["AKE", "AKH", "ALA", "PMC", "PAG", "PLA", "DKE", "OTHER"], "AKE"),
           EN("etat", ["BON", "MOYEN", "REPARER", "REFORME"], "BON"),
           EN("statut", ["DISPONIBLE", "EN_SERVICE", "EN_TRANSIT", "PERDU", "ENDOMMAGE"], "DISPONIBLE")]),

        E("cargo-security", "air_cargo_security", "CargoSecurityScreen", "air-cargo-security-screens", "security",
          "Sûreté fret arien", "Air cargo security",
          "Screening RC/AC/KC selon reglement (RA, KC, AC statuses).",
          "Screening per regulated agent / known consignor statuses.",
          "Aucun chargement sans chaine surete complete.", "No loading without complete security chain.",
          "ScanLine", "reference",
          [F("reference", "str", "Reference screening", "Screening reference", required=True, search=True),
           F("numero_awb", "str", "Numero AWB", "AWB number"),
           F("statut_expediteur", "str", "Statut expediteur", "Consignor status"),
           F("methode_screening", "str", "Methode screening", "Screening method"),
           F("date_screening", "datetime", "Date screening", "Screening date"),
           F("operateur", "str", "Operateur", "Operator"),
           F("resultat", "str", "Resultat", "Result"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut_expediteur", ["RA", "KC", "AC", "UNKNOWN"], "UNKNOWN"),
           EN("methode_screening", ["RX", "EXP", "ETD", "CHIMIQUE", "VISUEL", "BIEN_DETECTEUR"], "RX"),
           EN("resultat", ["CLAIR", "SUSPECT", "SAISISSEMENT"], "CLAIR"),
           EN("statut", ["EN_ATTENTE", "VALIDE", "REJETE", "ESCALADE"], "VALIDE")]),

        E("dangerous-goods-air", "air_dg_shipments", "AirDangerousGoods", "air-dangerous-goods", "dgr",
          "Marchandises dangereuses IATA", "IATA dangerous goods",
          "DGD / etiquette / classe ONU conforme IATA DGR.",
          "IATA DGD / labels / UN class.",
          "Formation DGR recurrente tous les 2 ans.", "DGR training every 2 years.",
          "AlertOctagon", "reference",
          [F("reference", "str", "Reference DGD", "DGD reference", required=True, search=True),
           F("numero_awb", "str", "AWB lie", "Linked AWB"),
           F("un_number", "str", "Numero ONU", "UN number"),
           F("classe", "str", "Classe IATA", "Class"),
           F("packaging_group", "str", "Groupe emballage", "Packing group"),
           F("quantite", "str", "Quantite", "Quantity"),
           F("etiquettes", "str", "Etiquettes", "Labels"),
           F("statut", "str", "Statut", "Status")],
          [EN("classe", ["1", "2", "3", "4", "5", "6", "7", "8", "9"], "3"),
           EN("packaging_group", ["I", "II", "III", "N/A"], "III"),
           EN("statut", ["DECLARER", "ACCEPTE", "REFUSE", "TRANSFERT"], "DECLARER")]),

        E("flight-ops", "air_flight_operations", "FlightOperation", "air-flight-operations", "flightops",
          "Operations vol", "Flight operations",
          "Plans de vol, NOTAM, METAR, reserves equipage.",
          "Flight plans, NOTAM, METAR, crew reserves.",
          "Decision OPE engage la responsabilite commandant.", "OPE decision binds pilot-in-command.",
          "PlaneTakeoff", "reference",
          [F("reference", "str", "Reference OPE", "OPE reference", required=True, search=True),
           F("numero_vol", "str", "Numero vol", "Flight number"),
           F("aeronef", "str", "Aeronef", "Aircraft"),
           F("aeroport_depart", "str", "Aeroport depart", "Departure airport"),
           F("aeroport_arrivee", "str", "Aeroport arrivee", "Arrival airport"),
           F("date_std", "datetime", "STD", "STD"),
           F("date_sta", "datetime", "STA", "STA"),
           F("date_ata", "datetime", "ATA", "ATA"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "BARREE", "DECOLLE", "EN_VOL", "POSE", "ANNULE", "DEROUTE", "RETOUR_BASE"], "PLANIFIE")]),

        E("crew-scheduling", "air_crew_rosters", "CrewRoster", "air-crew-rosters", "crew",
          "Navigation planning", "Crew scheduling",
          "PNT (pilotes), PNC (Cabin), qualification ligne / aeronef.",
          "Flight deck (PNT), cabin (PNC), type/route qualification.",
          "Repos obligatoire 10h avant report.", "Mandatory 10h rest before duty.",
          "Users", "reference",
          [F("reference", "str", "Reference tour", "Duty reference", required=True, search=True),
           F("nom_membre", "str", "Nom membre", "Member name"),
           F("role", "str", "Role", "Role"),
           F("licence", "str", "Licence", "Licence"),
           F("qualification", "str", "Qualification", "Qualification"),
           F("date_prise_service", "datetime", "Prise service", "Duty start"),
           F("date_fin_service", "datetime", "Fin service", "Duty end"),
           F("heures_vol_mois", "int", "Heures vol (mois)", "Monthly flight hours"),
           F("statut", "str", "Statut", "Status")],
          [EN("role", ["COMMANDANT", "COPILOT", "PNC_CHEF", "PNC", "MéDECIN"], "COMMANDANT"),
           EN("statut", ["PLANIFIE", "EN_SERVICE", "REPOS", "MALADIE", "FORMATE", "SUSPENDU"], "PLANIFIE")]),

        E("aircraft-maintenance", "air_mro_checks", "AircraftCheck", "air-mro-checks", "mro",
          "Maintenance aeronefs (MRO)", "Aircraft maintenance",
          "Checks A/B/C/D, lourdes, AD/SB applicables.",
          "A/B/C/D checks, heavy, applicable AD/SB.",
          "Cde de maintenance obligatoire apres check C.", "CofA revalidation mandatory after C check.",
          "Wrench", "reference",
          [F("reference", "str", "Reference ordre", "Work order reference", required=True, search=True),
           F("immatriculation", "str", "Aeronef", "Aircraft"),
           F("type_check", "str", "Type check", "Check type"),
           F("atelier", "str", "Atelier", "Workshop"),
           F("date_debut", "date", "Date debut", "Start date"),
           F("date_fin_prevue", "date", "Fin prevue", "Planned end"),
           F("date_retour_service", "date", "Retour service", "Return to service"),
           F("heures_arret", "int", "Heures AOG", "AOG hours"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_check", ["A", "C", "D", "LOURDE", "ADR", "SB", "TROUVE"], "A"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "SURSEAN", "ANNULE"], "PLANIFIE")]),

        E("airport-cargo", "air_cargo_warehouses", "AirportCargoWarehouse", "air-cargo-warehouses", "cargo",
          "Terminal fret aerien", "Air cargo terminal",
          "Magasinage, temperature, zone DCU / surete.",
          "Storage, temperature, security/Customs zones.",
          "Zone sous surveillance video continue.", "Zone under continuous CCTV.",
          "Building2", "code_entrepot",
          [F("code_entrepot", "str", "Code entrepot", "Warehouse code", required=True, search=True),
           F("aeroport", "str", "Aeroport", "Airport"),
           F("superficie_m2", "int", "Superficie (m2)", "Area (m2)"),
           F("capacite_palettes", "int", "Capacite palettes", "Pallet capacity"),
           F("zones_froides", "bool", "Zones froides", "Cold zones"),
           F("zone_douaniere", "bool", "Zone douaniere", "Customs zone"),
           F("zone_surete", "bool", "Zone surete", "Security zone"),
           F("occupation_pct", "int", "Occupation (%)", "Occupancy (%)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "SATURATION", "TRAVAUX", "FERME"], "ACTIF")]),

        E("air-tariffs", "air_tariffs", "AirTariff", "air-tariffs", "tariffs",
          "Tarification aerienne", "Air freight tariffs",
          "Grille TACT / CDG / surcharges carburant et securite.",
          "TACT/CDG rate grid + fuel/security surcharges.",
          "Reférence IATA TACT + contrats bilateraux.", "IATA TACT reference + bilateral agreements.",
          "Calculator", "code_tarif",
          [F("code_tarif", "str", "Code tarif", "Tariff code", required=True, search=True),
           F("origine", "str", "Origine", "Origin"),
           F("destination", "str", "Destination", "Destination"),
           F("poids_min_kg", "int", "Poids min (kg)", "Min weight (kg)"),
           F("type_cargo", "str", "Type cargo", "Cargo type"),
           F("prix_par_kg_xaf", "int", "Prix (XAF/kg)", "Price (XAF/kg)"),
           F("surcharges_xaf", "int", "Surcharges", "Surcharges"),
           F("validite_debut", "date", "Debut validite", "Valid from"),
           F("validite_fin", "date", "Fin validite", "Valid until"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_cargo", ["GENERAL", "PERISSABLE", "DG", "VIVANT", "DIPLO", "ECOM", "OTHER"], "GENERAL"),
           EN("statut", ["ACTIF", "BROUILLON", "EXPIRE", "GELE"], "ACTIF")]),
    ],
)
