"""Manifest Vague D — batch D3 (portails RH / commercial, « sober & justifie »).

  - commercial_d2     (+1 -> portail-commercial 20) : veille concurrence.
    module_key distinct pour etendre le module deja genere (pas d' eecrasement :
    registre « registres_d », table/classe/chemin neuf, migration idempotente).
    perm_module="b2b" (« b2b.*.* » RESPONSABLE_COMMERCIAL).
  - employe_d         (+17 -> portail-employe 20) : demarches self-service saisies
    par le collaborateur, DISTINCTES des tables maitresses rh_deep.
    perm_module="rh" (« rh.*.* » ADMIN_RH).
  - chef_personnel_d  (+15 -> chef-personnel 20) : actes d' encadrement RH,
    DISTINCTS du portail employe (cote manager).
    perm_module="rh".

Chaine Alembic 093-095 depuis 092_commercial_d_deep. Aucune valeur fabriquee.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── portail-commercial (+1 -> 20) : veille concurrence ──────────────────────
MODULES["commercial_d2"] = dict(
    module_key="commercial_d2", module_slug="portail-commercial",
    module_path="portail-commercial", perm_module="b2b",
    registre_filename="registres_d",
    revision="093", down_revision="092_commercial_d_deep",
    entities=[
        E("competitor-notes", "comm_competitor_notes", "CommCompetitorNote", "comm-competitor-notes",
          "competitor_note", "Notes de veille concurrence", "Competitor notes",
          "Observation de veille concurrentielle saisie par le commercial.",
          "Competitive-intelligence observation captured by the salesperson.",
          "Le concurrent et le fait observe alimentent la strategie.",
          "The competitor and observed fact feed the strategy.",
          "Radar", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("concurrent", "str", "Concurrent", "Competitor"),
           F("fait_observe", "text", "Fait observe", "Observed fact"),
           F("marche", "str", "Marche", "Market"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISIE", "VERIFIEE", "PARTAGEE", "CLASSE"])]),
    ],
)

# ─── portail-employe (+17 -> 20) : self-service collaborateur ────────────────
MODULES["employe_d"] = dict(
    module_key="employe_d", module_slug="portail-employe",
    module_path="portail-employe", perm_module="rh",
    registre_filename="registres_c",
    revision="094", down_revision="093_commercial_d2_deep",
    entities=[
        E("leave-requests", "emp_leave_requests", "EmpLeaveRequest", "emp-leave-requests",
          "leave_request", "Demandes de conges", "Leave requests",
          "Demande de conge saisie par le collaborateur.",
          "Leave request raised by the employee.",
          "Les dates et le solde restant encadrent la demande.",
          "Dates and remaining balance frame the request.",
          "CalendarDays", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("type_conge", "str", "Type", "Leave type"),
           F("debut", "date", "Debut", "Start"),
           F("fin", "date", "Fin", "End"),
           F("jours", "int", "Jours", "Days"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_conge", ["CP", "RTT", "SANS_TRAITEMENT", "EVENTEMENT"]),
           EN("statut", ["SOUMIS", "EN_COURS", "ACCEPTE", "REFUSE", "ANNULE"])]),

        E("timesheet-entries", "emp_timesheet_entries", "EmpTimesheetEntry", "emp-timesheet-entries",
          "timesheet_entry", "Feuilles de temps", "Timesheet entries",
          "Saisie quotidienne du temps de travail.",
          "Daily work-time logging.",
          "Le total hebdomadaire doit egaler le temps contractuel.",
          "The weekly total must equal the contractual time.",
          "Clock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("date", "date", "Date", "Date"),
           F("heures", "num", "Heures", "Hours"),
           F("projet", "str", "Projet", "Project"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISI", "SOUMIS", "VALIDE", "CORRIGE"])]),

        E("overtime-requests", "emp_overtime_requests", "EmpOvertimeRequest", "emp-overtime-requests",
          "overtime_request", "Demandes d' heures supplementaires", "Overtime requests",
          "Demande de validation d' heures supplementaires.",
          "Request to validate overtime hours.",
          "Le contingent annuel borne les heures declarees.",
          "The annual cap bounds the declared hours.",
          "Hourglass", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("minutes", "int", "Minutes", "Minutes"),
           F("motif", "str", "Motif", "Reason"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMIS", "ACCORD", "REFUS", "RECUPERE"])]),

        E("attendance-corrections", "emp_attendance_corrections", "EmpAttendanceCorrection", "emp-attendance-corrections",
          "attendance_correction", "Regularisations de pointage", "Attendance corrections",
          "Demande de correction d' un pointage errone ou oublie.",
          "Request to fix a wrong or missed clock-in.",
          "L' heure reellement effectuee est justifiee.",
          "The actual worked time is justified.",
          "CalendarCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("date_concernee", "date", "Date concernee", "Affected date"),
           F("motif", "text", "Motif", "Reason"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDEE", "INSTRUIT", "APPLIQUEE", "REFUSEE"])]),

        E("shift-swaps", "emp_shift_swaps", "EmpShiftSwap", "emp-shift-swaps",
          "shift_swap", "Echanges de poste", "Shift swaps",
          "Demande d' echange de poste entre deux collaborateurs.",
          "Request to swap a shift between two employees.",
          "L' accord des deux parties valide l' echange.",
          "Both parties' agreement validates the swap.",
          "ArrowLeftRight", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("demandeur", "str", "Demandeur", "Requester"),
           F("partenaire", "str", "Partenaire", "Partner"),
           F("date_poste", "datetime", "Date du poste", "Shift date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSE", "ACCEPTE_PARTENAIRE", "VALIDE_RH", "REFUSE"])]),

        E("training-enrollments", "emp_training_enrollments", "EmpTrainingEnrollment", "emp-training-enrollments",
          "training_enrollment", "Inscriptions formation", "Training enrollments",
          "Inscription d' un collaborateur a une action de formation.",
          "Employee enrollment in a training action.",
          "Le plan de formation et le budget encadrent l' inscription.",
          "The training plan and budget frame the enrollment.",
          "GraduationCap", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("formation", "str", "Formation", "Training"),
           F("date_debut", "date", "Debut", "Start"),
           F("organism", "str", "Organisme", "Provider"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDEE", "VALIDEE", "SUIVIE", "ABANDONNEE"])]),

        E("skill-declarations", "emp_skill_declarations", "EmpSkillDeclaration", "emp-skill-declarations",
          "skill_declaration", "Declarations de competences", "Skill declarations",
          "Auto-declaration d' une competence par le collaborateur.",
          "Self-declaration of a skill by the employee.",
          "Le niveau declare est ensuite evalue par le manager.",
          "The declared level is then assessed by the manager.",
          "Star", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("competence", "str", "Competence", "Skill"),
           F("niveau", "str", "Niveau", "Level"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("niveau", ["DEBUTANT", "INTERMEDIAIRE", "AUTONOME", "EXPERT"]),
           EN("statut", ["DECLAREE", "EVALUEE", "VALIDEE", "ECARTEE"])]),

        E("certification-renewals", "emp_certification_renewals", "EmpCertificationRenewal", "emp-certification-renewals",
          "certification_renewal", "Renouvellements de certification", "Certification renewals",
          "Demande de renouvellement d' une certification / habilitation.",
          "Request to renew a certification / authorization.",
          "La date d' expiration impose l' anticipation.",
          "The expiry date forces anticipation.",
          "Award", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("certification", "str", "Certification", "Certification"),
           F("expire_le", "date", "Expire le", "Expires"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_RENOUVELER", "DEMANDEE", "OCTROYEE", "PERIMEE"])]),

        E("personal-info-changes", "emp_personal_info_changes", "EmpPersonalInfoChange", "emp-personal-info-changes",
          "personal_info_change", "Modifications d' etat civil", "Personal info changes",
          "Demande de mise a jour d' une donnee personnelle.",
          "Request to update a personal data item.",
          "La piece justificative appuie la modification.",
          "The supporting document backs the change.",
          "UserCog", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("champ", "str", "Champ modifie", "Changed field"),
           F("nouvelle_valeur", "str", "Nouvelle valeur", "New value"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("champ", ["ADRESSE", "TELEPHONE", "SITUATION_FAMILIALE", "BENEFICIAIRE"]),
           EN("statut", ["DEMANDEE", "JUSTIFIEE", "APPLIQUEE", "REFUSEE"])]),

        E("bank-details-updates", "emp_bank_updates", "EmpBankDetailsUpdate", "emp-bank-details-updates",
          "bank_details_update", "Changements de RIB", "Bank details updates",
          "Demande de changement du compte de versement de la paie.",
          "Request to change the payroll bank account.",
          "Un RIB valide atteste la securite du virement.",
          "A validated RIB secures the transfer.",
          "Wallet", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("banque", "str", "Banque", "Bank"),
           F("date_effet", "date", "Date d' effet", "Effective date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "VERIFIEE", "ACTIVE", "REJETEE"])]),

        E("emergency-contacts", "emp_emergency_contacts", "EmpEmergencyContact", "emp-emergency-contacts",
          "emergency_contact", "Contacts d' urgence", "Emergency contacts",
          "Contact a prevenir en cas d' urgence pour le collaborateur.",
          "Contact to alert in an emergency for the employee.",
          "Le lien et le telephone rendent le contact actionnable.",
          "Relationship and phone make the contact actionable.",
          "Phone", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("nom", "str", "Nom", "Name"),
           F("lien", "str", "Lien", "Relationship"),
           F("telephone", "str", "Telephone", "Phone"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_JOUR", "A_VERIFIER", "OBSOLETE"])]),

        E("badge-requests", "emp_badge_requests", "EmpBadgeRequest", "emp-badge-requests",
          "badge_request", "Demandes de badge", "Badge requests",
          "Demande de badge d' acces ou de renouvellement.",
          "Request for an access badge or renewal.",
          "Le motif (nouveau / perte) declenche la fabrication.",
          "The reason (new/lost) triggers fabrication.",
          "BadgeCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("motif", "str", "Motif", "Reason"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("motif", ["NOUVEAU", "PERTE", "VOL", "RENOUVELLEMENT", "DEGRADATION"]),
           EN("statut", ["DEMANDE", "FABRIQUE", "REMIS", "BLOQUE"])]),

        E("access-requests", "emp_access_requests", "EmpAccessRequest", "emp-access-requests",
          "access_request", "Demandes d' acces", "Access requests",
          "Demande d' acces a un systeme, un local ou un equipement.",
          "Request for access to a system, room or equipment.",
          "Le niveau d' acces est justifie par la fonction.",
          "The access level is justified by the role.",
          "KeyRound", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("ressource", "str", "Ressource", "Resource"),
           F("type_acces", "str", "Type d' acces", "Access type"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_acces", ["LOGIQUE", "PHYSIQUE", "TEMPORAIRE"]),
           EN("statut", ["DEMANDE", "INSTRUIT", "ACCORDE", "REFUSE", "REVOQUE"])]),

        E("document-uploads", "emp_document_uploads", "EmpDocumentUpload", "emp-document-uploads",
          "document_upload", "Depot de documents RH", "HR document uploads",
          "Depot par le collaborateur d' un piece demandee par les RH.",
          "Employee upload of a document requested by HR.",
          "La typologie et la validite structurent le dossier.",
          "Typology and validity structure the file.",
          "Archive", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("type_piece", "str", "Type de piece", "Document type"),
           F("fichier", "str", "Fichier", "File"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_piece", ["PIECE_IDENTITE", "RIB", "DIPLOME", "ATTESTATION"]),
           EN("statut", ["DEPOSE", "VERIFIE", "REJETE", "EXPIRE"])]),

        E("self-reviews", "emp_self_reviews", "EmpSelfReview", "emp-self-reviews",
          "self_review", "Auto-evaluations", "Self reviews",
          "Auto-evaluation redigee par le collaborateur pour l' entretien annuel.",
          "Self-assessment written for the annual review.",
          "Les objectifs atteints sont auto-poses avant la revue manager.",
          "Achieved goals are self-stated before the manager review.",
          "ClipboardCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("periode", "str", "Periode", "Period"),
           F("accomplissements", "text", "Accomplissements", "Achievements"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "SOUMISE", "DISCUTE", "CLOTURE"])]),

        E("internal-mobility-applications", "emp_mobility_apps", "EmpMobilityApplication", "emp-internal-mobility-applications",
          "mobility_application", "Candidatures internes", "Internal mobility applications",
          "Candidature du collaborateur a un poste interne ouvert.",
          "Employee application to an open internal position.",
          "Le poste cible et la motivation structurent la candidature.",
          "Target role and motivation frame the application.",
          "GitBranch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("poste_cible", "str", "Poste cible", "Target role"),
           F("motivation", "text", "Motivation", "Motivation"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEPOSEE", "PRESELECTIONNE", "ENTRETIEN", "RETENU", "NON_RETENU"])]),

        E("sickness-declarations", "emp_sickness_declarations", "EmpSicknessDeclaration", "emp-sickness-declarations",
          "sickness_declaration", "Declarations d' arret maladie", "Sickness declarations",
          "Declaration d' un arret de travail pour maladie par le collaborateur.",
          "Employee declaration of a sick-leave stop.",
          "La date et la duree de l' arret encadrent le controle.",
          "The stop date and duration frame the control.",
          "Stethoscope", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("debut", "date", "Debut", "Start"),
           F("duree_jours", "int", "Duree (jours)", "Duration (days)"),
           F("justificatif", "bool", "Justificatif fourni", "Proof provided"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DECLARE", "JUSTIFIE", "PROLONGE", "REPRIS", "CONTROLE"])]),
    ],
)

# ─── chef-personnel (+15 -> 20) : actes d' encadrement RH ────────────────────
MODULES["chef_personnel_d"] = dict(
    module_key="chef_personnel_d", module_slug="chef-personnel",
    module_path="chef-personnel", perm_module="rh",
    registre_filename="registres_c",
    revision="095", down_revision="094_employe_d_deep",
    entities=[
        E("recruitment-campaigns", "chp_recruitment_campaigns", "ChpRecruitmentCampaign", "chp-recruitment-campaigns",
          "recruitment_campaign", "Campagnes de recrutement", "Recruitment campaigns",
          "Ouverture d' une campagne de recrutement pour un besoin.",
          "Opening of a recruitment campaign for a need.",
          "Le poste et le volume attendu cadrent la campagne.",
          "The role and expected volume frame the campaign.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("poste", "str", "Poste", "Role"),
           F("volume", "int", "Volume", "Volume"),
           F("ouverture", "date", "Ouverture", "Opening"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERTE", "EN_COURS", "POURVUE", "CLOTUREE", "GELEE"])]),

        E("job-postings", "chp_job_postings", "ChpJobPosting", "chp-job-postings",
          "job_posting", "Offres d' emploi", "Job postings",
          "Publication d' une offre pour un poste a pourvoir.",
          "Publication of a job offer for an open role.",
          "Le canal et la date de parution pilotent l' audience.",
          "Channel and publish date drive reach.",
          "Briefcase", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("canal", "str", "Canal", "Channel"),
           F("parution", "date", "Parution", "Published"),
           F("candidats", "int", "Candidats", "Candidates"),
           F("statut", "str", "Statut", "Status")],
          [EN("canal", ["INTERNE", "SITE", "JOBBOARD", "RESEAU"]),
           EN("statut", ["BROUILLON", "PUBLIEE", "PAUSEE", "RETIRE"])]),

        E("candidate-selections", "chp_candidate_selections", "ChpCandidateSelection", "chp-candidate-selections",
          "candidate_selection", "Selection de candidats", "Candidate selections",
          "Decision de selection sur un candidat a un poste.",
          "Selection decision on a candidate for a role.",
          "La phase du tunnel trace l' avancement.",
          "The pipeline stage traces the progress.",
          "ListChecks", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("candidat", "str", "Candidat", "Candidate"),
           F("poste", "str", "Poste", "Role"),
           F("phase", "str", "Phase", "Stage"),
           F("evaluateur", "str", "Evaluateur", "Evaluator"),
           F("statut", "str", "Statut", "Status")],
          [EN("phase", ["TRI", "ENTRETIEN", "TEST", "OFFRE", "REFUS"]),
           EN("statut", ["EN_COURS", "RETENU", "ECARTE"])]),

        E("interview-schedules", "chp_interview_schedules", "ChpInterviewSchedule", "chp-interview-schedules",
          "interview_schedule", "Planifications d' entretiens", "Interview schedules",
          "Creneau d' entretien fixe entre un candidat et un evaluateur.",
          "Interview slot between a candidate and an evaluator.",
          "Le format et les participants conditionnent l' entretien.",
          "Format and participants condition the interview.",
          "CalendarDays", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("candidat", "str", "Candidat", "Candidate"),
           F("date", "datetime", "Date", "Date"),
           F("format", "str", "Format", "Format"),
           F("evaluateur", "str", "Evaluateur", "Evaluator"),
           F("statut", "str", "Statut", "Status")],
          [EN("format", ["TELEPHONE", "VISIO", "SUR_SITE"]),
           EN("statut", ["PLANIFIE", "TENU", "MANQUE", "REPORTE"])]),

        E("offer-approvals", "chp_offer_approvals", "ChpOfferApproval", "chp-offer-approvals",
          "offer_approval", "Validations d' offres", "Offer approvals",
          "Circuit de validation d' une proposition d' embauche.",
          "Approval workflow of a hiring offer.",
          "La remuneration proposee doit respecter la fourchette budgetaire.",
          "The proposed pay must respect the budget range.",
          "FileCheck2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("candidat", "str", "Candidat", "Candidate"),
           F("poste", "str", "Poste", "Role"),
           F("remuneration", "num", "Remuneration", "Compensation"),
           F("validateur", "str", "Validateur", "Approver"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "EN_COURS", "APPROUVEE", "REJETEE", "NEGOCIEE"])]),

        E("onboarding-checklists", "chp_onboarding_checklists", "ChpOnboardingChecklist", "chp-onboarding-checklists",
          "onboarding_checklist", "Checklists d' integration", "Onboarding checklists",
          "Jalons d' integration d' un nouveau arrive.",
          "Onboarding milestones of a new hire.",
          "Le taux d' etapes faites mesure la qualite de l' arrivee.",
          "The completion rate measures arrival quality.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("etapes_total", "int", "Etapes", "Steps"),
           F("etapes_faites", "int", "Etapes faites", "Steps done"),
           F("date_debut", "date", "Debut", "Start"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "TERMINEE", "PARTIELLE"])]),

        E("probation-reviews", "chp_probation_reviews", "ChpProbationReview", "chp-probation-reviews",
          "probation_review", "Revues de periode d' essai", "Probation reviews",
          "Bilan de fin de periode d' essai d' un collaborateur.",
          "End-of-probation assessment of an employee.",
          "La decision (titulariser / renouveler) clot l' essai.",
          "The decision (confirm/renew) closes the trial.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("date_echeance", "date", "Echeance", "Due date"),
           F("avis", "str", "Avis", "Verdict"),
           F("statut", "str", "Statut", "Status")],
          [EN("avis", ["TITULARISE", "RENOUVELE", "ROMPU"]),
           EN("statut", ["A_JUGER", "JUGE", "SIGNIFIE"])]),

        E("exit-interviews", "chp_exit_interviews", "ChpExitInterview", "chp-exit-interviews",
          "exit_interview", "Entretiens de depart", "Exit interviews",
          "Entretien realise lors du depart d' un collaborateur.",
          "Interview conducted on an employee's departure.",
          "La motif de depart alimente la marque employeur.",
          "The departure reason feeds employer brand.",
          "BookOpen", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("motif", "str", "Motif", "Reason"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("motif", ["DEMISSION", "LICENCIEMENT", "RETRAITE", "FIN_CDD", "INTERNE"]),
           EN("statut", ["PLANIFIE", "TENU", "ANALYSE", "CLASSE"])]),

        E("headcount-requests", "chp_headcount_requests", "ChpHeadcountRequest", "chp-headcount-requests",
          "headcount_request", "Demandes de creation de poste", "Headcount requests",
          "Demande de validation d' un nouveau poste.",
          "Request to validate a new position.",
          "Le budget et la justification encadrent la demande.",
          "Budget and justification frame the request.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("departement", "str", "Departement", "Department"),
           F("poste", "str", "Poste", "Role"),
           F("masse_salariale", "num", "Masse salariale", "Salary cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "INSTRUIT", "APPROUVEE", "REFUSEE"])]),

        E("org-movements", "chp_org_movements", "ChpOrgMovement", "chp-org-movements",
          "org_movement", "Mouvements organisationnels", "Org movements",
          "Changement de service, manager ou niveau d' un collaborateur.",
          "Change of department, manager or level for an employee.",
          "La date d' effet redecrit l' organigramme.",
          "The effective date rewrites the org chart.",
          "GitBranch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("type_mouvement", "str", "Type", "Movement type"),
           F("date_effet", "date", "Date d' effet", "Effective date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_mouvement", ["PROMOTION", "TRANSFERT", "REASSIGNATION", "INTERRIM"]),
           EN("statut", ["PROJETE", "VALIDEE", "APPLIQUEE", "ANNULEE"])]),

        E("disciplinary-actions", "chp_disciplinary_actions", "ChpDisciplinaryAction", "chp-disciplinary-actions",
          "disciplinary_action", "Mesures disciplinaires", "Disciplinary actions",
          "Sanction ou mesure disciplinaire decidee a l' encontre d' un collaborateur.",
          "Sanction or disciplinary measure decided against an employee.",
          "La gravite et la procedure garantie tracent la mesure.",
          "Severity and due process trace the measure.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("motif", "text", "Motif", "Reason"),
           F("type_mesure", "str", "Type de mesure", "Measure type"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_mesure", ["RAPPEL", "AVERTISSEMENT", "MISE_PIED", "EXCLUSION", "LICENCIEMENT"]),
           EN("statut", ["ENGAGEE", "NOTIFIEE", "CONTESTEE", "CLOTURE"])]),

        E("training-plans", "chp_training_plans", "ChpTrainingPlan", "chp-training-plans",
          "training_plan", "Plans de formation", "Training plans",
          "Plan de formation annuel arbitre pour un departement.",
          "Annual training plan arbitrated for a department.",
          "Le budget et les priorites cadrent le plan.",
          "Budget and priorities frame the plan.",
          "Target", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("departement", "str", "Departement", "Department"),
           F("exercice", "str", "Exercice", "Fiscal year"),
           F("budget", "num", "Budget", "Budget"),
           F("actions", "int", "Actions", "Actions"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ELABORE", "SOUMIS", "ARBITRE", "EN_COURS", "CLOTURE"])]),

        E("absence-approvals", "chp_absence_approvals", "ChpAbsenceApproval", "chp-absence-approvals",
          "absence_approval", "Validations d' absences", "Absence approvals",
          "Validation manager d' une demande d' absence d' un collaborateur.",
          "Manager approval of an employee's absence request.",
          "Le solde et la charge d' equipe conditionnent l' accord.",
          "Balance and team load condition the approval.",
          "CalendarCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("manager", "str", "Manager", "Manager"),
           F("debut", "date", "Debut", "Start"),
           F("fin", "date", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_VALIDER", "ACCEPTEE", "REFUSEE", "REPORTEE"])]),

        E("payroll-adjustment-requests", "chp_payroll_adjustments", "ChpPayrollAdjustmentRequest", "chp-payroll-adjustment-requests",
          "payroll_adjustment_request", "Demandes d' ajustement de paie", "Payroll adjustment requests",
          "Demande d' ajustement exceptionnel de la paie d' un collaborateur.",
          "Exceptional payroll adjustment request for an employee.",
          "Le montant et la justification engagent le controle RH.",
          "The amount and justification commit the HR control.",
          "Banknote", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("motif", "str", "Motif", "Reason"),
           F("montant", "num", "Montant", "Amount"),
           F("periode", "str", "Periode", "Period"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "INSTRUIT", "APPROUVE", "REJETE", "PAYE"])]),

        E("policy-acknowledgements", "chp_policy_acks", "ChpPolicyAck", "chp-policy-acknowledgements",
          "policy_ack", "Accuses de politique RH", "Policy acknowledgements",
          "Prise de connaissance et acceptation d' une politique RH.",
          "Reading and acceptance of an HR policy.",
          "L' accuse horodate prouve la diffusion de la regle.",
          "The timestamped acknowledgement proves rule dissemination.",
          "FileText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("politique", "str", "Politique", "Policy"),
           F("version", "str", "Version", "Version"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_SIGNER", "SIGNEE", "EXPIREE", "A_RENOUVELER"])]),
    ],
)
