"""Manifest Wave 4 (suite) : fluvial/lacustre + logistique 3PL sous contrat."""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── transport-fluvial-lacustre ────────────────────────────────────────────
MODULES["fluvial"] = dict(
    module_key="fluvial", module_slug="transport-fluvial",
    module_path="transport-fluvial", perm_module="fluvial",
    revision="064", down_revision="063_aerien_deep",
    entities=[
        E("barge-fleet", "fluv_barges", "FluvialBarge", "fluvial-barges", "barge_fleet",
          "Flotte peniches / chalands", "Barge fleet",
          "Referentiel peniches, chalands et automoteurs fluviaux.",
          "Barges, lighters and self-propelled craft.",
          "Tirant d'eau max selon saison / voie.", "Max draft per season/channel.",
          "Ship", "numero_flotte",
          [F("numero_flotte", "str", "Numero flotte", "Fleet number", required=True, search=True),
           F("type", "str", "Type", "Type"),
           F("capacite_tonnes", "int", "Capacite (t)", "Capacity (t)"),
           F("tirant_eau_max_m", "str", "Tirant d'eau max (m)", "Max draft (m)"),
           F("longueur_m", "int", "Longueur (m)", "Length (m)"),
           F("largeur_m", "int", "Largeur (m)", "Beam (m)"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["PENICHE", "CHALAND", "AUTOMOTEUR", "Pousse_pousse", "TANKER_FLUV", "CONTENEURS"], "PENICHE"),
           EN("statut", ["OPERATIONNEL", "ATELIER", "ARRETE_SAISON", "REFORME"], "OPERATIONNEL")]),

        E("tow-fleet", "fluv_towboats", "FluvialTowboat", "fluvial-towboats", "tow_fleet",
          "Remorqueurs fluviaux", "River tug fleet",
          "Remorqueurs d'estuaire et de voie interieure.",
          "Estuary and inland waterway tugs.",
          "Puissance bollee pour convois.", "Bollard pull rated for convoys.",
          "Anchor", "numero_tug",
          [F("numero_tug", "str", "Numero remorqueur", "Tug number", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("puissance_kw", "int", "Puissance (kW)", "Power (kW)"),
           F("bollard_pull_t", "int", "Bollard pull (t)", "Bollard pull (t)"),
           F("zone_operation", "str", "Zone operation", "Operating area"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OPERATIONNEL", "PANNE", "MAINTENANCE"], "OPERATIONNEL")]),

        E("lock-transits", "fluv_lock_transits", "LockTransit", "fluvial-lock-transits", "locks",
          "Transits d'ecluses", "Lock transits",
          "Passages d'ecluses avec horaires, poids, dimensions.",
          "Lock passages with timing, weight, dimensions.",
          "Reservation obligatoire via VNF/COPR.", "Mandatory reservation.",
          "DoorOpen", "reference",
          [F("reference", "str", "Reference passage", "Transit reference", required=True, search=True),
           F("nom_ecluse", "str", "Nom ecluse", "Lock name"),
           F("date_passage", "datetime", "Date passage", "Transit date"),
           F("numero_peniche", "str", "Peniche concernee", "Barge number"),
           F("masse_tonnes", "int", "Masse (t)", "Mass (t)"),
           F("tirant_eau_m", "str", "Tirant d'eau (m)", "Draft (m)"),
           F("attente_minutes", "int", "Attente (min)", "Waiting (min)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_ATTENTE", "EN_COURS", "PASSAGE_OK", "REFUSE", "REPORTE"], "PLANIFIE")]),

        E("river-depth", "fluv_depth_surveys", "RiverDepthSurvey", "fluvial-depth-surveys", "depth",
          "Sondes bathymetriques", "River depth surveys",
          "Mesures periodiques de fond de voie / seuils / tirant d'eau pratique.",
          "Periodic bed / threshold / practical draft survey.",
          "Declenche restriction de tirant d'eau.", "Triggers draft restriction.",
          "Ruler", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("bief", "str", "Bief", "Reach"),
           F("date_mesure", "date", "Date mesure", "Survey date"),
           F("profondeur_min_cm", "int", "Profondeur min (cm)", "Min depth (cm)"),
           F("tirant_eau_pmax_cm", "int", "TPE pratique max (cm)", "Max practical draft (cm)"),
           F("debit_m3s", "int", "Debit (m3/s)", "Flow (m3/s)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NORMAL", "RESTRITIF", "CRUE", "EPROUVE", "BLOCAGE"], "NORMAL")]),

        E("river-ports", "fluv_terminals", "FluvialTerminal", "fluvial-terminals", "terminals",
          "Terminaux fluviaux", "River terminals",
          "Quais, appontements et zones de transbordement fluvial.",
          "Quays, jetties and transshipment areas.",
          "Connecte au port maritime (hinterland).", "Linked to seaport (hinterland).",
          "Warehouse", "code_terminal",
          [F("code_terminal", "str", "Code terminal", "Terminal code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("fleuve", "str", "Fleuve", "River"),
           F("pays", "str", "Pays", "Country"),
           F("nb_appontements", "int", "Nb appontements", "Berths"),
           F("longueur_quai_m", "int", "Longueur quai (m)", "Quay length (m)"),
           F("connecte_port_maritime", "bool", "Relie port maritime", "Connected to seaport"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "TRAVAUX", "FERME", "PROJET"], "ACTIF")]),

        E("bulk-river", "fluv_bulk_operations", "FluvialBulkOperation", "fluvial-bulk-operations", "bulk",
          "Vrac fluvial", "River bulk operations",
          "Chargement/dechargement vrac solide ou liquide.",
          "Bulk solid or liquid loading/unloading.",
          "Pompage / grue / banderoule selon produit.", "Pump / crane / belt per product.",
          "Droplet", "reference",
          [F("reference", "str", "Reference operation", "Operation reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("categorie", "str", "Categorie", "Category"),
           F("quantite_tonnes", "int", "Quantite (t)", "Quantity (t)"),
           F("terminal", "str", "Terminal", "Terminal"),
           F("date_operation", "datetime", "Date", "Date"),
           F("duree_heures", "int", "Duree (h)", "Duration (h)"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["SOLIDE", "LIQUIDE", "GATEUX"], "SOLIDE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "INTERROMPU"], "PLANIFIE")]),

        E("navigation-safety", "fluv_safety_records", "FluvialSafetyRecord", "fluvial-safety-records", "safety",
          "Securite navigation", "Navigation safety",
          "Balises, accidents, secours, arret technique.",
          "Beacons, incidents, rescue, technical stops.",
          "Declenchement plan ORSEC si accident grave.", "ORSEC plan trigger for serious incidents.",
          "LifeBuoy", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("date_evenement", "datetime", "Date evenement", "Event date"),
           F("bief", "str", "Bief", "Reach"),
           F("type_evenement", "str", "Type evenement", "Event type"),
           F("gravite", "str", "Gravite", "Severity"),
           F("batiments_impliques", "text", "Batiments impliques", "Vessels involved"),
           F("description", "text", "Description", "Description"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_evenement", ["ECHELLEMENT", "COLLISION", "COULEMENT", "INCENDIE", "PANNE_MOTOR", "Balisage", "AUTRE"], "PANNE_MOTOR"),
           EN("gravite", ["NEANT", "MINEURE", "MAJEURE", "CRITIQUE"], "MINEURE"),
           EN("statut", ["OUVERT", "ENQUETE", "CLOTURE", "TRANSFERT_JUSTICE"], "OUVERT")]),

        E("river-tariffs", "fluv_tariffs", "FluvialTariff", "fluvial-tariffs", "tariffs",
          "Tarification fluviale", "River tariffs",
          "Prix par tonne / km selon bief et type produit.",
          "Price per ton-km per reach and product.",
          "Refacte selon niveau d'eau / saison.", "Adjusted per water level / season.",
          "Calculator", "code_tarif",
          [F("code_tarif", "str", "Code tarif", "Tariff code", required=True, search=True),
           F("bief", "str", "Bief", "Reach"),
           F("produit", "str", "Produit", "Product"),
           F("prix_par_tonne_xaf", "int", "Prix (XAF/t)", "Price (XAF/t)"),
           F("saisonnalite", "str", "Saisonnalite", "Season"),
           F("remise_volume_pct", "int", "Remise volume (%)", "Volume discount (%)"),
           F("validite_debut", "date", "Debut validite", "Valid from"),
           F("validite_fin", "date", "Fin validite", "Valid until"),
           F("statut", "str", "Statut", "Status")],
          [EN("saisonnalite", ["HAUTE_EAU", "BASSE_EAU", "NORMALE"], "NORMALE"),
           EN("statut", ["ACTIF", "BROUILLON", "EXPIRE", "GELE"], "ACTIF")]),

        E("river-waybills", "fluv_waybills", "FluvialWaybill", "fluvial-waybills", "waybills",
          "Lettres de voiture fluviale CMNI", "CMNI inland waybills",
          "Titres de transport CMNI / nationaux fluviaux.",
          "CMNI or national inland waybills.",
          "Applicable sur Rhin, Senegal, Congo.", "Applies to Rhine, Senegal, Congo.",
          "FileText", "numero",
          [F("numero", "str", "Numero LCV fluviale", "Inland waybill number", required=True, search=True),
           F("expediteur", "str", "Expediteur", "Sender"),
           F("destinataire", "str", "Destinataire", "Consignee"),
           F("port_depart", "str", "Port depart", "Loading port"),
           F("port_arrivee", "str", "Port arrivee", "Discharge port"),
           F("produit", "str", "Produit", "Product"),
           F("quantite_tonnes", "int", "Quantite (t)", "Quantity (t)"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMISE", "CHARGEE", "TRANSIT", "LIVREE", "LITIGE"], "EMISE")]),

        E("fleet-positioning", "fluv_positions", "FluvialPosition", "fluvial-positions", "positions",
          "Positionnement flotte fluviale", "Fleet positioning",
          "AIS fluvial / GPS / VHF positionnement temps reel.",
          "Inland AIS / GPS / VHF real-time positioning.",
          "Declenche alerte si arret non prevu.", "Alerts on unplanned stop.",
          "MapPinned", "reference",
          [F("reference", "str", "Reference relevé", "Position reference", required=True, search=True),
           F("numero_flotte", "str", "Bateau", "Vessel"),
           F("date_releve", "datetime", "Date releve", "Position date"),
           F("latitude", "str", "Latitude", "Latitude"),
           F("longitude", "str", "Longitude", "Longitude"),
           F("vitesse_nd", "str", "Vitesse (nd)", "Speed (kn)"),
           F("cap", "str", "Cap", "Heading"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_MOUVEMENT", "AMARRE", "ATTENTE_ECLUSE", "ARRET_TECHNIQUE", "PERDU"], "EN_MOUVEMENT")]),
    ],
)


# ─── logistique-3pl ───────────────────────────────────────────────────────
MODULES["log3pl"] = dict(
    module_key="log3pl", module_slug="logistique-3pl",
    module_path="logistique-3pl", perm_module="log3pl",
    revision="065", down_revision="064_fluvial_deep",
    entities=[
        E("contract-agreements", "tpl_contracts", "TplContract", "tpl-contracts", "contracts",
          "Contrats cadres 3PL", "3PL framework contracts",
          "Accords de sous-traitance logistique longue duree.",
          "Long-term logistics outsourcing agreements.",
          "Engage SLA + penalites journalieres.", "Binds SLA + daily penalties.",
          "FileSignature", "numero_contrat",
          [F("numero_contrat", "str", "Numero contrat", "Contract number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("perimetre", "str", "Perimetre", "Scope"),
           F("sites_couverts", "text", "Sites couverts", "Sites covered"),
           F("date_debut", "date", "Date debut", "Start date"),
           F("date_fin", "date", "Date fin", "End date"),
           F("valeur_annuelle_xaf", "int", "Valeur annuelle", "Annual value"),
           F("statut", "str", "Statut", "Status")],
          [EN("perimetre", ["ENTREPOT", "TRANSPORT", "BOUT_BOUT", "CUSTOMS", "FULL_3PL"], "FULL_3PL"),
           EN("statut", ["BROUILLON", "EN_VIGUEUR", "RENEGOCIE", "EXPIRE", "RESILIE"], "EN_VIGUEUR")]),

        E("warehouse-3pl", "tpl_warehouses", "TplWarehouse", "tpl-warehouses", "warehouses",
          "Entrepots sous contrat", "Contracted warehouses",
          "Sites 3PL engages avec client donneur d'ordre.",
          "Sites committed under client contract.",
          "Cartographie multi-sites / capacites par produit.", "Multi-site map / capacity by product.",
          "Building", "code_site",
          [F("code_site", "str", "Code site", "Site code", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("localisation", "str", "Localisation", "Location"),
           F("surface_m2", "int", "Surface (m2)", "Area (m2)"),
           F("capacite_palettes", "int", "Capacite palettes", "Pallet capacity"),
           F("zones_froides", "bool", "Zones froides", "Cold zones"),
           F("contract_associe", "str", "Contrat associe", "Linked contract"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "SATURATION", "TRAVAUX", "FERME"], "ACTIF")]),

        E("crossdock-plans", "tpl_crossdocks", "TplCrossDock", "tpl-crossdocks", "crossdock",
          "Plans cross-dock", "Cross-dock plans",
          "Flux de transit rapide sans stockage.",
          "Fast-throughput no-storage flows.",
          "Fenetre creneau <4h obligatoire.", "Mandatory slot <4h.",
          "ArrowLeftRight", "reference",
          [F("reference", "str", "Reference plan", "Plan reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("date_operation", "datetime", "Date operation", "Operation date"),
           F("nb_entrees", "int", "Nb entrees", "Inbound count"),
           F("nb_sorties", "int", "Nb sorties", "Outbound count"),
           F("duree_foresee_min", "int", "Duree prevue (min)", "Planned duration (min)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "RETARDE", "ANNULE"], "PLANIFIE")]),

        E("pick-pack-lines", "tpl_picking_lines", "TplPickingLine", "tpl-picking-lines", "pickpack",
          "Lignes de preparation", "Picking / packing lines",
          "Ordres de preparation client, picking / packing / shipping.",
          "Client order preparation, picking / packing / shipping.",
          "Tracabilite operateur + temps unitaire.", "Operator + unit-time traceability.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference ordre", "Order reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("client", "str", "Client", "Client"),
           F("type_preparation", "str", "Type preparation", "Picking type"),
           F("nb_lignes", "int", "Nb lignes", "Lines"),
           F("nb_colis", "int", "Nb colis", "Parcels"),
           F("operateur", "str", "Operateur", "Operator"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_preparation", ["PCE", "COLIS", "PAL", "CROSSDOCK"], "COLIS"),
           EN("statut", ["EN_ATTENTE", "EN_COURS", "TERMINE", "BLOQUE", "ANNULE"], "EN_ATTENTE")]),

        E("kpi-slas", "tpl_sla_kpis", "TplSlaKpi", "tpl-sla-kpis", "slakpi",
          "KPI / SLA contractuels", "SLA / KPI contractual",
          "Taux de service, OTIF, erreurs, penalites.",
          "Service rate, OTIF, errors, penalties.",
          "Revue mensuelle avec client.", "Monthly client review.",
          "Target", "reference",
          [F("reference", "str", "Reference mesure", "Measure reference", required=True, search=True),
           F("contrat_associe", "str", "Contrat", "Contract"),
           F("periode", "str", "Periode", "Period"),
           F("kpi", "str", "KPI", "KPI"),
           F("valeur_cible", "str", "Valeur cible", "Target"),
           F("valeur_reelle", "str", "Valeur reelle", "Actual"),
           F("penalite_appliquee_xaf", "int", "Penalite (XAF)", "Penalty (XAF)"),
           F("statut", "str", "Statut", "Status")],
          [EN("kpi", ["OTIF", "TAUX_SERVICE", "ERREUR_PREP", "RETARD_LIVRAISON", "CASSE", "AUTRE"], "OTIF"),
           EN("statut", ["CONFORME", "SOUS_SEUIL", "AU_DESSUS", "LITIGE"], "CONFORME")]),

        E("billing-3pl", "tpl_invoices", "TplInvoice", "tpl-invoices", "billing",
          "Facturation 3PL", "3PL billing",
          "Facturation mensuelle des prestations logistiques.",
          "Monthly logistics service billing.",
          "Refacturation selon grille + extras.", "Grid + extras billing.",
          "Receipt", "numero_facture",
          [F("numero_facture", "str", "Numero facture", "Invoice number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("periode", "str", "Periode", "Period"),
           F("montant_ht_xaf", "int", "Montant HT (XAF)", "Net amount"),
           F("tva_xaf", "int", "TVA (XAF)", "VAT"),
           F("total_ttc_xaf", "int", "Total TTC (XAF)", "Gross amount"),
           F("date_emission", "date", "Emission", "Issue date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "EMISE", "ENVOYEE", "PAYEE", "REJETEE"], "BROUILLON")]),

        E("inventory-valuation", "tpl_inventory_valuations", "TplInventoryValuation", "tpl-inventory-valuations", "valuation",
          "Valorisation stock client", "Client inventory valuation",
          "Inventaires periodiques et valorisation aux conditions contractuelles.",
          "Periodic stock-take under contractual rules.",
          "Ecart >2% declenche expertise.", ">2% variance triggers expertise.",
          "Scale", "reference",
          [F("reference", "str", "Reference inventaire", "Stock-take reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("client", "str", "Client", "Client"),
           F("date_inventaire", "date", "Date inventaire", "Stock-take date"),
           F("valeur_theorique_xaf", "int", "Valeur theorique", "Theoretical value"),
           F("valeur_physique_xaf", "int", "Valeur physique", "Physical value"),
           F("ecart_pct", "int", "Ecart (%)", "Variance (%)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_COURS", "CLOTURE", "EXPERTISE", "VALIDE"], "PLANIFIE")]),

        E("sub-3pl-providers", "tpl_sub_providers", "TplSubProvider", "tpl-sub-providers", "subcontractors",
          "Sous-traitants secondaires", "Sub-contractors",
          "Prestataires appeles par le 3PL principal (carriers, handlers).",
          "Secondary providers engaged by the lead 3PL.",
          "Audit annuel + contrat cadre.", "Annual audit + master agreement.",
          "Users", "code_fournisseur",
          [F("code_fournisseur", "str", "Code fournisseur", "Vendor code", required=True, search=True),
           F("raison_sociale", "str", "Raison sociale", "Legal name"),
           F("type_prestation", "str", "Type prestation", "Service type"),
           F("zone_couverte", "str", "Zone couverte", "Coverage"),
           F("date_debut_contrat", "date", "Debut contrat", "Contract start"),
           F("date_audit_precedent", "date", "Dernier audit", "Last audit"),
           F("note_qualite", "str", "Note qualite", "Quality score"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_prestation", ["TRANSPORT", "MANUTENTION", "STOCKAGE", "CUSTOMS", "SECURITE", "NETTOIEMENT"], "TRANSPORT"),
           EN("statut", ["ACTIF", "SUSPENDU", "NOIR", "SORTI"], "ACTIF")]),

        E("reverse-logistics", "tpl_reverse_ops", "TplReverseOperation", "tpl-reverse-operations", "reverse",
          "Logistique retour / SAV", "Reverse logistics",
          "Retour produit, reconditionnement, recycling, destruction.",
          "Product returns, refurbish, recycle, dispose.",
          "Tracabilite reglementaire DEEE.", "WEEE regulatory traceability.",
          "Recycle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("type_operation", "str", "Type operation", "Type"),
           F("nb_unites", "int", "Nb unites", "Units"),
           F("site_prise_en_charge", "str", "Site", "Site"),
           F("date_prise_en_charge", "date", "Prise en charge", "Intake date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_operation", ["RETOUR_STANDARD", "SAV_REPARATION", "RECONDITIONNEMENT", "RECYCLAGE", "DESTRUCTION"], "RETOUR_STANDARD"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "BLOQUE"], "PLANIFIE")]),

        E("control-tower", "tpl_control_towers", "TplControlTower", "tpl-control-towers", "controltower",
          "Tour de controle multi-flux", "Multi-flow control tower",
          "Pilotage transversal commandes, stock, transport, incidents.",
          "Cross-cutting order/stock/transport/incident command.",
          "Alertes croisees temps reel.", "Real-time cross alerts.",
          "RadioTower", "reference",
          [F("reference", "str", "Reference session", "Session reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("date_horodatage", "datetime", "Horodatage", "Timestamp"),
           F("nombre_alertes", "int", "Nb alertes", "Alerts count"),
           F("nombre_incidents", "int", "Nb incidents", "Incidents count"),
           F("taux_service_pct", "int", "Taux service (%)", "Service level (%)"),
           F("operateur_tour", "str", "Operateur tour", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_MARCHE", "DEGRADE", "HORS_LIGNE"], "EN_MARCHE")]),
    ],
)
