"""Manifest Vague D — batch D2b (portails metier « sober & justifie »).

  - portail-declarant  -> perm_module="transit" (« transit.*.* » TRANSIT_PRINCIPAL)
    traces documentaires que le declarant en douane prepare, DISTINCTES des
    dossiers/declarations maitresses du routeur transit_deep.
  - portail-commercial -> perm_module="b2b" (« b2b.*.* » RESPONSABLE_COMMERCIAL)
    objets de prospection/gestion de compte que le commercial saisit, DISTINCTS
    des contrats/reservations maitresses du routeur b2b_deep.

Chaine Alembic 091-092 depuis 090_qhse_portal_d_deep. Aucune valeur fabriquee ;
statut = cycle de vie metier explicite.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── portail-declarant (+19 -> 20) ───────────────────────────────────────────
MODULES["declarant_d"] = dict(
    module_key="declarant_d", module_slug="portail-declarant",
    module_path="portail-declarant", perm_module="transit",
    registre_filename="registres_c",
    revision="091", down_revision="090_qhse_portal_d_deep",
    entities=[
        E("customs-declarations", "decl_customs_declarations", "DeclCustomsDeclaration", "decl-customs-declarations",
          "customs_declaration", "Declarations en douane", "Customs declarations",
          "Declaration detaillee deposee par le declarant pour une masse.",
          "Detailed declaration filed by the declarant for a shipment.",
          "Le regime douanier determine les droits dus.",
          "The customs regime determines the duties owed.",
          "ScrollText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("masse", "str", "Masse", "Shipment"),
           F("regime", "str", "Regime", "Regime"),
           F("valeur_douane", "num", "Valeur en douane", "Customs value"),
           F("date_depot", "datetime", "Date depot", "Filing date"),
           F("statut", "str", "Statut", "Status")],
          [EN("regime", ["IMPORT", "EXPORT", "TRANSIT", "ENTREPOT"]),
           EN("statut", ["PREPARATION", "DEPOSEE", "VALIDEE", "REJETEE", "CONTROLE"])]),

        E("hs-classifications", "decl_hs_classifications", "DeclHsClassification", "decl-hs-classifications",
          "hs_classification", "Classifications douanieres (HS)", "HS classifications",
          "Attribution du code SH/HS d' une marchandise.",
          "Assignment of the HS code of a good.",
          "Le code conditionne droits et reglementations.",
          "The code conditions duties and regulations.",
          "Tags", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("designation", "str", "Designation", "Description"),
           F("code_hs", "str", "Code SH", "HS code"),
           F("taux_droit", "num", "Taux de droit", "Duty rate"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSE", "LIE", "REVOQUE", "A_REVISER"])]),

        E("origin-certificates", "decl_origin_certificates", "DeclOriginCertificate", "decl-origin-certificates",
          "origin_certificate", "Certificats d' origine", "Origin certificates",
          "Justificatif d' origine preferentielle ou non d' une marchandise.",
          "Proof of preferential or non-preferential origin.",
          "Le type et le pays d' origine ouvrent un droit preferentiel.",
          "Type and origin country open a preferential right.",
          "Award", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type", "str", "Type", "Type"),
           F("pays_origine", "str", "Pays d' origine", "Origin country"),
           F("numero", "str", "Numero", "Number"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["EUR1", "A.TR", "CERTINE", "ATTA_ORIGINE"]),
           EN("statut", ["DEMANDE", "EMIS", "EXPIRE", "REVOQUE"])]),

        E("customs-valuations", "decl_customs_valuations", "DeclCustomsValuation", "decl-customs-valuations",
          "customs_valuation", "Valeurs en douane", "Customs valuations",
          "Determination de la valeur en douane d' une marchandise.",
          "Determination of the customs value of a good.",
          "La methode de valuation (transaction, identique...) conditionne la base.",
          "The valuation method conditions the base.",
          "Scale", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("masse", "str", "Masse", "Shipment"),
           F("methode", "str", "Methode", "Method"),
           F("valeur", "num", "Valeur", "Value"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("methode", ["TRANSACTION", "IDENTIQUE", "SIMILAIRE", "DEDUCTION", "RECONSTITUE"]),
           EN("statut", ["CALCULE", "SOUMIS", "ACCEPTE", "RECONTESTE"])]),

        E("incoterms-records", "decl_incoterms", "DeclIncotermsRecord", "decl-incoterms-records",
          "incoterms_record", "Incoterms", "Incoterms records",
          "Incoterm applicable a une operation d' import / export.",
          "Incoterm applicable to an import/export operation.",
          "L' incoterm repartit frais et transfert de risque.",
          "The incoterm splits cost and risk transfer.",
          "Ship", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("code", "str", "Code", "Code"),
           F("lieu", "str", "Lieu", "Place"),
           F("vendeur", "str", "Vendeur", "Seller"),
           F("acheteur", "str", "Acheteur", "Buyer"),
           F("statut", "str", "Statut", "Status")],
          [EN("code", ["EXW", "FCA", "FOB", "CFR", "CIF", "DAP", "DPU", "DDP"]),
           EN("statut", ["PROPOSE", "ACCEPTE", "AMENDE", "CADUC"])]),

        E("import-licenses", "decl_import_licenses", "DeclImportLicense", "decl-import-licenses",
          "import_license", "Licences d' importation", "Import licenses",
          "Autorisation administrative d' importer certaines marchandises.",
          "Administrative authorization to import certain goods.",
          "Le quota et la validite bornent la licence.",
          "Quota and validity bound the license.",
          "FileBadge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("quota", "int", "Quota", "Quota"),
           F("utilisable", "int", "Utilise", "Used"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDEE", "OCTROYEE", "EPUISEE", "EXPIREE"])]),

        E("export-licenses", "decl_export_licenses", "DeclExportLicense", "decl-export-licenses",
          "export_license", "Licences d' exportation", "Export licenses",
          "Autorisation d' exporter des biens a double usage ou regulates.",
          "Authorization to export dual-use or regulated goods.",
          "La destination et la nature du bien conditionnent l' autorisation.",
          "Destination and goods nature condition the authorization.",
          "FileCheck2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("bien", "str", "Bien", "Goods"),
           F("destination", "str", "Destination", "Destination"),
           F("usage", "str", "Usage", "Use"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("usage", ["CIVIL", "DOUBLE_USAGE", "MILITAIRE"]),
           EN("statut", ["INSTRUIT", "ACCORD", "REFUSE", "EXPIRE"])]),

        E("pre-clearance-submissions", "decl_pre_clearances", "DeclPreClearance", "decl-pre-clearance-submissions",
          "pre_clearance", "Pre-dedouanements", "Pre-clearance submissions",
          "Depot anticipe du dossier pour fluidifier la sortie.",
          "Advance filing to smooth the release.",
          "Anticiper le depot reduit les temps d' immoobilisation.",
          "Filing early reduces dwell time.",
          "Hourglass", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("masse", "str", "Masse", "Shipment"),
           F("arrivee_prevue", "datetime", "Arrivee prevue", "ETA"),
           F("depot", "datetime", "Depot", "Submission"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PREPARE", "DEPOSE", "ACCEPTE", "REFUSE", "TARDIF"])]),

        E("customs-invoices", "decl_customs_invoices", "DeclCustomsInvoice", "decl-customs-invoices",
          "customs_invoice", "Factures commerciales", "Customs invoices",
          "Facture commerciale jointe au dossier douanier.",
          "Commercial invoice attached to the customs file.",
          "La devise et la base (CIF/FOB) justifient la valeur.",
          "Currency and basis (CIF/FOB) justify the value.",
          "Receipt", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("fournisseur", "str", "Fournisseur", "Supplier"),
           F("montant", "num", "Montant", "Amount"),
           F("devise", "str", "Devise", "Currency"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("devise", ["XOF", "EUR", "USD"]),
           EN("statut", ["JOINT", "VERIFIE", "ECART", "MANQUANT"])]),

        E("packing-lists", "decl_packing_lists", "DeclPackingList", "decl-packing-lists",
          "packing_list", "Colisages douaniers", "Customs packing lists",
          "Listage des colis d' une masse pour le controle douanier.",
          "Parcel listing of a shipment for customs control.",
          "Le nombre de colis doit correspondre au connaissement.",
          "Parcel count must match the bill of lading.",
          "Boxes", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("masse", "str", "Masse", "Shipment"),
           F("nb_colis", "int", "Nb colis", "Parcels"),
           F("poids_net", "num", "Poids net", "Net weight"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ETABLI", "CONTROLE", "ECART", "VALIDE"])]),

        E("certificates-of-analysis", "decl_coa", "DeclCertificateAnalysis", "decl-certificates-of-analysis",
          "certificate_analysis", "Certificats d' analyse", "Certificates of analysis",
          "Analyse laboratoire attestant la conformite d' une marchandise.",
          "Lab analysis attesting a good's conformity.",
          "Les parametres analyzes prouvent la conformite normative.",
          "Analyzed parameters prove normative conformity.",
          "FlaskConical", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("laboratoire", "str", "Laboratoire", "Laboratory"),
           F("parametres", "text", "Parametres", "Parameters"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "CONFORME", "NON_CONFORME", "REFAIRE"])]),

        E("phytosanitary-applications", "decl_phyto_apps", "DeclPhytosanitaryApp", "decl-phytosanitary-applications",
          "phytosanitary_app", "Demandes phytosanitaires", "Phytosanitary applications",
          "Demande de certificat phytosanitaire pour vegetaux/produits.",
          "Request for a phytosanitary certificate for plants/products.",
          "L' inspection conditionne la delivrance du certificat.",
          "The inspection conditions the certificate issue.",
          "BookMarked", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("destination", "str", "Destination", "Destination"),
           F("date_controle", "date", "Date controle", "Control date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "CONTROLE", "DELIVRE", "REFUSE"])]),

        E("customs-payments", "decl_customs_payments", "DeclCustomsPayment", "decl-customs-payments",
          "customs_payment", "Paiements douaniers", "Customs payments",
          "Acquittement des droits et taxes de douane.",
          "Settlement of customs duties and taxes.",
          "Le montant paye doit egaler la liquidation.",
          "The amount paid must equal the assessment.",
          "Banknote", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("declaration", "str", "Declaration", "Declaration"),
           F("montant", "num", "Montant", "Amount"),
           F("type_droit", "str", "Type de droit", "Duty type"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_droit", ["DROIT_COMMUN", "TVA_IMPORT", "STATISTIQUE", "PARAFISCAL"]),
           EN("statut", ["LIQUIDE", "A_PAYER", "PAYE", "CONTESTE"])]),

        E("transit-documents", "decl_transit_documents", "DeclTransitDocument", "decl-transit-documents",
          "transit_document", "Documents de transit (T1/T2)", "Transit documents (T1/T2)",
          "Document d' accompagnement d' un regime de transit.",
          "Accompanying document of a transit regime.",
          "Le dechargement au bureau d' arrivee clot le transit.",
          "Discharge at the arrival office closes the transit.",
          "Container", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type", "str", "Type", "Type"),
           F("bureau_depart", "str", "Bureau de depart", "Departure office"),
           F("bureau_arrivee", "str", "Bureau d' arrivee", "Arrival office"),
           F("garantie", "num", "Garantie", "Guarantee"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["T1", "T2", "TD", "CARNET_TIR"]),
           EN("statut", ["EMIS", "EN_ROUTE", "DECHARGE", "NON_DECHARGE"])]),

        E("dangerous-goods-decls", "decl_dg_declarations", "DeclDangerousGoods", "decl-dangerous-goods-decls",
          "dangerous_goods_decl", "Declarations marchandises dangereuses", "Dangerous goods declarations",
          "Declaration ADR/IMDG d' une expedition de matieres dangereuses.",
          "ADR/IMDG declaration of a dangerous goods shipment.",
          "Le numero ONU et la classe conditionnent l' acceptation.",
          "UN number and class condition acceptance.",
          "Siren", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("numero_onu", "str", "Numero ONU", "UN number"),
           F("classe", "str", "Classe", "Class"),
           F("quantite", "num", "Quantite", "Quantity"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PREPAREE", "VERIFIEE", "ACCEPT", "REFUSEE"])]),

        E("bonded-warehouse-entries", "decl_bonded_entries", "DeclBondedWarehouseEntry", "decl-bonded-warehouse-entries",
          "bonded_warehouse_entry", "Entrees en entrepot sous douane", "Bonded warehouse entries",
          "Depot de marchandise sous controle douanier sans paiement immediat.",
          "Storing goods under customs control without immediate payment.",
          "La duree de sejour et la mise en libre prouve la sortie.",
          "Stay duration and release prove the exit.",
          "Archive", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("entrepot", "str", "Entrepot", "Warehouse"),
           F("masse", "str", "Masse", "Shipment"),
           F("entree", "datetime", "Entree", "Entry"),
           F("sortie_prevue", "datetime", "Sortie prevue", "Planned exit"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_ENTREPOT", "PARTIELLE", "SORTIE", "LITIGE"])]),

        E("duty-relief-claims", "decl_duty_relief", "DeclDutyReliefClaim", "decl-duty-relief-claims",
          "duty_relief_claim", "Demandes de franchise de droits", "Duty relief claims",
          "Demande d' exoneration ou de remboursement de droits.",
          "Request for duty exemption or drawback.",
          "Le motif (investissement, regime) justifie la franchise.",
          "The reason (investment, regime) justifies the relief.",
          "Percent", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("motif", "str", "Motif", "Reason"),
           F("declaration", "str", "Declaration", "Declaration"),
           F("montant_exonere", "num", "Montant exonere", "Relieved amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("motif", ["INVESTISSEMENT", "REEXPORT", "ENTREPOT", "ACCORD"]),
           EN("statut", ["DEMANDE", "INSTRUIT", "ACCORD", "REFUS"])]),

        E("manifest-corrections", "decl_manifest_corrections", "DeclManifestCorrection", "decl-manifest-corrections",
          "manifest_correction", "Rectifications de manifeste", "Manifest corrections",
          "Demande de rectification d' un manifeste de chargement.",
          "Request to correct a loading manifest.",
          "L' ecart constate doit etre motive et trace.",
          "The observed variance must be justified and traced.",
          "FileWarning", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("manifeste", "str", "Manifeste", "Manifest"),
           F("objet_rectification", "text", "Objet de la rectification", "Correction object"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "EN_COURS", "APPLIQUEE", "REJETEE"])]),

        E("customs-audit-support", "decl_audit_support", "DeclCustomsAuditSupport", "decl-customs-audit-support",
          "customs_audit_support", "Support controle douanier", "Customs audit support",
          "Dossier de pieces prepare pour un controle / verification douane.",
          "Evidence pack prepared for a customs audit.",
          "La completeness des pieces conditionne la levee du controle.",
          "Document completeness conditions the audit closure.",
          "FolderSearch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("controle", "str", "Controle", "Audit"),
           F("periode", "str", "Periode", "Period"),
           F("pieces_fournies", "int", "Pieces fournies", "Docs provided"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "RASSEMBLE", "SOUVIS", "CLOTURE"])]),
    ],
)

# ─── portail-commercial (+16 -> 20) ──────────────────────────────────────────
MODULES["commercial_d"] = dict(
    module_key="commercial_d", module_slug="portail-commercial",
    module_path="portail-commercial", perm_module="b2b",
    registre_filename="registres_c",
    revision="092", down_revision="091_declarant_d_deep",
    entities=[
        E("leads", "comm_leads", "CommLead", "comm-leads",
          "lead", "Pistes commerciales", "Leads",
          "Contact potentiel identifie par le commercial.",
          "Potential contact identified by the salesperson.",
          "La source et la qualification pilotent le suivi.",
          "Source and qualification drive the follow-up.",
          "UserPlus", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prospect", "str", "Prospect", "Prospect"),
           F("source", "str", "Source", "Source"),
           F("segment", "str", "Segment", "Segment"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("source", ["SALON", "INBOUND", "PROSPECTION", "RECOMMANDATION"]),
           EN("statut", ["NOUVEAU", "QUALIFIE", "TRANSFORME", "PERDU"])]),

        E("opportunities", "comm_opportunities", "CommOpportunity", "comm-opportunities",
          "opportunity", " opportunites", "Opportunities",
          "Occasion de vente suivie en pipeline par le commercial.",
          "Sales opportunity tracked in the pipeline.",
          "Le montant et la phase estiment la probalite de gain.",
          "Amount and stage estimate the win probability.",
          "Target", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("libelle", "str", "Libelle", "Title"),
           F("montant_estime", "num", "Montant estime", "Estimated amount"),
           F("cloture_prevue", "date", "Cloture prevue", "Expected close"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["QUALIFIEE", "PROPOSITION", "NEGOCIATION", "GAGNEE", "PERDUE"])]),

        E("quotes", "comm_quotes", "CommQuote", "comm-quotes",
          "quote", "Devis", "Quotes",
          "Proposition commerciale chiffree emise pour un client.",
          "Priced commercial proposal issued to a client.",
          "La validite borne la duree de l' offre.",
          "Validity bounds the offer duration.",
          "FileText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("montant", "num", "Montant", "Amount"),
           F("validite", "date", "Validite", "Validity"),
           F("date_emission", "date", "Emission", "Issued"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "EMIS", "ACCEPTE", "REFUSE", "EXPIRE"])]),

        E("sales-orders", "comm_sales_orders", "CommSalesOrder", "comm-sales-orders",
          "sales_order", "Commandes clients", "Sales orders",
          "Commande fermee passe par le client via le commercial.",
          "Firmed order placed by the client via the salesperson.",
          "La confirmation de commande engage la livraison.",
          "The order confirmation commits delivery.",
          "ShoppingCart", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("devis", "str", "Devis", "Quote"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ENREGISTREE", "CONFIRME", "EN_PREPARATION", "LIVREE", "ANNULEE"])]),

        E("customer-visits", "comm_customer_visits", "CommCustomerVisit", "comm-customer-visits",
          "customer_visit", "Visites clients", "Customer visits",
          "Compte-rendu d' une visite chez un client.",
          "Report of a visit to a client.",
          "L' objectif et le resultat structurent la relation.",
          "The objective and outcome structure the relationship.",
          "MapPinned", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("date", "datetime", "Date", "Date"),
           F("interlocuteur", "str", "Interlocuteur", "Contact"),
           F("compte_rendu", "text", "Compte-rendu", "Report"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EFFECTUE", "REPORTE", "ANNULE"])]),

        E("samples-requests", "comm_samples", "CommSampleRequest", "comm-samples-requests",
          "sample_request", "Demandes d' echantillons", "Sample requests",
          "Demande d' envoi d' un echantillon a un prospect/client.",
          "Request to send a sample to a prospect/client.",
          "La quantite et le destinataire preparent l' envoi.",
          "Quantity and recipient prepare the shipment.",
          "Boxes", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("produit", "str", "Produit", "Product"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "PREPARE", "EXPEDIE", "FEEDBACK", "REFUSE"])]),

        E("tenders", "comm_tenders", "CommTender", "comm-tenders",
          "tender", "Appels d' offres", "Tenders",
          "Reponse a un appel d' offres public ou prive.",
          "Response to a public or private tender.",
          "La date limite et le depot engagent la candidature.",
          "The deadline and filing commit the bid.",
          "Newspaper", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("acheteur", "str", "Acheteur", "Buyer"),
           F("objet", "str", "Objet", "Object"),
           F("date_limite", "date", "Date limite", "Deadline"),
           F("montant_offre", "num", "Montant offre", "Bid amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["IDENTIFIE", "EN_PREPARATION", "SOUMIS", "GAGNE", "PERDU"])]),

        E("contract-renewals", "comm_contract_renewals", "CommContractRenewal", "comm-contract-renewals",
          "contract_renewal", "Renouvellements de contrat", "Contract renewals",
          "Suivi du renouvellement d' un contrat client.",
          "Tracking of a client contract renewal.",
          "L' echeance et la valeur engageent l' anticipation.",
          "The due date and value drive the anticipation.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("contrat", "str", "Contrat", "Contract"),
           F("echeance", "date", "Echeance", "Due date"),
           F("valeur", "num", "Valeur", "Value"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_TRAITER", "NEGOCIE", "RENOUVELE", "RESILIE"])]),

        E("price-requests", "comm_price_requests", "CommPriceRequest", "comm-price-requests",
          "price_request", "Demandes de prix", "Price requests",
          "Demande de tarification specifique d' un client.",
          "Request for a client's specific pricing.",
          "La remise accordee est justifiee par le volume.",
          "The granted discount is justified by volume.",
          "CircleDollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("produit", "str", "Produit", "Product"),
           F("remise", "num", "Remise (%)", "Discount (%)"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["REÇUE", "INSTRUIT", "ACCEPTE", "REFUSE"])]),

        E("credit-requests", "comm_credit_requests", "CommCreditRequest", "comm-credit-requests",
          "credit_request", "Demandes d' encours client", "Credit requests",
          "Demande d' augmentation de la ligne de credit d' un client.",
          "Request to raise a client's credit line.",
          "Le montant sollicite doit rester coherent avec le risque.",
          "The requested amount must stay consistent with risk.",
          "CreditCard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("encours_actuel", "num", "Encours actuel", "Current limit"),
           F("montant_souhaite", "num", "Montant souhaite", "Desired amount"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMIS", "INSTRUIT", "ACCORDE", "REFUSE", "EXPIRE"])]),

        E("order-modifications", "comm_order_modifications", "CommOrderModification", "comm-order-modifications",
          "order_modification", "Modifications de commande", "Order modifications",
          "Avenant demande par le client sur une commande confirmee.",
          "Change requested by the client on a confirmed order.",
          "Toute modification apres confirmation est tracee et justifiee.",
          "Any post-confirmation change is traced and justified.",
          "GitBranch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commande", "str", "Commande", "Order"),
           F("changement", "text", "Changement", "Change"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "APPLIQUE", "REFUSE", "IMPACT_COUT"])]),

        E("customer-complaints", "comm_complaints", "CommCustomerComplaint", "comm-customer-complaints",
          "customer_complaint", "Reclamations clients", "Customer complaints",
          "Reclamation exprimee par un client via son commercial.",
          "Complaint raised by a client via the salesperson.",
          "Le delai de traitement mesure la qualite de service.",
          "The handling time measures service quality.",
          "MessageSquare", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("objet", "str", "Objet", "Subject"),
           F("canal", "str", "Canal", "Channel"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("canal", ["EMAIL", "TELEPHONE", "PORTAIL", "VISITE"]),
           EN("statut", ["OUVERTE", "EN_COURS", "RESOLUE", "ESCALADEE"])]),

        E("upsell-records", "comm_upsells", "CommUpsellRecord", "comm-upsell-records",
          "upsell_record", "Actions de vente additionnelle", "Upsell records",
          "Opportunite de vente supplementaire sur un compte existant.",
          "Additional sales opportunity on an existing account.",
          "Le potentiel identifie alimente le chiffre d' affaires.",
          "The identified potential feeds revenue.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("offre", "str", "Offre", "Offer"),
           F("montant_potentiel", "num", "Montant potentiel", "Potential amount"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["IDENTIFIE", "PROPOSE", "CONVERTI", "PERDU"])]),

        E("commission-statements", "comm_commissions", "CommCommissionStatement", "comm-commission-statements",
          "commission_statement", "Etats de commission", "Commission statements",
          "Calcul de la commission due au commercial sur ses ventes.",
          "Calculation of the commission owed to the salesperson.",
          "Le taux applique aux ventes valide conditionne la commission.",
          "The rate applied to validated sales conditions the commission.",
          "Percent", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commercial", "str", "Commercial", "Salesperson"),
           F("periode", "str", "Periode", "Period"),
           F("base_vente", "num", "Base de vente", "Sales base"),
           F("taux", "num", "Taux (%)", "Rate (%)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CALCULE", "SOUMIS", "VALIDE", "PAYE", "CONTESTE"])]),

        E("pipeline-reviews", "comm_pipeline_reviews", "CommPipelineReview", "comm-pipeline-reviews",
          "pipeline_review", "Revues de pipeline", "Pipeline reviews",
          "Revue periodique du pipeline commercial d' un representant.",
          "Periodic review of a rep's sales pipeline.",
          "La valeur ponderee projette le chiffre d' affaires futur.",
          "The weighted value projects future revenue.",
          "LineChart", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("commercial", "str", "Commercial", "Salesperson"),
           F("nb_opportunites", "int", "Nb opportunites", "Opportunities"),
           F("valeur_ponderee", "num", "Valeur ponderee", "Weighted value"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "FAITE", "A_ACTION", "CLOTURE"])]),
    ],
)
