"""Manifest Vague A : porte les 6 modules metiers core a >= 20 sous-modules reels.

Chaque module ci-dessous est une EXTENSION (« *_b ») d'un module deja genere :
  - module_slug / module_path / perm_module IDENTIQUES au module d'origine
    -> le routeur est monte sous le MEME prefixe /api/v1/<slug> et les nouveaux
    codes de permission <perm_module>.<nouveau_sous>.<action> sont deja couverts
    par les wildcards ROLE_GRANTS existants (CHEF_PARC « aerien/ferroviaire/
    fluvial/log3pl/parc.*.* », QHSE « qhse.*.* », AUDITEUR « *.read ») ;
  - module_key / table / class_name / slug / entite DIFFERENTS -> aucun conflit
    de route, de table ou de classe ; registre_frontend separe (registres_b).

Honnetete Zero-Mock : chaque entite est un objet metier reel et nomme du domain
(dock scheduling, RMA, MAWB/HAWB, BSD, PTW, etc.), pas un placeholder creux.

Convention d'honnetete : aucune valeur par defaut fabriquee ; NULL = « non
enregistre » ; statut = cycle de vie metier explicite.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── logistique-3pl (+9 -> 20) ────────────────────────────────────────────
MODULES["log3pl_b"] = dict(
    module_key="log3pl_b", module_slug="logistique-3pl",
    module_path="logistique-3pl", perm_module="log3pl",
    registre_filename="registres_b",
    revision="067", down_revision="066_merge_expansion_rbac",
    entities=[
        E("dock-appointments", "tplb_dock_appointments", "TplDockAppointment", "tplb-dock-appointments",
          "dock_appointment", "Rendez-vous quais (dock scheduling)", "Dock appointments",
          "Reservation des creneaux de quai pour chargement/dechargement.",
          "Dock slot reservation for loading/unloading.",
          "Un creneau par vehicule ; penalite si no-show.", "One slot per vehicle; no-show penalty.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference creneau", "Slot reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("numero_quai", "str", "Numero quai", "Dock number"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("immatriculation", "str", "Immatriculation", "Plate"),
           F("type_mouvement", "str", "Type mouvement", "Movement type"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_mouvement", ["ENTREE", "SORTIE"], "ENTREE"),
           EN("statut", ["RESERVE", "CONFIRME", "EN_COURS", "TERMINE", "NO_SHOW", "ANNULE"], "RESERVE")]),

        E("loading-plans", "tplb_loading_plans", "TplLoadingPlan", "tplb-loading-plans",
          "loading_plan", "Plans de chargement camion", "Truck loading plans",
          "Calage et plan de chargement par expedition.",
          "Stowage and loading plan per shipment.",
          "Verifie charge utile et repartition essieux.", "Checks payload and axle load.",
          "Layers", "reference",
          [F("reference", "str", "Reference plan", "Plan reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("numero_camion", "str", "Camion", "Truck"),
           F("nb_colis", "int", "Nb colis", "Parcels"),
           F("poids_total_kg", "int", "Poids total (kg)", "Total weight (kg)"),
           F("volume_m3", "int", "Volume (m3)", "Volume (m3)"),
           F("taux_remplissage_pct", "int", "Taux remplissage (%)", "Fill rate (%)"),
           F("date_plan", "datetime", "Date plan", "Plan date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "VALIDE", "CHARGE", "PARTI", "ANNULE"], "BROUILLON")]),

        E("shipment-manifests", "tplb_shipment_manifests", "TplShipmentManifest", "tplb-shipment-manifests",
          "shipment_manifest", "Manifestes d' expedition", "Shipment manifests",
          "Manifeste regroupant les colis d' une expedition.",
          "Manifest grouping parcels of a shipment.",
          "Document opposable au transporteur.", "Document enforceable against carrier.",
          "ScrollText", "numero_manifeste",
          [F("numero_manifeste", "str", "Numero manifeste", "Manifest number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("site_depart", "str", "Site depart", "Origin site"),
           F("site_arrivee", "str", "Site arrivee", "Destination site"),
           F("nb_colis", "int", "Nb colis", "Parcels"),
           F("poids_total_kg", "int", "Poids total (kg)", "Total weight (kg)"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERT", "CLOTURE", "TRANSFERT", "LIVRE", "ANNULE"], "OUVERT")]),

        E("inventory-transfers", "tplb_inventory_transfers", "TplInventoryTransfer", "tplb-inventory-transfers",
          "inventory_transfer", "Transferts inter-entrepots", "Inter-warehouse transfers",
          "Mouvement de stock entre deux sites du donneur d ordre.",
          "Stock movement between two client sites.",
          "Ecart d inventaire si reception != expedition.", "Variance if receipt != shipment.",
          "ArrowRightLeft", "reference",
          [F("reference", "str", "Reference transfert", "Transfer reference", required=True, search=True),
           F("site_source", "str", "Site source", "Source site"),
           F("site_destinataire", "str", "Site destinataire", "Destination site"),
           F("sku", "str", "SKU", "SKU"),
           F("quantite_expediee", "int", "Quantite expediee", "Shipped qty"),
           F("quantite_recue", "int", "Quantite recue", "Received qty"),
           F("date_transfert", "date", "Date transfert", "Transfer date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "EXPEDIE", "EN_TRANSIT", "RECU", "ECART", "CLOTURE"], "DEMANDE")]),

        E("cold-chain-logs", "tplb_cold_chain_logs", "TplColdChainLog", "tplb-cold-chain-logs",
          "cold_chain_log", "Journal chaine du froid", "Cold chain logs",
          "Releves de temperature des produits sous temperature dirigee.",
          "Temperature readings for temperature-controlled goods.",
          "Alerte si sortie de plage contractuelle.", "Alert when out of contractual range.",
          "ThermometerSnowflake", "reference",
          [F("reference", "str", "Reference releve", "Reading reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("produit", "str", "Produit", "Product"),
           F("sonde", "str", "Sonde", "Probe"),
           F("temperature_c", "num", "Temperature (C)", "Temperature (C)"),
           F("plage_min_c", "num", "Plage min (C)", "Min range (C)"),
           F("plage_max_c", "num", "Plage max (C)", "Max range (C)"),
           F("date_releve", "datetime", "Date releve", "Reading date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "HORS_PLAGE", "RUPTURE", "VERIFIE"], "CONFORME")]),

        E("return-authorizations", "tplb_return_authorizations", "TplReturnAuthorization", "tplb-return-authorizations",
          "return_authorization", "Autorisations de retour (RMA)", "Return authorizations (RMA)",
          "Dossiers de retour client acceptes et traces.",
          "Accepted and tracked customer return files.",
          "Numero RMA requis avant prise en charge.", "RMA number required before intake.",
          "PackageCheck", "numero_rma",
          [F("numero_rma", "str", "Numero RMA", "RMA number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("commande_originale", "str", "Commande originale", "Original order"),
           F("motif_retour", "str", "Motif retour", "Return reason"),
           F("nb_unites", "int", "Nb unites", "Units"),
           F("date_demande", "date", "Date demande", "Request date"),
           F("decision", "str", "Decision", "Decision"),
           F("statut", "str", "Statut", "Status")],
          [EN("motif_retour", ["CASSE", "ERREUR_PREP", "NON_CONFORME", "SURCOMMANDE", "AUTRE"], "CASSE"),
           EN("decision", ["ACCEPTE", "REFUSE", "REMBOURSE", "REMPPLACE"], "ACCEPTE"),
           EN("statut", ["OUVERT", "EN_ATTENTE", "RECU", "TRAITE", "CLOTURE"], "OUVERT")]),

        E("carrier-rates", "tplb_carrier_rates", "TplCarrierRate", "tplb-carrier-rates",
          "carrier_rate", "Grille tarifaire transporteurs", "Carrier rate cards",
          "Barèmes transporteurs par zone, poids et tranche.",
          "Carrier tariffs by zone, weight and bracket.",
          "Sert au calcul de facturation et au choix du transporteur.", "Drives billing and carrier choice.",
          "TableProperties", "code_tarif",
          [F("code_tarif", "str", "Code tarif", "Rate code", required=True, search=True),
           F("transporteur", "str", "Transporteur", "Carrier"),
           F("zone", "str", "Zone", "Zone"),
           F("poids_kg", "int", "Poids (kg)", "Weight (kg)"),
           F("prix_base_xaf", "int", "Prix base (XAF)", "Base price (XAF)"),
           F("prix_par_kg_xaf", "int", "Prix / kg (XAF)", "Price per kg (XAF)"),
           F("validite_debut", "date", "Debut validite", "Valid from"),
           F("validite_fin", "date", "Fin validite", "Valid until"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIF", "BROUILLON", "EXPIRE", "GELE"], "ACTIF")]),

        E("order-nodes", "tplb_order_nodes", "TplOrderNode", "tplb-order-nodes",
          "order_node", "Jalons de commande (track & trace)", "Order milestones (track & trace)",
          "Points de controle horodate d une commande (prise en charge a livraison).",
          "Timestamped checkpoints of an order (pickup to delivery).",
          "Alimente la promesse de service au client.", "Feeds the client service promise.",
          "GitCommitHorizontal", "reference",
          [F("reference", "str", "Reference jalon", "Milestone reference", required=True, search=True),
           F("numero_commande", "str", "Numero commande", "Order number"),
           F("code_jalon", "str", "Code jalon", "Milestone code"),
           F("libelle_jalon", "str", "Libelle", "Label"),
           F("date_horodatage", "datetime", "Horodatage", "Timestamp"),
           F("lieu", "str", "Lieu", "Location"),
           F("operateur", "str", "Operateur", "Operator"),
           F("statut", "str", "Statut", "Status")],
          [EN("code_jalon", ["COMMANDE", "PREPARATION", "ENLEVE", "TRANSIT", "LIVRE", "RETOUR"], "COMMANDE"),
           EN("statut", ["ATTEINT", "EN_RETARD", "MANQUANT"], "ATTEINT")]),

        E("damage-claims", "tplb_damage_claims", "TplDamageClaim", "tplb-damage-claims",
          "damage_claim", "Reclamations avaries 3PL", "3PL damage claims",
          "Dossiers d avarie et de litige sur les prestations.",
          "Damage and dispute files on services.",
          "Reserve financee si avarie > seuil.", "Financial reserve if damage above threshold.",
          "FileWarning", "numero_dossier",
          [F("numero_dossier", "str", "Numero dossier", "Claim number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("expedition_associee", "str", "Expedition associee", "Linked shipment"),
           F("type_avarie", "str", "Type avarie", "Damage type"),
           F("montant_reclame_xaf", "int", "Montant reclame (XAF)", "Claimed amount (XAF)"),
           F("date_ouverture", "date", "Date ouverture", "Open date"),
           F("date_resolution", "date", "Date resolution", "Resolution date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_avarie", ["CASSE", "PERTE", "VOL", "RETARD", "MAUVAIS_ETAT"], "CASSE"),
           EN("statut", ["OUVERT", "INSTRUCTION", "INDEMNISE", "REJETE", "CLOTURE"], "OUVERT")]),
    ],
)


# ─── transport-fluvial (+9 -> 20) ─────────────────────────────────────────
MODULES["fluvial_b"] = dict(
    module_key="fluvial_b", module_slug="transport-fluvial",
    module_path="transport-fluvial", perm_module="fluvial",
    registre_filename="registres_b",
    revision="068", down_revision="067_log3pl_b_deep",
    entities=[
        E("canal-sections", "flvb_canal_sections", "FluvialCanalSection", "fluvb-canal-sections",
          "canal_section", "Sections de voie navigable", "Canal sections",
          "Troncons de voie d eau avec cotes, biefs et restrictions.",
          "Waterway reaches with gauges, locks and restrictions.",
          "Base du calcul de tirant d eau pratique.", "Basis of practical draft calc.",
          "Route", "code_section",
          [F("code_section", "str", "Code section", "Section code", required=True, search=True),
           F("nom_bief", "str", "Nom du bief", "Reach name"),
           F("longueur_km", "int", "Longueur (km)", "Length (km)"),
           F("nb_ecluses", "int", "Nb ecluses", "Locks"),
           F("gabarit_max_t", "int", "Gabarit max (t)", "Max gauge (t)"),
           F("profondeur_cote_cm", "int", "Profondeur cotee (cm)", "Design depth (cm)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERT", "RESTRICTION", "TRAVAUX", "FERME"], "OUVERT")]),

        E("convoys", "flvb_convoys", "FluvialConvoy", "flvb-convoys",
          "convoy", "Convois pousses", "Push convoys",
          "Attelage pousseur + peniches associees.",
          "Pusher plus attached barges.",
          "Longueur et masse cumulées controlees.", "Combined length and mass checked.",
          "Link", "numero_convoi",
          [F("numero_convoi", "str", "Numero convoi", "Convoy number", required=True, search=True),
           F("pousseur", "str", "Pousseur", "Pusher"),
           F("nb_peniches", "int", "Nb peniches", "Barges"),
           F("masse_total_t", "int", "Masse totale (t)", "Total mass (t)"),
           F("longueur_total_m", "int", "Longueur totale (m)", "Total length (m)"),
           F("itineraire", "str", "Itineraire", "Route"),
           F("date_depart", "datetime", "Date depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONSTITUE", "EN_ROUTE", "ARRIVE", "DISSOCIE"], "CONSTITUE")]),

        E("ballast-operations", "flvb_ballast_ops", "FluvialBallastOperation", "flvb-ballast-operations",
          "ballast_operation", "Lestage / delestage", "Ballast operations",
          "Operations de lestage pour stabilite et tirant d eau.",
          "Ballasting for stability and draft.",
          "Enregistre masse d eau de lestage.", "Records ballast water mass.",
          "Droplets", "reference",
          [F("reference", "str", "Reference operation", "Operation reference", required=True, search=True),
           F("numero_flotte", "str", "Bateau", "Vessel"),
           F("type_operation", "str", "Type operation", "Operation type"),
           F("masse_balle_t", "int", "Masse lestage (t)", "Ballast mass (t)"),
           F("date_operation", "datetime", "Date", "Date"),
           F("terminal", "str", "Terminal", "Terminal"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_operation", ["LESTAGE", "DELESTAGE"], "LESTAGE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE"], "PLANIFIE")]),

        E("water-gauges", "flvb_water_gauges", "FluvialWaterGauge", "flvb-water-gauges",
          "water_gauge", "Echelles d eau / limnimetres", "Water level gauges",
          "Releves de niveau d eau par poste de mesure.",
          "Water level readings per gauging station.",
          "Declenche restriction quand cote sous seuil.", "Triggers restriction below threshold.",
          "Waves", "code_poste",
          [F("code_poste", "str", "Code poste", "Station code", required=True, search=True),
           F("nom_poste", "str", "Nom poste", "Station name"),
           F("bief", "str", "Bief", "Reach"),
           F("cote_cm", "int", "Cote (cm)", "Level (cm)"),
           F("cote_seuil_restr_cm", "int", "Seuil restriction (cm)", "Restriction threshold (cm)"),
           F("date_releve", "datetime", "Date releve", "Reading date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NORMAL", "BASE", "CREUE", "CRUE"], "NORMAL")]),

        E("berthing-slots", "flvb_berthing_slots", "FluvialBerthingSlot", "flvb-berthing-slots",
          "berthing_slot", "Creneaux d amarrage", "Berthing slots",
          "Attribution de postes d amarrage par creneau.",
          "Berth allocation per time slot.",
          "Evite conflit d occupation des appontements.", "Avoids berth occupancy conflict.",
          "Anchor", "reference",
          [F("reference", "str", "Reference creneau", "Slot reference", required=True, search=True),
           F("terminal", "str", "Terminal", "Terminal"),
           F("numero_appontement", "str", "Appontement", "Berth"),
           F("numero_flotte", "str", "Bateau", "Vessel"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["RESERVE", "OCCUPE", "LIBERE", "ANNULE"], "RESERVE")]),

        E("crew-rosters-river", "flvb_crew_rosters", "FluvialCrewRoster", "flvb-crew-rosters",
          "crew_roster", "Equipages fluviaux", "River crew rosters",
          "Affectation des equipes par bateau et par rotation.",
          "Crew assignment per vessel and rotation.",
          "Controle temps de repos reglementaire.", "Regulatory rest-time check.",
          "Users", "reference",
          [F("reference", "str", "Reference rotation", "Rotation reference", required=True, search=True),
           F("numero_flotte", "str", "Bateau", "Vessel"),
           F("chef_bord", "str", "Chef de bord", "Captain"),
           F("nb_marins", "int", "Nb marins", "Crew size"),
           F("date_debut", "date", "Debut", "Start"),
           F("date_fin", "date", "Fin", "End"),
           F("heures_service", "int", "Heures service", "Service hours"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EN_SERVICE", "REPOS", "TERMINE"], "PLANIFIE")]),

        E("cargo-manifests-river", "flvb_cargo_manifests", "FluvialCargoManifest", "flvb-cargo-manifests",
          "cargo_manifest", "Manifestes de chargement fluviaux", "River cargo manifests",
          "Liste des marchandises chargees par convoi.",
          "Goods loaded per convoy.",
          "Piece jointe a la lettre de voiture CMNI.", "Annex to the CMNI waybill.",
          "ListChecks", "numero_manifeste",
          [F("numero_manifeste", "str", "Numero manifeste", "Manifest number", required=True, search=True),
           F("numero_convoi", "str", "Convoi", "Convoy"),
           F("terminal_depart", "str", "Depart", "Origin terminal"),
           F("terminal_arrivee", "str", "Arrivee", "Destination terminal"),
           F("nb_colis", "int", "Nb colis", "Items"),
           F("masse_total_t", "int", "Masse totale (t)", "Total mass (t)"),
           F("date_emission", "date", "Date emission", "Issue date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMISE", "CHARGEE", "EN_ROUTE", "LIVRE", "CLOTURE"], "EMISE")]),

        E("port-fees-river", "flvb_port_fees", "FluvialPortFee", "flvb-port-fees",
          "port_fee", "Droits de port fluvial", "River port dues",
          "Tarifs de stationnement et de manutention par terminal.",
          "Berthing and handling dues per terminal.",
          "Factures au bateau ou au chargeur.", "Billed to vessel or shipper.",
          "ReceiptText", "code_tarif",
          [F("code_tarif", "str", "Code tarif", "Fee code", required=True, search=True),
           F("terminal", "str", "Terminal", "Terminal"),
           F("categorie", "str", "Categorie", "Category"),
           F("assiette", "str", "Assiette", "Basis"),
           F("montant_xaf", "int", "Montant (XAF)", "Amount (XAF)"),
           F("unite", "str", "Unite", "Unit"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["STATIONNEMENT", "MANUTENTION", "PASSAGE", "OUTILLAGE"], "STATIONNEMENT"),
           EN("statut", ["ACTIF", "BROUILLON", "EXPIRE"], "ACTIF")]),

        E("vessel-inspections", "flvb_vessel_inspections", "FluvialVesselInspection", "flvb-vessel-inspections",
          "vessel_inspection", "Visites techniques batellerie", "Vessel technical inspections",
          "Controles reglementaires des bateaux (communautaire/national).",
          "Regulatory vessel checks (EU/national).",
          "Conditionne la mise en service.", "Gates vessel release to service.",
          "ClipboardCheck", "numero_pv",
          [F("numero_pv", "str", "Numero PV", "Report number", required=True, search=True),
           F("numero_flotte", "str", "Bateau", "Vessel"),
           F("type_visite", "str", "Type visite", "Inspection type"),
           F("date_visite", "date", "Date visite", "Inspection date"),
           F("date_echeance", "date", "Echeance", "Due date"),
           F("resultat", "str", "Resultat", "Result"),
           F("observations", "text", "Observations", "Observations"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_visite", ["INITIALE", "PERIODIQUE", "SUPPLEMENTAIRE", "IMPREVUE"], "PERIODIQUE"),
           EN("resultat", ["CONFORME", "RESERVE", "NON_CONFORME"], "CONFORME"),
           EN("statut", ["PLANIFIEE", "EN_COURS", "VALIDEE", "EXPIREE"], "PLANIFIEE")]),
    ],
)


# ─── transport-aerien (+7 -> 20) ──────────────────────────────────────────
MODULES["aerien_b"] = dict(
    module_key="aerien_b", module_slug="transport-aerien",
    module_path="transport-aerien", perm_module="aerien",
    registre_filename="registres_b",
    revision="069", down_revision="068_fluvial_b_deep",
    entities=[
        E("house-waybills", "airb_house_waybills", "HouseAirWaybill", "airb-house-waybills",
          "house_waybill", "Lettres de transport house (HAWB)", "House air waybills",
          "Fractions consolidees sous une MAWB.",
          "Consolidated fractions under a master AWB.",
          "L agent de fret emet le HAWB au client.", "Forwarder issues HAWB to client.",
          "FileText", "numero_hawb",
          [F("numero_hawb", "str", "Numero HAWB", "HAWB number", required=True, search=True),
           F("numero_mawb", "str", "Numero MAWB", "MAWB number"),
           F("expediteur", "str", "Expediteur", "Shipper"),
           F("destinataire", "str", "Destinataire", "Consignee"),
           F("nb_colis", "int", "Nb colis", "Pieces"),
           F("poids_kg", "int", "Poids (kg)", "Weight (kg)"),
           F("nature_marchandise", "str", "Nature marchandise", "Goods type"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMIS", "CONSOLIDE", "CHARGE", "LIVRE", "LITIGE"], "EMIS")]),

        E("perishable-cargo", "airb_perishable_cargo", "PerishableCargo", "airb-perishable-cargo",
          "perishable_cargo", "Fret perishable (chaine du froid)", "Perishable cargo",
          "Marchandises perissables sous temperature dirigee.",
          "Temperature-controlled perishable goods.",
          "Respect des delais IATA PERishable.", "IATA perishable time limits.",
          "Snowflake", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("numero_mawb", "str", "MAWB", "MAWB"),
           F("produit", "str", "Produit", "Product"),
           F("plage_temp_c", "str", "Plage temperature (C)", "Temp range (C)"),
           F("poids_kg", "int", "Poids (kg)", "Weight (kg)"),
           F("date_embarquement", "datetime", "Embarquement", "Loading time"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["RECU", "CHAMBRE_FROIDE", "EMBARQUE", "LIVRE", "RUPTURE_CHAINE"], "RECU")]),

        E("live-animal-shipments", "airb_live_animals", "LiveAnimalShipment", "airb-live-animals",
          "live_animal", "Fret vivant (animaux)", "Live animal shipments",
          "Transport d animaux vivants conforme CRDA.",
          "Live animal transport compliant with CRDA.",
          "Conteneurs et ventilation homologues.", "Approved containers and ventilation.",
          "PawPrint", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("numero_mawb", "str", "MAWB", "MAWB"),
           F("espece", "str", "Espece", "Species"),
           F("nb_animaux", "int", "Nb animaux", "Animals"),
           F("type_conteneur", "str", "Type conteneur", "Container type"),
           F("date_depart", "datetime", "Depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_conteneur", ["CR1", "CR2", "CR3", "CONTAINER"], "CR1"),
           EN("statut", ["RESERVE", "ACCEPTE", "EN_VOL", "ARRIVE", "REFUSE"], "RESERVE")]),

        E("chartered-flights", "airb_chartered_flights", "CharteredFlight", "airb-chartered-flights",
          "chartered_flight", "Vols affretes", "Chartered flights",
          "Affretements ad hoc pour fret ou projet.",
          "Ad hoc charters for cargo or projects.",
          "Contrat d affretement et creneau reserve.", "Charter agreement and slot reserved.",
          "PlaneTakeoff", "numero_affretement",
          [F("numero_affretement", "str", "Numero affretement", "Charter number", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("immatriculation", "str", "Aéronef", "Aircraft"),
           F("depart_aeroport", "str", "Aeroport depart", "Origin airport"),
           F("arrivee_aeroport", "str", "Aeroport arrivee", "Destination airport"),
           F("capacite_tonnes", "int", "Capacite (t)", "Capacity (t)"),
           F("date_vol", "datetime", "Date vol", "Flight date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEVIS", "CONFIRME", "EFFECTUE", "ANNULE"], "CONFIRME")]),

        E("customs-clearance-air", "airb_customs_clearance", "AirCustomsClearance", "airb-customs-clearance",
          "customs_clearance", "Dedouanement fret aerien", "Air customs clearance",
          "Dossiers de dechargement et formalites douane aeroport.",
          "Aircraft offload and airport customs formalities.",
          "Bloque la mise a disposition tant que non decharge.", "Blocks release until cleared.",
          "Stamp", "numero_dossier",
          [F("numero_dossier", "str", "Numero dossier", "File number", required=True, search=True),
           F("numero_mawb", "str", "MAWB", "MAWB"),
           F("type_operation", "str", "Type operation", "Operation type"),
           F("bureau_douane", "str", "Bureau de douane", "Customs office"),
           F("droits_xaf", "int", "Droits (XAF)", "Duties (XAF)"),
           F("date_depot", "date", "Date depot", "Filing date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_operation", ["IMPORT", "EXPORT", "TRANSIT"], "IMPORT"),
           EN("statut", ["EN_ATTENTE", "DEPOSE", "CONTROLE", "DECHARGE", "BLOQUE"], "EN_ATTENTE")]),

        E("apron-movements", "airb_apron_movements", "ApronMovement", "airb-apron-movements",
          "apron_movement", "Mouvements piste (apron)", "Apron movements",
          "Mouvements aéronefs et vehicules piste par poste.",
          "Aircraft and ground vehicle movements per stand.",
          "Coordination PRA / marshaller.", "Stand and marshaller coordination.",
          "Move", "reference",
          [F("reference", "str", "Reference mouvement", "Movement reference", required=True, search=True),
           F("poste_parc", "str", "Poste de parc", "Stand"),
           F("immatriculation", "str", "Aéronef", "Aircraft"),
           F("type_mouvement", "str", "Type mouvement", "Movement type"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("date_fin", "datetime", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_mouvement", ["ARRIVEE", "DEPART", "PUSHBACK", "REPOSITIONNEMENT"], "ARRIVEE"),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "RETARDE"], "PLANIFIE")]),

        E("noise-compliance", "airb_noise_compliance", "NoiseComplianceRecord", "airb-noise-compliance",
          "noise_compliance", "Conformite nuisances sonores", "Noise compliance",
          "Mesures et conformite bruit des aéronefs / restrictions nocturnes.",
          "Aircraft noise measurements and curfew compliance.",
          "Sanction possible si depassement quota.", "Sanction if quota exceeded.",
          "VolumeX", "reference",
          [F("reference", "str", "Reference mesure", "Measurement reference", required=True, search=True),
           F("immatriculation", "str", "Aéronef", "Aircraft"),
           F("coefficient_bruit_db", "int", "Coefficient bruit (dB)", "Noise coefficient (dB)"),
           F("creneau", "str", "Creneau", "Time window"),
           F("date_mesure", "date", "Date mesure", "Measure date"),
           F("quota_consomme", "int", "Quota consomme", "Quota used"),
           F("statut", "str", "Statut", "Status")],
          [EN("creneau", ["JOUR", "SOIREE", "NUIT"], "JOUR"),
           EN("statut", ["CONFORME", "DEPASSEMENT", "SANCTIONNE", "EXEMPT"], "CONFORME")]),
    ],
)
