"""Manifest Vague C : porte 7 modules (compta/finance/RH/B2B/reports/admin/superadmin)
a >= 20 sous-modules reels.

Meme principe d'EXTENSION (« *_c ») que Vagues A/B.

POINT IMPORTANT - perm_module : le perm_module des manifests d'origine etait
obsolete (ex. « compta », « finance »). Les ROUTERS REELS deja deployes imposent
un autre prefixe, couvert par un wildcard ROLE_GRANTS :
  - comptabilite-ohada -> routeurs require_perm("comptabilite.*")  (« comptabilite.*.* »)
  - finance-ohada      -> routeurs require_perm("tresorerie.*")     (« tresorerie.*.* »)
  - rh-personnel       -> require_perm("rh.*")                      (« rh.*.* »)
  - client-b2b         -> require_perm("b2b.*")                     (« b2b.*.* »)
  - reports-bi / admin-saas / superadmin-cadc -> consoles plateforme
    (« reports.* » / « admin.* » / « superadmin.* ») : accessibles par les roles
    d'administration (et superuser), coherent avec les sous-modules deja presents.
On reutilise donc le prefixe REEL du routeur pour que les nouvelles routes soient
effectivement atteignables (pas des ecrans morts).

Honnetete Zero-Mock : chaque entite est un objet metier reel et nomme (contre-
passation, rapprochement bancaire, prevision de tresorerie, plan de formation,
contrat client, plan d'abonnement SaaS, cle de licence...), pas un placeholder.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── comptabilite-ohada (+2 -> 20) ───────────────────────────────────────────
MODULES["compta_c"] = dict(
    module_key="compta_c", module_slug="comptabilite-ohada",
    module_path="comptabilite-ohada", perm_module="comptabilite",
    registre_filename="registres_c",
    # Re-parente sur 081_coldchain_deep (branche pipeline->courier->coldchain restee
    # en tete separate sur 078_dashboard_b_deep) pour garder un seul head lineaire.
    revision="079", down_revision="081_coldchain_deep",
    entities=[
        E("journal-reversals", "cmptc_journal_reversals", "CmptcJournalReversal", "cmptc-journal-reversals",
          "journal_reversal", "Contre-passations d'ecritures", "Journal reversals",
          "Annulation d' une ecriture comptable par une ecriture inverse.",
          "Cancellation of a journal entry by an inverse entry.",
          "La contre-passation reference l' ecriture annulee ; jamais de suppression.",
          "Reversal references the cancelled entry; never delete.",
          "History", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ecriture_origine", "str", "Ecriture d'origine", "Original entry"),
           F("date_reversal", "date", "Date de contre-passation", "Reversal date"),
           F("compte_debit", "str", "Compte debit", "Debit account"),
           F("compte_credit", "str", "Compte credit", "Credit account"),
           F("montant", "num", "Montant", "Amount"),
           F("motif", "text", "Motif", "Reason"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSEE", "VALIDEE", "COMPTABILISEE", "REJETEE"])]),

        E("bank-reconciliations", "cmptc_bank_reconciliations", "CmptcBankReconciliation", "cmptc-bank-reconciliations",
          "bank_reconciliation", "Rapprochements bancaires", "Bank reconciliations",
          "Rapprochement entre solde comptable et releve bancaire.",
          "Match between book balance and bank statement.",
          "Ecart = solde comptable - solde bancaire ; points de controle justifies.",
          "Difference = book - bank; justified control points.",
          "Landmark", "reference",
          [F("reference", "str", "Reference rapprochement", "Reconciliation ref", required=True, search=True),
           F("compte_banque", "str", "Compte bancaire", "Bank account"),
           F("date_releve", "date", "Date releve", "Statement date"),
           F("solde_comptable", "num", "Solde comptable", "Book balance"),
           F("solde_bancaire", "num", "Solde bancaire", "Bank balance"),
           F("ecart", "num", "Ecart", "Difference"),
           F("date_rapprochement", "date", "Date rapprochement", "Reconciliation date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "EQUILIBRE", "ECART_CONSTATE", "VALIDE"])]),
    ],
)

# ─── finance-ohada (+2 -> 20) ────────────────────────────────────────────────
MODULES["finance_c"] = dict(
    module_key="finance_c", module_slug="finance-ohada",
    module_path="finance-ohada", perm_module="tresorerie",
    registre_filename="registres_c",
    revision="080", down_revision="079_compta_c_deep",
    entities=[
        E("cash-flow-forecasts", "finc_cash_flow_forecasts", "FincCashFlowForecast", "finc-cash-flow-forecasts",
          "cash_flow_forecast", "Previsions de tresorerie", "Cash flow forecasts",
          "Projection des entrees et sorties de tresorerie par periode.",
          "Projection of treasury inflows and outflows by period.",
          "Position finale = solde debut + entrees - sorties.",
          "Closing position = opening + inflows - outflows.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference prevision", "Forecast reference", required=True, search=True),
           F("periode", "str", "Periode", "Period"),
           F("solde_debut", "num", "Solde de debut", "Opening balance"),
           F("entrees_prevues", "num", "Entrees prevues", "Expected inflows"),
           F("sorties_prevues", "num", "Sorties prevues", "Expected outflows"),
           F("position_finale", "num", "Position finale", "Closing position"),
           F("horizon_jours", "int", "Horizon (jours)", "Horizon (days)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "SOUMIS", "VALIDE", "REVISION"])]),

        E("invoice-financing", "finc_invoice_financings", "FincInvoiceFinancing", "finc-invoice-financings",
          "invoice_financing", "Affacturage / escompte de factures", "Invoice financing",
          "Affacturage de factures clients pour accelerer la tresorerie.",
          "Factoring of client invoices to accelerate treasury.",
          "Le facteur avance un pourcentage de la facture ; marge et risque porteurs.",
          "Factor advances a percentage of the invoice; margin and recourse tracked.",
          "Coins", "reference",
          [F("reference", "str", "Reference dossier", "Facility reference", required=True, search=True),
           F("affacteur", "str", "Affacteur", "Factor"),
           F("facture", "str", "Facture cee", "Assigned invoice"),
           F("montant_facture", "num", "Montant facture", "Invoice amount"),
           F("avance_pct", "int", "Avance (%)", "Advance (%)"),
           F("commission", "num", "Commission", "Fee"),
           F("date_echeance", "date", "Echeance facture", "Invoice due date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "ACCEPTEE", "AVANCEE", "RECOUVREE", "REJETEE"])]),
    ],
)

# ─── rh-personnel (+2 -> 20) ─────────────────────────────────────────────────
MODULES["rh_c"] = dict(
    module_key="rh_c", module_slug="rh-personnel",
    module_path="rh-personnel", perm_module="rh",
    registre_filename="registres_c",
    revision="081", down_revision="080_finance_c_deep",
    entities=[
        E("training-plans", "rhc_training_plans", "RhCTrainingPlan", "rhc-training-plans",
          "training_plan", "Plans de formation", "Training plans",
          "Plan individuel ou collectif de developpement des competences.",
          "Individual or collective skills development plan.",
          "Heures financees vs heures realisees suivies par plan.",
          "Funded vs delivered hours tracked per plan.",
          "GraduationCap", "reference",
          [F("reference", "str", "Reference plan", "Plan reference", required=True, search=True),
           F("intitule", "str", "Intitule", "Title"),
           F("categorie", "str", "Categorie", "Category"),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("organisme", "str", "Organisme", "Provider"),
           F("heures_financees", "int", "Heures financees", "Funded hours"),
           F("heures_realisees", "int", "Heures realisees", "Delivered hours"),
           F("date_debut", "date", "Date debut", "Start date"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["TECHNIQUE", "SECURITE", "MANAGEMENT", "REGLEMENTAIRE"]),
           EN("statut", ["PLANIFIE", "EN_COURS", "TERMINE", "ABANDONNE"])]),

        E("disciplinary-records", "rhc_disciplinary_records", "RhCDisciplinaryRecord", "rhc-disciplinary-records",
          "disciplinary_record", "Registre disciplinaire", "Disciplinary records",
          "Consigne des sanctions et mesures disciplinaires.",
          "Log of sanctions and disciplinary measures.",
          "Chaque sanction reference un motif et une date d'effet.",
          "Each sanction references a reason and an effective date.",
          "Gavel", "reference",
          [F("reference", "str", "Reference dossier", "Case reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("type_sanction", "str", "Type de sanction", "Sanction type"),
           F("motif", "text", "Motif", "Reason"),
           F("date_effet", "date", "Date d'effet", "Effective date"),
           F("date_fin_effet", "date", "Fin d'effet", "End date"),
           F("decideur", "str", "Decideur", "Decision maker"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_sanction", ["AVERTISSEMENT", "BLAME", "MISE_PIED", "SUSPENSION", "LICENCIEMENT"]),
           EN("statut", ["OUVERT", "INSTRUIT", "APPLIQUEE", "LEVEE", "CONTESTEE"])]),
    ],
)

# ─── client-b2b (+5 -> 20) ───────────────────────────────────────────────────
MODULES["b2b_c"] = dict(
    module_key="b2b_c", module_slug="client-b2b",
    module_path="client-b2b", perm_module="b2b",
    registre_filename="registres_c",
    revision="082", down_revision="081_rh_c_deep",
    entities=[
        E("contract-agreements", "b2bc_contracts", "B2bCContractAgreement", "b2bc-contracts",
          "contract_agreement", "Contrats-cadres clients", "Contract agreements",
          "Accord commercial cadre avec un client B2B.",
          "Framework commercial agreement with a B2B client.",
          "Prix et echeance engages pour la duree du contrat.",
          "Prices and terms committed for the contract duration.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference contrat", "Contract reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("type_contrat", "str", "Type de contrat", "Contract type"),
           F("date_debut", "date", "Debut", "Start date"),
           F("date_fin", "date", "Fin", "End date"),
           F("valeur_annuelle", "num", "Valeur annuelle", "Annual value"),
           F("contact", "str", "Contact", "Contact"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_contrat", ["CADRE", "PRESTATION", "TRANSPORT", "MANUTENTION"]),
           EN("statut", ["NEGOCIATION", "SIGNE", "EXECUTION", "EXPIRE", "RESILIE"])]),

        E("price-lists", "b2bc_price_lists", "B2bCPriceList", "b2bc-price-lists",
          "price_list", "Grilles tarifaires client", "Price lists",
          "Tarifies negocies appliques aux commandes d' un client.",
          "Negotiated rates applied to a client's orders.",
          "Version et validite datent la grille.",
          "Version and validity date the list.",
          "Tags", "reference",
          [F("reference", "str", "Reference grille", "List reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("version", "str", "Version", "Version"),
           F("devise", "str", "Devise", "Currency"),
           F("date_debut_validite", "date", "Debut validite", "Valid from"),
           F("date_fin_validite", "date", "Fin validite", "Valid to"),
           F("remise_globale_pct", "int", "Remise globale (%)", "Global discount (%)"),
           F("statut", "str", "Statut", "Status")],
          [EN("devise", ["XOF", "EUR", "USD"]),
           EN("statut", ["BROUILLON", "ACTIVE", "GELEE", "REMPLEE"])]),

        E("sales-orders", "b2bc_sales_orders", "B2bCSalesOrder", "b2bc-sales-orders",
          "sales_order", "Commandes clients", "Sales orders",
          "Commande passee par un client B2B.",
          "Order placed by a B2B client.",
          "Le total engage la preparation jusqu' a la livraison.",
          "Total commits preparation through delivery.",
          "ShoppingCart", "reference",
          [F("reference", "str", "Reference commande", "Order reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("date_commande", "date", "Date commande", "Order date"),
           F("nb_lignes", "int", "Nombre de lignes", "Line count"),
           F("montant_total", "num", "Montant total", "Total amount"),
           F("date_livraison_souhaitee", "date", "Livraison souhaitee", "Requested delivery"),
           F("contrat_ref", "str", "Contrat", "Contract"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NOUVELLE", "CONFIRME", "EN_PREPARATION", "EXPEDIEE", "LIVREE", "ANNULEE"])]),

        E("customer-credit-accounts", "b2bc_credit_accounts", "B2bCCreditAccount", "b2bc-credit-accounts",
          "credit_account", "Encours clients", "Customer credit accounts",
          "Suivi de l'encours et de la limite de credit d' un client.",
          "Tracking of a client's balance and credit limit.",
          "L'encours ne doit pas depasser la limite accordee.",
          "Balance must not exceed the granted limit.",
          "CreditCard", "reference",
          [F("reference", "str", "Reference compte", "Account reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("limite_credit", "num", "Limite de credit", "Credit limit"),
           F("encours", "num", "Encours", "Balance"),
           F("delai_paiement_jours", "int", "Delai de paiement (j)", "Payment terms (d)"),
           F("date_dernier_paiement", "date", "Dernier paiement", "Last payment"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_TEMPS", "EN_RETARD", "BLOQUE", "SUSPENDU"])]),

        E("support-tickets", "b2bc_support_tickets", "B2bCSupportTicket", "b2bc-support-tickets",
          "support_ticket", "Tickets support client", "Support tickets",
          "Demande d' assistance ou reclamation d' un client B2B.",
          "Assistance request or complaint from a B2B client.",
          "Priorite et SLA conditionnent la prise en charge.",
          "Priority and SLA drive handling.",
          "LifeBuoy", "reference",
          [F("reference", "str", "Reference ticket", "Ticket reference", required=True, search=True),
           F("client", "str", "Client", "Client"),
           F("sujet", "str", "Sujet", "Subject"),
           F("categorie", "str", "Categorie", "Category"),
           F("priorite", "str", "Priorite", "Priority"),
           F("date_ouverture", "datetime", "Ouverture", "Opened"),
           F("date_resolution", "datetime", "Resolution", "Resolved"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["LIVRAISON", "FACTURATION", "QUALITE", "TECHNIQUE"]),
           EN("priorite", ["BASSE", "NORMALE", "HAUTE", "URGENTE"]),
           EN("statut", ["OUVERT", "EN_COURS", "RESOLU", "CLOTURE", "REOUVERT"])]),
    ],
)

# ─── reports-bi (+5 -> 20) ───────────────────────────────────────────────────
MODULES["reports_c"] = dict(
    module_key="reports_c", module_slug="reports-bi",
    module_path="reports-bi", perm_module="reports",
    registre_filename="registres_c",
    revision="083", down_revision="082_b2b_c_deep",
    entities=[
        E("scheduled-reports", "rptc_scheduled_reports", "RptcScheduledReport", "rptc-scheduled-reports",
          "scheduled_report", "Rapports planifies", "Scheduled reports",
          "Execution periodique automatique d' un rapport.",
          "Automatic periodic run of a report.",
          "Frequence et destinataires parametrent l' envoi.",
          "Frequency and recipients drive delivery.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference rapport", "Report reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("frequence", "str", "Frequence", "Frequency"),
           F("format", "str", "Format", "Format"),
           F("destinataires", "str", "Destinataires", "Recipients"),
           F("prochaine_execution", "datetime", "Prochaine execution", "Next run"),
           F("statut", "str", "Statut", "Status")],
          [EN("frequence", ["QUOTIDIEN", "HEBDOMADAIRE", "MENSUEL", "TRIMESTRIEL"]),
           EN("format", ["PDF", "XLSX", "CSV"]),
           EN("statut", ["ACTIF", "SUSPENDU", "EN_ERREUR"])]),

        E("report-templates", "rptc_templates", "RptcReportTemplate", "rptc-report-templates",
          "report_template", "Modeles de rapport", "Report templates",
          "Definition reutilisable de la mise en page d' un rapport.",
          "Reusable definition of a report layout.",
          "Versionne le modele ; les rapports s' y referent.",
          "Versioned model; reports reference it.",
          "LayoutTemplate", "reference",
          [F("reference", "str", "Reference modele", "Template reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("categorie", "str", "Categorie", "Category"),
           F("source_donnees", "str", "Source de donnees", "Data source"),
           F("version", "str", "Version", "Version"),
           F("nb_blocs", "int", "Nombre de blocs", "Block count"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["OPERATIONNEL", "FINANCIER", "RH", "QUALITE"]),
           EN("statut", ["BROUILLON", "PUBLIE", "ARCHIVE"])]),

        E("data-exports", "rptc_data_exports", "RptcDataExport", "rptc-data-exports",
          "data_export", "Extractions de donnees", "Data exports",
          "Demande d' extraction d' un jeu de donnees au format fichier.",
          "Request to extract a dataset into a file.",
          "Tracabilite : qui, quand, quel volume exporte.",
          "Traceability: who, when, how many rows exported.",
          "Download", "reference",
          [F("reference", "str", "Reference extraction", "Export reference", required=True, search=True),
           F("libelle", "str", "Libelle", "Label"),
           F("module_source", "str", "Module source", "Source module"),
           F("format", "str", "Format", "Format"),
           F("filtres", "text", "Filtres", "Filters"),
           F("lignes_exportees", "int", "Lignes exportees", "Rows exported"),
           F("demandeur", "str", "Demandeur", "Requester"),
           F("date_export", "datetime", "Date export", "Export date"),
           F("statut", "str", "Statut", "Status")],
          [EN("format", ["CSV", "XLSX", "JSON", "PDF"]),
           EN("statut", ["EN_ATTENTE", "EN_COURS", "TERMINE", "ECHEC"])]),

        E("ad-hoc-queries", "rptc_ad_hoc_queries", "RptcAdHocQuery", "rptc-ad-hoc-queries",
          "ad_hoc_query", "Requetes ad hoc", "Ad-hoc queries",
          "Requete analytique ponctuelle construite par un utilisateur.",
          "One-off analytical query built by a user.",
          "Une requete est partageable et versionnee.",
          "A query can be shared and versioned.",
          "Terminal", "reference",
          [F("reference", "str", "Reference requete", "Query reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("source_donnees", "str", "Source de donnees", "Data source"),
           F("dimensions", "text", "Dimensions", "Dimensions"),
           F("auteur", "str", "Auteur", "Author"),
           F("derniere_execution", "datetime", "Derniere execution", "Last run"),
           F("partage", "bool", "Partagee", "Shared"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "ENREGISTREE", "PUBLIEE", "ARCHIVEE"])]),

        E("olap-cubes", "rptc_olap_cubes", "RptcOlapCube", "rptc-olap-cubes",
          "olap_cube", "Cubes analytiques", "OLAP cubes",
          "Cube multidimensionnel prepoure pour l' analyse.",
          "Pre-computed multidimensional cube for analysis.",
          "Dimensions et mesures definissent les coupes disponibles.",
          "Dimensions and measures define available cuts.",
          "Database", "reference",
          [F("reference", "str", "Reference cube", "Cube reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("source", "str", "Source", "Source"),
           F("dimensions", "text", "Dimensions", "Dimensions"),
           F("mesures", "text", "Mesures", "Measures"),
           F("nb_lignes", "int", "Nombre de lignes", "Row count"),
           F("date_dernier_refresh", "datetime", "Dernier refresh", "Last refresh"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_CONSTRUCTION", "PRET", "OBSOLETE", "ERREUR"])]),
    ],
)

# ─── admin-saas (+5 -> 20) ───────────────────────────────────────────────────
MODULES["admin_c"] = dict(
    module_key="admin_c", module_slug="admin-saas",
    module_path="admin-saas", perm_module="admin",
    registre_filename="registres_c",
    revision="084", down_revision="083_reports_c_deep",
    entities=[
        E("subscription-plans", "admc_subscription_plans", "AdmCSubscriptionPlan", "admc-subscription-plans",
          "subscription_plan", "Plans d' abonnement", "Subscription plans",
          "Offres tarifaires SaaS et leurs limites.",
          "SaaS pricing tiers and their limits.",
          "Prix, periode et quotas definissent le plan.",
          "Price, period and quotas define the plan.",
          "Layers", "reference",
          [F("reference", "str", "Reference plan", "Plan reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("prix_mensuel", "num", "Prix mensuel", "Monthly price"),
           F("nb_utilisateurs", "int", "Nb utilisateurs", "User seats"),
           F("nb_modules", "int", "Nb modules", "Module count"),
           F("periode", "str", "Periode", "Billing period"),
           F("statut", "str", "Statut", "Status")],
          [EN("periode", ["MENSUEL", "TRIMESTRIEL", "ANNUEL"]),
           EN("statut", ["ACTIF", "ANCIEN", "BETA"])]),

        E("tenant-invites", "admc_tenant_invites", "AdmCTenantInvite", "admc-tenant-invites",
          "tenant_invite", "Invitations des locataires", "Tenant invites",
          "Invitation d' un utilisateur a rejoindre un tenant.",
          "Invitation of a user to join a tenant.",
          "Lien a echeance ; statut suit l' acceptation.",
          "Time-limited link; status follows acceptance.",
          "UserPlus", "reference",
          [F("reference", "str", "Reference invitation", "Invite reference", required=True, search=True),
           F("email", "str", "Email", "Email"),
           F("tenant", "str", "Tenant", "Tenant"),
           F("role_propose", "str", "Role propose", "Proposed role"),
           F("invite_par", "str", "Invite par", "Invited by"),
           F("date_expiration", "datetime", "Expiration", "Expiry"),
           F("statut", "str", "Statut", "Status")],
          [EN("role_propose", ["ADMIN", "MANAGER", "OPERATEUR", "LECTURE"]),
           EN("statut", ["EN_ATTENTE", "ACCEPTEE", "EXPIREE", "REVOQUEE"])]),

        E("api-tokens", "admc_api_tokens", "AdmCApiToken", "admc-api-tokens",
          "api_token", "Jeton d' API", "API tokens",
          "Credenciaux d' acces programmatique a l' API.",
          "Programmatic API access credentials.",
          "Portee et echeance bornent chaque jeton ; secret jamais stocke en clair.",
          "Scope and expiry bound each token; secret never stored in clear.",
          "KeyRound", "reference",
          [F("reference", "str", "Reference jeton", "Token reference", required=True, search=True),
           F("nom", "str", "Nom", "Name"),
           F("tenant", "str", "Tenant", "Tenant"),
           F("portee", "str", "Portee", "Scope"),
           F("cree_le", "datetime", "Cree le", "Created"),
           F("expire_le", "datetime", "Expire le", "Expires"),
           F("derniere_utilisation", "datetime", "Derniere utilisation", "Last used"),
           F("statut", "str", "Statut", "Status")],
          [EN("portee", ["LECTURE", "ECRITURE", "ADMIN"]),
           EN("statut", ["ACTIF", "REVOQUE", "EXPIRE"])]),

        E("billing-invoices", "admc_billing_invoices", "AdmCBillingInvoice", "admc-billing-invoices",
          "billing_invoice", "Factures d' abonnement", "Billing invoices",
          "Facturation recurrente des abonnements SaaS.",
          "Recurring billing of SaaS subscriptions.",
          "Montant TTC, echeance et suivi de paiement.",
          "Total amount, due date and payment tracking.",
          "Receipt", "reference",
          [F("reference", "str", "Reference facture", "Invoice reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("periode_facturee", "str", "Periode facturee", "Billed period"),
           F("montant_ht", "num", "Montant HT", "Net amount"),
           F("tva", "num", "TVA", "VAT"),
           F("montant_ttc", "num", "Montant TTC", "Total amount"),
           F("date_echeance", "date", "Echeance", "Due date"),
           F("statut", "str", "Statut", "Status")],
          [EN("periode_facturee", ["MENSUELLE", "TRIMESTRIELLE", "ANNUELLE"]),
           EN("statut", ["BROUILLON", "EMISE", "PAYEE", "EN_RETARD", "ANNULEE"])]),

        E("usage-metering", "admc_usage_metering", "AdmCUsageMetering", "admc-usage-metering",
          "usage_metering", "Mesure d' usage", "Usage metering",
          "Releve de consommation des ressources par tenant pour la facturation.",
          "Per-tenant resource consumption reading for billing.",
          "Unite mesuree et periode conditionnent la consommation facturable.",
          "Measured unit and period drive billable consumption.",
          "Activity", "reference",
          [F("reference", "str", "Reference releve", "Metering reference", required=True, search=True),
           F("tenant", "str", "Tenant", "Tenant"),
           F("ressource", "str", "Ressource", "Resource"),
           F("unite", "str", "Unite", "Unit"),
           F("quantite_consommee", "num", "Quantite consommee", "Consumed quantity"),
           F("periode", "str", "Periode", "Period"),
           F("date_releve", "datetime", "Date releve", "Reading date"),
           F("statut", "str", "Statut", "Status")],
          [EN("ressource", ["API_CALLS", "STOCKAGE_GO", "TRANSACTION", "SIEGE_MOIS"]),
           EN("periode", ["MENSUEL", "TRIMESTRIEL", "ANNUEL"]),
           EN("statut", ["COLLECTE", "VALIDE", "FACTURE", "ANOMALIE"])]),
    ],
)

# ─── superadmin-cadc (+5 -> 20) ──────────────────────────────────────────────
MODULES["superadmin_c"] = dict(
    module_key="superadmin_c", module_slug="superadmin-cadc",
    module_path="superadmin-cadc", perm_module="superadmin",
    registre_filename="registres_c",
    revision="085", down_revision="084_admin_c_deep",
    entities=[
        E("audit-log-reviews", "sac_audit_log_reviews", "SaCAuditLogReview", "sac-audit-log-reviews",
          "audit_log_review", "Revues des journaux d' audit", "Audit log reviews",
          "Examen periodique des journaux d' activite sensible.",
          "Periodic review of sensitive activity logs.",
          "Chaque revue consigne un verdict et un perimetre.",
          "Each review records a verdict and a scope.",
          "ScrollText", "reference",
          [F("reference", "str", "Reference revue", "Review reference", required=True, search=True),
           F("perimetre", "str", "Perimetre", "Scope"),
           F("date_debut", "datetime", "Debut", "From"),
           F("date_fin", "datetime", "Fin", "To"),
           F("evenements_examines", "int", "Evenements examines", "Events reviewed"),
           F("reviewer", "str", "Reviewer", "Reviewer"),
           F("verdict", "str", "Verdict", "Verdict"),
           F("statut", "str", "Statut", "Status")],
          [EN("verdict", ["CONFORME", "ANOMALIE", "INVESTIGATION"]),
           EN("statut", ["PLANIFIEE", "EN_COURS", "CLOTUREE"])]),

        E("system-parameters", "sac_system_parameters", "SaCSystemParameter", "sac-system-parameters",
          "system_parameter", "Parametres systeme", "System parameters",
          "Reglage global de la plateforme (valeur cle/parametre).",
          "Global platform setting (key/value).",
          "Toute modification est tracable et reversible.",
          "Any change is traceable and reversible.",
          "Settings", "reference",
          [F("reference", "str", "Cle du parametre", "Parameter key", required=True, search=True),
           F("valeur", "text", "Valeur", "Value"),
           F("categorie", "str", "Categorie", "Category"),
           F("portee", "str", "Portee", "Scope"),
           F("modifie_par", "str", "Modifie par", "Modified by"),
           F("date_modification", "datetime", "Date modification", "Modified at"),
           F("statut", "str", "Statut", "Status")],
          [EN("categorie", ["SECURITE", "PERFORMANCE", "CONFINEMENT", "INTEGRATION"]),
           EN("portee", ["GLOBAL", "TENANT"]),
           EN("statut", ["ACTIF", "DESACTIVE", "A_REVALIDER"])]),

        E("platform-alerts", "sac_platform_alerts", "SaCPlatformAlert", "sac-platform-alerts",
          "platform_alert", "Alertes plateforme", "Platform alerts",
          "Notification d' un incident ou depassement de seuile technique.",
          "Notification of a technical incident or threshold breach.",
          "Severite et acquittement structurent la reponse.",
          "Severity and acknowledgement structure the response.",
          "BellRing", "reference",
          [F("reference", "str", "Reference alerte", "Alert reference", required=True, search=True),
           F("titre", "str", "Titre", "Title"),
           F("source", "str", "Source", "Source"),
           F("severite", "str", "Severite", "Severity"),
           F("date_detection", "datetime", "Detection", "Detected at"),
           F("acquitte_par", "str", "Acquitte par", "Acknowledged by"),
           F("statut", "str", "Statut", "Status")],
          [EN("severite", ["INFO", "WARNING", "CRITIQUE", "BLOQUANT"]),
           EN("statut", ["NOUVELLE", "ACQUITTEE", "RESOLUE", "FAUSSE_ALARME"])]),

        E("migration-runs", "sac_migration_runs", "SaCMigrationRun", "sac-migration-runs",
          "migration_run", "Executions de migration", "Migration runs",
          "Journal des deploiements de migrations base de donnees.",
          "Log of database migration deployments.",
          "Reversible ; statut et duree consignes a chaque run.",
          "Reversible; status and duration logged per run.",
          "GitBranch", "reference",
          [F("reference", "str", "Reference run", "Run reference", required=True, search=True),
           F("revision", "str", "Revision", "Revision"),
           F("environnement", "str", "Environnement", "Environment"),
           F("lance_par", "str", "Lance par", "Launched by"),
           F("date_debut", "datetime", "Debut", "Start"),
           F("duree_sec", "int", "Duree (s)", "Duration (s)"),
           F("statut", "str", "Statut", "Status")],
          [EN("environnement", ["DEV", "STAGING", "PROD"]),
           EN("statut", ["EN_COURS", "SUCCES", "ECHEC", "RETOUR_ARRIERE"])]),

        E("license-keys", "sac_license_keys", "SaCLicenseKey", "sac-license-keys",
          "license_key", "Cles de licence", "License keys",
          "Cles de licence produit et leur activation.",
          "Product license keys and their activation.",
          "Une cle a un etat et un titulaire identifies.",
          "A key has an identified state and holder.",
          "Key", "reference",
          [F("reference", "str", "Reference cle", "Key reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("titulaire", "str", "Titulaire", "Holder"),
           F("sieges_licencies", "int", "Sieges licencies", "Licensed seats"),
           F("date_activation", "date", "Activation", "Activation date"),
           F("date_expiration", "date", "Expiration", "Expiry date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["INACTIVE", "ACTIVE", "EXPIREE", "RESILIEE", "SUSPENDUE"])]),
    ],
)
