"""Manifest Vague D — batch D4 (portails « sober & justifie », domaines riches).

  - portail-frais            -> perm_module="tresorerie" (« tresorerie.*.* » DAF/
    CHEF_COMPTABLE) : pieces du circuit de note de frais saisies par le role.
  - annuaire-prestataires    -> perm_module="transport" (CHEF_PARC « transport.*.* »
    etend sa responsabilite aux sous-traitants / prestataires) : objets
    d' annuaire et de suivi des prestataires, DISTINCTS des tables maitresses.
  - portail-collaborateur    -> perm_module="rh" (« rh.*.* » ADMIN_RH) : traces que
    le collaborateur (interne/externes) produit, DISTINCTS du portail employe.

Chaine Alembic 096-098 depuis 095_chef_personnel_d_deep. Aucune valeur fabriquee ;
statut = cycle de vie metier explicite ; identifiants d' enum sans point ni chiffre.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── portail-frais (+19 -> 20) ───────────────────────────────────────────────
MODULES["frais_d"] = dict(
    module_key="frais_d", module_slug="portail-frais",
    module_path="portail-frais", perm_module="tresorerie",
    registre_filename="registres_c",
    revision="096", down_revision="095_chef_personnel_d_deep",
    entities=[
        E("expense-reports", "fra_expense_reports", "FraExpenseReport", "fra-expense-reports",
          "expense_report", "Notes de frais", "Expense reports",
          "Note de frais consolidee soumise par le collaborateur.",
          "Consolidated expense report submitted by the employee.",
          "Le total et la periode encadrent la soumission.",
          "Total and period frame the submission.",
          "Receipt", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("periode", "str", "Periode", "Period"),
           F("total", "num", "Total", "Total"),
           F("nb_justificatifs", "int", "Nb justificatifs", "Receipts"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "SOUMISE", "EN_COURS", "APPROUVEE", "REJETEE"])]),

        E("expense-receipts", "fra_expense_receipts", "FraExpenseReceipt", "fra-expense-receipts",
          "expense_receipt", "Justificatifs de frais", "Expense receipts",
          "Piece justificative rattachee a une ligne de frais.",
          "Supporting document attached to an expense line.",
          "La date et le montant du justificatif prouvent la depense.",
          "The receipt date and amount prove the expense.",
          "Upload", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("note_frais", "str", "Note de frais", "Expense report"),
           F("fournisseur", "str", "Fournisseur", "Vendor"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["JOINT", "LISIBLE", "ILISIBLE", "DUPLIQUET"])]),

        E("expense-advances", "fra_expense_advances", "FraExpenseAdvance", "fra-expense-advances",
          "expense_advance", "Avances de frais", "Expense advances",
          "Avance consentie avant la depense reelle.",
          "Advance granted before the actual expense.",
          "Le montant avance doit etre ensuite justifie ou rembourse.",
          "The advance must later be justified or repaid.",
          "Wallet", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("montant", "num", "Montant", "Amount"),
           F("motif", "str", "Motif", "Reason"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDEE", "VERSEE", "JUSTIFIEE", "REMBOURSEE", "SOLDE"])]),

        E("per-diem-claims", "fra_per_diem", "FraPerDiemClaim", "fra-per-diem-claims",
          "per_diem_claim", "Indemnites forfaitaires", "Per diem claims",
          "Demande d' indemnite journaliere forfaitaire.",
          "Daily flat-rate indemnity claim.",
          "Le barme et le nombre de jours calculent l' indemnite.",
          "The scale and days compute the indemnity.",
          "Coins", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("jours", "int", "Jours", "Days"),
           F("taux_journalier", "num", "Taux journalier", "Daily rate"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDEE", "CALCULEE", "APPROUVEE", "PAYEE"])]),

        E("mileage-claims", "fra_mileage_claims", "FraMileageClaim", "fra-mileage-claims",
          "mileage_claim", "Frais kilometriques", "Mileage claims",
          "Indemnisation de deplacements en vehicule personnel.",
          "Reimbursement of personal-vehicle travel.",
          "La distance x le bareme justifie le montant.",
          "Distance times the rate justifies the amount.",
          "Gauge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("km", "int", "Kilometres", "Kilometers"),
           F("trajet", "str", "Trajet", "Route"),
           F("montant", "num", "Montant", "Amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DECLARE", "VERIFIE", "APPROUVE", "REJETE"])]),

        E("meal-expenses", "fra_meal_expenses", "FraMealExpense", "fra-meal-expenses",
          "meal_expense", "Frais de restauration", "Meal expenses",
          "Repis professionnels engages et justifies.",
          "Professional meals incurred and justified.",
          "Les participants et le motif professionnel conditionnent l' acceptation.",
          "Attendees and business purpose condition acceptance.",
          "Coffee", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("montant", "num", "Montant", "Amount"),
           F("nb_personnes", "int", "Nb personnes", "People"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DECLARE", "JUSTIFIE", "APPROUVE", "PLAFOND_DEPASSE"])]),

        E("travel-bookings", "fra_travel_bookings", "FraTravelBooking", "fra-travel-bookings",
          "travel_booking", "Reservations de deplacement", "Travel bookings",
          "Reservation de transport pour un deplacement professionnel.",
          "Transport booking for a business trip.",
          "Le respect de la politique voyage limite le cout.",
          "Travel-policy compliance caps the cost.",
          "Plane", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("mode", "str", "Mode", "Mode"),
           F("destination", "str", "Destination", "Destination"),
           F("date_depart", "date", "Depart", "Departure"),
           F("statut", "str", "Statut", "Status")],
          [EN("mode", ["AVION", "TRAIN", "BUS", "LOCATION"]),
           EN("statut", ["DEMANDEE", "RESERVEE", "ANNULEE", "EFFECTUE"])]),

        E("hotel-stays", "fra_hotel_stays", "FraHotelStay", "fra-hotel-stays",
          "hotel_stay", "Nuits d' hotel", "Hotel stays",
          "Hebergement hotelier lie a un deplacement.",
          "Hotel lodging tied to a trip.",
          "Le nombre de nuits et le tarif nuit encadrent la depense.",
          "Nights and nightly rate bound the expense.",
          "BedDouble", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("hotel", "str", "Hotel", "Hotel"),
           F("nuits", "int", "Nuits", "Nights"),
           F("montant", "num", "Montant", "Amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["RESERVE", "EN_COURS", "FACTURE", "REMBOURSE", "ANNULE"])]),

        E("transport-expenses", "fra_transport_expenses", "FraTransportExpense", "fra-transport-expenses",
          "transport_expense", "Frais de transport local", "Transport expenses",
          "Taxi, VTC, péage et transports locaux.",
          "Taxi, ride-hailing, tolls and local transport.",
          "Le motif et le trajet prouvent le caractere professionnel.",
          "Purpose and route prove the business nature.",
          "Car", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("type", "str", "Type", "Type"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["TAXI", "VTC", "PEAGE", "METRO", "CARBURANT"]),
           EN("statut", ["DECLARE", "JUSTIFIE", "APPROUVE", "REJETE"])]),

        E("client-entertainment", "fra_client_entertainment", "FraClientEntertainment", "fra-client-entertainment",
          "client_entertainment", "Frais de representation client", "Client entertainment",
          "Depenses d' reception liees a un client.",
          "Hospitality expenses tied to a client.",
          "Le client recu et le business purpose encadrent la depense.",
          "The hosted client and business purpose bound the expense.",
          "Users", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("client", "str", "Client", "Client"),
           F("montant", "num", "Montant", "Amount"),
           F("nb_invites", "int", "Nb invites", "Guests"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIEE", "ENGAGEE", "APPROUVEE", "REJETEE"])]),

        E("conference-fees", "fra_conference_fees", "FraConferenceFee", "fra-conference-fees",
          "conference_fee", "Frais de salon et conference", "Conference fees",
          "Inscription et frais lies a un evenement professionnel.",
          "Registration and costs tied to a professional event.",
          "L' evenement et le role (participant/exposant) justifient la depense.",
          "The event and role (attendee/exhibitor) justify the expense.",
          "BookOpen", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Employee"),
           F("evenement", "str", "Evenement", "Event"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "INSCIT", "FACTURE", "REMBOURSE"])]),

        E("office-supplies", "fra_office_supplies", "FraOfficeSupply", "fra-office-supplies",
          "office_supply", "Achats de fournitures", "Office supplies",
          "Achat de petites fournitures pour le service.",
          "Purchase of minor supplies for the department.",
          "Le centre de cout et le bon de commande encadrent l' achat.",
          "The cost center and purchase order bound the buy.",
          "Boxes", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("demandeur", "str", "Demandeur", "Requester"),
           F("article", "str", "Article", "Item"),
           F("montant", "num", "Montant", "Amount"),
           F("centre_cout", "str", "Centre de cout", "Cost center"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "COMMANDE", "RECU", "PAYE"])]),

        E("card-transactions", "fra_card_transactions", "FraCardTransaction", "fra-card-transactions",
          "card_transaction", "Transactions carte entreprise", "Card transactions",
          "Paiement effectue avec la carte de l' entreprise.",
          "Payment made with the company card.",
          "Le rapprochement transaction / justificatif clot la carte.",
          "Matching transaction to receipt closes the card.",
          "CreditCard", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("titulaire", "str", "Titulaire", "Holder"),
           F("marchand", "str", "Marchand", "Merchant"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEBIT", "JUSTIFIE", "RAPPROCHE", "CONTESTE"])]),

        E("currency-conversions", "fra_currency_conversions", "FraCurrencyConversion", "fra-currency-conversions",
          "currency_conversion", "Conversions de devise", "Currency conversions",
          "Conversion d' un frais en devise vers la devise de remboursement.",
          "Conversion of a foreign-currency expense to reimbursement currency.",
          "Le taux applique et la date figent la conversion.",
          "The applied rate and date freeze the conversion.",
          "Percent", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("frais", "str", "Frais", "Expense"),
           F("devise_source", "str", "Devise source", "Source currency"),
           F("montant_source", "num", "Montant source", "Source amount"),
           F("taux", "num", "Taux", "Rate"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_CONVERTIR", "CONVERTI", "VALIDE", "Ecart_TAU"])]),

        E("expense-approvals", "fra_expense_approvals", "FraExpenseApproval", "fra-expense-approvals",
          "expense_approval", "Validations de frais", "Expense approvals",
          "Validation hiérarchique d' une note de frais.",
          "Managerial approval of an expense report.",
          "Le valideur et la date attestent le controle N+1.",
          "The approver and date evidence the N+1 control.",
          "CheckCircle2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("note_frais", "str", "Note de frais", "Expense report"),
           F("valideur", "str", "Validateur", "Approver"),
           F("commentaire", "text", "Commentaire", "Comment"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_ATTENTE", "APPROUVE", "REJETE", "RETOUR"])]),

        E("expense-disputes", "fra_expense_disputes", "FraExpenseDispute", "fra-expense-disputes",
          "expense_dispute", "Litiges de frais", "Expense disputes",
          "Contestation d' un refus ou d' un montant de frais.",
          "Challenge of an expense rejection or amount.",
          "Le motif du litige et la piece jointe relancent l' examen.",
          "The dispute reason and attachment reopen the review.",
          "XCircle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("note_frais", "str", "Note de frais", "Expense report"),
           F("motif", "text", "Motif", "Reason"),
           F("montant_conteste", "num", "Montant conteste", "Disputed amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERT", "EXAMINE", "RESOLU", "MAINTENU"])]),

        E("vat-recovery", "fra_vat_recovery", "FraVatRecovery", "fra-vat-recovery",
          "vat_recovery", "Recuperation TVA sur frais", "VAT recovery",
          "Identification de la TVA recuperable sur une depense.",
          "Identification of recoverable VAT on an expense.",
          "La mention TVA sur la facture conditionne la recuperation.",
          "The VAT line on the invoice conditions recovery.",
          "Landmark", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("frais", "str", "Frais", "Expense"),
           F("montant_ht", "num", "Montant HT", "Net amount"),
           F("tva", "num", "TVA", "VAT"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_VERIFIER", "RECUPERABLE", "NON_RECUPERABLE", "INTEGRE"])]),

        E("expense-budget-tracking", "fra_budget_tracking", "FraExpenseBudgetTracking", "fra-expense-budget-tracking",
          "expense_budget_tracking", "Suivi budget de frais", "Expense budget tracking",
          "Comparaison budget alloue / frais engages par centre de cout.",
          "Comparison of allocated budget vs incurred expense per cost center.",
          "Le depassement du budget declenche l' alerte.",
          "Exceeding budget triggers the alert.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("centre_cout", "str", "Centre de cout", "Cost center"),
           F("periode", "str", "Periode", "Period"),
           F("budget", "num", "Budget", "Budget"),
           F("engage", "num", "Engage", "Committed"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NOMINAL", "TENDU", "DEPASSE", "GELE"])]),

        E("expense-categories", "fra_expense_categories", "FraExpenseCategory", "fra-expense-categories",
          "expense_category", "Categories de frais", "Expense categories",
          "Referentiel des categories de frais autorisees.",
          "Reference of allowed expense categories.",
          "Le plafond par categorie encadre la saisie.",
          "The per-category cap frames entry.",
          "ListChecks", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("libelle", "str", "Libelle", "Label"),
           F("plafond", "num", "Plafond", "Cap"),
           F("justificatif_requis", "bool", "Justificatif requis", "Receipt required"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIVE", "SUSPENDUE", "ARCHIVEE"])]),
    ],
)

# ─── annuaire-prestataires (+17 -> 20) ───────────────────────────────────────
MODULES["annuaire_d"] = dict(
    module_key="annuaire_d", module_slug="annuaire-prestataires",
    module_path="annuaire-prestataires", perm_module="transport",
    registre_filename="registres_c",
    revision="097", down_revision="096_frais_d_deep",
    entities=[
        E("provider-profiles", "prov_profiles", "ProvProfile", "prov-provider-profiles",
          "provider_profile", "Fiches prestataires", "Provider profiles",
          "Fiche d' identite d' un prestataire / sous-traitant.",
          "Identity record of a provider / subcontractor.",
          "Le type de prestation et la zone definissent le champs d' action.",
          "Service type and zone define the scope.",
          "Building2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("raison_sociale", "str", "Raison sociale", "Company name"),
           F("type_prestation", "str", "Type de prestation", "Service type"),
           F("zone", "str", "Zone", "Zone"),
           F("contact", "str", "Contact", "Contact"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_prestation", ["TRANSPORT", "MANUTENTION", "SECURITE", "NETTOYAGE", "INGENIERIE"]),
           EN("statut", ["PROSPECT", "REFERENC", "ACTIF", "SUSPENDU", "SORTI"])]),

        E("provider-categories", "prov_categories", "ProvCategory", "prov-provider-categories",
          "provider_category", "Categories de prestataires", "Provider categories",
          "Classification des prestataires par metier.",
          "Classification of providers by trade.",
          "La categorie pilote le workflow de qualification.",
          "The category drives the qualification workflow.",
          "Tags", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("libelle", "str", "Libelle", "Label"),
           F("exigence_documentaire", "bool", "Exigence documentaire", "Doc requirement"),
           F("nb_prestataires", "int", "Nb prestataires", "Providers"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ACTIVE", "ARCHIVEE"])]),

        E("provider-certifications", "prov_certifications", "ProvCertification", "prov-provider-certifications",
          "provider_certification", "Certifications prestataires", "Provider certifications",
          "Certification / agrement detenu par un prestataire.",
          "Certification / accreditation held by a provider.",
          "La validite de la certification conditionne la mise en service.",
          "Certification validity conditions deployment.",
          "Award", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("intitule", "str", "Intitule", "Title"),
           F("emetteur", "str", "Emetteur", "Issuer"),
           F("expire_le", "date", "Expire le", "Expires"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["VALIDE", "EXAMEN", "EXPIRE", "REVOQUE"])]),

        E("insurance-attestations", "prov_insurance", "ProvInsuranceAttestation", "prov-insurance-attestations",
          "insurance_attestation", "Attestations d' assurance", "Insurance attestations",
          "Attestation d' assurance RC / caution d' un prestataire.",
          "Liability insurance / bond attestation of a provider.",
          "Le montant couvert et la date limite encadrent l' assurance.",
          "Covered amount and deadline bound the insurance.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("type_assurance", "str", "Type", "Insurance type"),
           F("montant_couvert", "num", "Montant couvert", "Covered amount"),
           F("expire_le", "date", "Expire le", "Expires"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_assurance", ["RC_PRO", "MARCHANDISE_TRANSPORT", "CAUTION", "FLOTTE"]),
           EN("statut", ["A_JOUR", "A_RENOUVELER", "EXPIREE"])]),

        E("service-contracts", "prov_contracts", "ProvServiceContract", "prov-service-contracts",
          "service_contract", "Contrats de prestation", "Service contracts",
          "Contrat cadre ou ponctuel lie a un prestataire.",
          "Framework or one-off contract with a provider.",
          "La duree et le montant engagent la relation.",
          "Duration and amount commit the relationship.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("objet", "str", "Objet", "Object"),
           F("montant", "num", "Montant", "Amount"),
           F("echeance", "date", "Echeance", "End date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["NEGOCIE", "SIGNE", "EN_COURS", "ECHOUE", "RESILIE"])]),

        E("provider-evaluations", "prov_evaluations", "ProvEvaluation", "prov-provider-evaluations",
          "provider_evaluation", "Evaluations de prestataires", "Provider evaluations",
          "Scoring periodique d' un prestataire sur des criteres.",
          "Periodic scoring of a provider on criteria.",
          "Le score global conditionne le renouvellement.",
          "The overall score conditions renewal.",
          "Star", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("periode", "str", "Periode", "Period"),
           F("score", "int", "Score", "Score"),
           F("evalueur", "str", "Evaluateur", "Evaluator"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["REUNIE", "EN_COURS", "PUBLIEE", "CONTESTEE"])]),

        E("provider-incidents", "prov_incidents", "ProvIncident", "prov-provider-incidents",
          "provider_incident", "Incidents prestataires", "Provider incidents",
          "Manquement ou incident impute a un prestataire.",
          "Breach or incident attributed to a provider.",
          "La gravite alimente la notation et la mise en demeure.",
          "Severity feeds the scoring and the formal notice.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("description", "text", "Description", "Description"),
           F("gravite", "str", "Gravite", "Severity"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("gravite", ["MINEUR", "MAJEUR", "CRITIQUE"]),
           EN("statut", ["OUVERT", "RECONNU", "CORRIGE", "SANCTIONNE"])]),

        E("availability-calendars", "prov_availability", "ProvAvailabilityCalendar", "prov-availability-calendars",
          "availability_calendar", "Calendriers de disponibilite", "Availability calendars",
          "Disponible declaree par un prestataire pour une periode.",
          "Availability declared by a provider for a period.",
          "Le taux de disponibilite oriente l' affectation des missions.",
          "The availability rate guides mission assignment.",
          "CalendarDays", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("semaine", "str", "Semaine", "Week"),
           F("creneaux_libres", "int", "Creneaux libres", "Free slots"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DISPONIBLE", "PARTIEL", "COMPLET", "INJOIGNABLE"])]),

        E("price-lists", "prov_price_lists", "ProvPriceList", "prov-price-lists",
          "price_list", "Grilles tarifaires prestataires", "Provider price lists",
          "Barime de prix propose par un prestataire.",
          "Rate card offered by a provider.",
          "La date d' application et la validite encadrent le tarif.",
          "Application date and validity bound the rate.",
          "CircleDollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("unite_prix", "num", "Prix unitaire", "Unit price"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSEE", "HARMONISEE", "REJETEE", "EXPIREE"])]),

        E("provider-contacts", "prov_contacts", "ProvContact", "prov-provider-contacts",
          "provider_contact", "Contacts prestataires", "Provider contacts",
          "Interlocuteur designe chez un prestataire.",
          "Designated contact person at a provider.",
          "Le role (commercial / exploitation) structure la relation.",
          "The role (sales / ops) structures the relationship.",
          "Contact", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("nom", "str", "Nom", "Name"),
           F("role", "str", "Role", "Role"),
           F("telephone", "str", "Telephone", "Phone"),
           F("statut", "str", "Statut", "Status")],
          [EN("role", ["COMMERCIAL", "EXPLOITATION", "DIRECTION", "FACTURATION"]),
           EN("statut", ["ACTIF", "ANCIEN", "A_VERIFIER"])]),

        E("provider-onboarding", "prov_onboarding", "ProvOnboarding", "prov-provider-onboarding",
          "provider_onboarding", "Onboarding prestataires", "Provider onboarding",
          "Parcours de référencement d' un nouveau prestataire.",
          "Onboarding path of a newly referenced provider.",
          "La complete des pieces conditionne la mise en service.",
          "Document completeness conditions go-live.",
          "UserCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("etapes_faites", "int", "Etapes faites", "Steps done"),
           F("etapes_total", "int", "Etapes", "Total steps"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMARRE", "EN_COURS", "BLOQUE", "REFERENC", "ABANDONNE"])]),

        E("provider-reviews", "prov_reviews", "ProvReview", "prov-provider-reviews",
          "provider_review", "Avis sur prestataires", "Provider reviews",
          "Retour qualitatif libre apres une prestation.",
          "Free qualitative feedback after a service.",
          "L' avis vient completer le score formel.",
          "The review complements the formal score.",
          "MessageSquare", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("commentaire", "text", "Commentaire", "Comment"),
           F("nb_etoiles", "int", "Nb etoiles", "Stars"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PUBLIE", "MODERE", "SIGNALE"])]),

        E("rfq-requests", "prov_rfq", "ProvRfqRequest", "prov-rfq-requests",
          "rfq_request", "Demandes de devis", "RFQ requests",
          "Consultation prix lancee aupres de plusieurs prestataires.",
          "Price consultation launched with several providers.",
          "Les offres recues comparent pour selectionner.",
          "Received bids are compared to select.",
          "FileText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("objet", "str", "Objet", "Object"),
           F("nb_offres", "int", "Nb offres", "Bids"),
           F("date_limite", "date", "Date limite", "Deadline"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERTE", "CLOTUREE", "ATTRIBUEE", "INFROME"])]),

        E("provider-interventions", "prov_interventions", "ProvIntervention", "prov-provider-interventions",
          "provider_intervention", "Interventions prestataires", "Provider interventions",
          "Mission realisee par un prestataire sur site.",
          "Mission carried out by a provider on site.",
          "Le compte-rendu d' intervention atteste le service fait.",
          "The intervention report evidences the service done.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("site", "str", "Site", "Site"),
           F("date", "datetime", "Date", "Date"),
           F("compte_rendu", "text", "Compte-rendu", "Report"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIEE", "EN_COURS", "FAITE", "VALIDEE", "REFAIRE"])]),

        E("compliance-documents", "prov_compliance_docs", "ProvComplianceDoc", "prov-compliance-documents",
          "compliance_document", "Documents de conformite", "Compliance documents",
          "Piece de conformite exigee d' un prestataire (Kbis, reglement...).",
          "Compliance document required from a provider.",
          "La validite de la piece conditionne la reference.",
          "Document validity conditions the reference status.",
          "FileBadge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("type_piece", "str", "Type", "Doc type"),
           F("expire_le", "date", "Expire le", "Expires"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_piece", ["REGISTRE_COMMERCE", "ATTEST_FISCALE", "ATTEST_SOCIALE", "AGREMENT"]),
           EN("statut", ["VALIDE", "MANQUANT", "EXPIRE", "EN_COURS"])]),

        E("provider-bank-details", "prov_bank_details", "ProvBankDetail", "prov-provider-bank-details",
          "provider_bank_detail", "Coordonnees bancaires prestataires", "Provider bank details",
          "RIB du prestataire pour le reglement des factures.",
          "Provider bank account for invoice settlement.",
          "Un IBAN verifie evite le paiement vers un compte erroné.",
          "A verified IBAN prevents payment to a wrong account.",
          "Landmark", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("banque", "str", "Banque", "Bank"),
           F("iban_verifie", "bool", "IBAN verifie", "IBAN verified"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ENREGISTRE", "VERIFIE", "CHANGEMENT", "REJETE"])]),

        E("provider-blacklist", "prov_blacklist", "ProvBlacklist", "prov-provider-blacklist",
          "provider_blacklist", "Exclusions de prestataires", "Provider blacklist",
          "Mise a l' index / exclusion d' un prestataire.",
          "Blacklisting / exclusion of a provider.",
          "Le motif et la duree justifient la mise a l' index.",
          "The reason and duration justify the blacklisting.",
          "Ban", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("prestataire", "str", "Prestataire", "Provider"),
           F("motif", "text", "Motif", "Reason"),
           F("debut", "date", "Debut", "Start"),
           F("fin_prevue", "date", "Fin prevue", "Planned end"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSEE", "ACTIVE", "LEVEE", "PERPETUELLE"])]),
    ],
)

# ─── portail-collaborateur (+19 -> 20) ───────────────────────────────────────
MODULES["collaborateur_d"] = dict(
    module_key="collaborateur_d", module_slug="portail-collaborateur",
    module_path="portail-collaborateur", perm_module="rh",
    registre_filename="registres_c",
    revision="098", down_revision="097_annuaire_d_deep",
    entities=[
        E("assignment-records", "coll_assignments", "CollAssignment", "coll-assignment-records",
          "assignment_record", "Affectations de mission", "Assignment records",
          "Affectation d' un collaborateur a une mission / un site.",
          "Assignment of a collaborator to a mission / site.",
          "La periode et le responsable encadrent l' affectation.",
          "Period and manager bound the assignment.",
          "Briefcase", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("mission", "str", "Mission", "Mission"),
           F("site", "str", "Site", "Site"),
           F("debut", "date", "Debut", "Start"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["AFFECTE", "EN_COURS", "TERMINE", "INTERROMPU"])]),

        E("daily-activity-logs", "coll_activity_logs", "CollActivityLog", "coll-daily-activity-logs",
          "daily_activity_log", "Journaux d' activite", "Daily activity logs",
          "Declaration quotidienne de l' activite realisee.",
          "Daily declaration of the activity performed.",
          "Le contenu et la duree tracent la journee.",
          "Content and duration trace the day.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("date", "date", "Date", "Date"),
           F("heures", "num", "Heures", "Hours"),
           F("activite", "text", "Activite", "Activity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISI", "SOUMIS", "VALIDE", "CORRIGE"])]),

        E("deliverable-submissions", "coll_deliverables", "CollDeliverable", "coll-deliverable-submissions",
          "deliverable_submission", "Remises de livrables", "Deliverable submissions",
          "Soumission d' un livrable attendu par le donneur d' ordre.",
          "Submission of a deliverable expected by the client.",
          "L' acceptance du livrable clot la tache.",
          "Deliverable acceptance closes the task.",
          "Package", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("livrable", "str", "Livrable", "Deliverable"),
           F("mission", "str", "Mission", "Mission"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMIS", "EN_REVUE", "ACCEPTE", "RETOUR", "REJETE"])]),

        E("timesheet-declarations", "coll_timesheets", "CollTimesheet", "coll-timesheet-declarations",
          "timesheet_declaration", "Declarations de temps", "Timesheet declarations",
          "Declaration du temps passe sur une mission.",
          "Declaration of time spent on a mission.",
          "Le cumul hebdo engage la facturation au client.",
          "The weekly total commits the client billing.",
          "Clock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("mission", "str", "Mission", "Mission"),
           F("heures", "num", "Heures", "Hours"),
           F("semaine", "str", "Semaine", "Week"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISI", "SOUMIS", "APPROUVE", "FACTURE", "REJETE"])]),

        E("site-access-logs", "coll_site_access", "CollSiteAccessLog", "coll-site-access-logs",
          "site_access_log", "Journaux d' acces site", "Site access logs",
          "Enregistrement d' un acces physique du collaborateur sur un site.",
          "Record of a collaborator's physical access to a site.",
          "L' entree / sortie atteste la presence.",
          "Entry/exit evidences presence.",
          "KeyRound", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("site", "str", "Site", "Site"),
           F("entree", "datetime", "Entree", "Entry"),
           F("sortie", "datetime", "Sortie", "Exit"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERT", "FERME", "ANOMALE"])]),

        E("work-instruction-receipts", "coll_instruction_receipts", "CollWorkInstructionReceipt", "coll-work-instruction-receipts",
          "work_instruction_receipt", "Accuses de consignes", "Work instruction receipts",
          "Accuse de reception d' une consigne de travail.",
          "Acknowledgement of receipt of a work instruction.",
          "L' accuse prouve la prise de connaissance de la consigne.",
          "The acknowledgement evidences the instruction was read.",
          "FileCheck2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("consigne", "str", "Consigne", "Instruction"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_LIRE", "ACCEPTE", "REFUSE", "EXPIRE"])]),

        E("incident-reports", "coll_incidents", "CollIncidentReport", "coll-incident-reports",
          "incident_report", "Signalements d' incident", "Incident reports",
          "Incident constate par le collaborateur sur le terrain.",
          "Incident observed by the collaborator on the ground.",
          "La date et la gravite qualifient l' incident.",
          "Date and severity qualify the incident.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("lieu", "str", "Lieu", "Location"),
           F("description", "text", "Description", "Description"),
           F("gravite", "str", "Gravite", "Severity"),
           F("statut", "str", "Statut", "Status")],
          [EN("gravite", ["MINEUR", "MAJEUR", "CRITIQUE"]),
           EN("statut", ["DECLARE", "PRIS_EN_CHARGE", "RESOLU", "ESCALADE"])]),

        E("quality-check-submissions", "coll_quality_checks", "CollQualityCheck", "coll-quality-check-submissions",
          "quality_check_submission", "Remises de controles qualite", "Quality check submissions",
          "Resultat d' un controle qualite saisi par le collaborateur.",
          "Result of a quality check entered by the collaborator.",
          "La conformite mesuree conditionne la validation.",
          "The measured conformity conditions validation.",
          "CheckCircle2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("controle", "str", "Controle", "Check"),
           F("point_testes", "int", "Points testes", "Points tested"),
           F("anomalies", "int", "Anomalies", "Defects"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISI", "CONFORME", "NON_CONFORME", "A_REFAIRE"])]),

        E("training-completions", "coll_training_completions", "CollTrainingCompletion", "coll-training-completions",
          "training_completion", "Attestations de formation", "Training completions",
          "Validation de la fin d' une formation par le collaborateur.",
          "Validation of the end of a training by the collaborator.",
          "Le succes conditionne l' habilitation delivree.",
          "Success conditions the issued authorization.",
          "GraduationCap", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("formation", "str", "Formation", "Training"),
           F("date", "date", "Date", "Date"),
           F("score", "int", "Score", "Score"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SUIVI", "REUSSI", "ECHOUE", "CERTIFIE"])]),

        E("equipment-issues", "coll_equipment_issues", "CollEquipmentIssue", "coll-equipment-issues",
          "equipment_issue", "Signalements de probleme equipement", "Equipment issues",
          "Probleme rencontre sur un equipement mis a disposition.",
          "Problem met on a provided equipment.",
          "Le blocage d' un equipement immobilise la tache.",
          "A blocked equipment halts the task.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("equipement", "str", "Equipement", "Equipment"),
           F("probleme", "text", "Probleme", "Problem"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SIGNAL", "REPARATION", "REMPLACER", "RESOLU"])]),

        E("shift-attendance", "coll_shift_attendance", "CollShiftAttendance", "coll-shift-attendance",
          "shift_attendance", "Presences par poste", "Shift attendance",
          "Enregistrement de presence sur un poste de travail.",
          "Attendance record on a work shift.",
          "La presence effective conditionne la paie.",
          "Actual attendance conditions the payroll.",
          "CalendarCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("poste", "str", "Poste", "Shift"),
           F("date", "date", "Date", "Date"),
           F("arrivee", "datetime", "Arrivee", "Arrival"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PRESENT", "ABSENT", "RETARD", "JUSTIFIE"])]),

        E("travel-orders", "coll_travel_orders", "CollTravelOrder", "coll-travel-orders",
          "travel_order", "Ordres de mission", "Travel orders",
          "Ordre de mission autorisant un deplacement.",
          "Travel order authorizing a trip.",
          "Le trajet autorise et la duree encadrent la mission.",
          "The authorized route and duration bound the mission.",
          "Navigation", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("destination", "str", "Destination", "Destination"),
           F("debut", "date", "Debut", "Start"),
           F("fin", "date", "Fin", "End"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "APPROUVE", "EN_COURS", "CLOTURE", "ANNULE"])]),

        E("expense-declarations", "coll_expense_declarations", "CollExpenseDeclaration", "coll-expense-declarations",
          "expense_declaration", "Declarations de frais", "Expense declarations",
          "Declaration de frais engages en mission par le collaborateur.",
          "Declaration of expenses incurred on mission.",
          "Le montant doit etre appuye par des justificatifs.",
          "The amount must be backed by receipts.",
          "Receipt", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("mission", "str", "Mission", "Mission"),
           F("montant", "num", "Montant", "Amount"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DECLARE", "JUSTIFIE", "REMBOURSE", "REJETE"])]),

        E("certification-uploads", "coll_cert_uploads", "CollCertificationUpload", "coll-certification-uploads",
          "certification_upload", "Depot de certifications", "Certification uploads",
          "Depot par le collaborateur d' une piece de certification.",
          "Collaborator upload of a certification document.",
          "La validite de la piece maintient l' habilitation active.",
          "Document validity keeps the authorization active.",
          "FileBadge", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("certification", "str", "Certification", "Certification"),
           F("expire_le", "date", "Expire le", "Expires"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEPOSE", "VERIFIE", "REJETE", "EXPIRE"])]),

        E("task-completions", "coll_task_completions", "CollTaskCompletion", "coll-task-completions",
          "task_completion", "Achevements de taches", "Task completions",
          "Cloture d' une tache assignee au collaborateur.",
          "Closure of a task assigned to the collaborator.",
          "L' horodatage d' achevement alimente le suivi de charge.",
          "The completion timestamp feeds workload tracking.",
          "CheckCircle2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("tache", "str", "Tache", "Task"),
           F("acheve_le", "datetime", "Acheve le", "Completed at"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "FAITE", "VALIDEE", "REOUVERTE"])]),

        E("feedback-submissions", "coll_feedback", "CollFeedback", "coll-feedback-submissions",
          "feedback_submission", "Remontees terrain", "Feedback submissions",
          "Retour d' experience emis par le collaborateur sur le terrain.",
          "Field feedback raised by the collaborator.",
          "La remontee alimente l' amelioration continue.",
          "The feedback feeds continuous improvement.",
          "Send", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("sujet", "str", "Sujet", "Topic"),
           F("contenu", "text", "Contenu", "Content"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMIS", "PRIS_EN_COMPTE", "TRAITE", "CLASSE"])]),

        E("availability-declarations", "coll_availability", "CollAvailability", "coll-availability-declarations",
          "availability_declaration", "Declarations de disponibilite", "Availability declarations",
          "Disponible declaree par le collaborateur pour une periode.",
          "Availability declared by the collaborator for a period.",
          "La disponibilite conditionne l' affectation future.",
          "Availability conditions future assignment.",
          "CalendarClock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("periode", "str", "Periode", "Period"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DISPONIBLE", "PARTIEL", "INDISPONIBLE"])]),

        E("contract-renewal-requests", "coll_contract_renewals", "CollContractRenewalRequest", "coll-contract-renewal-requests",
          "contract_renewal_request", "Demandes de renouvellement de contrat", "Contract renewal requests",
          "Demande de renouvellement du contrat du collaborateur.",
          "Request to renew the collaborator's contract.",
          "L' echeance contractuelle impose l' anticipation.",
          "The contract end date forces anticipation.",
          "FileSignature", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("echeance", "date", "Echeance", "End date"),
           F("type", "str", "Type", "Type"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["CDD", "INTERIM", "PRESTATION", "ALTERNANCE"]),
           EN("statut", ["DEMANDE", "INSTRUIT", "RENOUVELE", "NON_RENOUVELE"])]),

        E("document-requests", "coll_document_requests", "CollDocumentRequest", "coll-document-requests",
          "document_request", "Demandes de documents", "Document requests",
          "Demande d' un document administratif au collaborateur.",
          "Request for an administrative document from the collaborator.",
          "La reponse dans les delais conditionne la conformite du dossier.",
          "Timely response conditions file compliance.",
          "FolderSearch", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("collaborateur", "str", "Collaborateur", "Collaborator"),
           F("document", "str", "Document", "Document"),
           F("delai", "date", "Delai", "Deadline"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DEMANDE", "REPONDUE", "RELANCE", "CLASSE"])]),
    ],
)
