"""Manifest Vague D — batch D2 (portails metier « sober & justifie »).

Principe d'honnetete : on n'invente PAS des ecrans creux. Chaque enregistrement
ci-dessous est une trace que le ROLE saisit réellement sur le terrain, DISTINCTE
des tables maitresses operationnelles du module pilote (parc / qhse). Le
perm_module choisi est le wildcard qu'un role SUPERVISANT detient deja
(ROLE_GRANTS), donc les endpoints sont reellement atteignables et consommables :
  - portail-technicien -> perm_module="parc"  (« parc.*.* » CHEF_PARC)
  - portail-qhse       -> perm_module="qhse"  (« qhse.*.* » officier QHSE)

Chaine Alembic 089-090 depuis 088_magasinier_c_deep (tete lineaire unique).
Aucune valeur par defaut fabriquee ; statut = cycle de vie metier explicite.
"""


def E(slug, table, cn, entite, perm, titre, titreEn, desc, descEn, aide, aideEn, icon,
      unicite, fields, enums=None):
    return dict(slug=slug, table=table, class_name=cn, entite=entite, perm=perm,
                titre=titre, titreEn=titreEn, description=desc, descriptionEn=descEn,
                aide=aide, aideEn=aideEn, icon=icon, unicite=unicite,
                fields=fields, enums=enums or [])


def F(name, typ, label, labelEn=None, required=False, search=False):
    d = dict(name=name, type=typ, label=label, labelEn=labelEn or label)
    if required:
        d["required"] = True
    if search:
        d["search"] = True
    return d


def EN(name, values, default=None):
    d = dict(name=name, values=values)
    if default:
        d["default"] = default
    return d


MODULES = {}

# ─── portail-technicien (+19 -> 20) : traces d' atelier du technicien ────────
MODULES["technicien_d"] = dict(
    module_key="technicien_d", module_slug="portail-technicien",
    module_path="portail-technicien", perm_module="parc",
    registre_filename="registres_c",
    revision="089", down_revision="088_magasinier_c_deep",
    entities=[
        E("work-orders", "tech_work_orders", "TechWorkOrder", "tech-work-orders",
          "work_order", "Ordres de travail", "Work orders",
          "Ordre d' intervention recu et execute par le technicien.",
          "Intervention order received and executed by the technician.",
          "Le kilometrage/moteur justifie le declenchement.",
          "Odometer/hour-meter justifies the trigger.",
          "Wrench", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("type_travaux", "str", "Type de travaux", "Work type"),
           F("description", "text", "Description", "Description"),
           F("ouverture", "datetime", "Ouverture", "Opened"),
           F("cloture", "datetime", "Cloture", "Closed"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_travaux", ["PREVENTIF", "CORRECTIF", "AMLIORATIF", "CONTROLE"]),
           EN("statut", ["OUVERT", "EN_COURS", "EN_ATTENTE_PIECE", "TERMINE", "ANNULE"])]),

        E("intervention-sheets", "tech_intervention_sheets", "TechInterventionSheet", "tech-intervention-sheets",
          "intervention_sheet", "Fiches d' intervention", "Intervention sheets",
          "Compte-rendu detaille d' une intervention realisee.",
          "Detailed report of a performed intervention.",
          "La main d' oeuvre et la duree tracent l' effort reel.",
          "Labor and duration record the real effort.",
          "ClipboardCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre_travail", "str", "Ordre de travail", "Work order"),
           F("technicien", "str", "Technicien", "Technician"),
           F("duree_min", "int", "Duree (min)", "Duration (min)"),
           F("main_oeuvre", "num", "Main d' oeuvre", "Labor cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["BROUILLON", "VALIDEE", "RETOUR_CLIENT", "CLOTUREE"])]),

        E("diagnoses", "tech_diagnoses", "TechDiagnosis", "tech-diagnoses",
          "diagnosis", "Diagnostics", "Diagnoses",
          "Diagnostic technique pose avant reparation.",
          "Technical diagnosis made before repair.",
          "La cause racine identifiee guide la reparation.",
          "The identified root cause guides the repair.",
          "Stethoscope", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("symptome", "str", "Symptome", "Symptom"),
           F("cause_racine", "text", "Cause racine", "Root cause"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "CONFIRME", "INDETERMIN", "ESCALADE"])]),

        E("parts-consumption", "tech_parts_consumption", "TechPartConsumption", "tech-parts-consumption",
          "part_consumption", "Consommation de pieces", "Parts consumption",
          "Pieces detachees posees lors d' une intervention.",
          "Spare parts fitted during an intervention.",
          "La quantite et la reference engageent le stock.",
          "Quantity and reference commit the stock.",
          "Package", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre_travail", "str", "Ordre de travail", "Work order"),
           F("piece", "str", "Piece", "Part"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("cout_unitaire", "num", "Cout unitaire", "Unit cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["RESERVE", "POSE", "RETOURNE", "RUPTURE"])]),

        E("preventive-plans", "tech_preventive_plans", "TechPreventivePlan", "tech-preventive-plans",
          "preventive_plan", "Plans d' entretien preventif", "Preventive plans",
          "Echeancier d' entretien planifie d' un vehicule.",
          "Scheduled maintenance calendar of a vehicle.",
          "L' intervalle (km ou jours) determine la prochaine echeance.",
          "The interval (km or days) sets the next due date.",
          "CalendarCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("operation", "str", "Operation", "Operation"),
           F("intervalle_km", "int", "Intervalle (km)", "Interval (km)"),
           F("derniere_realisation", "date", "Derniere realization", "Last done"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "PROCHE", "EN_RETARD", "FAIT"])]),

        E("breakdown-tickets", "tech_breakdown_tickets", "TechBreakdownTicket", "tech-breakdown-tickets",
          "breakdown_ticket", "Billets de panne", "Breakdown tickets",
          "Signalement de panne transmis au technicien.",
          "Breakdown report routed to the technician.",
          "La severite priorise la prise en charge.",
          "Severity prioritizes the response.",
          "AlertTriangle", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("lieu", "str", "Lieu", "Location"),
           F("severite", "str", "Severite", "Severity"),
           F("recu", "datetime", "Recu", "Received"),
           F("statut", "str", "Statut", "Status")],
          [EN("severite", ["BLOQUANT", "MAJEUR", "MINEUR"]),
           EN("statut", ["NOUVEAU", "AFFECTE", "REPARATION", "REMORQUE", "CLOTURE"])]),

        E("repair-reports", "tech_repair_reports", "TechRepairReport", "tech-repair-reports",
          "repair_report", "Rapports de reparation", "Repair reports",
          "Bilan de fin de reparation et remise en service.",
          "End-of-repair summary and return to service.",
          "Le test de sortie certifie la remise en service.",
          "The exit test certifies the return to service.",
          "FileText", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre_travail", "str", "Ordre de travail", "Work order"),
           F("travaux_realises", "text", "Travaux realises", "Work performed"),
           F("test_sortie_ok", "bool", "Test de sortie OK", "Exit test OK"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["REDAIGE", "VALIDE", "RETOUR", "REMIS_SERVICE"])]),

        E("calibration-records", "tech_calibration_records", "TechCalibrationRecord", "tech-calibration-records",
          "calibration_record", "Fiches d' etalonnage", "Calibration records",
          "Etalonnage d' un instrument de mesure du parc.",
          "Calibration of a fleet measuring instrument.",
          "La tolerance et la prochaine date encadrent la validite.",
          "Tolerance and next date bound validity.",
          "Ruler", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("instrument", "str", "Instrument", "Instrument"),
           F("tolerance", "str", "Tolerance", "Tolerance"),
           F("date_etalonnage", "date", "Date etalonnage", "Calibration date"),
           F("prochaine_date", "date", "Prochaine echeance", "Next due"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "AJUSTE", "HORS_TOLERANCE", "REFORME"])]),

        E("equipment-checklists", "tech_equipment_checklists", "TechEquipmentChecklist", "tech-equipment-checklists",
          "equipment_checklist", "Controles d' equipement atelier", "Equipment checklists",
          "Checklist de verification d' un equipement d' atelier.",
          "Verification checklist of a workshop equipment.",
          "Un point en defaut rend l' equipement indisponible.",
          "A failed point makes the equipment unavailable.",
          "ListChecks", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("equipement", "str", "Equipement", "Equipment"),
           F("points_controles", "int", "Points controles", "Points checked"),
           F("anomalies", "int", "Anomalies", "Defects"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "SURVEILLE", "INDISPONIBLE"])]),

        E("tool-loans", "tech_tool_loans", "TechToolLoan", "tech-tool-loans",
          "tool_loan", "Prets d' outillage", "Tool loans",
          "Sortie et retour d' outillage par le technicien.",
          "Tool issue and return by the technician.",
          "Le retour non enregistre bloque l' inventaire d' outillage.",
          "An unlogged return blocks the tool inventory.",
          "Hammer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("outil", "str", "Outil", "Tool"),
           F("technicien", "str", "Technicien", "Technician"),
           F("sortie", "datetime", "Sortie", "Issued"),
           F("retour", "datetime", "Retour", "Returned"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EMPRUNTE", "RETOURNE", "PERDU", "ENDOMMAGE"])]),

        E("safety-lockouts", "tech_safety_lockouts", "TechSafetyLockout", "tech-safety-lockouts",
          "safety_lockout", "Consignations de securite", "Safety lockouts",
          "Consignation (LOTO) d' une installation avant intervention.",
          "Lock-out/tag-out of an installation before intervention.",
          "L' autorisation de levee engage le responsable.",
          "The release authorization commits the responsible person.",
          "Lock", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("installation", "str", "Installation", "Installation"),
           F("motif", "str", "Motif", "Reason"),
           F("pose", "datetime", "Pose", "Applied"),
           F("levee", "datetime", "Levee", "Released"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["POSEE", "ACTIVE", "LEVEE", "ANOMALIE"])]),

        E("warranty-claims", "tech_warranty_claims", "TechWarrantyClaim", "tech-warranty-claims",
          "warranty_claim", "Reclamations de garantie", "Warranty claims",
          "Demande de prise en charge sous garantie d' une piece.",
          "Request to cover a part under warranty.",
          "Le numero de serie et la date d' achat conditionnent l' admissibilite.",
          "Serial number and purchase date condition admissibility.",
          "BadgeCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("piece", "str", "Piece", "Part"),
           F("fournisseur", "str", "Fournisseur", "Supplier"),
           F("date_achat", "date", "Date d' achat", "Purchase date"),
           F("montant", "num", "Montant", "Amount"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "INSTRUIT", "ACCEPTEE", "REJETEE"])]),

        E("service-appointments", "tech_service_appointments", "TechServiceAppointment", "tech-service-appointments",
          "service_appointment", "RDV d' atelier", "Service appointments",
          "Creneau planifie pour une intervention en atelier.",
          "Scheduled slot for a workshop intervention.",
          "Le créneau reserve immobilise le vehicule a une date donnee.",
          "The booked slot grounds the vehicle on a given date.",
          "CalendarDays", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("creneau", "datetime", "Creneau", "Slot"),
           F("atelier", "str", "Atelier", "Workshop"),
           F("duree_min", "int", "Duree (min)", "Duration (min)"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "CONFIRME", "HONORE", "MANQUE", "REPORTE"])]),

        E("labor-timesheets", "tech_labor_timesheets", "TechLaborTimesheet", "tech-labor-timesheets",
          "labor_timesheet", "Feuilles de temps main d' oeuvre", "Labor timesheets",
          "Temps passe par le technicien sur chaque ordre.",
          "Time spent by the technician on each order.",
          "Le temps declare alimente le cout de main d' oeuvre.",
          "Logged time feeds the labor cost.",
          "Timer", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre_travail", "str", "Ordre de travail", "Work order"),
           F("technicien", "str", "Technicien", "Technician"),
           F("minutes", "int", "Minutes", "Minutes"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SAISI", "SOUMIS", "VALIDE", "AJUSTE"])]),

        E("upgrade-requests", "tech_upgrade_requests", "TechUpgradeRequest", "tech-upgrade-requests",
          "upgrade_request", "Demandes d' amlioration", "Upgrade requests",
          "Demande d' amlioration technique sur un vehicule ou un equipement.",
          "Technical improvement request on a vehicle or equipment.",
          "Le gain attendu justifie l' investissement.",
          "The expected gain justifies the investment.",
          "TrendingUp", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("cible", "str", "Cible", "Target"),
           F("objet", "str", "Objet", "Object"),
           F("gain_attendu", "text", "Gain attendu", "Expected gain"),
           F("cout_estime", "num", "Cout estime", "Estimated cost"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSE", "ETUDIE", "APPROUVE", "REJETE", "INSTALLE"])]),

        E("failure-analyses", "tech_failure_analyses", "TechFailureAnalysis", "tech-failure-analyses",
          "failure_analysis", "Analyses de panne", "Failure analyses",
          "Analyse des causes d' une panne repetitive ou critique.",
          "Root-cause analysis of a recurring or critical failure.",
          "La frequence et la criticite priorisent l' action preventive.",
          "Frequency and criticality prioritize the preventive action.",
          "Microscope", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("mode_defaillance", "str", "Mode de defaillance", "Failure mode"),
           F("frequence", "int", "Frequence", "Frequency"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["OUVERTE", "ANALYSEE", "ACTION_PLANIFIEE", "CLOTUREE"])]),

        E("spare-requests", "tech_spare_requests", "TechSpareRequest", "tech-spare-requests",
          "spare_request", "Demandes de pieces", "Spare requests",
          "Demande de reapprovisionnement de pieces pour l' atelier.",
          "Restocking request of parts for the workshop.",
          "Le stock bas declenche la demande au magasin.",
          "Low stock triggers the request to the store.",
          "Boxes", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("piece", "str", "Piece", "Part"),
           F("quantite", "int", "Quantite", "Quantity"),
           F("demandeur", "str", "Demandeur", "Requester"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "EN_ATTENTE", "SERVI", "RUPTURE", "ANNULEE"])]),

        E("inspection-records", "tech_inspection_records", "TechInspectionRecord", "tech-inspection-records",
          "inspection_record", "Fiches de controle technique", "Inspection records",
          "Controle technique / reglementaire d' un vehicule.",
          "Technical / regulatory inspection of a vehicle.",
          "La date de validite conditionne la circulation.",
          "Validity date conditions circulation.",
          "ClipboardList", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("vehicule", "str", "Vehicule", "Vehicle"),
           F("type_controle", "str", "Type de controle", "Inspection type"),
           F("date_controle", "date", "Date controle", "Inspection date"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("type_controle", ["TECHNIQUE", "SECURITE", "ENVIRONNEMENT", "HABilitation"]),
           EN("statut", ["CONFORME", "RESERVES", "NON_CONFORME", "A_REFAIRE"])]),

        E("work-order-costs", "tech_work_order_costs", "TechWorkOrderCost", "tech-work-order-costs",
          "work_order_cost", "Couts d' ordre de travail", "Work order costs",
          "Imputation des couts (pieces + MO) d' un ordre de travail.",
          "Cost posting (parts + labor) of a work order.",
          "La somme pieces + MO doit egaler le cout total facture.",
          "Parts plus labor must equal the billed total.",
          "CircleDollarSign", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("ordre_travail", "str", "Ordre de travail", "Work order"),
           F("cout_pieces", "num", "Cout pieces", "Parts cost"),
           F("cout_mo", "num", "Cout main d' oeuvre", "Labor cost"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["ESTIME", "EN_COURS", "CLOTURE", "FACTURE"])]),
    ],
)

# ─── portail-qhse (+19 -> 20) : declarations terrain du role securite ────────
MODULES["qhse_portal_d"] = dict(
    module_key="qhse_portal_d", module_slug="portail-qhse",
    module_path="portail-qhse", perm_module="qhse",
    registre_filename="registres_c",
    revision="090", down_revision="089_technicien_d_deep",
    entities=[
        E("hazard-reports", "qsp_hazard_reports", "QspHazardReport", "qsp-hazard-reports",
          "hazard_report", "Signalements de dangers", "Hazard reports",
          "Danger constate et signale par un operateur terrain.",
          "Hazard observed and reported by a field operator.",
          "La localisation et la gravite qualifient le danger.",
          "Location and severity qualify the hazard.",
          "TriangleAlert", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("lieu", "str", "Lieu", "Location"),
           F("description", "text", "Description", "Description"),
           F("gravite", "str", "Gravite", "Severity"),
           F("signale_le", "datetime", "Signale le", "Reported at"),
           F("statut", "str", "Statut", "Status")],
          [EN("gravite", ["FAIBLE", "MOYENNE", "ELEVEE", "CRITIQUE"]),
           EN("statut", ["SIGNAL", "EVALUE", "MAITRISE", "SUPPRIME"])]),

        E("near-misses", "qsp_near_misses", "QspNearMiss", "qsp-near-misses",
          "near_miss", "Presqu' accidents", "Near misses",
          "Evenement sans dommage mais revelateur d' un risque.",
          "Event without harm but revealing a risk.",
          "Les presqu' accidents anticipent l' accident reel.",
          "Near misses anticipate real accidents.",
          "AlertOctagon", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("lieu", "str", "Lieu", "Location"),
           F("situation", "text", "Situation", "Situation"),
           F("date", "datetime", "Date", "Date"),
           F("témoin", "str", "Temoin", "Witness"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["DECLARE", "ANALYSE", "ACTION_EN_COURS", "CLOTURE"])]),

        E("safety-observations", "qsp_safety_observations", "QspSafetyObservation", "qsp-safety-observations",
          "safety_observation", "Observations de securite", "Safety observations",
          "Comportement ou situation observe lors d' une ronde securite.",
          "Behavior or situation seen during a safety walk.",
          "Positive ou a corriger : la nature pilote le suivi.",
          "Positive or to correct: nature drives follow-up."),
          "Eye", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("zone", "str", "Zone", "Zone"),
           F("observation", "text", "Observation", "Observation"),
           F("nature", "str", "Nature", "Nature"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("nature", ["BONNE_PRATIQUE", "ECART", "DANGER"]),
           EN("statut", ["ENREGISTRE", "SUIVI", "CLOTURE"])]),

        E("ppe-attestations", "qsp_ppe_attestations", "QspPpeAttestation", "qsp-ppe-attestations",
          "ppe_attestation", "Attestations de port d' EPI", "PPE attestations",
          "Attestation du port des EPI par l' operateur a une date.",
          "Attestation of PPE wearing by the operator on a date.",
          "Le controle atteste la conformite quotidienne.",
          "The check evidences daily compliance.",
          "ShieldCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("operateur", "str", "Operateur", "Operator"),
           F("epi_controles", "int", "EPI controles", "PPE checked"),
           F("conforme", "bool", "Conforme", "Compliant"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "PARTIEL", "NON_CONFORME", "RAPPEL"])]),

        E("toolbox-talks", "qsp_toolbox_talks", "QspToolboxTalk", "qsp-toolbox-talks",
          "toolbox_talk", "Quarts d' heure securite", "Toolbox talks",
          "Briefe securite animee aupres d' une equipe.",
          "Safety briefing held for a crew.",
          "L' emargement atteste la diffusion du message.",
          "The sign-in sheet evidences the message spread.",
          "Megaphone", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("sujet", "str", "Sujet", "Topic"),
           F("anime_par", "str", "Anime par", "Led by"),
           F("nb_participants", "int", "Nb participants", "Participants"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "ANIME", "REPORTE", "ANNULE"])]),

        E("work-permit-requests", "qsp_work_permits", "QspWorkPermitRequest", "qsp-work-permit-requests",
          "work_permit_request", "Demandes de permis de travail", "Work permit requests",
          "Demande d' autorisation pour une tache a risque.",
          "Authorization request for a hazardous task.",
          "La zone et le type conditionnent la validation.",
          "Zone and type condition the approval.",
          "FileCheck2", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("type", "str", "Type", "Type"),
           F("lieu", "str", "Lieu", "Location"),
           F("demandeur", "str", "Demandeur", "Requester"),
           F("debut", "datetime", "Debut", "Start"),
           F("statut", "str", "Statut", "Status")],
          [EN("type", ["POINT_CHAUD", "ESPACE_CONFINE", "HAUTEUR", "ELECTRIQUE"]),
           EN("statut", ["SOUMIS", "EN_COURS_VALID", "ACCEPTE", "REFUSE", "CLOTURE"])]),

        E("safety-training-log", "qsp_safety_training_logs", "QspSafetyTrainingLog", "qsp-safety-training-log",
          "safety_training_log", "Suivi formation securite", "Safety training log",
          "Participation d' un operateur a une formation securite.",
          "Operator's participation in a safety training.",
          "La validite du certificat conditionne l' habilitation.",
          "Certificate validity conditions the authorization.",
          "GraduationCap", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("operateur", "str", "Operateur", "Operator"),
           F("formation", "str", "Formation", "Training"),
           F("date", "date", "Date", "Date"),
           F("validite", "date", "Validite", "Validity"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["INSCIT", "SUIVI", "REUSSI", "ECHOUE", "EXPIRE"])]),

        E("exposure-records", "qsp_exposure_records", "QspExposureRecord", "qsp-exposure-records",
          "exposure_record", "Registres d' exposition", "Exposure records",
          "Exposition mesuree d' un operateur a un agent nocif.",
          "Measured exposure of an operator to a harmful agent.",
          "La valeur vs la VLEP determine la conformite.",
          "Value vs limit determines compliance.",
          "Activity", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("operateur", "str", "Operateur", "Operator"),
           F("agent", "str", "Agent", "Agent"),
           F("valeur", "num", "Valeur mesuree", "Measured value"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUS_SEUIL", "PROCHE_SEUIL", "DEPASSE", "A_REMETRE"])]),

        E("first-aid-log", "qsp_first_aid_log", "QspFirstAidLog", "qsp-first-aid-log",
          "first_aid_log", "Registre de premiers secours", "First aid log",
          "Intervention de premiers secours sur un collaborateur.",
          "First-aid intervention on a coworker.",
          "La gravite oriente l' orientation medicale.",
          "Severity guides the medical direction.",
          "Cross", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("personne", "str", "Personne", "Person"),
           F("nature_blessure", "str", "Nature", "Injury nature"),
           F("date", "datetime", "Date", "Date"),
           F("secouriste", "str", "Secouriste", "First aider"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOINS_LOCAUX", "ORIENTE", "HOSPITALISE", "CLOTURE"])]),

        E("safety-suggestions", "qsp_safety_suggestions", "QspSafetySuggestion", "qsp-safety-suggestions",
          "safety_suggestion", "Suggestions de securite", "Safety suggestions",
          "Propose d' amelioration securite emise par un operateur.",
          "Safety improvement proposed by an operator.",
          "L' evaluation qualifie l' interet de la suggestion.",
          "The evaluation qualifies the suggestion's value.",
          "Lightbulb", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("auteur", "str", "Auteur", "Author"),
           F("idee", "text", "Ide", "Idea"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SOUMISE", "EVALUEE", "RETENUE", "ECARTEE", "MISE_EN_OEUVRE"])]),

        E("stop-work-authorities", "qsp_stop_work", "QspStopWorkAuthority", "qsp-stop-work-authorities",
          "stop_work", "Droits de retrait", "Stop work authorities",
          "Exercice du droit de retrait pour danger imminent.",
          "Exercise of the right to withdraw for imminent danger.",
          "La reprise exige la levee du danger.",
          "Resumption requires the danger to be lifted.",
          "OctagonX", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("motif", "text", "Motif", "Reason"),
           F("declenche_le", "datetime", "Declenche le", "Triggered at"),
           F("reprise_le", "datetime", "Reprise le", "Resumed at"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["EN_COURS", "DANGER_EVALUE", "REPRIS", "CONSTATE_ABUSIF"])]),

        E("spill-reports", "qsp_spill_reports", "QspSpillReport", "qsp-spill-reports",
          "spill_report", "Signalements de deversement", "Spill reports",
          "Deversement accidentel de produit signale au QHSE.",
          "Accidental product spill reported to QHSE.",
          "Le volume et la nature definissent la decontamination.",
          "Volume and nature define the decontamination.",
          "Droplets", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("volume", "num", "Volume", "Volume"),
           F("lieu", "str", "Lieu", "Location"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["SIGNAL", "CONTENU", "DECONTAMINE", "DECLARE_AUTORITE"])]),

        E("msds-acknowledgements", "qsp_msds_acks", "QspMsdsAck", "qsp-msds-acknowledgements",
          "msds_ack", "Accuses FDS", "MSDS acknowledgements",
          "Prise de connaissance de la fiche de donnees de securite.",
          "Reading of the safety data sheet.",
          "L' accuse atteste la comprehension du produit.",
          "The acknowledgement evidences understanding of the product.",
          "FileWarning", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("produit", "str", "Produit", "Product"),
           F("operateur", "str", "Operateur", "Operator"),
           F("date", "date", "Date", "Date"),
           F("version_fds", "str", "Version FDS", "SDS version"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_LIRE", "LU", "EXPIRE", "A_RENOUVELER"])]),

        E("ergonomics-assessments", "qsp_ergonomics", "QspErgonomicsAssessment", "qsp-ergonomics-assessments",
          "ergonomics_assessment", "Evaluations ergonomiques", "Ergonomics assessments",
          "Evaluation ergonomique d' un poste de travail.",
          "Ergonomic assessment of a workstation.",
          "Le score de contrainte oriente amenagement.",
          "The strain score guides the layout change.",
          "PersonStanding", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("poste", "str", "Poste", "Workstation"),
           F("contrainte", "str", "Contrainte", "Strain"),
           F("score", "int", "Score", "Score"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("contrainte", ["REPETITIF", "PORT_CHARGE", "POSTURE", "VIBRATION"]),
           EN("statut", ["EVALUE", "A_AMENAGER", "AMENAGE", "RECONTROLE"])]),

        E("hygiene-checks", "qsp_hygiene_checks", "QspHygieneCheck", "qsp-hygiene-checks",
          "hygiene_check", "Controles d' hygiene", "Hygiene checks",
          "Controle d' hygiene d' un local ou d' un poste.",
          "Hygiene check of a room or workstation.",
          "La conformite conditionne l' usage du local.",
          "Compliance conditions the room's use.",
          "SprayCan", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("local", "str", "Local", "Room"),
           F("point_controle", "str", "Point de controle", "Check point"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["CONFORME", "A_NETTOYER", "NON_CONFORME", "RECONTROLE"])]),

        E("inspection-findings", "qsp_inspection_findings", "QspInspectionFinding", "qsp-inspection-findings",
          "inspection_finding", "Constats d' inspection", "Inspection findings",
          "Constat releve lors d' une inspection QHSE.",
          "Finding raised during a QHSE inspection.",
          "La non-conformite ouvre une action corrective.",
          "The non-conformity opens a corrective action.",
          "SearchCheck", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("inspection", "str", "Inspection", "Inspection"),
           F("constat", "text", "Constat", "Finding"),
           F("criticite", "str", "Criticite", "Criticality"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("criticite", ["MINEUR", "MAJEUR", "CRITIQUE"]),
           EN("statut", ["RELEVE", "EN_COURS", "RESOLU", "VERIFIE"])]),

        E("corrective-action-replies", "qsp_capa_replies", "QspCapaReply", "qsp-corrective-action-replies",
          "capa_reply", "Reponses aux actions correctives", "Corrective action replies",
          "Reponse d' un operateur a une action corrective qui lui est demandee.",
          "Operator's reply to a corrective action assigned to them.",
          "La preuve jointe valide la realisation de l' action.",
          "The attached evidence validates the action.",
          "Reply", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("action_corrective", "str", "Action corrective", "Corrective action"),
           F("reponse", "text", "Reponse", "Reply"),
           F("operateur", "str", "Operateur", "Operator"),
           F("date", "datetime", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["A_FAIRE", "REPONDUE", "VALIDE", "INSUFFISANTE"])]),

        E("risk-assessment-inputs", "qsp_risk_inputs", "QspRiskAssessmentInput", "qsp-risk-assessment-inputs",
          "risk_assessment_input", "Contributions a l' evaluation des risques",
          "Risk assessment inputs",
          "Remontee terrain alimentant l' evaluation des risques d' un poste.",
          "Field feed into the risk assessment of a task.",
          "La frequence x gravite alimente la cotation.",
          "Frequency x severity feeds the rating.",
          "Target", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("activite", "str", "Activite", "Activity"),
           F("risque_identifie", "text", "Risque identifie", "Identified risk"),
           F("cotation", "int", "Cotation", "Rating"),
           F("date", "date", "Date", "Date"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PROPOSE", "INTEGRE", "ECARTE", "REVISER"])]),

        E("evacuation-drills", "qsp_evacuation_drills", "QspEvacuationDrill", "qsp-evacuation-drills",
          "evacuation_drill", "Exercices d' evacuation", "Evacuation drills",
          "Participation et chronometrage d' un operateur a un exercice d' evacuation.",
          "Operator's participation and timing in an evacuation drill.",
          "Le temps d' evacuation mesure evalue la performance.",
          "The measured evacuation time assesses performance.",
          "Siren", "reference",
          [F("reference", "str", "Reference", "Reference", required=True, search=True),
           F("site", "str", "Site", "Site"),
           F("date", "datetime", "Date", "Date"),
           F("duree_sec", "int", "Duree (s)", "Duration (s)"),
           F("nb_evacues", "int", "Nb evacues", "Evacuees"),
           F("statut", "str", "Statut", "Status")],
          [EN("statut", ["PLANIFIE", "EFFECTUE", "NON_CONFORME", "REPROGRAMME"])]),
    ],
)
