"""Pydantic schemas for EVO-LOG backend"""
from app.schemas.user import UserCreate, UserUpdate, UserResponse, RoleCreate, RoleResponse, PermissionCreate, PermissionResponse
from app.schemas.agency import AgencyCreate, AgencyUpdate, AgencyResponse
from app.schemas.tiers import TiersCreate, TiersUpdate, TiersResponse, ClientCreate, ClientResponse, FournisseurCreate, FournisseurResponse
from app.schemas.transport import CamionCreate, CamionUpdate, CamionResponse, ConducteurCreate, ConducteurResponse, MissionCreate, MissionUpdate, MissionResponse
from app.schemas.transport_international import (
    OrdreTransportCreate, OrdreTransportUpdate, OrdreTransportResponse,
    CarnetTIRCreate, CarnetTIRUpdate, CarnetTIRResponse,
    CMRCreate, CMRUpdate, CMRResponse,
    ScelleRoutierCreate, ScelleRoutierUpdate, ScelleRoutierResponse,
    PositionTransportCreate, PositionTransportResponse,
    CETSuiviCreate, CETSuiviResponse,
    AssuranceFAPCreate, AssuranceFAPUpdate, AssuranceFAPResponse,
    PlanningLivraisonCreate, PlanningLivraisonUpdate, PlanningLivraisonResponse,
    PreuveLivraisonCreate, PreuveLivraisonUpdate, PreuveLivraisonResponse,
    IncidentTransportCreate, IncidentTransportUpdate, IncidentTransportResponse,
    ControleRoutierCreate, ControleRoutierResponse,
    TaxeRoutiereCreate, TaxeRoutiereResponse,
    CorridorCEMACCreate, CorridorCEMACUpdate, CorridorCEMACResponse,
    RapportTransportResponse
)
from app.schemas.acquisition import (
    AppelOffresCreate, AppelOffresUpdate, AppelOffresResponse,
    CahierChargesCreate, CahierChargesUpdate, CahierChargesResponse,
    LigneCDCCreate, LigneCDCUpdate, LigneCDCResponse,
    OffreCreate, OffreUpdate, OffreResponse,
    LigneOffreCreate, LigneOffreUpdate, LigneOffreResponse,
    EvaluationOffreCreate, EvaluationOffreResponse,
    ComparatifCreate, ComparatifUpdate, ComparatifResponse,
    LigneComparatifCreate, LigneComparatifResponse,
    ContratCadreCreate, ContratCadreUpdate, ContratCadreResponse,
    BonCommandeCreate, BonCommandeUpdate, BonCommandeResponse,
    LigneBCCreate, LigneBCUpdate, LigneBCResponse,
    ReceptionCreate, ReceptionUpdate, ReceptionResponse,
    LigneReceptionCreate, LigneReceptionUpdate, LigneReceptionResponse,
    LitigeFournisseurCreate, LitigeFournisseurUpdate, LitigeFournisseurResponse,
    HistoriqueLitigeCreate, HistoriqueLitigeResponse,
    EvaluationFournisseurCreate, EvaluationFournisseurUpdate, EvaluationFournisseurResponse,
    RapportFournisseurResponse
)
from app.schemas.finance import (
    PlanComptableOHADACreate, PlanComptableOHADAUpdate, PlanComptableOHADAResponse,
    EcritureComptableCreate, EcritureComptableUpdate, EcritureComptableResponse,
    ExerciceComptableCreate, ExerciceComptableUpdate, ExerciceComptableResponse,
    FactureCreate, FactureUpdate, FactureResponse,
    LigneFactureCreate, LigneFactureUpdate, LigneFactureResponse,
    ReglementCreate, ReglementUpdate, ReglementResponse,
    TVADeclarableCreate, TVADeclarableUpdate, TVADeclarableResponse,
    RetenueSourceCreate, RetenueSourceUpdate, RetenueSourceResponse,
    ISDeclarableCreate, ISDeclarableUpdate, ISDeclarableResponse,
    CentimesAdditionnelsCreate, CentimesAdditionnelsUpdate, CentimesAdditionnelsResponse,
    PatenteCreate, PatenteUpdate, PatenteResponse,
    BilanCreate, BilanUpdate, BilanResponse,
    CompteResultatCreate, CompteResultatUpdate, CompteResultatResponse,
    SignatureElectroniqueCreate, SignatureElectroniqueUpdate, SignatureElectroniqueResponse,
    RapportFiscalResponse
)
from app.schemas.qhse import (
    AnalyseRisqueCreate, AnalyseRisqueUpdate, AnalyseRisqueResponse,
    ActionPreventionCreate, ActionPreventionUpdate, ActionPreventionResponse,
    PlanPreventionCreate, PlanPreventionUpdate, PlanPreventionResponse,
    EPIRequisCreate, EPIRequisUpdate, EPIRequisResponse,
    AccidentTravailCreate, AccidentTravailUpdate, AccidentTravailResponse,
    InvestigationAccidentCreate, InvestigationAccidentUpdate, InvestigationAccidentResponse,
    NormeCertificationCreate, NormeCertificationUpdate, NormeCertificationResponse,
    AuditQualiteCreate, AuditQualiteUpdate, AuditQualiteResponse,
    HACCPPlanCreate, HACCPPlanUpdate, HACCPPlanResponse,
    PointCritiqueCCPCreate, PointCritiqueCCPUpdate, PointCritiqueCCPResponse,
    EnregistrementHACCPCreate, EnregistrementHACCPUpdate, EnregistrementHACCPResponse,
    FormationQHSECreate, FormationQHSEUpdate, FormationQHSEResponse,
    IndicateurQHSECreate, IndicateurQHSEUpdate, IndicateurQHSEResponse,
    RapportSecuriteResponse
)
from app.schemas.documents import (
    DocumentCreate, DocumentUpdate, DocumentResponse,
    DossierCreate, DossierUpdate, DossierResponse,
    VersionDocumentCreate, VersionDocumentResponse,
    SignatureDocumentCreate, SignatureDocumentUpdate, SignatureDocumentResponse,
    WorkflowDocumentCreate, WorkflowDocumentUpdate, WorkflowDocumentResponse,
    SceauNumeriqueCreate, SceauNumeriqueUpdate, SceauNumeriqueResponse,
    AnalyseOCRCreate, AnalyseOCRResponse,
    ArchivageLegalCreate, ArchivageLegalUpdate, ArchivageLegalResponse,
    TemplateDocumentCreate, TemplateDocumentUpdate, TemplateDocumentResponse,
    PartageDocumentCreate, PartageDocumentUpdate, PartageDocumentResponse,
    HistoriqueDocumentCreate, HistoriqueDocumentResponse,
    RapportDocumentsResponse
)
from app.schemas.maintenance_gmao import (
    OrdreMaintenanceCreate, OrdreMaintenanceUpdate, OrdreMaintenanceResponse,
    EquipementGMAOCreate, EquipementGMAOUpdate, EquipementGMAOResponse,
    PlanMaintenanceCreate, PlanMaintenanceUpdate, PlanMaintenanceResponse,
    PieceRechangeGMAOCreate, PieceRechangeGMAOUpdate, PieceRechangeGMAOResponse,
    CalibrationCreate, CalibrationUpdate, CalibrationResponse,
    PerformanceEquipementCreate, PerformanceEquipementResponse,
    RapportMaintenanceResponse
)
from app.schemas.integration import (
    IntegrationCreate, IntegrationUpdate, IntegrationResponse,
    RequeteIntegrationCreate, RequeteIntegrationUpdate, RequeteIntegrationResponse,
    WebhookIntegrationCreate, WebhookIntegrationUpdate, WebhookIntegrationResponse,
    SYDONIAPlusCreate, SYDONIAPlusUpdate, SYDONIAPlusResponse,
    GuichetUniqueCreate, GuichetUniqueUpdate, GuichetUniqueResponse,
    PCSCreate, PCSUpdate, PCSResponse,
    IntegrationBanqueCreate, IntegrationBanqueUpdate, IntegrationBanqueResponse,
    IntegrationAssureurCreate, IntegrationAssureurUpdate, IntegrationAssureurResponse,
    IntegrationTransitaireCreate, IntegrationTransitaireUpdate, IntegrationTransitaireResponse,
    SynchronisationCreate, SynchronisationUpdate, SynchronisationResponse,
    RapportIntegrationResponse
)
from app.schemas.notifications import (
    NotificationCreate, NotificationUpdate, NotificationResponse,
    TemplateNotificationCreate, TemplateNotificationUpdate, TemplateNotificationResponse,
    PreferenceNotificationCreate, PreferenceNotificationUpdate, PreferenceNotificationResponse,
    CampagneNotificationCreate, CampagneNotificationUpdate, CampagneNotificationResponse,
    HistoriqueEnvoiCreate, HistoriqueEnvoiResponse,
    EmailNotificationCreate, EmailNotificationResponse,
    SMSNotificationCreate, SMSNotificationResponse,
    WhatsAppNotificationCreate, WhatsAppNotificationResponse,
    PushNotificationCreate, PushNotificationResponse,
    RapportNotificationsResponse
)
from app.schemas.reporting import (
    DashboardExecutifCreate, DashboardExecutifUpdate, DashboardExecutifResponse,
    KPICreate, KPIUpdate, KPIResponse,
    RapportCreate, RapportUpdate, RapportResponse,
    ExportCreate, ExportUpdate, ExportResponse,
    WidgetCreate, WidgetUpdate, WidgetResponse,
    TableauBordOperationnelCreate, TableauBordOperationnelUpdate, TableauBordOperationnelResponse,
    IndicateurFinancierCreate, IndicateurFinancierUpdate, IndicateurFinancierResponse,
    IndicateurDouanierCreate, IndicateurDouanierUpdate, IndicateurDouanierResponse,
    RapportExecutifResponse, RapportFinancierResponse, RapportDouanierResponse
)
from app.schemas.finance import FactureCreate, FactureUpdate, FactureResponse, PaiementCreate, PaiementResponse, CompteCreate, CompteResponse, EcritureComptableCreate, EcritureComptableResponse
from app.schemas.parc import VehiculeCreate, VehiculeUpdate, VehiculeResponse, EquipementCreate, EquipementResponse, MaintenanceCreate, MaintenanceResponse
from app.schemas.magasin import StockCreate, StockUpdate, StockResponse, MouvementStockCreate, MouvementStockResponse, EntrepotCreate, EntrepotResponse
from app.schemas.magasin_douane import (
    EntrepotDouaneCreate, EntrepotDouaneUpdate, EntrepotDouaneResponse,
    DeclarationEntrepotCreate, DeclarationEntrepotUpdate, DeclarationEntrepotResponse,
    LigneEntrepotCreate, LigneEntrepotUpdate, LigneEntrepotResponse,
    FicheMagasinCreate, FicheMagasinUpdate, FicheMagasinResponse,
    MouvementFicheCreate, MouvementFicheResponse,
    InventaireDouanierCreate, InventaireDouanierUpdate, InventaireDouanierResponse,
    LigneInventaireDouanierCreate, LigneInventaireDouanierResponse,
    SurveillanceMagazinCreate, SurveillanceMagazinUpdate, SurveillanceMagazinResponse,
    MiseConsommationCreate, MiseConsommationUpdate, MiseConsommationResponse,
    ReexportationCreate, ReexportationUpdate, ReexportationResponse,
    DestructionCreate, DestructionUpdate, DestructionResponse,
    EntretienStockCreate, EntretienStockUpdate, EntretienStockResponse,
    AssuranceStockCreate, AssuranceStockUpdate, AssuranceStockResponse,
    CompteRenduManutentionCreate, CompteRenduManutentionUpdate, CompteRenduManutentionResponse,
    RapportEntrepotResponse
)
from app.schemas.acconage import (
    NavireCreate, NavireResponse, EscaleCreate, EscaleUpdate, EscaleResponse, OperationAcconageCreate, OperationAcconageResponse,
    StowagePlanCreate, StowagePlanResponse, PositionConteneurCreate, PositionConteneurResponse,
    GrueCreate, GrueUpdate, GrueResponse, ReservationGrueCreate, ReservationGrueResponse,
    RemorqueurCreate, RemorqueurUpdate, RemorqueurResponse, AmarageCreate, AmarageResponse,
    ConteneurCreate, ConteneurUpdate, ConteneurResponse,
    ConnaissementCreate, ConnaissementUpdate, ConnaissementResponse,
    PackingListCreate, PackingListResponse,
    ManifesteCreate, ManifesteUpdate, ManifesteResponse, MarchandiseDangereuseCreate, MarchandiseDangereuseResponse,
    SurestarieCreate, SurestarieUpdate, SurestarieResponse,
    THCCreate, THCUpdate, THCResponse,
    NettoyageCaleCreate, NettoyageCaleUpdate, NettoyageCaleResponse, RapportEscaleResponse
)
from app.schemas.transit import DossierTransitCreate, DossierTransitUpdate, DossierTransitResponse, DeclarationDouaniereCreate, DeclarationDouaniereResponse
from app.schemas.transit_avance import (
    BureauDouaneCreate, BureauDouaneUpdate, BureauDouaneResponse,
    DossierTransitAvanceCreate, DossierTransitAvanceUpdate, DossierTransitAvanceResponse,
    VisitePhysiqueCreate, VisitePhysiqueUpdate, VisitePhysiqueResponse,
    ValorisationDouaniereCreate, ValorisationDouaniereResponse,
    NomenclatureCEMACCreate, NomenclatureCEMACUpdate, NomenclatureCEMACResponse,
    DeclarationDouaniereAvanceCreate, DeclarationDouaniereAvanceUpdate, DeclarationDouaniereAvanceResponse,
    LigneDeclarationCreate, LigneDeclarationResponse,
    BonADCreate, BonADUpdate, BonADResponse,
    AvisMiseConsommationCreate, AvisMiseConsommationUpdate, AvisMiseConsommationResponse,
    CreditEnlevementCreate, CreditEnlevementUpdate, CreditEnlevementResponse,
    DroitPortCreate, DroitPortUpdate, DroitPortResponse,
    TimbreUsageCreate, TimbreUsageUpdate, TimbreUsageResponse,
    LitigeDouanierCreate, LitigeDouanierUpdate, LitigeDouanierResponse,
    ArchivageDossierCreate, ArchivageDossierUpdate, ArchivageDossierResponse,
    ProcedureUrgenteCreate, ProcedureUrgenteUpdate, ProcedureUrgenteResponse,
    RapportDossierResponse
)
from app.schemas.tenant import (
    CompanyCreate, CompanyUpdate, CompanyResponse,
    SubscriptionPlanCreate, SubscriptionPlanUpdate, SubscriptionPlanResponse,
    SubscriptionCreate, SubscriptionUpdate, SubscriptionResponse,
    DepartmentCreate, DepartmentUpdate, DepartmentResponse,
    B2BPortalCreate, B2BPortalUpdate, B2BPortalResponse,
    RapportCompaniesResponse, RapportRevenusResponse
)
from app.schemas.maintenance import InterventionCreate, InterventionUpdate, InterventionResponse, PieceRechangeCreate, PieceRechangeResponse
from app.schemas.qhse import IncidentCreate, IncidentUpdate, IncidentResponse, RapportQHSEResponse, ProcedureSecuriteCreate, ProcedureSecuriteResponse
from app.schemas.audit import AuditLogResponse
from app.schemas.rh import (
    CongeCreate, CongeUpdate, CongeResponse, SoldeCongeResponse,
    AbsenceCreate, AbsenceUpdate, AbsenceResponse,
    TempsTravailCreate, TempsTravailUpdate, TempsTravailResponse, HeuresMensuellesResponse,
    FormationCreate, FormationUpdate, FormationResponse,
    ParticipationFormationCreate, ParticipationFormationUpdate, ParticipationFormationResponse,
    EvaluationPerformanceCreate, EvaluationPerformanceUpdate, EvaluationPerformanceResponse,
    ContratTravailCreate, ContratTravailUpdate, ContratTravailResponse,
    SalaireCreate, SalaireResponse,
    PrimeCreate, PrimeResponse,
    DocumentEmployeCreate, DocumentEmployeUpdate, DocumentEmployeResponse,
    OrganigrammeCreate, OrganigrammeUpdate, OrganigrammeResponse,
    CompetenceCreate, CompetenceUpdate, CompetenceResponse,
    CompetenceEmployeCreate, CompetenceEmployeUpdate, CompetenceEmployeResponse,
    BulletinPaieResponse
)
from app.schemas.magasin_avance import (
    PeremptionCreate, PeremptionResponse,
    ReservationStockCreate, ReservationStockResponse,
    KitArticleCreate, KitArticleResponse,
    ComposantKitCreate, ComposantKitResponse,
    EmplacementDetailCreate, EmplacementDetailResponse,
    TransfertStockCreate, TransfertStockResponse,
    InventaireTournantCreate, InventaireTournantResponse,
    LigneInventaireCreate, LigneInventaireResponse,
    FournisseurStockCreate, FournisseurStockResponse,
    CommandeFournisseurCreate, CommandeFournisseurResponse,
    LigneCommandeFournisseurCreate, LigneCommandeFournisseurResponse,
    BonReceptionCreate, BonReceptionResponse,
    LigneBonReceptionCreate, LigneBonReceptionResponse,
    BonSortieCreate, BonSortieResponse,
    LigneBonSortieCreate, LigneBonSortieResponse,
    RetourClientCreate, RetourClientUpdate, RetourClientResponse,
    LitigeTransporteurCreate, LitigeTransporteurUpdate, LitigeTransporteurResponse,
    ColisCreate, ColisUpdate, ColisResponse,
    RotationStockResponse, PrecisionInventaireResponse, PerformanceFournisseurResponse
)
from app.schemas.transport_avance import (
    DispatchBase, DispatchCreate, DispatchUpdate, DispatchResponse,
    OptimisationTourneesRequest, EquilibreChargeResponse,
    ArretBase, ArretCreate, ArretResponse,
    PODBase, PODCreate, PODUpdate, PODResponse,
    DocumentPODBase, DocumentPODCreate, DocumentPODResponse,
    TableauBordTransportResponse, KPIResponse, AlertPerformanceResponse
)

__all__ = [
    "UserCreate", "UserUpdate", "UserResponse", "RoleCreate", "RoleResponse", "PermissionCreate", "PermissionResponse",
    "AgencyCreate", "AgencyUpdate", "AgencyResponse",
    "TiersCreate", "TiersUpdate", "TiersResponse", "ClientCreate", "ClientResponse", "FournisseurCreate", "FournisseurResponse",
    "CamionCreate", "CamionUpdate", "CamionResponse", "ConducteurCreate", "ConducteurResponse", "MissionCreate", "MissionUpdate", "MissionResponse",
    "OrdreTransportCreate", "OrdreTransportUpdate", "OrdreTransportResponse",
    "CarnetTIRCreate", "CarnetTIRUpdate", "CarnetTIRResponse",
    "CMRCreate", "CMRUpdate", "CMRResponse",
    "ScelleRoutierCreate", "ScelleRoutierUpdate", "ScelleRoutierResponse",
    "PositionTransportCreate", "PositionTransportResponse",
    "CETSuiviCreate", "CETSuiviResponse",
    "AssuranceFAPCreate", "AssuranceFAPUpdate", "AssuranceFAPResponse",
    "PlanningLivraisonCreate", "PlanningLivraisonUpdate", "PlanningLivraisonResponse",
    "PreuveLivraisonCreate", "PreuveLivraisonUpdate", "PreuveLivraisonResponse",
    "IncidentTransportCreate", "IncidentTransportUpdate", "IncidentTransportResponse",
    "ControleRoutierCreate", "ControleRoutierResponse",
    "TaxeRoutiereCreate", "TaxeRoutiereResponse",
    "CorridorCEMACCreate", "CorridorCEMACUpdate", "CorridorCEMACResponse",
    "RapportTransportResponse",
    "AppelOffresCreate", "AppelOffresUpdate", "AppelOffresResponse",
    "CahierChargesCreate", "CahierChargesUpdate", "CahierChargesResponse",
    "LigneCDCCreate", "LigneCDCUpdate", "LigneCDCResponse",
    "OffreCreate", "OffreUpdate", "OffreResponse",
    "LigneOffreCreate", "LigneOffreUpdate", "LigneOffreResponse",
    "EvaluationOffreCreate", "EvaluationOffreResponse",
    "ComparatifCreate", "ComparatifUpdate", "ComparatifResponse",
    "LigneComparatifCreate", "LigneComparatifResponse",
    "ContratCadreCreate", "ContratCadreUpdate", "ContratCadreResponse",
    "BonCommandeCreate", "BonCommandeUpdate", "BonCommandeResponse",
    "LigneBCCreate", "LigneBCUpdate", "LigneBCResponse",
    "ReceptionCreate", "ReceptionUpdate", "ReceptionResponse",
    "LigneReceptionCreate", "LigneReceptionUpdate", "LigneReceptionResponse",
    "LitigeFournisseurCreate", "LitigeFournisseurUpdate", "LitigeFournisseurResponse",
    "HistoriqueLitigeCreate", "HistoriqueLitigeResponse",
    "EvaluationFournisseurCreate", "EvaluationFournisseurUpdate", "EvaluationFournisseurResponse",
    "RapportFournisseurResponse",
    "PlanComptableOHADACreate", "PlanComptableOHADAUpdate", "PlanComptableOHADAResponse",
    "EcritureComptableCreate", "EcritureComptableUpdate", "EcritureComptableResponse",
    "ExerciceComptableCreate", "ExerciceComptableUpdate", "ExerciceComptableResponse",
    "FactureCreate", "FactureUpdate", "FactureResponse",
    "LigneFactureCreate", "LigneFactureUpdate", "LigneFactureResponse",
    "ReglementCreate", "ReglementUpdate", "ReglementResponse",
    "TVADeclarableCreate", "TVADeclarableUpdate", "TVADeclarableResponse",
    "RetenueSourceCreate", "RetenueSourceUpdate", "RetenueSourceResponse",
    "ISDeclarableCreate", "ISDeclarableUpdate", "ISDeclarableResponse",
    "CentimesAdditionnelsCreate", "CentimesAdditionnelsUpdate", "CentimesAdditionnelsResponse",
    "PatenteCreate", "PatenteUpdate", "PatenteResponse",
    "BilanCreate", "BilanUpdate", "BilanResponse",
    "CompteResultatCreate", "CompteResultatUpdate", "CompteResultatResponse",
    "SignatureElectroniqueCreate", "SignatureElectroniqueUpdate", "SignatureElectroniqueResponse",
    "RapportFiscalResponse",
    "AnalyseRisqueCreate", "AnalyseRisqueUpdate", "AnalyseRisqueResponse",
    "ActionPreventionCreate", "ActionPreventionUpdate", "ActionPreventionResponse",
    "PlanPreventionCreate", "PlanPreventionUpdate", "PlanPreventionResponse",
    "EPIRequisCreate", "EPIRequisUpdate", "EPIRequisResponse",
    "AccidentTravailCreate", "AccidentTravailUpdate", "AccidentTravailResponse",
    "InvestigationAccidentCreate", "InvestigationAccidentUpdate", "InvestigationAccidentResponse",
    "NormeCertificationCreate", "NormeCertificationUpdate", "NormeCertificationResponse",
    "AuditQualiteCreate", "AuditQualiteUpdate", "AuditQualiteResponse",
    "HACCPPlanCreate", "HACCPPlanUpdate", "HACCPPlanResponse",
    "PointCritiqueCCPCreate", "PointCritiqueCCPUpdate", "PointCritiqueCCPResponse",
    "EnregistrementHACCPCreate", "EnregistrementHACCPUpdate", "EnregistrementHACCPResponse",
    "FormationQHSECreate", "FormationQHSEUpdate", "FormationQHSEResponse",
    "IndicateurQHSECreate", "IndicateurQHSEUpdate", "IndicateurQHSEResponse",
    "RapportSecuriteResponse",
    "DocumentCreate", "DocumentUpdate", "DocumentResponse",
    "DossierCreate", "DossierUpdate", "DossierResponse",
    "VersionDocumentCreate", "VersionDocumentResponse",
    "SignatureDocumentCreate", "SignatureDocumentUpdate", "SignatureDocumentResponse",
    "WorkflowDocumentCreate", "WorkflowDocumentUpdate", "WorkflowDocumentResponse",
    "SceauNumeriqueCreate", "SceauNumeriqueUpdate", "SceauNumeriqueResponse",
    "AnalyseOCRCreate", "AnalyseOCRResponse",
    "ArchivageLegalCreate", "ArchivageLegalUpdate", "ArchivageLegalResponse",
    "TemplateDocumentCreate", "TemplateDocumentUpdate", "TemplateDocumentResponse",
    "PartageDocumentCreate", "PartageDocumentUpdate", "PartageDocumentResponse",
    "HistoriqueDocumentCreate", "HistoriqueDocumentResponse",
    "RapportDocumentsResponse",
    "OrdreMaintenanceCreate", "OrdreMaintenanceUpdate", "OrdreMaintenanceResponse",
    "EquipementGMAOCreate", "EquipementGMAOUpdate", "EquipementGMAOResponse",
    "PlanMaintenanceCreate", "PlanMaintenanceUpdate", "PlanMaintenanceResponse",
    "PieceRechangeGMAOCreate", "PieceRechangeGMAOUpdate", "PieceRechangeGMAOResponse",
    "CalibrationCreate", "CalibrationUpdate", "CalibrationResponse",
    "PerformanceEquipementCreate", "PerformanceEquipementResponse",
    "RapportMaintenanceResponse",
    "IntegrationCreate", "IntegrationUpdate", "IntegrationResponse",
    "RequeteIntegrationCreate", "RequeteIntegrationUpdate", "RequeteIntegrationResponse",
    "WebhookIntegrationCreate", "WebhookIntegrationUpdate", "WebhookIntegrationResponse",
    "SYDONIAPlusCreate", "SYDONIAPlusUpdate", "SYDONIAPlusResponse",
    "GuichetUniqueCreate", "GuichetUniqueUpdate", "GuichetUniqueResponse",
    "PCSCreate", "PCSUpdate", "PCSResponse",
    "IntegrationBanqueCreate", "IntegrationBanqueUpdate", "IntegrationBanqueResponse",
    "IntegrationAssureurCreate", "IntegrationAssureurUpdate", "IntegrationAssureurResponse",
    "IntegrationTransitaireCreate", "IntegrationTransitaireUpdate", "IntegrationTransitaireResponse",
    "SynchronisationCreate", "SynchronisationUpdate", "SynchronisationResponse",
    "RapportIntegrationResponse",
    "NotificationCreate", "NotificationUpdate", "NotificationResponse",
    "TemplateNotificationCreate", "TemplateNotificationUpdate", "TemplateNotificationResponse",
    "PreferenceNotificationCreate", "PreferenceNotificationUpdate", "PreferenceNotificationResponse",
    "CampagneNotificationCreate", "CampagneNotificationUpdate", "CampagneNotificationResponse",
    "HistoriqueEnvoiCreate", "HistoriqueEnvoiResponse",
    "EmailNotificationCreate", "EmailNotificationResponse",
    "SMSNotificationCreate", "SMSNotificationResponse",
    "WhatsAppNotificationCreate", "WhatsAppNotificationResponse",
    "PushNotificationCreate", "PushNotificationResponse",
    "RapportNotificationsResponse",
    "DashboardExecutifCreate", "DashboardExecutifUpdate", "DashboardExecutifResponse",
    "KPICreate", "KPIUpdate", "KPIResponse",
    "RapportCreate", "RapportUpdate", "RapportResponse",
    "ExportCreate", "ExportUpdate", "ExportResponse",
    "WidgetCreate", "WidgetUpdate", "WidgetResponse",
    "TableauBordOperationnelCreate", "TableauBordOperationnelUpdate", "TableauBordOperationnelResponse",
    "IndicateurFinancierCreate", "IndicateurFinancierUpdate", "IndicateurFinancierResponse",
    "IndicateurDouanierCreate", "IndicateurDouanierUpdate", "IndicateurDouanierResponse",
    "RapportExecutifResponse", "RapportFinancierResponse", "RapportDouanierResponse",
    "CompanyCreate", "CompanyUpdate", "CompanyResponse",
    "SubscriptionPlanCreate", "SubscriptionPlanUpdate", "SubscriptionPlanResponse",
    "SubscriptionCreate", "SubscriptionUpdate", "SubscriptionResponse",
    "DepartmentCreate", "DepartmentUpdate", "DepartmentResponse",
    "B2BPortalCreate", "B2BPortalUpdate", "B2BPortalResponse",
    "RapportCompaniesResponse", "RapportRevenusResponse",
    "FactureCreate", "FactureUpdate", "FactureResponse", "PaiementCreate", "PaiementResponse", "CompteCreate", "CompteResponse", "EcritureComptableCreate", "EcritureComptableResponse",
    "VehiculeCreate", "VehiculeUpdate", "VehiculeResponse", "EquipementCreate", "EquipementResponse", "MaintenanceCreate", "MaintenanceResponse",
    "StockCreate", "StockUpdate", "StockResponse", "MouvementStockCreate", "MouvementStockResponse", "EntrepotCreate", "EntrepotResponse",
    "EntrepotDouaneCreate", "EntrepotDouaneUpdate", "EntrepotDouaneResponse",
    "DeclarationEntrepotCreate", "DeclarationEntrepotUpdate", "DeclarationEntrepotResponse",
    "LigneEntrepotCreate", "LigneEntrepotUpdate", "LigneEntrepotResponse",
    "FicheMagasinCreate", "FicheMagasinUpdate", "FicheMagasinResponse",
    "MouvementFicheCreate", "MouvementFicheResponse",
    "InventaireDouanierCreate", "InventaireDouanierUpdate", "InventaireDouanierResponse",
    "LigneInventaireDouanierCreate", "LigneInventaireDouanierResponse",
    "SurveillanceMagazinCreate", "SurveillanceMagazinUpdate", "SurveillanceMagazinResponse",
    "MiseConsommationCreate", "MiseConsommationUpdate", "MiseConsommationResponse",
    "ReexportationCreate", "ReexportationUpdate", "ReexportationResponse",
    "DestructionCreate", "DestructionUpdate", "DestructionResponse",
    "EntretienStockCreate", "EntretienStockUpdate", "EntretienStockResponse",
    "AssuranceStockCreate", "AssuranceStockUpdate", "AssuranceStockResponse",
    "CompteRenduManutentionCreate", "CompteRenduManutentionUpdate", "CompteRenduManutentionResponse",
    "RapportEntrepotResponse",
    "NavireCreate", "NavireResponse", "EscaleCreate", "EscaleUpdate", "EscaleResponse", "OperationAcconageCreate", "OperationAcconageResponse",
    "StowagePlanCreate", "StowagePlanResponse", "PositionConteneurCreate", "PositionConteneurResponse",
    "GrueCreate", "GrueUpdate", "GrueResponse", "ReservationGrueCreate", "ReservationGrueResponse",
    "RemorqueurCreate", "RemorqueurUpdate", "RemorqueurResponse", "AmarageCreate", "AmarageResponse",
    "ConteneurCreate", "ConteneurUpdate", "ConteneurResponse",
    "ConnaissementCreate", "ConnaissementUpdate", "ConnaissementResponse",
    "PackingListCreate", "PackingListResponse",
    "ManifesteCreate", "ManifesteUpdate", "ManifesteResponse", "MarchandiseDangereuseCreate", "MarchandiseDangereuseResponse",
    "SurestarieCreate", "SurestarieUpdate", "SurestarieResponse",
    "THCCreate", "THCUpdate", "THCResponse",
    "NettoyageCaleCreate", "NettoyageCaleUpdate", "NettoyageCaleResponse", "RapportEscaleResponse",
    "DossierTransitCreate", "DossierTransitUpdate", "DossierTransitResponse", "DeclarationDouaniereCreate", "DeclarationDouaniereResponse",
    "BureauDouaneCreate", "BureauDouaneUpdate", "BureauDouaneResponse",
    "DossierTransitAvanceCreate", "DossierTransitAvanceUpdate", "DossierTransitAvanceResponse",
    "VisitePhysiqueCreate", "VisitePhysiqueUpdate", "VisitePhysiqueResponse",
    "ValorisationDouaniereCreate", "ValorisationDouaniereResponse",
    "NomenclatureCEMACCreate", "NomenclatureCEMACUpdate", "NomenclatureCEMACResponse",
    "DeclarationDouaniereAvanceCreate", "DeclarationDouaniereAvanceUpdate", "DeclarationDouaniereAvanceResponse",
    "LigneDeclarationCreate", "LigneDeclarationResponse",
    "BonADCreate", "BonADUpdate", "BonADResponse",
    "AvisMiseConsommationCreate", "AvisMiseConsommationUpdate", "AvisMiseConsommationResponse",
    "CreditEnlevementCreate", "CreditEnlevementUpdate", "CreditEnlevementResponse",
    "DroitPortCreate", "DroitPortUpdate", "DroitPortResponse",
    "TimbreUsageCreate", "TimbreUsageUpdate", "TimbreUsageResponse",
    "LitigeDouanierCreate", "LitigeDouanierUpdate", "LitigeDouanierResponse",
    "ArchivageDossierCreate", "ArchivageDossierUpdate", "ArchivageDossierResponse",
    "ProcedureUrgenteCreate", "ProcedureUrgenteUpdate", "ProcedureUrgenteResponse",
    "RapportDossierResponse",
    "InterventionCreate", "InterventionUpdate", "InterventionResponse", "PieceRechangeCreate", "PieceRechangeResponse",
    "IncidentCreate", "IncidentUpdate", "IncidentResponse", "RapportQHSEResponse", "ProcedureSecuriteCreate", "ProcedureSecuriteResponse",
    "AuditLogResponse",
    "CongeCreate", "CongeUpdate", "CongeResponse", "SoldeCongeResponse",
    "AbsenceCreate", "AbsenceUpdate", "AbsenceResponse",
    "TempsTravailCreate", "TempsTravailUpdate", "TempsTravailResponse", "HeuresMensuellesResponse",
    "FormationCreate", "FormationUpdate", "FormationResponse",
    "ParticipationFormationCreate", "ParticipationFormationUpdate", "ParticipationFormationResponse",
    "EvaluationPerformanceCreate", "EvaluationPerformanceUpdate", "EvaluationPerformanceResponse",
    "ContratTravailCreate", "ContratTravailUpdate", "ContratTravailResponse",
    "SalaireCreate", "SalaireResponse",
    "PrimeCreate", "PrimeResponse",
    "DocumentEmployeCreate", "DocumentEmployeUpdate", "DocumentEmployeResponse",
    "OrganigrammeCreate", "OrganigrammeUpdate", "OrganigrammeResponse",
    "CompetenceCreate", "CompetenceUpdate", "CompetenceResponse",
    "CompetenceEmployeCreate", "CompetenceEmployeUpdate", "CompetenceEmployeResponse",
    "BulletinPaieResponse",
    "PeremptionCreate", "PeremptionResponse",
    "ReservationStockCreate", "ReservationStockResponse",
    "KitArticleCreate", "KitArticleResponse",
    "ComposantKitCreate", "ComposantKitResponse",
    "EmplacementDetailCreate", "EmplacementDetailResponse",
    "TransfertStockCreate", "TransfertStockResponse",
    "InventaireTournantCreate", "InventaireTournantResponse",
    "LigneInventaireCreate", "LigneInventaireResponse",
    "FournisseurStockCreate", "FournisseurStockResponse",
    "CommandeFournisseurCreate", "CommandeFournisseurResponse",
    "LigneCommandeFournisseurCreate", "LigneCommandeFournisseurResponse",
    "BonReceptionCreate", "BonReceptionResponse",
    "LigneBonReceptionCreate", "LigneBonReceptionResponse",
    "BonSortieCreate", "BonSortieResponse",
    "LigneBonSortieCreate", "LigneBonSortieResponse",
    "RetourClientCreate", "RetourClientUpdate", "RetourClientResponse",
    "LitigeTransporteurCreate", "LitigeTransporteurUpdate", "LitigeTransporteurResponse",
    "ColisCreate", "ColisUpdate", "ColisResponse",
    "RotationStockResponse", "PrecisionInventaireResponse", "PerformanceFournisseurResponse",
    "TourneeCreate", "TourneeUpdate", "TourneeResponse",
    "LivraisonCreate", "LivraisonUpdate", "LivraisonResponse",
    "FraisKilometriqueCreate", "FraisKilometriqueResponse",
    "TempsConduiteCreate", "TempsConduiteResponse", "ConformiteTempsResponse",
    "SousTraitantCreate", "SousTraitantUpdate", "SousTraitantResponse",
    "ContratSousTraitantCreate", "ContratSousTraitantUpdate", "ContratSousTraitantResponse",
    "MissionSousTraitantCreate", "MissionSousTraitantUpdate", "MissionSousTraitantResponse",
    "AccidentTransportCreate", "AccidentTransportUpdate", "AccidentTransportResponse",
    "MaintenancePreventiveCreate", "MaintenancePreventiveUpdate", "MaintenancePreventiveResponse",
    "PositionGPSCreate", "PositionGPSResponse",
    "ZoneGeofencingCreate", "ZoneGeofencingUpdate", "ZoneGeofencingResponse",
    "EvenementVehiculeCreate", "EvenementVehiculeResponse",
    "CoutKmResponse", "AnomalieCarburantResponse", "PerformanceSousTraitantResponse",
    "StatistiquesAccidentsResponse", "ComportementConducteurResponse", "KPITransportResponse"
]